### ISSUE TITLE
Double spaces after the period.

### ISSUE THREAD

**Issue by julianeroell** [holacracyone/Holacracy-Constitution#10]
I noticed that the constitution is formatted with double spaces after periods. I find this ugly and difficult to work with. It also goes against all style recommendations that I know.

Is there a specific reason that this is being used or would you accept an edit that replaced all ".  " with ". "?

**Comment by brianjrobertson** [comment]
No reason; please do feel free to change and I'll accept.

**Comment by RashidGilanpour** [comment]
Thanks for this suggestion @martinroell. I've removed all double spaces from Holacracy-Constitution.md
