### ISSUE TITLE
Use "Individual" instead of "Role" in §2.7.1

### ISSUE THREAD

**Issue by chrcowan** [holacracyone/Holacracy-Constitution#100]
2.7.1 talks about cross links...it starts, "If the linked entity is a **role**, then that role may participate in the target circle..." blah blah blah. 

The next paragraph starts, "If the linked entity is a **circle** or a **group**, then a special purpose Cross link role is automatically created instead..." blah blah blah. 

So, it seems like the distinction is basically between an individual and a collective, but why couldn't the individual linked entity be an individual person rather than a role? 

For example, I am cross linked into a circle as a "resident" of a property. That isn't a pre-existing role, but only becomes one once the cross link role is created. 

I would pitch for changing the beginning to, "If the linked entity is _an individual person_ or role, then that _individual _may participate in the target circle..."  

Or, just say "individual" and rely on the contrast to "circle" or "group."

**Comment by brianjrobertson** [comment]
@chrcowan:  It's tagged for clean-up; feel free to submit the change if you'd like.
