### ISSUE TITLE
Rules for Surrogate Rep Link

### ISSUE THREAD

**Issue by oliviercp** [holacracyone/Holacracy-Constitution#101]
Currently the rules of section 2.5.4 apply equally to all Elected Roles. They make enough sense for Facilitators and Secretaries, but don't seem very logical for Rep Links. 

Section 2.5.4 says:

> 2.5.4 Surrogates for Elected Roles
> 
> A surrogate may temporarily fill an Elected Role when one is unfilled, or when the person who normally fills the Role is unavailable for a Circle meeting or feels unable or unwilling to enact the Role’s duties.
> 
> In any given instance where a surrogate is needed, the surrogate is, in this order of precedence:
> 
> (a) someone explicitly specified by the person to be replaced; or
> (b) the acting Facilitator of the Circle; or
> (c) the acting Secretary of the Circle; or
> (d) the Lead Link of the Circle; or
> (e) the first Core Circle Member of the Circle to declare he or she is acting as the surrogate.

Playing this out: 

a) the absent Rep Link designated someone else to replace them --> makes sense
b) and c) if not, then the Facilitator or Secretary of the (sub)circle would act as Rep Link for the super-circle --> doesn't make sense, as their roles' purposes have nothing to do with Rep Linking... at least no more than any other role in the circle.
d) Lead Link would act as both LL and RL temporarily --> makes sense, but we lose the dual linking feature, though it's still better than nothing
e) Seems potentially harmful for _any_ Circle Member to act as Rep Link...!

**Comment by brianjrobertson** [comment]
Agreed; feel free to submit a change...

**Comment by oliviercp** [comment]
I know... :)  I need to think about it a bit more, I just wanted to record
the issue for now.
