### ISSUE TITLE
Use "feel" as the verb associated with "tension" instead of "sense"

### ISSUE THREAD

**Issue by smichel17** [holacracyone/Holacracy-Constitution#102]
See the [relevant discussion](http://community.holacracy.org/topic/is-tension-essential-new-vocabulary-or-can-we-use-issue-instead).

**Comment by brianjrobertson** [comment]
That link appears to be broken; please re-open if you think this is still relevant and can share more about the reason/need for this.

**Comment by smichel17** [comment]
Fixed the link. Here's the relevant quote from that thread:

You said (very abridged),

> Most importantly, "tension" points to an experience - a feeling - where "issue" points to a thought - a mental construct

I replied (less abridged),

> I was previously thinking of a tension as "the gap between how things are and how they could be." But really -- if I understand you correctly -- a tension is the *feeling* produced by that gap. [...]
> 
> I think my misunderstanding stems from the way we talk about Tensions. For example, emphasis mine, in one of the [videos](https://youtu.be/zGLJRpAKS6E?t=24m14s) linked on the home page: you define Tension as "**the feeling** you get when you sense **_a gap_** between what is and what could be." The tension is the **feeling**; the gap is the _**thing** you sense._ But then you immediately say, "..Anything I sense, any _**tension** I sense_, any gap, anything that could be better.."
> 
> Although Tension is correctly defined, it's used as it if is the gap itself. I haven't checked everywhere, but I'm pretty sure that available materials consistently refer to "sensing" tensions, when really, a tension is _felt,_ not _sensed_.

**Comment by MiekeByerley** [comment]
Maybe, I can shed a little light pertaining the the terms. Feeling is a
subset of Sensing, Feeling indicates a direct application to the individual
experiencing it. Sensing however, may not have a direct application on the
individual, it may be observed, conjectured, rationalised. Tension is an
energy gap and like with electricity energy wants to flow, when it comes to
a gap it will arc to connect and this arc evokes a response, this is
tension. A tension evokes a response where as a feeling doesn't
necessarily, you may not feel the arc but you may well sense it though, and
indeed your feeling of frustration is a response to the tension. :)

**Comment by brianjrobertson** [comment]
Thanks Stephan & Mieke, that's helpful.  It's a close call, but it seems to me that "sensing" is the better choice here, based on Mieke's comments and reviewing google's definition of [sense](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=define%3A%20sense) vs. [feel](https://www.google.com/search?q=define%3A+feel&rlz=1C5CHFA_enUS689US689&oq=define%3A+feel&aqs=chrome..69i57j69i58.2095j0j7&sourceid=chrome&ie=UTF-8).

Anyone have other opinions/arguments to pitch for feel over sense?

**Comment by smichel17** [comment]
I think there's some unclear messaging around what a tension is, and this leads to people interpreting the word in whatever way they're used to, like I originally did in the discussion I linked.

Sometimes, "tension" is used to refer to **the gap between how things are and how they could be.**
Other times, it's used to refer to **the feeling or experience produced by such a gap.**

Sometimes it's used both ways in the same breath! Here's a longer quote of Brian from the [spot in the video](https://youtu.be/zGLJRpAKS6E?t=24m14s) I quoted above (emphasis mine):

> I define Tension as simply **the feeling you get when you sense a gap between where we are and where we could be,** or some potential that's better in some way. We sense a lot of these, yet how many people can say, "**Anything I sense, any _Tension_ I sense, any gap, anything that could be better** -- I know exactly what to do with it to drive rapid, meaningful change anywhere in the organization."? Very few companies today can fully harness the sensing that everyone within is doing more often than not, **you get people who have sensed issues for years,** and don't know how to drive a change.

That video is on the front page of holacracy.org. It was my first introduction to Holacracy. Within 3 sentences of learning about the concept of a Tension, I've heard it described as both the feeling and the gap, _and_ I've seen "issue" used as a synonym. In retrospect, I'm not surprised that I started thinking "Tension" and "issue" were interchangeable. I understand the value of describing it in different ways, since different people might respond better to different descriptions, but you should always be describing the same thing.

According to Google, you feel an experience, emotion, or sensation. You sense, well, anything. I checked the constitution just now; [§1.2.1](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#121-processing-tensions) clearly states that a tension is the gap, not the feeling, so it stands to reason you'd sense, not feel, it.

> A tension evokes a response where as a feeling doesn't necessarily, you may not feel the arc but you may well sense it though, and indeed your feeling of frustration is a response to the tension. :)

So to paraphrase, you might FEEL frustrated because you SENSE a tension. And the introductory video defines "Tension" differently because it reflects an older state of Holacracy.

---

So we know what a Tension is. Next question: how it _should_ be?

For me, it comes back to Brian's story about the low voltage light. The moral of the story is that if someone close to the work sees unrealized potential, we shouldn't discount their observation just because only they can see it. However, humans are really bad at that. Holacracy has a solution: give the person the power to realize the potential.

The generalized conclusion is **the person nearest the work knows it the best.** I can suggest a change to someone else's Role, but it's their responsibility to enact it or not. If I try to force an unwanted change through, no matter what my reason, I'm outvoting the low voltage light. That's why Circle Members aren't allowed to make Proposals for another role without permission.

Let's come back to sensing gaps vs feeling... feelings. Emphasis mine.

> Maybe, I can shed a little light pertaining the the terms. Feeling is a subset of Sensing, **Feeling indicates a direct application to the individual experiencing it. Sensing however, may not have a direct application on the individual,** it may be observed, conjectured, rationalised.

I think this hits the nail on the head. It's also why I think that Tensions-as-feelings is more appropriate than Tensions-as-gaps. When we decide that others can sense a tension that's holding back one of your roles, it opens the door to people trying to solve tensions that don't affect any of their roles. In my own experience with Holacracy, I was guilty of this for a long time. If a tension is a feeling, it is mine and mine alone. Someone else might try to help solve whatever problem is causing that feeling, but they're doing it on my behalf -- you can tell someone "You think you sense that but you don't"; it's impossible to say the same about a feeling (or to say the reverse, "You may not feel that, but it's there.").

Obviously there's a rule saying you can't act on another's behalf without permission, so you might say this is a moot point. But remember that we're talking vocabulary here. We want to use the vocabulary that gives the right impression without requiring people to memorize a bunch of rules.

---

Finally, I want to be a low voltage light. I feel a tension with regards to the way we explain Holacracy, because, in the words of someone who I was trying to teach,

> I am suspicious of how difficult it is for me to parse these fairly simple concepts

I am not sure of all the changes we could make to solve this tension. I think that this phrasing change would be a small step forward.

**Comment by smichel17** [comment]
Sorry for the essay.

**Comment by brianjrobertson** [comment]
Stephen:  I do appreciate the feedback on how we convey it and I'm sure that could be improved, though to keep this post focused on the goal for this forum of if/how to change the Constitution, this part of what you wrote seems the most compelling: "_If a tension is a feeling, it is mine and mine alone._"  Using "feel" vs. "sense" definitely has an advantage there, and would help highlight the very personal nature of feeling/sensing a tension.  On the other hand, "feel" still seems like a subset of how we "sense", and we can "sense" a tension in other ways than through what I'd normally think of as a "feeling" (although that's a common one)...  Both words seems to have different pros/cons here (which is probably why I often switch them up, to convey a gestalt of what I'm trying to point to).  Curious if anyone else has perspectives on which one to standardize on in the constitution?  Either way, I do think it's the experience triggered by the gap that we're talking about and should be defining tension in terms of, not the gap itself...

**Comment by MiekeByerley** [comment]
"When we decide that others can sense a tension that's holding back one of your roles, it opens the door to people trying to solve tensions that don't affect any of their roles. In my own experience with Holacracy, I was guilty of this for a long time. If a tension is a feeling, it is mine and mine alone." - This is not necessarily true when others can sense a tension that is holding back one of your roles it amplifies you sensing capacity, it does not automatically entitle them to fix the tension :). Think of it  this way, if a frog is placed in water which is slowly heated the frog does not feel that it is being boiled alive, however an outside observer will note (through sensing) that the frog is being boiled alive and can therefore raise the alarm to the frog to get out. Also I would challenge that a tension only ever affects your own role (directly yes), roles are connected like drops of water in an ocean so the tension in one role ripples and affects other roles. A single Oak in the middle of a Forest is not a Solitary unit but a member of a intricately connected ecosystem. I would agree that the gap is not the tension per say but creates tension because the gap changes the energy flow which is what we sense, so in essence Tension could be said to be a Energy Flow Spike (using electricity as an example). There is another element "Feel" is emotive and reactive (Pathos) so much easier to convey or express to another (so in explaining is generally easier to use when impressing a point), sensing is more nebulous in nature but proactive (requires awareness), more encompassing and therefore also makes it harder to evoke connection with however, (this is an important element) it adds the very important natures of Ethos and Logos, thereby rounding out the concept being explained. It is the order in which they occur in relation to the gap that is essentially an important aspect one is proactive, the other reactive.

**Comment by brianjrobertson** [comment]
I remain super intrigued by this inquiry and dialog, however I'm not seeing enough compelling perspectives from enough on-the-ground Holacracy practitioners to proceed with the change, so I'm closing the issue for now.  If anyone else following this has something to offer though, please do and I will reopen if enough new perspectives are added.

**Comment by karilen** [comment]
Many don't know how to sense tensions. I don't think changing the word to feel would help, but anything for people to know how to sense the tensions. There is a reframe needed of tension in orgs, and I can see that happening.
