### ISSUE TITLE
Breakdown from Unconstitutional Behavior

### ISSUE THREAD

**Issue by tylerdanke** [holacracyone/Holacracy-Constitution#103]
If there is only one single circle and there are not super circles nor subcircles it seems that then the wording of 3.5.2 does not allow for a Breakdown from Unconstitutional Behavior and that seems to be a flaw.

**Comment by tylerdanke** [comment]
I have actually had this happen in my organization where I have had the Secretary not inviting the Facilitator to meetings. This commit does not fully resolve the situation. The way that it is currently worded Facilitator of their own circle can declare a process breakdown because of a pattern of behavior but can not declare a process breakdown because of the outputs in their own circle. Also if the Facilitator declares a Process Breakdown within their own circle, there is no process for restoration. I can see that the process for restoration is to facilitate and process tensions which makes the ability for a Facilitator of their own circle to be able to call Process Breakdown irrelevant. 
I commented the above on the commit.

Added this: This issue is especially important in organizations with only a single circle.

**Comment by brianjrobertson** [comment]
@tylerdanke Let me know if this additional change addresses your tension here.

**Comment by tylerdanke** [comment]
This change fully processes my tension.

Sadly I no longer operate my organization with a single circle so I no
longer can test for stuff like this. I wonder if there are other clauses in
the Constitution that are an issue for single circle organizations.

On Dec 23, 2017 10:11 PM, "brianjrobertson" <notifications@github.com>
wrote:

Closed #103
<https://github.com/holacracyone/Holacracy-Constitution/issues/103>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/holacracyone/Holacracy-Constitution/issues/103#event-1400549352>,
or mute the thread
