### ISSUE TITLE
purpose description aligned with glassfrog (1.1a)

### ISSUE THREAD

**Issue by KoenVeltman** [holacracyone/Holacracy-Constitution#109]
In glassfrog (on the role page behind the question mark next to purpose on the top left) there is a pragmatic description of what a purpose is that I hear frequently quoted. propose to add it here for clarity and alignment with real life practice.

Suggestion for 1.1.a: `- **(a)** a **_“Purpose”_**, is the ongoing outcome for a role to achieve. Which is a capacity, potential, or unrealizable goal that the Role will pursue or express on behalf of the Organization. The purpose helps to define the "identity" of the role.`

**Comment by KoenVeltman** [comment]
if I did it correctly then this one is translated into a pull request..

**Comment by brianjrobertson** [comment]
This one doesn't make sense to me; I think the constitutional definition is better (and GlassFrog adds that last piece about identity for coaching - it's not part of the formal definition).
