### ISSUE TITLE
Diff to existing version 4.0

### ISSUE THREAD

**Issue by julianeroell** [holacracyone/Holacracy-Constitution#11]
Could you also upload the current version 4.0 of the constitution (maybe as a separate branch)? It would help me working on the development version if I could easily see the changes that it already has, compared to 4.0.

**Comment by brianjrobertson** [comment]
Sorry Martin, no plans to do that on our side - too much work for the gain.  And the diff would be so significant I'm not sure it'd be useful - it's just a mess of red-lined changes throughout, as it was nearly a rewrite.
