### ISSUE TITLE
cross link references (2.7)

### ISSUE THREAD

**Issue by KoenVeltman** [holacracyone/Holacracy-Constitution#111]
I find 2.7 one of the more complex articles in the constitution. In this issue I try to explain how I see it function. And with a few questions and suggestions for simplification. I dont have an answer yet. But happy to make a proposal when there is more input.

What could be a more natural way to reference the two circles at play in article 2.7 on how cross links work. I find it difficult to explain the cross link concept due to the technicality of the words in this article. Most notably "linked entity" and "target circle" . Could it be for example referred to as the "Host" and "visitor" or any other meaningful distinction we are used to in real life. Making it normal to talk about the cross links home circle and visiting circle? Or something else that can even visually represent the cross-link concept.

Why is the differentiation in 2.7.1 between cross link and cross-link role necessary? What would go wrong if we drop this distinction?

Is it useful to state that a functioning cross-link setup requires a policy that states the invitation (at least this is how I understand the beginning of 2.7) and what the role is accountable for (2.7.1)

Why is the third paragraph of 2.7.1 needed (`In this case,..., meaning the target circle`)? And if it is needed what does it do?

what is the most simple way to explain the authority of a cross link. I dont understand the meaning of the two paragraphs of section 2.7.3. Maybe this section would benefit most from a different name tagging than Target circle and linked entity.

Why is there a difference in the two paragraphs of 2.7.4 difference in how the cross link role can be changed? Potential benefit of starting with what the two circles both can do and only then stating what is different in what they can do in governance?

**Comment by brianjrobertson** [comment]
The entire Cross Links section was cut; closing this issue.
