### ISSUE TITLE
change name of article III and IV

### ISSUE THREAD

**Issue by KoenVeltman** [holacracyone/Holacracy-Constitution#112]
In general we are all used to talk about the tactical meeting process and the governance meeting process. But there are some elements of article III and IV that are not a process. For example article 4.3 about individual action.

Suggestion to drop the word process in the article name and just call it 
III Governance
IV Operations

**Comment by MiekeByerley** [comment]
I actually think there is a more fundamental issue underlying this and a number of other issues that have been raised. Which is the chronological order of document Flow. What I mean with this is that Article I deals with the smallest constructs (Role) then Article II deals with the expanding construct and connections (Circles, Sub-Circles, Crucial Roles) so the flow is small to large. Article III deals with the larger environmental Process (Governance) and Article IV deals with the more local Process, exactly the obverse flow large to small. Then Adoption the widest sphere of concern is tacked on the end. This rather awkward structuring method also extends to the flow of the Articles themselves. The result is complex Mental gymnastics on the part of the Reader. AS a very Quick outline I would propose the following:
Article I - Role Construct
  1.1
      1.1(a) Dealt with under Article I & II
      1.1(c) Dealt with under Article I & II
      1.1(b) Dealt with under New Article III 
  1.2
  1.2.1
  1.2.2
  1.2.3
  1.2.4
  1.2.5
[Carve out 1.3 and 1.4]
Article II Circle Construct
  2.1
     2.3
     2.2
     2.5
     2.7
     2.6
     2.1.1
     2.4
[Carve out 2.1.2, 2.1.3, and 2.7.3]
New Article III - Authority
     place all carved out sections under this (order to be determined)
Article IV (with new proposed Name - Operations)
    4.1  
    New Out-of Meeting Tactical process (to Mirror the Out-of-Meeting Governance Process)
    4.2
[Carve out 4.3]
Article III (with new proposed Name - Governance) 
    3.1
    3.2 Rename - Out of Meeting Governance Process
    3.3 
    3.4
    3.5
Article V - Adoption
    5.1
    5.5
    5.4
    5.2
    5.3

I hope this makes sense.
