### ISSUE TITLE
one article for testing proposals/objections (3.2.3 & 3.2.5)

### ISSUE THREAD

**Issue by KoenVeltman** [holacracyone/Holacracy-Constitution#119]
article 3.2.3 and 3.2.5 use a lot of the same language and describe (almost?) the same activities by the facilitator.

suggestion to simplify by first having articles 3.2.2 and 3.2.4 on the criteria for valid proposals and valid objections. and then have a single article on testing proposals and objections.

**Comment by brianjrobertson** [comment]
This was made irrelevant by issue #193 and the fix to that; there is no longer a "Testing Proposals" section, nor any need of one.
