### ISSUE TITLE
change order of governance articles (3.2 and 3.3)

### ISSUE THREAD

**Issue by KoenVeltman** [holacracyone/Holacracy-Constitution#120]
suggestion to put current article 3.3 governance meetings before 3.2 changing governance. 
Primarily because 3.2 is quite technical. and is easier understood when the meeting process is introduced. then for example testing proposals is much easier to understand.

**Comment by brianjrobertson** [comment]
Not so sure about this - the meeting process is built on top of the based threshold defined in 3.2, and you can use that even outside of the meeting process.  Anyone else have opinions here?

**Comment by MiekeByerley** [comment]
I agree with Koen on this one as the default is for Governance to happen
within a Governance Meeting, with Governance outside of Meeting requiring a
stated Policy. Thus the default is that Changing Governance (although
possible to do outside of the meeting) is a subset of the Governance
Meeting.

**Comment by brianjrobertson** [comment]
This is covered by #114
