### ISSUE TITLE
governance meeting attendance (3.3.1)

### ISSUE THREAD

**Issue by KoenVeltman** [holacracyone/Holacracy-Constitution#121]
simplify wording in article 3.3.1  in the sentence `The acting Facilitator... normally Core Circle members`.
Change the word `become` to `are regarded as`. Similar change in the second paragraph of this article

**Comment by brianjrobertson** [comment]
That replaces one word with three, and seems more complex, not simpler.  How does this help simplify?  Any other opinions on this one out there?

**Comment by julianeroell** [comment]
I am curious as to what prompted the suggestion. Koen, would you say more? 

To me, "becomes" is clear and strong, whereas "being regarded as..." seems more vague. I am thinking: "So I am _being regarded as_ a Core Circle member, but I _am_ not one (?), so might I _not_ have some rights that I would _usually_ have, if I _was_ a Core Circle Member?" 

If I know that I _am_ a Core Circle Member (for the duration of the meeting) then I don't have that thought process. :-)

**Comment by KoenVeltman** [comment]
@martinaroell good question. its been more then a year since I posted this. 
re-reading it, "become for the duration of the meeting" does sound very similar to "are regarded as core circle members".

I think I posted this that "regarded as" fits more the temporary nature than "becomes". but with "for the duration of the meeting" already in the sentence it might not make a huge difference.

**Comment by brianjrobertson** [comment]
Dropping this one...
