### ISSUE TITLE
facilitator stops commenting (3.3.5)

### ISSUE THREAD

**Issue by KoenVeltman** [holacracyone/Holacracy-Constitution#123]
it is mentioned in a few of the steps that the facilitator will stop all out of process communication. For me the repetition (in slightly different terms) for me weakens the strong role the facilitator has here to hold the process.

Suggestion to take it out of each of the sub points in 3.3.5 a-f. and highlight it more at the start of 3.3.5 in language like `The facilitator must enact the integrating decision making process. The facilitator will use the following process and will not allow any comment or interaction not aligned with these exact steps:`

**Comment by brianjrobertson** [comment]
I tried to find a way to do this, but any potential change I found seemed to lose clarity of rules or weaken the clear stance the facilitator must take; thus, I'm dropping this issue.  If someone else wants to take a stab at it and submit a pull request for evaluation, by all means feel free...
