### ISSUE TITLE
integrative election process different proposal order (3.3.6e)

### ISSUE THREAD

**Issue by KoenVeltman** [holacracyone/Holacracy-Constitution#124]
suggest to change the order of options the Facilitator has when there is a tie in votes. To focus on the more likely and potentially meaningful proposal given that an election was called for. E.g., although original option (i) to blindly select someone is the simplest option I would put it it last. 

(iii) if only one of the tied candidates has nominated himself or herself, propose that person; or 
(iv) go back to the previous step and require each participant who nominated someone other than a tied candidate to change that nomination to one of the tied candidates, then continue back to this step and re-apply its rules; or
(ii) if the person currently filling the Role is among those tied, propose that person; or 
(i) blindly select one of the tied candidates randomly, and propose that person.

**Comment by brianjrobertson** [comment]
I think (iv) needs to stay last to avoid confusion and readability challenges; it also seems to be by far the least likely option to get used in my experience, and usually for good reason I think. The other reorderings make sense, so I'm implementing those.
