### ISSUE TITLE
single description of role duties (1.2 and 4.1)

### ISSUE THREAD

**Issue by KoenVeltman** [holacracyone/Holacracy-Constitution#128]
Technically filling a role is equivalent to being a circle member (core or non-core). As every role is part of a circle by definition of article II. You cannot fill a role without being part of a circle. 

Article 1.2 describes the responsibilities of role filling. Article 4.1 are duties of circle members (when filling a role). Also in the actual text of the two articles there are cross-references and overlap in text.

What would a single article look like. And where would it fit best? This would create an amazing reference for people to have a single spot to look up what is expected of them when filling a role.

**Comment by brianjrobertson** [comment]
Done.
