### ISSUE TITLE
invitations governance vs tactical

### ISSUE THREAD

**Issue by KoenVeltman** [holacracyone/Holacracy-Constitution#129]
there is a difference in the text used to invite non circle members. between the governance (3.3.1) and operations (4.1.4) articles.

I have a sense of why the description is different (the governance invitation is only for governance meetings, where tactical can happen any time). But it is not made explicit why 4.1.4 needs to use a slightly different text than 3.3.1. 

I would either make it the same text for invitations. or make explicit (and self-explenatory) why tactical invitations are different from governance invitations

**Comment by brianjrobertson** [comment]
I believe this is effectively resolved now...
