### ISSUE TITLE
Merge Rep Link appointment from sub-circle & multi-filled role 

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#132]
Sub-circles and partially-represented multi-filled roles (i.e. those with some appointments excluded as Core Circle Members) are effectively the same concept, yet selection of a representative works differently between the two, and each has issues:  The sub-circle Rep Link selection process is hard-coded (exactly one rep required, selected via integrative election process), which ensures a reasonable process for selection, but leaves no room for adapting to local conditions that might warrant variations.  On the other hand, the multi-filled role representative selection process is almost entirely open, which allows plenty of room for adaptability to local conditions, but also allows breaking a clear chain of effective tension processing (e.g. lead link autocratically chooses a representative that other role-fillers have trouble processing tensions through).  So, as someone dependent on selecting such a representative, I'd like these two processes to be merged into one process (used in both cases) that's somewhere between these two extremes, so that we get the benefits of both without the downsides of either.

**Comment by MiekeByerley** [comment]
Hi Brian,

Would this proposal not resolve your tension? I drafted this up already
back in July 2015 and submitted it, I was kindly informed that it was
received and that it would be submitted but since then I have heard nothing
back.

Very Kind Regards
Mieke

**Comment by brianjrobertson** [comment]
Hi Mieke - What proposal are you referring to?

Brian J. Robertson
HolacracyOne, LLC
http://holacracy.org http://holacracy.org/

See My Roles & Accountabilities » https://glassfrog.holacracy.org/person/47

Check out my book: http://holacracybook.com » http://holacracybook.com/

**Comment by MiekeByerley** [comment]
Hi Brian,

I attached to the email for your convenience :) are you able to see that? I
can attach it again if you like. It was to do with almost exactly what you
are highlighting.

**Comment by brianjrobertson** [comment]
Attachments are stripped out when you e-mail via Github like this, so it’s not coming through; e-mail me directly via brian@holacracyone.com.

Brian J. Robertson
HolacracyOne, LLC
http://holacracy.org http://holacracy.org/

See My Roles & Accountabilities » https://glassfrog.holacracy.org/person/47

Check out my book: http://holacracybook.com » http://holacracybook.com/

**Comment by MiekeByerley** [comment]
Hi Brian,

I have just done what you suggested so hopefully you have it.

**Comment by Roflcopterpaul** [comment]
I think merging these two together is an amazing idea, and I would suggest using the Rep Link to be the go-to for multi-filled Roles. As an elected Role, it is usually much easier for people to feel comfortable and confident going to them to process stuff instead of having to implicitly figure out who will do it each time, go to their LL, etc. This also drastically simplifies the process by just saying, "They use the RL to process stuff". Also, it's fairly simple to put a process into place in a Circle to give them more freedom in being able to attend meetings, have extra representation, etc.

**Comment by brianjrobertson** [comment]
Paul, can you clarify what you mean here: For who to use them as the go-to for what?  Thanks!

**Comment by Roflcopterpaul** [comment]
Sorry. I meant that the Rep Link could then be the Role that brings up Tensions on behalf of multi-filled Roles and minor Roles.

**Comment by brianjrobertson** [comment]
Makes sense and agreed!

**Comment by julianeroell** [comment]
I find the election process not too complicated and the limitation (only one Rep Link resulting) not too limiting. (The elected Rep Link could always get someone else in to help them process a tension (Article 3.3.1) if they needed, couldn't they?)

So if the choice was to use elections as a default (and thereby basically treating multi-filled roles like subcircles as I see it), that would work for me.

**Comment by brianjrobertson** [comment]
Note:  This issue is a subset of Issue #168.
