### ISSUE TITLE
Exchange the term "Accountability" for either "Duty" or "Responsibility" dependant on context.

### ISSUE THREAD

**Issue by MiekeByerley** [holacracyone/Holacracy-Constitution#133]
The reason for this is the position of power held in each of these terms. Accountability, denotes that someone or something is held Accountable, which requires an outside force being applied on that person or thing making it enforceable on the holder. Example "You Account for your actions" but to who? it requires a recipient. Duty and Responsibility do not stem from this same centre, they both require no answer to another. Example: "We take responsibility" we take ownership without it being enforced on us. My recommendation would be to use Duty in context to Organizational Constructs (e.g. roles etc) and Responsibility in context to Partners (e.g. Core Circle Members etc))
Duty is the formalised version of Responsibility so more apt within the Context of the Constitution:
NOUN
1.a moral or legal obligation; a responsibility: 
"it's my duty to uphold the law" · 
synonyms: responsibility · obligation · commitment · obedience · 
2. (duties) a task or action that one is required to perform as part of one's job: 
"the queen's official duties" · 
synonyms: job · task · chore · assignment · commission · mission ·

**Comment by julianeroell** [comment]
I like this a _lot_ AND would **prefer "Responsibility**" over "Duty" at any time:

A "Duty" seems like something that I _must_ do, while a "responsibility" gives me the "duty" (so to speak) to pay attention and _then decide_ wether to act or not. This seem more in line of what an "accountability" currently is. (English-non-native speaker here.)

I like "responsibility" because it emphasises relationships: When enacting an accountability/responsibility, I am actually _responding_ to an organisational need. The role creation was originally a _response_ to sensing a tension.

 "Accountability" always smelled of bureacracy and control (blue) to me , whereas "responsibility" connotates more community- and mutual-accountability based (green).

Big thumbs-up to this proposal.

**Comment by brianjrobertson** [comment]
Hmm, this one doesn't resonate with me; "responsibility" has a much more personal connotation to it than "accountability", which is more neutral and technical, and that's a major advantage in nudging people towards the paradigm shift that Holacracy aims for.  On top of that, the personal connotation of "responsibility" has an edge to it, of one being "to blame" ("irresponsible") if one doesn't do the thing (the definition of "responsibility" references blame, where "accountability" does not).  Yet in Holacracy it's a perfectly valid "accounting" of an "accountability" to say you consciously de-prioritized and dropped it - it's not your responsibility to do it, just to consciously consider and account for it; "accountability" is less heavy/weighty than "responsibility".  And "duty" is even stronger than "responsibility" in this regard - you must do it, as Martin says.

So, I'm gonna need to hear a lot more perspectives pitching for this change further to consider integrating it...

**Comment by julianeroell** [comment]
Thank you, Brian! I can follow that perspective.

**Comment by MiekeByerley** [comment]
I do understand where you are coming from Brian :) Let me see if I can refine it.

I think that as a partner (person) we are accountable for our assigned Roles, however the Role has a Responsibility and Duty to the Organisation. (of which it is a construct). It is the degree of separation that differentiates the term. E.g.  I am accountable for my role as a Mother (motherhood is conferred to me by a child), that role of Motherhood has a responsibility and duty to the child, so as a (functioning in the Role of) mother I am accountable for the responsibility and duty to my child. 

See I am only, accountable for those responsibilities and duties when acting in the capacity of a Mother and blame can only be apportioned to my person if I fail to be accountable for those self same aspects. That is the reason why a parent cannot be held culpable for the actions of a child, unless it is proven that the action was a direct result of a lack of accountability for the responsibility towards the child.

Interestingly your opening paragraph stipulates this same principle:
"Ratifiers and anyone else who agrees to take part in the governance and operations of the Organization (its “Partners”) may rely upon the authorities granted by this Constitution, and also agree to be bound by its duties and constraints."

**Comment by MiekeByerley** [comment]
P.s. Irresponsibility is the trait of lacking a **sense** of responsibility (lacking awareness) and not being accountable for your actions. So it is not a lack of responsibility but a lapse of accountability that makes one culpable and to blame.

**Comment by brianjrobertson** [comment]
Not seeing other voices pushing for this, and it's still not resonating with me, so I'm dropping this one.
