### ISSUE TITLE
Usability issue: Rules for special governance meetings are not obvious

### ISSUE THREAD

**Issue by tensiondriven** [holacracyone/Holacracy-Constitution#136]
Context: During a special governance meeting, I was trying to determine what the rules are that distinguish special governance meetings from regular governance meetings.  To find out, I had to read the entire section 3.3

Under 3.3:

> … if the meeting was scheduled at the special request of one participant, the Facilitator must place all agenda items raised by that participant before any raised by others, unless that participant allows otherwise.

Usability-wise, its it feels a bit disconnected that “special governance meetings” are mentioned under 3.3 and then under 3.3.4.b but these citations don’t reference each other - if a parenthetical was added,

> In addition to any regular, recurring Governance Meetings the Secretary schedules, the Secretary is responsible for scheduling additional special Governance Meetings promptly upon request of any Core Circle Member. ​_(See 3.3.4.b for rules related to special governance meetings.)_​

this would solve my tension - I would find the first reference to a special governance meeting, and be able to quickly find the section that clarifies the rules for them.

**Comment by brianjrobertson** [comment]
I get the issue, but the solution seems worse: it adds a reference (and a forward one at that) and a parenthetical clause, both of which are things I'd like to avoid as much as possible.  Any other ideas?

**Comment by tensiondriven** [comment]
Perhaps move

> In addition to any regular, recurring Governance Meetings the Secretary schedules, the Secretary is responsible for scheduling additional special Governance Meetings promptly upon request of any Core Circle Member.

and

> Further, if the meeting was scheduled at the special request of one participant, the Facilitator must place all agenda items raised by that participant before any raised by others, unless that participant allows otherwise.

to a new section, 

> 3.3.8. Special Governance Meetings
> 
> In addition to any regular, recurring Governance Meetings the Secretary schedules, the Secretary is responsible for scheduling additional special Governance Meetings promptly upon request of any Core Circle Member.
> 
> [In a Special Governance meeting], the Facilitator must place all agenda items raised by that participant before any raised by others, unless that participant allows otherwise.

That's all I can think of right now - this would group the concerns together.

**Comment by brianjrobertson** [comment]
That would remove the main concerns; though still, is the overhead of adding a section worth it for the clarity of putting those two together?  Not saying it isn't, but that's the open question now.  Anyone else have thoughts on that?  Yay/nay?

**Comment by ChristelHofman** [comment]
3.3.4b is clear enough for me. Although I can feel the tension if you start searching for "special governance meeting" in the constitution it is not immediatly clear how it works.

**Comment by Roflcopterpaul** [comment]
I personally think it makes the most sense as-is. However, for the sake of searching with ctrl+F, it might help if you reword the last sentence of 3.3.4 (b) to read:

**"Further, if in a special Governance Meeting scheduled at the request of one participant, the Facilitator must place all agenda items raised by that participant before any raised by others, unless that participant allows otherwise."**

This way, you can easily find it by searching "special governance".

**Comment by brianjrobertson** [comment]
Thanks @Roflcopterpaul, I'm going with that and calling this good enough.
