### ISSUE TITLE
Make "Golden Rule" more clear, up-front, and direct

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#137]
Often people miss or don't get the gravity of the "Golden Rule" of Holacracy in Section 1.3, or the related 4.1.5; these could be more clear and more "front & center", to really hit the point and leave less room for ambiguity or oversight.

**Comment by ChristelHofman** [comment]
Hi Brian, I totally agree. When people start reading / using the constitution 4.1 they first see what responsibilities they have in 1.2 The constitution could start with the freedom a role filler has (1.3 and in an more limiting way in 4.1.5) and then how they can make this freedom transparant to others (1.2) or how it is limited.

**Comment by bernardmariechiquet** [comment]
Brian, i fully agree too  - happy this could evolve and doing so, increase the Ferrari powershift. However, I would also kind of bridge more Section 1.3 with Section 2.1.3 at least for the last part of such Section, as I can observe it's difficult for people to understand their power without explaining also their authority regarding expenses and contracts.

**Comment by julianeroell** [comment]
4.3 "Individual Action" is also related.

**Comment by Roflcopterpaul** [comment]
I'd be curious if our approach would work in the way we usually explain it (simplified, of course) to new people:

**"As a Partner assigned to a Role, you have the authority to execute any Next-Actions you reasonably believe are useful for enacting your Role’s Purpose or Accountabilities. However, you cannot break any rules as defined by this Constitution or any Governance defined by your organization."**

Right now, 1.3 only references the Domain section which adds a lot of complication and doesn't fully (at least not easily) define that the other rules still apply. Saying you can virtually do anything in your Role as long as it doesn't break any of the other rules simplifies it and really helps get the point across. When teaching this piece, we basically just say, "You can do whatever you want if it makes sense in your Role, except break the rules." It really helps people to understand just how much power they have in this new system.

**Comment by brianjrobertson** [comment]
Interesting - it doesn’t cover that you can’t violate domains of parties outside the organization, where the current version is clear on that point, though I like the direction of it and the simplicity, and I’ll use it as a starting point when drafting an update.

**Comment by rebeccabrover** [comment]
When presented verbally, the phrase I hear most is "you have the authority to **take** any next-action". It's a subtle difference but take vs. execute is powerful in it's increased simplicity.

**Comment by bernardmariechiquet** [comment]
@Roflcopterpaul I love the simplicity of what you suggest *AND* to add on @brianjrobertson comment, there is a key part into the current phrasing **"or another sovereign entity"** for covering the outside of the Org. And may be this essential part may be covered elsewhere.
