### ISSUE TITLE
Section 3.2.6 (a) Rules for Integration

### ISSUE THREAD

**Issue by bernardmariechiquet** [holacracyone/Holacracy-Constitution#140]
I would suggest to modify the end of Section 3.2.6 (a) Rules for Integration by _in Section 3.2.4_ instead of _in this Section_ because it does not seem to be the case as I understand what a Section is.

**Comment by brianjrobertson** [comment]
Hmm, it is within the broader Section (3.2), just not the specific sub-section 3.2.6, so I think it could work as-is, but I do see that it could be confusing.  Yet, adding a specific section reference also adds to the feeling of the document being "heavy" and complex - generally, I try to avoid numbered cross-references whenever practical.  So, my question now - is it better to:

1) Keep it as-is, despite the potential confusion.
2) Replace with "in Section 3.2.4" as suggested, despite the addition of a numbered cross-ref.
3) Remove the reference entirely and leave the sentence as "... if it fails to meet the required validity criteria".

Any opinions?

For reference, [here's the section](http://www.holacracy.org/constitution#art326) we're discussing - see part (a).

**Comment by bernardmariechiquet** [comment]
Again I do think the notion of Section/Sub-Section is not referenced in whole document. So I would suggest to explicit what's in your mind.
People expect/use this document to assist them in the day to day referencing of the rules.
Now all that said, I think option 3 is fine here and workable even from a UX perspective.

**Comment by brianjrobertson** [comment]
See my comment on Issue #141 re the reason for not using "sub-section" in the document.

Curious if anyone else reading this has opinions on which of those three options above might be best?  It's a question not just for this specific case, but it could inform other use-cases as well...

**Comment by Roflcopterpaul** [comment]
For 3.2.6 - Upon first looking at it, I do wonder if "in this section" means that part I am reading right then, or something else somewhere in Section 3. I think specifying "in Section 3.2.4" is much more clear and allows for those reading to more quickly find exactly what they need.

Whereas in 4.1.3 (a), when it says, "... described in this section", it means all of 4.1.

So, to me, I would vote use different descriptions as needed. When referring to a specific section, reference it by number. When referring to the multiple sections covered before and after as a whole, stick with "in this section". To Bernard-Marie's suggestion of "sub-sections", I think if you ever need to get that granular, it would be easier to just reference the number - So, saying, "as defined in 4.1.2 (a)".

**Comment by brianjrobertson** [comment]
Hmm, I’ll submit a new issue to review all Section references and revise for clarity whenever practical.  Thanks!
