### ISSUE TITLE
Lengthen Duty of Transparency

### ISSUE THREAD

**Issue by Roflcopterpaul** [holacracyone/Holacracy-Constitution#143]
I feel that Duty of Transparency (4.1.1) should be lengthened to be transparent about even more, such as intent, what Role you are making a decision from, answers to any clarifying questions if you have the information, etc. Right now, you only _have_ to be transparent about very specific things, but it should be virtually anything work-related unless there are very valid reasons you couldn't be transparent about it. Even in that case, the Duties are Circle-specific, so there will likely never be a time when you need to keep information confidential from fellow Circle members.

**Comment by brianjrobertson** [comment]
Do you have real examples of where the lack of this got in the way, or is this an improvement suggested from idea/theory vs an experienced lack?

**Comment by Roflcopterpaul** [comment]
?I have no real examples because we've always just taught that you should be transparent about _everything_. It's just a suggestion to cover more situations and simplify it, but I've never had a concrete experience where the lack thereof has caused an issue.

Paul "Captain Anomaly" Walker
Human Stick Figure
All-Around Holacracy Baws
v View My Roles v
[Internalhttps://glassfrog.holacracy.org/people/9072] [Externalhttps://holacracy.zappos.com/public/myRoles/3BeNLHll2jAUuO0I8m3UNQ.zap]

**Comment by brianjrobertson** [comment]
Gotcha.  As a general approach, I make sure the Constitution evolves in the same way governance does within a circle - to be considered, a potential change needs to have a real example of where it would resolve an experienced tension, and not just from principle.  So, keep an eye out and re-open if/when you see such a case.
