### ISSUE TITLE
Contradiction between 3.2.1 and 3.3.3 with implications for 4.2.3(d)

### ISSUE THREAD

**Issue by MiekeByerley** [holacracyone/Holacracy-Constitution#145]
Sub-Section 3.3.3 states that _"The Facilitator must build an agenda of Tensions to process in a Governance Meeting by soliciting and capturing agenda items from all participants. This must be done within the meeting and not beforehand,"_
This seems to contradict or make impossible the ability under Sub-Section 3.2.1 to _"Alternatively, a Core Circle Member may distribute a Proposal to all other Core Circle Members asynchronously, out side of a Governance"_.

If according to 3.3.3 a Tension cannot be raised (solicited and captured) outside of a Governance Meeting how can as per 3.2.1 a Proposal be distributed outside of a Governance Meeting especially if it is then requested to be escalated to a Governance Meeting?

Secondly if this ought to be possible for Governance Meetings should it not be the same for Tactical Meetings as well? Why would that be different, why is out-of-meeting Governance possible but out-of meeting Triage not?

**Comment by brianjrobertson** [comment]
That quoted text only limits how the Facilitator must build the agenda, not anything beyond that.  To your question at the end, that is not only possible but the normal state of things; consider asking for more clarification there on the Community of Practice...
