### ISSUE TITLE
Request for processing Role's Purpose to added into section 4.1.2

### ISSUE THREAD

**Issue by bernardmariechiquet** [holacracyone/Holacracy-Constitution#148]
I noticed a kind of inconsistency/lack of symmetry between section 1.2.2 (a) http://www.holacracy.org/constitution#art122 :  
**1.2.2 Processing Purpose & Accountabilities
You are responsible for regularly considering how to enact your Role’s Purpose and each of your Role’s Accountabilities, by defining:**

And section 4.1.2 http://www.holacracy.org/constitution#art412 : 
**4.1.2 Duty of Processing
You have a duty to promptly process messages and requests from your fellow Circle Members, as follows:
(a) Requests for Processing: Other Circle Members may ask you to process any Accountability or Project on a Role you fill in the Circle. If you have no Next-Actions tracked for it, you must identify and capture a Next-Action if there are any reasonable ones you could take. If there aren’t, you must instead share what you’re waiting on. That must be either a Next-Action or Project tracked by another Role, or a specific event or condition that must happen before you can take further Next-Actions.**

So, I would suggest to add to 4.1.2 (a) "Requests fro Processing: Other Circle Members may ask you to process any Purpose or any Accountability or..." so that I may ask a fellow Circle Member to consider how to enact one of its Role's Purpose (and not only Accountabilities.)

Does it make sense?

**Comment by brianjrobertson** [comment]
I'm not so sure about this; it was intentional, because I don't know if that threshold makes sense for Purpose.  Do you have an actual case where you wanted to use that duty for a purpose?

**Comment by bernardmariechiquet** [comment]
Yep. I've noticed with quite a number of people that they are still waiting on new accountabilities into their roles to initiate new activities useful to express the purpose of their roles. Usually these new accountabilities are set in gov. by Lead Link sensing the need for such new activities, which is great on one side because it increases the capacities of the circle. On the other hand, there is here still room/value for the org. to get more from role fillers abilities to sense "into the purpose" by holding space for them to at least ask themselves what they could define as new action/project to express the purpose of their roles. If not I observe that many people are just considering their role accountabilities. I'm not saying here that we may expect from everyone to become an entrepreneur able to tune into their role's purpose to discover new activities useful to express the purpose, but at least, we may offer that space on behalf of the org. to get as much as possible from human abilities to create/innovate that way, for those who just need to give it a try.

**Comment by brianjrobertson** [comment]
Got it; I'll queue it up for v5.0.
