### ISSUE TITLE
Grammatical 'Person' of the Constitution

### ISSUE THREAD

**Issue by MiekeByerley** [holacracyone/Holacracy-Constitution#15]
I recognise that what I am raising, is in relation to one of the fundamental shifts of the Constitution. I don't know the driver or motivation for this change all I can mention is the Tension this has created for me. 

One of the fundamental concepts of Holacracy I always come back to is the degree of separation between Organisation and it's members, to quote HolacracyOne "Of the Company, through the People, for the Purpose". The Constitution pertains to the Organisation as per the first line under the Preamble "This Constitution defined rules and processes for the governance and operation of an Organisation". The Constitution does not pertain direct to the members of the Organisation, but is a condition of membership. 

What I mean with this is that in order for the principles of Holacracy to work, an Organisation cannot control the members (this is dictatorship), but has an obligation to control its functions, roles, processes (this is stipulation). The first is directed at a PERSON (removes freedom) the second is directed at a system CONSTRUCT (enhances freedom).

I mention this as the change in Grammatical Person from 3rd person to 2nd person shifts the direction of the Constitution from the Organisation (system constructs) to the Members (persons). Where the 3rd person clarified the distinction between Organisation and Member (the Organisation is not the Members and the Members are not the Organisation), which our Human Nature has a hard time keeping separate, the 2nd person now muddies and risks the age old problem of "roles defining a persons identity" and so power struggles.

By changing the Grammatical Person of the constitution you change the entity vested with power. Power in Holacracy is vested in the roles (system constructs) to ensure proper apportioning and eliminate power struggles. By changing the constitution to 2nd person you vest the power squarely back in People.

This is highlighted in the Grammatical Person, of 2nd person, introducing terms such as "You Must, You Shall, You Need, You cannot, You will, You have, You may, You may not" all of which are directed to PERSON and control a person. I don't need to mention the effect or the reactions this induces within an organisation.

**Comment by MiekeByerley** [comment]
I'll just add this bit that came from another discussion I had on another platform. Someone very wisely once stated that from Structure comes true Freedom, it is this which Holacracy strives for, freedom of evolutionary purpose of the Organisation. By doing this it enables freedom for the organisation as an autonomous entity with it's own purpose, function and goals within the world and it provides freedom to the people though letting them be people and not parts of a System. It creates what is better known as an Autonomous Alliance, and explains the importance of the separation between person and role.

**Comment by brianjrobertson** [comment]
The use of "you" is always preceded by "As a Partner" or "As someone filling a Role" or whatever, so it's always in context, and always dependent upon the agreement of someone to fill roles and align with these rules.  In short, despite the use of "you", if you actually read what's being said, it's not at all changing what's being governed in the slightest - it's just making it more accessible and readable by following some guidelines in the plain-english legal writing movement around speaking directly to the reader vs. making someone hold and juggle more concepts in their head to get the point.

**Comment by MiekeByerley** [comment]
Apologies, this point originated from a couple of discussions within FB and LinkedIn Groups about Validity of Policies etc. when directed at a person, the difference of understanding came from a tension (not mine) that a person was dictated to rather than having the option to self-manage. Changing the statement to a Third person Context resolved the Tension instantaneously, while no matter how it was  rephrased in 2nd person, it never managed to entirely resolve the issue. I had raised it, as I had come across the difficulty several times and the clearest way to resolve them was to keep to 3rd person.

**Comment by brianjrobertson** [comment]
Cool!
