### ISSUE TITLE
Ambiguity of # people who can fill the Lead Link role

### ISSUE THREAD

**Issue by Nick-Osborne** [holacracyone/Holacracy-Constitution#151]
Seems to me that there is some implicitness (is that even a word?) in the language around the number of people who can fill the LL role in the constitution, and that if its unconstitutional for more than one person to fill this role, then this could be more explicitly articulated in the constitution. I also have had questions from a client early in an Implementation about co-filling the LL role

**Comment by bernardmariechiquet** [comment]
Interesting. Any specific section you're referring to ? My interpretation of section 2.2 is that the Lead Link is filled by one person - "The person filling the Lead Link Role, while acting in that capacity, is referred to as the Circle’s “Lead Link”. And there are other pieces in other sections like 2.3.2 or 2.4.2 which grounds my interpretation.

**Comment by gmitterer** [comment]
I have always interpreted "the person" in Section 2.2 like Bernard Marie as "one person".

**Comment by Nick-Osborne** [comment]
Well, the constitution is written in many places assuming a single Lead Link role-filler; shows up in language in several places like “the Lead Link”.  And §2.6.3 says “A Circle’s Lead Link may assign someone to fill the Lead Link Role for each Sub-Circle” - not “one or more” but just “someone”.

But, there's enough ambiguity there for more than one person from organisations new to or practicing Holacracy to query with coaches about whether the LL role can be filled by more than one person, and there's nothing in the constitution which explicitly says that it can't be. So this request is to make that more explicit.

**Comment by brianjrobertson** [comment]
I'm submitting a temporary "fix" for this, although not a great one, because other upcoming changes will very likely shift this to allow multiple role-fillers anyway.
