### ISSUE TITLE
Article 2.4 says Lead Links may assign people to roles but does not mention removing people from roles

### ISSUE THREAD

**Issue by tensiondriven** [holacracyone/Holacracy-Constitution#154]
Ref: http://www.holacracy.org/constitution#art24

>The Lead Link of a Circle may assign people to fill Defined Roles in the Circle, unless that authority has been limited or delegated.

proposed change:

> The Lead Link of a Circle may assign or remove people to fill Defined Roles in the Circle, unless that authority has been limited or delegated.

The current text doesn't make it clear that Lead Links have the authority to remove people from Roles, which is an important part of the power structure of Holacracy.

**Comment by brianjrobertson** [comment]
The proposed change makes sense, although it's not proper English, so I would accept it in spirit but not as currently written.  That said, I wonder if the entire clause should be cut?  It's definitely not technically needed, given the Domain on the Lead Link role, although I wonder if it's still useful to have in the main text for clarity...?

**Comment by gmitterer** [comment]
Change makes sense to me. I would opt for keeping the sentence although it's technically unneeded. But it sets a higher bar for beginners by requiring a more profound understanding of mechanics (in order to derive that acc from the domain). Which is especially for the Lead Link role, which causes major struggles in the beginning, not helpful IMO. In addition it is good practice IMO to combine a domain with an Acc on how to act out this domain - otherwise it seems parked without any further expectations tied to it.

**Comment by bernardmariechiquet** [comment]
Would opt for removing the entire clause as Lead Link has got a clear accountabilty for assigning and re-assigning other Partners (see appendix A). The existence of such clause creates some weird redundancy IMO.

**Comment by gmitterer** [comment]
interesting, maybe i had a misunderstanding. my understanding was that @brianjrobertson considers to cut it from the accountabilities as well or just from the art 2.4. if it's just redundant and remains an Acc then I would underline @bernardmariechiquet's statement to cut it.

**Comment by brianjrobertson** [comment]
Yep, I meant just from 2.4.

**Comment by julianeroell** [comment]
I support removing the clause from 2.4. Well spotted!

2.4.2 could also use a nudge: "A Lead Link may assign multiple people..." could change to "Multiple people may be assigned..." or so (removing the "Lead Link" from there, as it may well be a different role, or a different process that does the role assignment.)

**Comment by bernardmariechiquet** [comment]
Love it @martinaroell

**Comment by brianjrobertson** [comment]
This has been addressed by a prior change.

**Comment by quikvans** [comment]
Is it possible to extract the "role assignment" accountability from the lead link and give it to a role within the circle?

**Comment by brianjrobertson** [comment]
@quikvans This forum isn't intended for Holacracy rule/practice questions like that; try posting on the [Community of Practice Forums](http://community.holacracy.org) instead.
