### ISSUE TITLE
Enable Async Elections

### ISSUE THREAD

**Issue by tylerdanke** [holacracyone/Holacracy-Constitution#155]
As a member of a circle that is difficult to get together at the same time and place I want feature the constitution to clarify if we can hold elections asynchronously or not so that benefit we can hold elections simply and easily with getting all circle members as able to participate if they so choose regardless of if they are able to be at a specific time and place.

**Comment by julianeroell** [comment]
I have the same need.

**Comment by brianjrobertson** [comment]
To consider:  Move election process out of Governance article and into Appendix, so it can be referenced more easily outside the context of Governance.  At the least, move it out of the Governance Meeting section and into its own top-level section within the Governance article.
