### ISSUE TITLE
Amend Facilitator Acc of "Auditing..."

### ISSUE THREAD

**Issue by gmitterer** [holacracyone/Holacracy-Constitution#156]
We have come across different interpretations of the Facilitators Acc "Auditing the meetings and records of Sub-Circles as needed, and declaring a Process Breakdown upon discovering a pattern of behavior that conflicts with the rules of the Constitution".
Especially the question if this can be expected (eg to derive a project as part of Fac weekly review) to audit records of sub-circles on an ongoing basis was questioned. The marker "as needed" indicates that it's somehow based on a specific tension rather than implying a "kind of" controlling mentality by auditing records of the sub on a continuous base.
It could be a bit clearer, maybe by substituting "as needed" by "on request" or a similar expression that helps to understand that there is a triggering event/tension.

**Comment by brianjrobertson** [comment]
Makes sense to me; please feel free to submit a pull-request with the change.

**Comment by brianjrobertson** [comment]
Implemented by #157.
