### ISSUE TITLE
Clarification in 2.3 and 2.3.1

### ISSUE THREAD

**Issue by gvandegrift** [holacracyone/Holacracy-Constitution#158]
In 2.3.1, I think it would be helpful to be more explicit about the fact that Lead Links of sub-circles are "core circle members".  I believe it is implied by 2.3.1a since 2.2.1 says "...just as if the Circle were only a Role and the Lead Link filled that Role."  Why not be more explicit by changing 2.3.1a to be "each Partner filling a Defined Role in the Circle (including Lead Links of sub-circles)" or to add 2.3.1e "Lead Links of sub-circles"?

**Comment by bernardmariechiquet** [comment]
I would not do so as from the Super-Circle perspective, a Sub-Circle is just a Role per definition at first sentence of 2.1. So from the Super-Circle perspective, any role filler is a *Core Circle Member* which is also true for Roles being themselves a Sub-Circle. Modifying 2.3.1 would IMO introduce some confusion as this Section is defining Membership within a Circle, and introducing Lead Links of Sub-Circles would change the frame of reference by introducing an holarchy which is not needed here.

**Comment by brianjrobertson** [comment]
Hmm, I appreciate the extra clarity, although I hate to add more words & complexity that isn't technically needed unless the addition is highly useful.  Anyone else have opinions here?

**Comment by karilen** [comment]
Seems unneeded though maybe people are confused because "lead link" is a pre defined role? I have not heard of others having this issue, though they could be.
This language would be the confusing part I suppose:
(a) each Partner filling a Defined Role in the Circle;

**Comment by gvandegrift** [comment]
I may very well be the minority (only?) opinion on this.  We haven't actually started our holacracy yet.  
We're doing lots of prep which got me to planning who to invite to Governance meetings ("core members"), so I looked at section 2.3.  I thought sub-circle Lead Links were supposed to be in Governance, but after reading 2.3, I began to question myself.  I was pretty sure I understood that Lead Links were seen as "filling a Defined Role" (the Defined Role being the sub-circle); but I wasn't 100% confident based on my reading.  A quick email to someone cleared it up.  Thinking that others might be faced with the same confusion, I figured I throw it out here.  All of that said, I definitely appreciate the idea of keeping the words to a minimum in a document like this.

**Comment by bernardmariechiquet** [comment]
To add on that, I would suggest (and I have no idea where) to make explicit that a Lead Link Role of a Circle is a pre defined role of such Circle, and a Defined Role into the Super-Circle (This Role being a Circle).  This may help better understanding this holarchy concept. May be this could be added at the beginning of section 2.2, or may be there should be something re holarchy into the Constitution.

**Comment by brianjrobertson** [comment]
I believe this is now clear given other changes.
