### ISSUE TITLE
Not clear who can create metrics, checklist items

### ISSUE THREAD

**Issue by tensiondriven** [holacracyone/Holacracy-Constitution#159]
As a circle member who has taken a project to define and report on a Metric, I'm confused about my authority to create the metric in the circle.  According to "4.1.1 Duty of Transparency":

> ‘You must also track and report on any metrics assigned to your Roles by the Circle’s Lead Link, or by any other Role or process granted the authority to define the Circle’s metrics.’

1) it is confusing to me that the *authority to create metrics* is listed under "Duty of transparency"

2) it is confusing that metric creation is mentioned here, but checklist item creation is not mentioned

This could be clarified a bit:

‘...You must also track and report on any metrics assigned to your Roles. Metrics and Checklist Items are assigned to Roles exclusively by a Circle's Lead Link(s), unless this authority has been changed by Policy.’

But I'd still like to see the rules for who can define these things moved to a more obvious section.

Related to https://github.com/holacracyone/Holacracy-Constitution/issues/73 which proposes to allow any Role to assign a Checklist Item or Metric to another Role.

**Comment by brianjrobertson** [comment]
The authority to create metrics isn't listed under Duty of Transparency; there are no restrictions on who can create metrics - anyone can.  It's just that you don't have a duty to do anything with those defined by other roles, just those defined by the Lead Link.  So, seems appropriate as-is to me, and useful in helping with the broader mindset shift (where authority exists until limited, and that doesn't affect anyone else unless another duty says it does).

**Comment by tensiondriven** [comment]
The title of this ticket is still accurate - "Not clear who can create metrics, checklist items"

You just said, 

> there are no restrictions on who can create metrics - anyone can.

but that's not clear to me anywhere in the Constitution.

So, in my mind this is still a problem, and is a current tension for me as I have a project to create a metric, and I'm not clear if I'm allowed to - having to open a ticket against the constitution shouldn't be necessary to find out who can create metrics.

**Comment by brianjrobertson** [comment]
Of course it's not, no more than it's spelled out in there that you are authorized to do any other specific act one could imagine. That's the whole point: the constitution doesn't spell out everything one is authorized to do, it asserts that you're authorized to do anything to serve your role unless it's explicitly forbidden (§1.3).  And defining metrics isn't explicitly forbidden, thus anyone is welcomed to do it.

**Comment by brianjrobertson** [comment]
Thus, I'd say it's perfectly clear in the constitution, if you understand that basic premise covered in §1.3...
