### ISSUE TITLE
Differentiate 2.5.4 for "Faciliator und Secretary" and "Rep Link"

### ISSUE THREAD

**Issue by ivobaettig** [holacracyone/Holacracy-Constitution#160]
2.5.4 "Surrogates for Elected Roles" does not make sense for the Rep Links
I suggest to separate the section into 

- "For Facilitator and Secretary" keep (a) - (e)
- "For Rep Link": just (a) 
(I would not suggest to add something like "(b) The Lead Link of the corresponding Sub-Circle" because of loosing the Lead/Rep-Link separation of duty - the circle can still elect a new Rep Link in case she/he would not attend the Super-Circle meetings regularly)

**Comment by brianjrobertson** [comment]
Do you have a concrete case where this got in the way or limited an organization somehow?  That's a required threshold for consideration of this kind of constitutional change.

**Comment by ivobaettig** [comment]
Yes, we had several meetings with none-present Rep-Links (with non-defined surrogates by the Rep Link) and it was unclear if it's ok that the Lead Link takes over reporting the Metrics (or the Facilitator or Secretary)

**Comment by brianjrobertson** [comment]
Ah, issue #65 will solve that...
