### ISSUE TITLE
Rep Link Inconsistency 

### ISSUE THREAD

**Issue by chrcowan** [holacracyone/Holacracy-Constitution#161]
It isn't clear enough whether the Rep Link should process tensions just within its Super-Circle, or anywhere in the broader Organization. 

The purpose states, "Tensions relevant to process in **the Super-Circle** channeled out and resolved."

But then the first accountability says, "Removing constraints within **the broader Organization** that limit the Sub-Circle."

**Comment by brianjrobertson** [comment]
Agreed - the purpose should say "in the broader Organization" or "outside the Sub-Circle" perhaps is better?  Feel free to submit a pull request to fix it.

**Comment by chrcowan** [comment]
Not sure how I feel about "broader organization" vs. "outside the sub-circle." I think I like "broader organization" better since its more colloquial. 

I'm not really sure what a pull request is. I don't see much explanation when I go to the sub section.

**Comment by brianjrobertson** [comment]
There are plenty of online tutorials; no github support is offered by my role.  :-)

**Comment by chrcowan** [comment]
Fair enough. Not knowing what it is, I'm not compelled to find out. I was just asking since you mentioned it. :)

**Comment by brianjrobertson** [comment]
It's how you submit a change to the constitution; so if you want to see this bug fixed, it's on you to submit the change... or you can just hope someone else fixes it, but there's no guarantee that'll happen.

**Comment by chrcowan** [comment]
Well, I played with creating a new pull request for about 10 minutes, watched a youtube video, still doesn't make any sense to me as a non-developer how to create a new pull request, so hopefully Constitution Steward will consider making it easier to submit feedback.

**Comment by KoenVeltman** [comment]
hi @chrcowan I have the same. as a non techie I find github very hard to get around. I did find a developer to have me explain it a bit. But it got me a couple months delayed in processing something for constitution 5.0. And still have many to go. so a +1 on your request!
