### ISSUE TITLE
Clarify tactical meeting process

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#162]
I've observed that several clarifications and process tweaks to tactical meeting triage would likely help:
- Clarify that triaging an agenda item starts with getting to a request (before anyone else can talk) and then processing that request.
- Encode triage pathways as possible requests; reframe “Share information” to “Request space to share”, and reframe “Try to set a new expectation” to “Request an ongoing expectation”.

**Comment by bernardmariechiquet** [comment]
Yes IMO it would definitively help! I would opt for both.
