### ISSUE TITLE
Enable "tactical meetings" across circle boundaries without confusion

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#163]
Define tactical meetings outside the context of a specific circle, as an operational meeting with specific roles invited, so that anyone can easily call for them with any group of roles and still call it a "tactical meeting" without confusion; then define tactical meetings of a circle as a default subset of that broader framing, with all Core Circle Members invited by default.

**Comment by julianeroell** [comment]
Yes. This would be awesome.
