### ISSUE TITLE
Clarify how policies that include deadlines work (or forbid them)

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#166]
A common question:  "If a policy says I need to do something in 3 days, does that make it higher priority than any prioritization a Lead Link can set?"

The current answer:  No, the Constitution is silent on that, thus it's up for interpretation what that means.  Because of that, there's lots of room for hope & blame management to sneak in.  Add clear rules on how prioritization works when there's a deadline specified in a policy like that, or outlaw it in the first place.

**Comment by brianjrobertson** [comment]
My intended solution for this is to say that deadlines in policies are treated as prioritizations; in other words, "within 3 days" would be a delegation of Circle Lead authority to prioritize, and effectively saying "doing this within 3 days, or as close to that as possible, is more important than any other work in this circle" (although of course work in other external circles could actually still be prioritized over that deadline by a relevant broader Circle Lead).  This would make clear that a deadline in a policy isn't a mandate to force reality to conform, just a simple prioritization relative to other work in the circle.

That said, I'm also thinking about dropping this one to keep the constitution simpler and not have to explain all of that for just one special edge-case.  If I drop this though, I'd personally still interpret the constitution this way anyway - I think it's the most reasonable interpretation I've found for what "within 3 days" means in a policy.  So, I could see advocating for this as an interpretation instead and suggesting coaches teach it this way; perhaps H1 could even publish a blog post on it to make this interpretation more official-ish (but obviously less official than including it in the constitution itself of course).

Thoughts?

**Comment by cassus** [comment]
This question came up sooner or later in every circle I worked with, so I think having 2-3 sentences about it in the constitution would worth it.
I'd also clarify if this is only for policies or it works in the same way for accountabilities.

I'm also not completely clear on how this exception fits with the general rule that governance doesn't set priorities or allocates time. Would "I don't have time for this" = "This conflicts with my current understanding of my priorities" be a valid objection for these cases?

**Comment by chrcowan** [comment]
@brianjrobertson I haven't ever come across it, so this is just speculation, but I think having a very small line in the constitution might work; e.g. "Time constraints defined in policies are prioritizations." 

If it's small enough, then it's not adding complexity, and for those people (like me) who haven't ever come across it, it's just as easy to ignore. Not sure how that fits with your mental model of what should be included, but for me, this kind of interpretation wouldn't be easy for an average reader to make intuitively (based on how often it apparently comes up), and therefore something should be said in the constitution itself.

**Comment by oliviercp** [comment]
@brianjrobertson I like @chrcowan approach above

**Comment by brianjrobertson** [comment]
I'd love some more eyes on this change; what do you think?  Does this make sense?  Is the language clear enough and simple enough (or do you have a simplification that's better)?  Does the location of the new section make sense?

Note this language also covers how to treat deadlines in Accountabilities, in addition to Policies.

**Comment by ebabinet** [comment]
The language is clear, but I'm concerned that there are now 3 different
sections that relate to how I prioritize my attention:
2.3.2 Prioritizing Your Attention
2.4.3 Duty of Prioritization
3.5.1 Meaning of Deadlines in Governance

I think it would be better if this was included in 2.3.2.

**Comment by brianjrobertson** [comment]
Nice catch @ebabinet, I'll merge it in.
