### ISSUE TITLE
Broaden duties from Circle Members to all Roles

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#167]
There are ample cases now where the duties would be more useful if to all roles vs. just circle members, and no known cases where the circle member limit is needed; so, let's update it accordingly.  (Note: These should not be broadened to all partners in personal or as-a-partner capacities, just to all partners in the capacity of their roles, to avoid potentially bottlenecking people with processing non-organizationally-serving requests.  Perhaps allow ignoring the request if the role it is coming from is not specified or reasonable.)

**Comment by bernardmariechiquet** [comment]
Wow, it sounds like a big shift. I'm wondering if this would not go against the backbox principle, that is very useful for reeducating their hierarchical behaviors to holarchical ones.

**Comment by brianjrobertson** [comment]
I've added Issue #217 to ensure holarchy-violating interpretations are not possible.
