### ISSUE TITLE
Merge multi-filled roles and sub-circles

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#168]
Multi-filled roles and sub-circles are conceptually the same construct, yet have different treatments in several key ways (e.g. how a representative is chosen to join the containing circle's governance meeting).  Consider reducing this complexity and clarifying ambiguities currently in multi-filled role rules by attempting to integrate the two rulesets and reframing one to just a specific case of the other.

**Comment by LouisChiquet** [comment]
Maybe merge the two concepts of Rep Link and Role Representative, define they're both elected, and that it's just a per default solution (so the Rep Link by Partners in the Circle and Role Representative by the Partners within the role), allowing people to change a policy if it's not satisfying them. Meaning it would also open the possibility to have multiples “Rep Links” as [1.6](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#16-role-representation) “_Each Role has one or more “Role Representatives” who will represent the Role within the Governance Process._”.

**Comment by bernardmariechiquet** [comment]
@brianjrobertson Would appreciate the Why and the reasoning/thinking behind such major refactor. Could you explain and gives cases.
