### ISSUE TITLE
3 Destinct Role Types and their terms 'Assign', 'Appoint' and 'Elect

### ISSUE THREAD

**Issue by MiekeByerley** [holacracyone/Holacracy-Constitution#17]
In recent discussions, pertaining to Filling Roles, in the Facebook Group and the LinkedIn Group, Brian suggested to raise this as an issue here. I had mentioned that, when discussing it with a collaborator in a direct exchange of thought, I used the terms 'Assign', 'Appoint' and 'Elect' very deliberately (I noted in the constitution that the terms Appoint and Assign have been used interchangeably, which is common).

Out of the 3 terms 'Assign' is the only one that requires the role to exist prior to the person, so all authorities, duties, responsibilities are firmly vested in the Role and upon assignment a member is granted full access to exercising those (this is what makes them a Defined Role they are defined then assigned). The role is the recipient of the person, even though we sometimes state that we assign a role to a person, what we really say is that the role receives its enabler in the form of a person. The other element that separates the 'Assign' is the need that generated the Role, assigned roles are generated by Organisational need, not by a human need.

The terms 'Appoint' and 'Elect' both are reliant upon the existence of people prior to roles they are generated by Human need. So all Authority, duties, and responsibilities rest in the person, the person in this instance is the receiver in that the appointed role enables the person to express the authorities through the means of the Role. In other words these roles are not needed unless there is more than one person.

What I have come to appreciates is that there are the Core Defined Roles (Assigned) which are purely Organisational or structural; then there are the Non-core Non-defined Roles (Elected) e.g. Facilitator and Secretary, which are purely Human or relational and then you have the Core Non-defined Roles (Elected/Appointed) e.g. Lead Link, Rep-Link and Cross-Link which are generated out of Human need but respond to Organisational need and as consequence become a hybrid.

This raises an interesting point, there are as a result three very distinct 'Types of Roles' differing in natures which deserve (I think) differentiating treatment. Core Defined Roles have been addressed through the term 'Assign', Non-core Non-defined Roles have been addressed through the term 'Elect', it is my humble opinion that Core Non-Defined Roles would best be serves through the term 'Appoint'. 
The question then would be how do we define and address 'Appoint' and how and by who would this be enacted within the constitution?

As an Organisation is an eco-SYSTEM of Autonomous HUMAN alliances in Holacratic terms, there will always be a need for Elections, Appointment, and Assigning functions. Holacracy simply creates an environment where each is used in its appropriate context and thereby protects the freedom and integrity of the whole and its parts.

**Comment by MiekeByerley** [comment]
Just an added note: Context-Link needs to be added to the Core Non-defined Roles group. It might also be prudent to elaborate on this Link a little as well.

**Comment by brianjrobertson** [comment]
I've updated the draft version to consistently use assign for most roles and appoint for elected roles.  Thanks for the suggestion!

**Comment by MiekeByerley** [comment]
:) Any thought on using "Appoint" for the Lead-Link, Rep-Link, Cross-Link and Context-Link roles? With the possibility of discovering what "Appoint' might look like.

**Comment by brianjrobertson** [comment]
Not sure what you mean by "discover what appoint might look like" - are you talking about just using a different word for what happens now, or changing the process?  "Assign" seems a better word choice for Lead Link, since you don't really assign/appoint someone to Lead Link in the first place - it's really an assignment to a circle-defined role first and foremost, that just happens to create a Lead Link when that role is really a circle.  And not sure how another word than "elect" would make sense for Rep Link...
