### ISSUE TITLE
Allow limits on what can be changed in a special governance meeting

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#176]
As a Secretary, I'd like to be able to announce in advance of a special governance meeting what roles and/or policies are on the table for change in that meeting, and restrict the governance meeting to only affecting those roles and policies (including preventing an expansion of the policy that would limit any role not explicitly named), so that I can more efficiently use our team's time by scheduling a special governance meeting to deal with one specific issue while giving other team members the known safety that they can skip the meeting without worrying about their roles getting affected by the output.

**Comment by gvandegrift** [comment]
Do you literally mean "restrict", i.e., those not affected cannot come?

**Comment by brianjrobertson** [comment]
No, I mean restrict what can be done in the meeting, not who can attend...

**Comment by bombino** [comment]
I see this as a positive change.  Meeting fatigue is a real thing and as many of my roles, knowing that I can safely skip a meeting would be helpful.
