### ISSUE TITLE
Add duty of transparency when prioritizing against a circle strategy

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#178]
As a Lead Link, I'd like to be able to count on people to call out when they are prioritizing something substantial against the guidance of a circle-level strategy or prioritization, so that I can use strategies to guide the circle while knowing I'll get the visibility and can consider how to respond to any prioritizations that are opposite my published strategies.  This will also help people understand that a strategy isn't a mandate, but just a heuristic to generally privilege when most else is equal.

**Comment by julianeroell** [comment]
I like this.
