### ISSUE TITLE
Proposal to include a Section under Circle Structure addressing Strategy

### ISSUE THREAD

**Issue by MiekeByerley** [holacracyone/Holacracy-Constitution#18]
I have noted the following:
Strategy is mentioned several times in the Constitution.
It is covered in the document 'From Aim to Action with Holacracy' mentioning Strategy Meetings.
There exists a Policy for Strategy Meeting within HolacracyOne's own structure.
GlassFrog identifies it as a separate Attribute along with a Circle's Purpose, Domains, and Accountabilities.

This indicates to me it is deserving of explanation and mention within the constitution.

Strategy - (a.k.a. Heuristics) Overall direction for prioritising the work of the circle and each of its roles, in service of the Purpose (i.e. which projects to prioritise over others). All roles within the circle are expected to align with the Strategy.

**Comment by brianjrobertson** [comment]
Section 2.2.2 already defines and addresses Strategy, and 4.1.3 references it re aligning with it; what else/more are you suggesting?

**Comment by MiekeByerley** [comment]
My apologies. What I was trying to convey was the following suggestion:

2.1 Circle Basics
A “Circle” is a Role that may further break itself down by defining its own contained Roles to, achieve its Purpose, control its Domains, and enact its Accountabilities, and define its Strategies. 

A "Strategy" being the overall direction for prioritising the work of the circle and each of its roles, in service of the Purpose (i.e. which projects to prioritise over others). All roles within the circle are expected to align with the Strategy.

2.2.2 Defines Priority and Strategy
A Circle’s Lead Link may define priorities for the Circle. In addition, the Lead Link may define more general heuristics for prioritization as per section 2.1.1, which guide the Circle’s Roles in self-identifying priorities on a case-by-case basis.

The reason I mentioned this is because it is only one of two embedded descriptions still in the Constitution (you have removed all the other) and I know from discussions else where they fall into the back ground due to being perceived as a side note. 

I considered this a specific Holacratic definition so thought it deserved more prominence and clarity and alignment with the rest of the document. I was also going to propose an alteration pertaining to the second embedded Description and the reordering of the sections in Article II, but had not had time to formulate this yet (it was 12 am local time). :)

**Comment by brianjrobertson** [comment]
Okay, that was helpful, thanks; I just updated the definition of Strategy to define it in-line vs. in a parenthetical clause.  I'm not sure about moving it earlier and merging it with the basic Circle definition, but I think it reads much better now.  Take a look and re-open this issue with some more details if you think it needs something more (or open a new one for the other definitions you think could be improved).
