### ISSUE TITLE
Secretary Role Name Change Suggestion

### ISSUE THREAD

**Issue by rebeccabrover** [holacracyone/Holacracy-Constitution#183]
Pitch to change _Secretary_ to _Keeper_. Not only does it remove the connotation often associated with Secretary in the management hierarchy, but it describes well the energy the role should hold as well as much of the work of the role does in terms of the Circle and records. There’s also the nice little sporting reference that lends itself well to the analogy narrative of Holacracy as a game. End of pitch.

**Comment by brianjrobertson** [comment]
Would love to hear thoughts anyone has on this; for, against, or otherwise...

**Comment by jds655** [comment]
I like it, in the vein of choosing language that fits the Role's intent and breaks old connotations/meanings.

**Comment by bernardmariechiquet** [comment]
I like the idea of removing the connotation even if with time I observe that the meaning of the word **Secretary** coming from the latin word **Secretarium** (keeping secret, treasure) is actually a great fit IMO.
I do like also the word **Keeper** as a recordkeeper with the nice sporting allusion. 
I'm just wondering if there is value in changing **now** the word **Secretary** as I see less and less connotation on such word, as if the mental representations associated to such word were evolving through Holacracy practice (same with negative connotation of the word Tension). I love the idea that a practice like Holacracy has got such power and capacities backed into it, to allow with time a reset of mental connotations.

**Comment by cassus** [comment]
I explained the Secretary role to a couple dozen people now, and the name worked well, it's a good first approximation. I often say it's more like a "legal secretary", not just doing note-taking but also responsible for interpretation when it's unclear.
I imagine I'd have a bit more trouble explaining with the Keeper name.

For me, this situation is similar to the Facilitator. It has a different energy from what most people have experienced as Facilitation before still, it's the best starting point I know.

**Comment by julianeroell** [comment]
I like "Keeper" or "Record Keeper", or maybe "Scribe" (not sure. The Secretary does more than just Scribe. In our meetings, they mostly scribe, though. :-))

"Secretary", although clear to me now and _somewhat_ easily explicable, always brings up unwanted associations in new Holacracy practitioners and in my view has much less functional clarity than "Keeper". 

I would support this change. Safe to try. :)

**Comment by gvandegrift** [comment]
FWIW, I like secretary.  It is used in very prestigious contexts as well, at least in the US (e.g., secretary of state).  To add to the mix, what about a longer full title like Constitutional Secretary, but then we could just continue calling it secretary for short?

**Comment by tylerdanke** [comment]
I like Secretary. I believe that we have an opportunity here to show that Secretary has positive connotations. I believe that Secretary is a universally used english word for the "keeper of the records and minutes and correspondence of meetings within this group of people". Keeper has none of those connotations and would be something significant to learn. Honestly even simply the way that this role name lends itself to normal meetings and organizations makes this role very palatable.

**Comment by rebeccabrover** [comment]
@gvandegrift Great insight on the prestige. I might counter that with the notion of reference in meetings to "Mister Secretary" or "Madam Secretary", which might be both odd and counter-productive to good Holacracy practice however I like your suggestion of official name of Constitutional Secretary (with CS or Secretary for short).
@tylerdanke One of the reasons I like keeper is _because_ it has a totally different meaning and is a jar to the system. I do see the argument that, similar to tension, secretary can be given new life and new meaning within the Holacracy Constitution however the same could be said for keeper (a guardian, a protector, a key player).
More experienced organizations seem to have little trouble after some time has passed however, due to the conventional connotation of secretary, those elected to the role in early practice are often administrative assistance or formerly subordinate team members who then often require quite a bit of coaching to energize their role outside of meetings well.
A seasoned legacy secretary is often inclined to take a more active role in translation of meaning, which can be harmful and a former junior admin is less likely to schedule when their former "boss" can't make a meeting which is truly harmful to early practice.
Changing the name to something else (certainly no super strong feelings about keeper specifically and could see equal benefit to perhaps archivist, curator, conservator or steward) I think would be a huge step in support the power-shift as a word with less conventional meaning would likely encourage a broader pool of early candidates from a variety of former power levels.
This could help promote better scheduling, more active participation early on and deeper understanding of the importance and power of the role.

**Comment by klaas1979** [comment]
I would go with the word Secretary just to make Holacracy better accessable for newbies. The reason for this: I have been a Scrum and Agile Coach for years and in the beginning all the fancy new names made it more difficult for beginners to get into Scrum. In the beginning their was a lot of laughter and not very nice talk about names like ScrumMaster, Sprint or Backlog. I guess it could be like this with the word "Keeper".

**Comment by brianjrobertson** [comment]
I see compelling reasons both for and against this change.  I think the compelling reasons for a name change like this need to be very clearly overbalancing the reasons against in order to justify going with the change, and in this case I think they are at least near balanced.  So, I'm dropping this issue.

**Comment by brianjrobertson** [comment]
I'm rethinking this one again, and seriously considering "Scribe" (thanks @martinaroell for the idea).  It doesn't have the stigma that makes Secretary occasionally problematic.  And the historical importance of the profession and what it eventually evolved into instills the word with at least some sense of meaning beyond just note taking; from Wikipedia:

> The work of scribes can involve copying manuscripts and other texts as well as secretarial and administrative duties such as the taking of dictation and keeping of business, judicial, and historical records for kings, nobles, temples, and cities. The profession has developed into public servants, journalists, accountants, typists, and lawyers.

Thoughts?  Is this worth the change from Secretary?

**Comment by gvandegrift** [comment]
IMHO, Scribe doesn't seem much better than Secretary.

Not sure why I didn't think about this when I posted earlier, but in re-reading the thread, another tack came to mind.  What about focusing on the "more powerful" attributes of the secretary and choose a name based on that.  The record-keeping just happens to be an additional responsibility for this person.  By more powerful, I'm referring to the secretary's responsibility to offer "rulings" on disputes over governance and the constitution.  So in that line of thinking, what about Arbiter, Justice, Jurist, Judge, Magistrate, ...?

**Comment by jeanlucchristin** [comment]
I lyke scribe or record keeper

**Comment by Learloj** [comment]
The role "scribe" is also used in the Dynamic Systems Development Method (DSDM) project framework [1]. Though the wiki page only mentions record keeping, I seem to remember the role also did the meeting invites. Personally the name feels a bit more about only the administrative things, and not necessarily about interpreting the governance and constitution (though neither does the name "secretary").

[1] https://en.wikipedia.org/wiki/Dynamic_systems_development_method

**Comment by MiekeByerley** [comment]
I have been reading through the comments and an interesting decriptor occured to me after mulling over the various comments about the role responsibilities.

The term **Attaché** poped into my mind, when you read the decription here below you will brobably get a feel for why it appeared as an alrenative to Secretary. 

"In diplomacy, an **attaché** is a person who is assigned ("attached") to the diplomatic or administrative staff of a higher placed person (Role) or another service (Circle) or agency (Organization)... An attaché is normally an official, under the authority of an ambassador (Super CIrcle) or other head of a diplomatic mission (Project Circle), who serves either as a diplomat or as a member of the support staff. _**They monitor various issues related to areas of intervention. To this end, they may undertake the planning for decisions which will be taken and make all necessary arrangements, manage the agenda, conduct research for the study of particular matters, and act as representative when necessary**_."

Food for thought.

**Comment by sitron** [comment]
scribe sounds pompous and even more focused towards "writing" than secretary to me

**Comment by jeanlucchristin** [comment]
Hello

I’m happy to arrive with an idea that i like a lot : 
« Role memory »

All the purpose of the role secretary is embedded in this word

I hope you will appreciate !! 😊🙏🏼

**Comment by matthewgilliland** [comment]
Scribe seems like a step backwards (and is also used in at least two other methodologies).

+1 for Recorder or Record-keeper. No word is going to perfectly capture all of our implications, and the less jargony, the better.

**Comment by brianjrobertson** [comment]
Okay, after two years of searching, I'm giving up on this issue and keeping Secretary, at least for this next version.
