### ISSUE TITLE
Reword lead link accountability for structuring governance

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#184]
The Lead Link accountability for "Structuring the Governance of the Circle to enact its Purpose and Accountabilities" has led to some misunderstanding; consider better wordings.

**Comment by julianeroell** [comment]
Something along the lines of "Proposing Governance changes for the Circle to better enact its Purpose and Accountabilities" to clarify that the LL cannot simply "Structure the Governance" but is merely called to _propose_ Governance to let the circle function better?

**Comment by bstillwagon-mylo** [comment]
I think there are two different approaches to take for this:

1. If the intent is for the LL to 'Establish the initial Governance...', I think this wording helps to clarify that the LL is accountable for the initial Governance, but not the ongoing changes.

2. If the intent is for the LL to continually propose changes to the circle, then I like the change @martinaroell suggested above.
