### ISSUE TITLE
Allow constraints on who fills elected roles

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#185]
In early practice, skilled coaches often want to require certain constraints on who fills elected roles, such as requiring a client to use them as Facilitator, or only electing a Facilitator or Secretary who is properly trained.  Find a way to clearly allow this, without allowing an unskilled circle member to compromise effective practice with a bad constraint...

**Comment by julianeroell** [comment]
I have been following the discussion of the CoP Forum and have not fully understood all thoughts of everyone. In my view, being able to raise an objection is sufficient - this transmits the information ("e.g. "I don't think someone without certification can hold Secretary well enough") effectively, moves towards integration ("if you get shadowed by an experienced coach, it's ok") or towards a new person being proposed for election. It prevents theoretical ideas ("No person without certification can facilitate well enough") from limiting electibility. I see no need for a constraint.

**Comment by brianjrobertson** [comment]
@martinaroell: That's not sufficient; often the perceived importance is coming from a coach outside of the circle, who thus can't raise an objection.

One possible solution:  Allow super-circles to impose constraints on elected roles during a Process Breakdown, and start all circles in a state of Process Breakdown upon initial Constitution adoption, until they reach the criteria to for process restoration (and rename Process Breakdown so this makes more intuitive sense; e.g. call it "Process Instability").

**Comment by bombino** [comment]
In our experience as an org, we've found that the harm that can be caused by a poor facilitator or secretary greatly outweighs the harm caused by limiting access to these elected roles.

The way we'd want this policy to read for our organization would be something like: "In order to be eligible to serve as Facilitator or Secretary, a Partner must have 12 months of Holacracy experience or have attended a facilitator training event sponsored by HolacracyOne."

Just food for thought.

**Comment by gmitterer** [comment]
@brianjrobertson I really like the idea of starting from a default process instability. I would only be afraid that this is not self-explanatory and hard to link to the early adoption phase tension you described (without a reference to the example). So I wonder how could it be a bit more explicit that this is the "rule" that allows for setting constraints on who gets elected in the early phase.

**Comment by brianjrobertson** [comment]
@gmitterer I like the idea too, but I share your concern as well, and I'm sensing it may be overkill - I'm not sure it's needed.  So for now I'm going to simply allow Circles to limit candidates for elected roles, until someone presents a case showing why that simple solution would cause harm, and then at that point I'll consider more complex solutions to meet this need without the harm.
