### ISSUE TITLE
Rework Lead Link accountability for "Establishing priorities and Strategies for the Circle"

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#188]
Rather than an ongoing expectation to establish them, it should be an expectation to do so when needed to resolve priority conflicts between two roles; beyond that, the Lead Link may do so still when needed to serve the circle's purpose, but it shouldn't be an expectation that others can demand of the lead link except in the event of a conflict.

**Comment by bernardmariechiquet** [comment]
Yep, this is clearly framed and It resonates a lot with my experience. I would suggest : - "Establishing relative priorities on demand" knowing that the conflict may involve more than 2 roles and sometimes one member may ask for relative priorities between projects to the Lead Link. On the top of that, I would take this opportunity to add the word  *relative* to the word priorities to avoid any confusion with the old power over people. For Strategies, I do agree this shouldn't be an expectation onto the Lead Link and at the same time, I love the idea that a Lead Link may also be challenged on that on (i.e. asked to consider if and how to enact such accountabilty for establishing strategies). This happen quite a lot still into for instance the manufacturing area where I have done a lot of work.
