### ISSUE TITLE
Reintroduce "Circle Member" as a defined term?

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#191]
After some of the recent changes, Circle Member was no longer a distinction that was really used, at least not in a meaningful way that wasn’t easily replaced with another distinction.  This seems super weird, but that’s where I accidentally arrived by following the tensions and solving other issues.  So it seemed the distinction was no longer useful, so I removed it [this commit](https://github.com/holacracyone/Holacracy-Constitution/commit/a46d23cce7f24f37c6438908d151eae097077aa0).

I'm wondering whether this is natural and we just need to get used to no longer having that defined term in v5.0, or if it'd be best to re-introduce it as a distinction to mean all Role Representatives invited to govern a Circle (i.e. what Core Circle Member used to mean), to simplify some of the places where that more clunky phrase is used in Article 3 (in the current dev version).  Thoughts?

**Comment by RashidGilanpour** [comment]
I like the additional distinctions made by removing/reducing usage of "Core Circle Members" 
In many cases, it seems "Core Circle Members" is too broad to represent and account for the multiple Holacracy mechanics (levers) at play in a circle's processes. 

"Role Representative" sounds more functional and dynamic where as "Circle Member" sounds more static and fixed 

Representing [the perspective of] a role, seems more in alignment with the practice than "membership" status

**Comment by FrancLom** [comment]
IMO Role Representative sounds misleading. It might make to believe (at least to uninformed people) that a Role Representative is a person representing a role (just one). I understand the concept behind the choice but I think that in the real world it will be less practical than "Core Circle Member". My 2 cents.

**Comment by FrancLom** [comment]
And I find the "Rep Link" rule specified in 1.6 rather harmful because it decreases the clarity of who are the Rep Links in a circle, how to choose them, how to remember who they are, and what are the differences accountabilities between the Role. The proof is that it took me many more neurons than usual to understand it! (but maybe it is just me?)

**Comment by bombino** [comment]
I like your commit as written.  I think Core Circle Member is a concept that has led to a lot of confusion for us and I am happy to see it go away.

**Comment by brianjrobertson** [comment]
The change I just submitted has indeed reintroduced Circle Member and Core Circle Member, but with different meanings and functions compared to the v4.1 terms.

Now, Circle Members means those Partners available to the Circle to assign to Roles; if someone isn't a Circle Member, the Circle can't assign them to Roles.

Core Circle Members still means those Circle Members who are invited to govern, but it's now an entirely derived term; in v4.1 the Lead Link could make someone a Core Circle Member, thus it was effectively a maintained list vs. a derived term.

That said, I'm going to open a new issue to try to remove or simply the Core Circle Member term if practical.
