### ISSUE TITLE
Recent changes seem to disallow circles from inviting external facilitators, was that intended?

### ISSUE THREAD

**Issue by bombino** [holacracyone/Holacracy-Constitution#194]
It seems to me that the change in d5a340d (even with the additional modification in commit 5c4d3b0) would prevent a practice that we currently engage in at Action Verb, which is to encourage circles to be facilitated by a person who is not otherwise a member of that circle. 

The thinking was that this allows the facilitator to focus on facilitating and holding the process rather than interjecting his or her personal opinions or positions.

Under Constitution version 4.1, we can achieve this by having the Lead Link add that person as a core circle member without a role and nominate them during the election to serve as Facilitator.  Of course, we still hold elections as prescribed in the Constitution.

Was external facilitation something that was intentionally eliminated in these recent changes, or did this just get overlooked?

**Comment by brianjrobertson** [comment]
The intent was not to exclude that possibility, just to require the elected Facilitator (or Secretary, if no elected Facilitator yet) to temporarily hand off the role to the outsider.  That said, I do see the value in allowing an election to select an outsider in certain cases - I'll submit a change.
