### ISSUE TITLE
Improve clarity of Objection validity criteria 3

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#195]
The third Objection validity criteria leaves enough ambiguity of meaning that it's harder to test against effectively than the other criteria.  I'm looking for potential evolutions to the test question and underlying criteria that will tighten this up while still capturing everything this criteria should capture and nothing it shouldn't.

So far, I'm thinking something like this for the test question:  “will the proposal create an immediate obstacle to your role's purpose or accountabilities, or are you anticipating a likely future impact?”... and "purpose or accountabilities" in there could perhaps be replaced with just "work".

Anyone see a better wording for that or a better underlying distinction, or any issues with that one?

**Comment by bernardmariechiquet** [comment]
The question is not totally clear for me. Are you speaking of a test question being included into the Constitution or are you working on the process cards ? Or both ?

**Comment by brianjrobertson** [comment]
Both...

**Comment by cassus** [comment]
> Do you know this impact will occur OR Are you anticipating this impact is likely to occur?

This is the hardest for new people to understand and apply to their objection, so some improvement would be nice.

I'm hesitant about the *immediate obstacle* part, that seems too strict and might filter out valid objections. Eg. If someone is 100% certain it will cause harm but in a week or two.

Often I translate the testing question as such:
> *Are you 100% sure* this impact will occur OR You think it's likely?

What do you think if this one?

**Comment by chrcowan** [comment]
Here are some alternatives I'm playing with: 
• Would the proposal *necessarily* cause the issue...or...
• Would the proposal *automatically* cause the issue...or…

I like "will the proposal create an immediate obstacle to your work, or are you anticipating a likely future impact?”

**Comment by ebabinet** [comment]
I completely agree that this 3rd testing question needs to be improved, however, I think the proposed phrasing "will the proposal create an immediate obstacle to your role's purpose or accountabilities" is getting too far away from what the question is intended to test, which is that the objection is based on "presently known facts or events".

How about "Do you have facts or data which indicate this impact will occur, or are you predicting that it is likely to occur?"

**Comment by gmitterer** [comment]
I am in favor of sharpening the question a bit. The option "will the proposal create an immediate obstacle to your roles' work, or are you anticipating a likely future impact?” somehow implicitly includes (replaces?) the test question 4 (does it impact one of your roles...).  

One additional perspective that I would like to add here: we are working in several adoptions where people speak English but it's not their native tongue. Any sophisticated wording (totally meaningful for natives) makes it very hard to use these questions for beginners (who struggle with Holacracy grammar and language :-)). So in practice I would go for a far easier language, such as the one @cassus suggested or one similar to @ebabinet "Do you have facts or data which indicate this impact will definitely occur, or do you think that it might happen?"

**Comment by bombino** [comment]
What about:  "Would this proposal create a tension that your Role would want to process immediately or could things unfold without creating immediate tension?"

**Comment by brianjrobertson** [comment]
Hmm, interesting @bombino - I wonder if, with the right wording along those lines, we could effectively cut that question down to a one vs. two part question, without losing the important distinctions that are captured right now by the two part process...  I'll reflect on that further.

**Comment by brianjrobertson** [comment]
How about replacing criteria 3 with:
- **(c)** The Proposal would necessarily cause the harm regardless of how future probabilities unfold, or predicting future events is useful because no opportunity is likely to exist to adequately sense and respond before significant harm could result.

Does that still capture everything you can think of that this criteria currently captures, with less false-positives?  @chrcowan especially?

**Comment by chrcowan** [comment]
@brianjrobertson I really like the direction....hmmm...I wrote and rewrote lots of comments, so I guess I'm still thinking it through!! LOL!

"The proposal would necessarily or immediately cause the harm, or predicting future events is needed because no opportunity is likely...."

**Comment by oliviercp** [comment]
@brianjrobertson I like where it's going to, but the sentence itself is hard to chew on IMO. 

I like @chrcowan's simplification. 

Here is another one, that I'm not entirely satisfied with either... 
> The proposal would already cause harm regardless of future events, or it could potentially cause harm depending on future events but there will likely be no opportunity to adequately sense and respond before significant harm could result.

**Comment by cassus** [comment]
Here's another take building on yours. I'm aiming to make it even simpler and easier to read.
> (c) The proposal would already cause harm regardless of future events, or the proposal could potentially cause significant harm before the circle can sense and adapt to avoid it.

**Comment by brianjrobertson** [comment]
@chrcowan If we change from:

> The Proposal would necessarily cause the harm regardless of how future probabilities unfold...

to:

> The proposal would necessarily or immediately cause the harm...

Think that's still clear enough to actually capture everything it needs to capture, without false positives?  i.e. Do you think the latter part you cut is implied enough even without being explicit about it?  Also, why add "or immediately" - isn't that covered by "necessarily" (what wouldn't be)?

Others have thoughts on this?

**Comment by brianjrobertson** [comment]
@ocompagne and @cassus, re:

> The proposal would already cause harm regardless of future events...

That doesn't work; sometimes it won't "already" cause harm, but it would "necessarily" cause harm, and if we filter down to only "already", it's nearly impossible to answer both this question and question number 2 with valid answers.  I think that's the wisdom in @chrcowan's original suggestion to use "necessarily" - it's broader and gets to the spirit of the criteria without that issue.

**Comment by brianjrobertson** [comment]
Okay, I'm going with this:

> (c) The proposal would immediately or necessarily cause the harm, or it might cause harm but that possibility still needs to be dealt with now because the Circle won't have an adequate opportunity to adapt before significant harm could result

But I'd still love to hear concerns about it or better ideas, especially from you @chrcowan as I know you've spent a lot of time on this one...
