### ISSUE TITLE
Remove constraint that Facilitator can't be Lead Link

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#197]
There have been several cases now where it really makes sense for the Lead Link to be able to serve as the elected Facilitator.  On the other side, there's a lack of proof that the current constitutional constraint against it is in fact needed.  So, I believe we should remove the constraint (although of course any given organization or circle could add it back via policy).  That said, as part of this, ensure a broader circle can constrain this in sub-circles, in case an org-wide constraint is in fact needed.

If you're reading this and have seen real cases where the current constitutional constraint seems clearly needed, even with the ability to specify an anchor-circle-level constraint that affects sub-circles, please share details.

**Comment by LouisChiquet** [comment]
Curious to know what's the concrete tension for having such? Knowing that Circle with two people works perfectly fine and policy, in order to extend the authority of whom, may be elected is possible.

Knowing, leaning on the rule that the Lead Link (which is often the ex-manager) can't be elected Facilitator helps lots for changing the mindset and allowing people to better take their marks and roles then if an ex-manager was facilitating (as they often vote for the ex-manager for example for Secretary, and often elects them when he's not already facilitator). I just got a concrete example with a customer, and having this rule in the Constitution on which to lean is very useful, as wouldn't be possible if I was for example to pass a Governance proposition for putting in place a policy for restricting it.

**Comment by brianjrobertson** [comment]
The tension is that sometimes the Lead Link really is the ideal Facilitator - I've seen several cases like that.  Once a company is practicing maturely, it doesn't matter whatsoever if LL is also Facilitator; and before that point, sometimes it's better than other options - e.g. sometimes, in small one-circle companies (often DIY adoptions), the LL is the driver of the Holacracy adoption and the only one trained in Holacracy, and a better option than anyone else.  One client of ours actually insisted on adopting a custom modified constitution that allowed Lead Link to be elected Facilitator for this exact reason: the founder/LL sensed that it simply made the most sense to allow himself to be facilitator if the group so elected, given his level of Holacracy skill and dedication (and in their case I agree).

That said, you can now (in latest dev version) constrain this with a policy, so there's no reason it wouldn't be possible to adopt a policy that prevented this; in fact, if you wanted to, you could start your clients with this policy as Initial Structure at the beginning of an adoption, and then let them remove it if/when they're ready to.

**Comment by karilen** [comment]
Or just make it explicit that the person being the Purpose Link can act as facilitator, so they can leave the role unfilled and have secretary appoint, or that they can act as facilitator but that there is an elected one who can take over if it seems they are not holding process.

**Comment by LouisChiquet** [comment]
“_the LL is the driver of the Holacracy adoption and the only one trained in Holacracy_”
It's actually a danger as this may re-install a new hierarchy, a hierarchy of those knowing Holacracy vs not knowing Holacracy (and not quoting/reading lots the Constitution as they think they know and have been trained), and the fact for DIY adoptions to allow for example in the Constitution LL to be facilitator greatly increase this danger in my opinion. While if the facilitator was somebody different, this may allow different interpretations of the rules and not “a single vision and interpretation”. The reason behind my tension is that sometimes people don't have much means, and so wish to launch themselves a bit alone, but with the minimum engagement at the start, and so when you're not yet launched, it's easy to undermine this important point for the success of the implementation.
