### ISSUE TITLE
Clarity of default / implicit domains

### ISSUE THREAD

**Issue by djwork** [holacracyone/Holacracy-Constitution#2]
When I read the constitution I notice references to what appear to be default / implicit domains:
-  From 2.1.1 "Further, each Circle may control its own functions and activities, as if a Domain of the Circle" (eg All functions & activities within the Circle)
-  From 5.2 "This “Anchor Circle” becomes the broadest Circle in the Organization, and automatically controls all Domains that the Organization itself controls" (eg All Company property & ordinary business affairs)

Am I correct that these are in fact implicit domains? If so I would like to propose addition of an appendix (similar to Appendix-A for core roles) to list implicit domains and maybe a few notes about example uses in the FAQ.

PS what happened to "all partner relationship" from v4.0 - clause 5.2.5?

**Comment by RashidGilanpour** [comment]
@djwork can you please open another issue about your PS question

**Comment by djwork** [comment]
I will but what I mean is "all partner relationships" is an example from v4.0 of another implicit domain and I was going to list it in the original issue but I couldn't find it in v4.1 and I wonder if it was dropped on purpose.

new issue https://github.com/holacracyone/Holacracy-Constitution/issues/6

**Comment by brianjrobertson** [comment]
Hmm, I think it's just those two you've listed, and not sure that's worth an appendix...

**Comment by djwork** [comment]
Notes in the FAQ then, my underlying tension is clarity is good in the organisation and good in the constitution.

**Comment by brianjrobertson** [comment]
@ocompagne Maybe something to clarify on the wiki...

**Comment by oliviercp** [comment]
@djwork we have a wiki, not hosted here on GitHub but at http://wiki.holacracy.org — if you are certified Practitioner you're welcome to an account and making changes (including creating pages). If you're not a certified practitioner, you should become one http://holacracy.org/practitioner-assessment :)

**Comment by oliviercp** [comment]
@djwork alternatively you can send us content and I'll be happy to post it there if it seems valuable to the community
