### ISSUE TITLE
Who is eligible for being elected?

### ISSUE THREAD

**Issue by tylerdanke** [holacracyone/Holacracy-Constitution#201]
As a Facilitator and circle member I look at the constitution section regarding elections when I am taking part in elections.

One question that consistently comes up with every single election is "Who is eligible for this position?" It would be helpful if the Describe Role section of the Integrative Election process would include include "The Facilitator may also describe the functions of the target Role, describe who is eligible to fill this Role, and present other relevant information about the Role.". 

I think this simple subtle mention might make elections less stressful on all involved.

**Comment by julianeroell** [comment]
I find this helpful and have created a patch that contains exactly the change that @tylerdanke has proposed.

**Comment by brianjrobertson** [comment]
@martinaroell and @tylerdanke: I'm reviewing your pull request now, though I'm not convinced (at least not yet) that it's worth merging this in, just because it adds words/complexity, but doesn't have any real effect; it's already allowed/covered by the clause that the Facilitator may "present other relevant information about the Role".  In general, I'm trying to avoid adding any new clauses/words that aren't really needed, to keep overall size and complexity down.  Anyone want to pitch for why this really should be included that explicitly?  And, why this particular phrase and not other specific relevant information that the facilitator could also choose to share?

**Comment by julianeroell** [comment]
For me, this is an existing problem that keeps re-occuring, even with experienced practitioners. People go out-of-process and ask: "wait, who is actually eligible? Can I nominate anyone, even non-circle-members?" etc etc. Allowing the facilitator explicitly to point out eligibility would make the process  much more smooth IMO. 

"other relevant information about the Role" doesn't immediately give me a connotation to eligibility. 

As for other information - I don't know. I am interested in _this_ change, as it solves a problem that has been bugging me.

**Comment by tylerdanke** [comment]
The only "other information" I have ever had to share was who was eligible.
I have had who was eligible come up as a confusion point on every single
election we have done. If you want to come out of this issue with a net
equal number of words I would argue for removal of "other information" and
adding "who is eligible".

On Nov 7, 2017 4:18 AM, "Martina Röll" <notifications@github.com> wrote:

For me, this is an existing problem that keeps re-occuring, even with
experienced practitioners. People go out-of-process and ask: "wait, who is
actually eligible? Can I nominate anyone, even non-circle-members?" etc
etc. Allowing the facilitator explicitly to point out eligibility would
make the process much more smooth IMO.

"other relevant information about the Role" doesn't immediately give me a
connotation to eligibility.

As for other information - I don't know. I am interested in *this* change,
as it solves a problem that has been bugging me.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/holacracyone/Holacracy-Constitution/issues/201#issuecomment-342437614>,
or mute the thread

**Comment by brianjrobertson** [comment]
Resolved by https://github.com/holacracyone/Holacracy-Constitution/commit/c7e42864d4dbc134ef219700398042a5e0f22978#diff-04da9410c23da8c7e2bb5e5c31f7d122
