### ISSUE TITLE
Allow a partner to terminate another's partnership for willful constitution violations

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#203]
Well, this ought to be a somewhat provocative potential new feature...

As a partner, I'd like the power to terminate another partner's partnership (or perhaps remove them from roles) for willful uncured violations of the constitution or the resulting domains and policies, after some safe guards are met (such as announcing my intent to do so, getting one or two other partners to confirm they've seen the issue, and waiting a reasonable period to allow others to propose governance to limit this power), so that the constitution has real teeth and partners who regularly ignore it are less likely to stick around, or more likely to align with it before it gets to that.

Anyone see potential cases where this new feature would break things or have a substantial negative impact?

**Comment by jorisleker** [comment]
As Holacracy does not govern the legal Employer <> Employee (or broader: Company <> Partner) relationship, this could result in people still having a legal relation with the company, but no longer being part of the organization as defined  in Holacracy. Would that be the correct way to interpret this feature?

**Comment by margauxchiquet** [comment]
@brianjrobertson This is not enough to fire someone in France. I don't think the constitution should deal with legal stuff because it is so different from one country to another and from one organization to another.

**Comment by LouisChiquet** [comment]
In addition to previous comments: I'd suspect to let it the way it is today, as there is a point for new companies adopting Holacracy, “Holacracy says nothing about the firing or your HR”, which often allows people to calm down about the stress of moving to Holacracy (which is already a major shift), even if that addition was to be as a per default proposal, and so allow to encode quietly their way of firing (which often isn't clear and is a challenge already to encode in GlassFrog, and there is the need of time to distillate and think of a better way often), Holacracy remain a tool, metamodel to design your organisation. I'd let it as an App.

**Comment by brianjrobertson** [comment]
Thanks for the comments; I'm going to close this issue and leave it to apps to fill in.
