### ISSUE TITLE
Clarify that Governance Meetings Have a Defined Length

### ISSUE THREAD

**Issue by bombino** [holacracyone/Holacracy-Constitution#204]
The Constitution is silent on whether Governance meetings can be scheduled for a specific length vs. whether they must be allowed to run until the agenda is completed.

We have Secretaries interpreting that Governance meetings can be scheduled for a small amount of time, and we are seeing needed agenda items left hanging.

At the very least, can this question be clarified in the constitution one way or another?

I would prefer it clarified to say that Governance Meetings last until all agenda items are processed.

**Comment by gmitterer** [comment]
@bombino would like to better understand your request:
I my understanding Gov Meetings don't last until all agenda items are processed but finish when the allotted time (authority of sec) is over. Up to the Sec to figure out a proper heartbeat of how often and how long is the best fit.

Are you pitching for a change in that approach or is your understanding a different one?

**Comment by julianeroell** [comment]
This point has also come up for us several times. The constitution is unclear about this to me, and different people have received different information in their Holacracy trainings (ranging from: "Governance Meetings can never be timeboxed" through "Policy can specify Governance Meeting timeboxes" to "It's all up to the Facilitators and Secretaries: When time is over, it is over.")

For the sake of simplicity, I would support the suggestion @bombino made and specify that Governance Meetings last until all agenda items have been processed. This would give clarity. 

From that basis, _then_, Secretaries would determine an appropriate heartbeat.

**Comment by bombino** [comment]
^ This.  I don't really care one way or another as to how it's clarified (though I have a slight preference for having them last until the agenda is completed), but I would like clarity in the constitution.

**Comment by gvandegrift** [comment]
Agree it would be nice to clarify.  However, I would lean toward time-boxing.  (People have to be able to keep schedules.)  If time-boxing were the rule, it would also be nice to have clarity about what you do with a tension mid-process.

**Comment by brianjrobertson** [comment]
The current constitutional intent (and what all trainings I've done have taught) is that the meeting is time-boxed and ends when the allotted time is over, unless extended by Secretary mid-way through.  Having the meeting go until the agenda is done is definitely not workable - you'd have some meetings that could last 24 hours - and I suspect that would enable all sorts of dysfunction.  So, sounds like the language could be clearer about the time-boxing; I'll tag this as an issue to resolve.

**Comment by bombino** [comment]
Clarification that they can be extended by the Secretary midway through would also be very appreciated, and for now, I will direct people to this thread.
