### ISSUE TITLE
New Section in Constitution to Explain Exactly What Can/Can't Be Done In A Policy

### ISSUE THREAD

**Issue by bombino** [holacracyone/Holacracy-Constitution#205]
Practitioner training generally teaches that policies can only restrict actions by a role or grant access to some part of a domain.  However, there are a ton of other things the Constitution says can be done in a Policy.

See: 1.6, 1.8, 2.5.2, 3.2.1, 3.3.3, 4.2.1.

We find this makes it very hard to teach what is and isn't possible in a Policy.

Do we need to break down the Policy concept into defined types?

**Comment by cassus** [comment]
I haven't thought of this before, but it did come up in some cases.
A minimal solution for my similar tension would be a cheat-sheet next to the constitution ( maybe similar to the Tact & Gov meeting cards, probably not as fancy ) listing all the additional things a policy can customize.

I argue against introducing a new concept next to Policy. I believe that would make initial learning harder.
In everyday life, people are used to rules having exceptions. The general rule is that Policies can only grant or restrict authority. The exceptions are explicit hooks in the constitution.

**Comment by brianjrobertson** [comment]
Yes indeed, and this is already captured via Issue #67
