### ISSUE TITLE
Remove Lead Link accountability for offering feedback to enhance role fit

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#214]
The Lead Link's accountability for "offering feedback to enhance fit" did not originally come from an actual tension (just a mental model/projection), and I haven't seen it as a necessary component of the lead link role; thus I'm removing it to keep the role as simple as possible, and leaving it fully to the realm of apps to address feedback needs in specific contexts when useful.

**Comment by bernardmariechiquet** [comment]
It resonates a lot. This one was a bit weird as it introduces confusion with any other HR functions like Mentorship.

**Comment by LouisChiquet** [comment]
Great work on cleaning the Lead Link role (with that issue, and the other ones you just checked), will help a lot when coming to coaching and allow people to understand more easily that a Lead Link ≠ manager!
