### ISSUE TITLE
Clarify Duty of Prioritization when circle strategies/prioritizations exist

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#218]
The last Duty of Prioritization currently reads:

> You must integrate and align with any official prioritizations or Strategies of the Circle, such as those specified by the Circle’s Lead Link, when assessing how to deploy your time, attention, and other resources to your work within the Circle.

This leaves a lot of ambiguity, and often triggers questions of how to effectively interpret that, and plenty of confusion.

To address, clarify that the duty is really to work on the highest ROI use of time/energy, with any circle-level strategies/priorities taken as givens/facts.  Further clarify that a lead link can clarify the relative value difference between any two initiatives, rather than just "A over B", and that the role-filler can use their judgment to estimate time/energy cost.  Thus, in the end, the LL should be able to specify a value estimate, the role-filler should be able to estimate cost, and the duty should clearly be to work on the highest overall ROI given value divided by cost (so someone would clearly be free to work on something the lead link says is less valuable, if the overall ROI is still better given time/energy cost).  And, do all that while keeping it super simple and not requiring actual numbers for any of these estimates unless actually desired.

**Comment by LouisChiquet** [comment]
[2.3.3 c](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#233-duty-of-prioritization) for reference.

First, this would need to be changed as effectively the defining strategies accountability can be delegated to another role or process (and with the accountability having changed from “_Establishing priorities and Strategies for the Circle_” to “_Judging the relative priority of Circle efforts on request to resolve priority conflicts across Roles_”) it would be for another thread more likely, a little bug. There are three scenarios in my mind, first one is if it's close to the current way of duties for the strategies, so more likely changing something like (with [] meaning it would be deleted) “_You must **judge**, integrate and align with any [official prioritizations or Strategies]**relative priorities** of the Circle[, such as those specified by the Circle’s Lead Link], when assessing how to deploy your time, attention, and other resources to your work within the Circle._”. The idea of adding “judge” is that people place also their thinking forward.

The second one, maybe doing something simpler, editing the accountability of Lead Link role “_Judging the relative priority of Circle efforts **and value** on request to resolve priority conflicts across Roles_” along a duty in [2.3.1](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#231-duty-of-transparency) to “_(g) Cost: Estimate time and effort cost for [res_”, I'd, however, put time and effort/energy, as something may naturally be long but ask little energy or the other way around.

Question is, is this new thing close to relative priorities in which case may be integrated with it (like by just clarifying/extending a bit the relative priorities definition), or is it totally different? And I'm also questioning if it's needed to be put in the Constitution (as we may speak of the intended point application) as effectively, in a service company I may perfectly see that, but for example, in a retail company, I don't see much (with relative priorities and heuristics being fine from what I can observe), so depending on the concrete cases, I'd more likely go with the third option which would be:

[1.3.2](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#132-lead-link-defines-priorities--strategies)

“_A Circle’s Lead Link may define relative priorities and **“work values”** for the Circle._

_In addition, the Lead Link may define a more general “Strategy” for the Circle, or multiple Strategies, which are heuristics that guide the Circle’s Roles in self-identifying priorities on an ongoing basis._”

Letting the Lead Link so publish/express those “work values” and people self-prioritise in function of this (or were you wishing something more pushy?).
A concrete example would be nice which is creating you this tension even if I (think) see what you're talking about.

**Comment by brianjrobertson** [comment]
That was helpful @LouisChiquet, thanks!  Inspired by your suggestion, I'm going with a generic change to replace the Lead Link "defining relative priorities" with the lead link "judging relative value", and making the duty to integrate and align with the value so declared.  That can be interpreted many ways, which is the idea - it could be interpreted as simply a stacked rank relative priority (i.e. "which is more valuable?"), but with the more generic and value-based language a role-filler could also push back and request more clarity on the relative value of each, not just a stacked-rank priority; and likewise, the lead link could refuse to make a simple stacked-rank priority decision, and instead choose to only offer the relative weight in value between them, leaving the role-filler to figure out the ROI from there given their own effort estimates.
