### ISSUE TITLE
Proposal to add a Section ahead of 2.4.1 Role Assignment for Defined Roles

### ISSUE THREAD

**Issue by MiekeByerley** [holacracyone/Holacracy-Constitution#22]
Another embedded Definition under 2.1 Circle Basics, (the Roles a Circle defines are its “Defined Roles”). Anyone filling a Defined Role within a Circle is a “Circle Member” of that Circle.

Propose to make it Section 2.4 Defined Roles: The Roles a Circle defines are its “Defined Roles”. Anyone filling a Defined Role within a Circle is a “Circle Member” of that Circle.

As it pertains and provides a foundation for that Section.

**Comment by brianjrobertson** [comment]
I'll adjust, thanks!
