### ISSUE TITLE
Clarify how objection criteria #4 applies in Anchor Circle without LL

### ISSUE THREAD

**Issue by bernardmariechiquet** [holacracyone/Holacracy-Constitution#222]
[Section 4.2.1](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#421-lead-link-for-the-anchor-circle)

There is different interpretations and some confusion coming with re being valid or not an objection which is not limiting a role filled by the objector. 
The following phrasing is not explicit enough : _If the Ratifiers leave the Anchor Circle without a Lead Link, all decisions that normally require Lead Link authority become valid outputs of the Circle’s Governance Process. Any Role within the Circle may thus exercise Lead Link authority operationally by making a Proposal via the Circle's Governance Process._

Don't know yet how to amend here - any thought?

**Comment by brianjrobertson** [comment]
@bernardmariechiquet Can you share more what the different interpretations are?  I'm not seeing a possible interpretation where the objection criteria wouldn't apply per-usual; can you share the logic of whoever thought it wouldn't?

**Comment by bernardmariechiquet** [comment]
@brianjrobertson Sure, happy to share. In a Board (without LL) meeting, there was a gov. proposal and an objection raised, the Facilitator tested it using 4th criteria re limiting your role. The proposal was not limiting any defined roles filled by the Objector within the Board but from Objector's perspective was that he was objecting from LL role using the interpretation he has re section 5.2.2 . The Secretary had another interpretation of same section. Is that clearer ?

**Comment by brianjrobertson** [comment]
Interesting.  That's definitely not the intent; I'll queue this up as an issue for clarification.  In the meantime, you could consider a policy that board members can appeal interpretation questions to H1, and that the Board Secretary is bound to use them... I would love to see H1 create a role to rule on interpretations as a service to the community when needed, and that would help us understand where more clarity is needed as well...

**Comment by bernardmariechiquet** [comment]
I will suggest next time I see that client a Policy to appeal interpretation to H1.
I'd be curious to get your interpretation in such case.

**Comment by brianjrobertson** [comment]
I looked at this a bit further, and I actually think that this issue may be indicating they need greater role clarity at the board level, rather than constitutional clarity that any board role can object as Lead Link; especially with the removal of Cross Links, there is now a need to carefully define board-level roles to ensure they're representing what you want them to represent, and not what you don't (actually that need was probably always there, but thinking of them as Cross Link that could act as a Lead Link probably hid it).  So, I'm closing this issue.
