### ISSUE TITLE
Who calls and facilitates first governance meeting of new circle?

### ISSUE THREAD

**Issue by tylerdanke** [holacracyone/Holacracy-Constitution#223]
Initial structure paragraph 5.3 in live constitution. 4.2 in development version.
A new subcircle is created by a governance meeting. Who calls for and facilitates the first governance meeting?

Currently it would be logical to use the Initial Structure paragraph in the Adoption Matters section to state that the Lead Link would call the first meetings and hold the first elections of those new circles.  But it is a bit clunky to use an Adoption Matters paragraph to be used when this is not a matter of a new adoption but only the creation of a new circle. 

If we use the "initial structure" paragraph to say that the Lead Link holds the first governance meeting, the Lead Link of that new subcircle can also define additional governance? Seems like a dangerous thing

**Comment by brianjrobertson** [comment]
I think this is already covered by the rules for surrogates:  https://www.holacracy.org/constitution#art254
