### ISSUE TITLE
Allow Super-Circle to remove Rep Links by providing alternate pathway

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#226]
As a Super-Circle, I'd like to be able to provide an alternate pathway that meets the tension processing need of Rep Links and then remove the ability for Rep Links to join my meetings, so that I can have a *lot* of Sub-Circles when that's appropriate, without overwhelming my meetings with Rep Links.

**Comment by oliviercp** [comment]
To clarify the tension: do you need them to have an alternate pathway for governance only, or for tactical meetings too — i.e. Rep Links processing tensions operationally outside of tactical would not enough?

**Comment by brianjrobertson** [comment]
Governance only; there is no alternate pathway needed for tactical meetings, because there's nothing you can do in a tactical meeting that you can't do outside a tactical, and the duties you can rely on operationally are no longer limited just to fellow circle members.
