### ISSUE TITLE
Remove Rep Links from default meeting attendance; allow opt-in to process tensions

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#227]
As a Super-Circle, I'd Rep Links to not be invited to meetings unless they've opted-in with a specific tension to process, so that newer Holacracy practitioners acting as Rep Links aren't showing up just to be involved where they perceive the power to be, and so my meetings stay leaner and don't cost so much in people's time unless there's a tangible reason for them to.

**Comment by bernardmariechiquet** [comment]
This is a great one, makes a lot of sense to me (many use cases) as it would remove the inconvenience of having too many people in the meeting. I would argue to allow Policy like "Any Rep Link may show up only in the case they have a tension they'd like to process and are fully prepared for that (meaning they feels it and has got all the required elements to do so including context, concrete case, etc"

**Comment by brianjrobertson** [comment]
I tried to implement this, and realized it's actually already perfectly allowed in v4.1 language: the Secretary must notify all Core Circle Members of the intended meeting, but has no requirement to actually invite them to the meeting (although they do have the right to show up and participate if they choose, and could of course ask the Secretary to include them on the meeting invite).  So, I don't believe any constitutional changes are needed here; there's no reason a Secretary couldn't just start doing this, or a coach couldn't instruct Secretaries to do so as a best-practice; given the change submitted for #226, a circle could even pass a policy saying the Secretary can't include Rep Links on a meeting invite and Rep Links can't attend unless the Rep Link explicitly requests it.  So, unless the intent is to _demand_ Secretaries not invite Rep Links, there's nothing needed here; and I don't think we want to mandate that constitutionally.
