### ISSUE TITLE
Limit non-partners filling Roles to only those who have agreed to enact all duties required of the assignment

### ISSUE THREAD

**Issue by tylerdanke** [holacracyone/Holacracy-Constitution#229]
1.4.3, 1.4.1, and 3.2 refer to external contractors, volunteers who are not Partners but who fill a role. This is not consistent with the definition of the term partner in the preamble.

**Comment by brianjrobertson** [comment]
I don't see any inconsistency; someone can agree to operationally do some work without "agreeing to take part in the **governance and** operations of the Organization" and without "also agreeing to be bound by [the Constitution's] duties and constraints."  Am I missing something?  How could it be clearer?

**Comment by tylerdanke** [comment]
I think what i am getting at is that it is awkward to allow someone role assignment without being a partner with all of the constitutional duties of filling a role. I wonder if those volunteers or external contractors should be Role Supporters and not Role Leads. Then it would be explicit as to who would have the constitutional role filling duties.

**Comment by brianjrobertson** [comment]
Hmm, I can see the value of limiting external parties to Role Supporters unless they've agreed to enact all of the duties a partner Role Lead would have... that makes a lot of sense.  Anyone else have thoughts on this?
