### ISSUE TITLE
Re-Order Article II Sections

### ISSUE THREAD

**Issue by MiekeByerley** [holacracyone/Holacracy-Constitution#23]
To provide a more aligned flow of ideas and development of Concept. Suggest the following Order of Sections: 

2.1 Circle Basics
2.3 Core Circle Members
2.4 Role Assignment (Defined Roles) see issue raised pertaining to this.
2.2 Circle Lead Link
2.5 Elected Roles
2.7 Cross Linking
2.6 Sub-Circles

**Comment by brianjrobertson** [comment]
This is quite a complex change; it's important terms are defined before their first use; "Lead Link" is used in 2.3 and 2.4, and "Sub-Circle" is used in 2.7, so this suggestion would require a pretty massive restructuring to figure out a way to avoid using the terms before the definition.  If you want to take a stab at that and submit a pull request I'll definitely consider it, but it's outside of the scope of anything I want to attempt at this point.

**Comment by MiekeByerley** [comment]
I'll have a look at it if I can help you. I will wait for v4.1 to be finalised and published before tackling this. Thank you for your vote of confidence and trust.
