### ISSUE TITLE
Is it helpful to post wording questions, wording feedback, or general questions/concerns as issues?

### ISSUE THREAD

**Issue by jennyslack** [holacracyone/Holacracy-Constitution#238]
Hey I am new to git hub and this is my first/second read through the 5.0 constitution in process of being updated. I have a bunch of feedback and questions and after beginning to post questions I realized this might not be the right method for processing that. I would love to support the development of this constitution. Is this the best place/method for that? Is whom ever is working ready for feedback of a new to the new document person?

**Comment by tylerdanke** [comment]
I am not the authority here but I thought I might be helpful by trying to answer your questions. Creating new issues or commenting on the existing issues is probably the most effective way to process your proposals with the 4.1 or 5.0 versions. This open github issues section is the right method for processing that and supporting the development of this constitution. @brianjrobertson  fills the Constitution Steward Role where he is accountable for "Drafting successive versions of the Holacracy Constitution to concretize and formalize effective patterns and core best-practices that have emerged in the practice and application of Holacracy." I have gathered previously that Brian is interested in and the entire purpose of this publicly viewable github repository is to hearing feedback.

**Comment by brianjrobertson** [comment]
Hey @jennyslack , sorry for the delay in response here; yes, I'd love to get your feedback.  The most helpful way to do that is to comment on the submission that made a change or in the issue that the change was solving, vs. opening a new issue; but do feel free to open a new issue if that's not easy in any given case - that's better than not sharing the feedback.

**Comment by brianjrobertson** [comment]
Note also that questions may not always get answered here, as the purpose of this platform is constitution development vs. learning, though do feel free to share questions as the development purpose is sometimes served by seeing what Q's people come up with.  HolacracyOne will be creating  others forums to help people meet their learnings needs for the new version once it's closer to launching (starting with the Holacracy Forum - I'll be leading a few sessions on v5.0 changes there).
