### ISSUE TITLE
Minor formating and sentence structures.

### ISSUE THREAD

**Issue by MiekeByerley** [holacracyone/Holacracy-Constitution#24]
PREAMBLE: The "Ratifies" adopt these rules (instead of: are adopting these rules)

1.2 Responsibilities of Role Filling: As a Partner of the Organization, you have the following responsibilities for each Role you are assigned to, (add: as per the following sections.) 

1.2.3 Processing Projects: including the defining of Next-Actions (instead of: Including by defining Next-Actions)

1.3 Authority to Act: any Next-Actions you reasonably believe to be necessary or desirable (instead of: any Next-Actions you reasonably believe are necessary or desirable)

2.1.1 Defining Roles & Policies: replace all "create" with "define".

**Comment by brianjrobertson** [comment]
Re Preamble:  Because this document is not itself signed, I think the current language makes more sense.

Re 1.2:  Not sure why those extra words would be needed?  The sentence already ends with a colon, and it seems obvious without that, no?

Re 1.2.3:  Current language is more action-oriented and direct; not sure what the value of this change would be.

Re 1.3:  This was already changed (see current head revision) to just "any Next-Actions you reasonably believe are useful for..."

Re 2.1.1:  Done, thanks!

Please feel free to re-open if you have further pitches/clarifications re any of the above.

**Comment by MiekeByerley** [comment]
PREAMBLE: I completely understand the signing part. However, the sentences convey different sentiments. The original is a Present Incomplete Action 'The "Ratifiers" are adopting these rules', in other words it is still in the process of adoption and has no binding effect (statement of intent). The proposed sentence particle is a Present Complete Action 'The "Ratifiers" adopt these rules', in other word it has been adopted and has a binding effect (statement of declaration). If a company is using the constitution then it necessitates that they have adopted it, and if they have adopted it requires a 'Statement of Declaration' whether this is on the Constitution Document or as a separate Annexure. 

1.2 Responsibilities of Role Filling: As a Partner of the Organization, you have the following responsibilities for each Role you are assigned to:
This statement leaves you abruptly hanging as it doesn't convey a finished idea. Initially I was looking for a bullet point list (and asking myself where the remainder of the paragraph was) but eventually realised that the points below related to it. By adding the proposed wording it completes the idea and automatically draws the expectation of the reader to the next section. 

1.2.3 Processing Projects: Including by defining any Next-Actions useful to move the Project forward.
This is a grammatically incorrect sentence structure as you cannot have a 'Preposition' between Including and defining, it should come after the 'Verb' defining which then requires an 'Article' before said verb. The proposed wording fixed the grammatical error.
