### ISSUE TITLE
Please clarify the procedure for improving translations

### ISSUE THREAD

**Issue by MaxTranced** [holacracyone/Holacracy-Constitution#240]
I am reading the Constitution in English and Romanian (my native language) in parallel (for better understanding). I am not a lawyer, nor a professional translator. I did notice many shortcomings in the translation.

Can I submit a pull request for the translation? If so, which version should I base the pull request on? v 4.1 which I have printed out, or the latest English version on github? What is the process for accepting the pull request?

My only qualifications are that I care about correct use of language, that I work for an organization using Holacracy and that I have basic understanding of the concept of holon and of integral theory. I request no compensation for my work nor any mention of my contribution.

If these points are clarified it might be a good idea to write the guidelines in the repository Readme for future reference.

Thank you!

**Comment by MaxTranced** [comment]
Also, if it is possible, I am willing to fill a role (in the HolacracyOne org) that is accountable for maintaining the Romanian translation up-to-date, as long as filling that role does not imply qualifications as a lawyer on my side nor tax reporting in the US. I am willing to do this work unpaid. I am OK with a lawyer checking and changing the translations.

**Comment by MaxTranced** [comment]
OK, so I've found this
https://github.com/holacracyone/Holacracy-Constitution-4.1-ROMANIAN/blob/master/Translation-Guidelines-EN.md

Based on that information, my new questions are:

* Who can modify the Readme file of the Romanian Constitution repository so that it includes a link to the guidelines?

* Who is the Translation Steward for Romanian? I found this role
https://app.glassfrog.com/roles/1675814
but it has a different name. I might spend considerable resources on improving the existing translation an would like to maximize the likelihood of it being accepted.

* How can I fill the Translation Steward role? Can I do that as an unpaid partner that does not need to report taxes to the USA? Can I do that if I have not studied the law?

**Comment by oliviercp** [comment]
Hi @MaxTranced, Olivier from HolacracyOne here. Thanks for offering to help with the Romanian translation!

Right now there is no Translation Steward for Romanian, so you just became the one :) There is no formal/legal status at play here, it's just our way to determine who in the community is the point person for a specific language. So I'll add you as an Admin for the Romanian repo.

**Comment by oliviercp** [comment]
@MaxTranced As far as I know, there is no one active on the Romanian translation at the moment, so you're basically on your own. Feel free to make the improvements that you see fit. And of course feel free to bring people to help you if you know any!

Thanks again for your time and willingness to make Holacracy more available to Romanian-speaking people :)

**Comment by oliviercp** [comment]
@MaxTranced Can you give me your name and email, so I can add you to our internal list of Translation Stewards, in case we need to contact you?  You can email me at olivier at holacracyone.com

**Comment by MaxTranced** [comment]
Thank you @ocompagne. I've sent you an email.
