### ISSUE TITLE
Define Harm

### ISSUE THREAD

**Issue by tylerdanke** [holacracyone/Holacracy-Constitution#241]
harm is not defined.

**Comment by brianjrobertson** [comment]
It's not actually used in the constitution...

**Comment by tylerdanke** [comment]
5.0 actually does now. Even if it didn't,  i would like to pitch that it is
not well enough explained.

**Comment by brianjrobertson** [comment]
Ah, good point, it is used.  Please feel free to re-open a new issue with either a specific suggestion to improve it, or a more specific argument on why the current text (and the sentence after harm is used) leaves too much ambiguity (ideally with a real example of when the lack of clarity got in the way).
