### ISSUE TITLE
Change Project to Result?

### ISSUE THREAD

**Issue by KoenVeltman** [holacracyone/Holacracy-Constitution#242]
During implementation there is often confustion about what a Project is. Especially compared to what a project is in the traditional sense (a very large thing you do as a team).
One of my clients suggested to change the name Project to Result. As that is how I explained it (A result or outcome you are going after).

its an easy word that people normally use in office settings.

Works great in tacticals "I like to request a Result from role X". "is it an action or a result you are looking for?"

I am indifferent between naming it a Result or an Outcome. Both great replacements of the word Project. Although Result is slightly more natural than Outcome in everyday language (at least in my work contexts).

Also for mature teams this can be a great language feature.
Have to look out though to make it not too cheesy. Are words like "results bord" "results progress round" working?

**Comment by julianeroell** [comment]
I like the general direction of this. Personally, I am used to using "Project" in the GTD sense of "any thing that has more than one step", so the term was never awkward for me, but many learners stumble over it.

As to using "Result" or "Outcome" - yeah, it _can_ work; and at the same time "Results Board" sounds weird (even wrong: as it will show _ongoing work_ and not what is commonly called an (end) "result"). 

My gut feeling is that even if we called "Projects" "Results", we would still use the word "project" for _the process of working on a "Result"_. Not sure if we'd have accomplished much then, but it would probably be safe to try. ;-)

Curious what other people think about this.

**Comment by brianjrobertson** [comment]
I generally think this would be a bad move, and contradicts the general strategy I'm applying of using words a novice user is more familiar with and then reshaping their meaning, over introducing new distinctions they're less comfortable with.  It also breaks the overlap in our definitions and GTD definitions, which is a more minor but still significant negative in my view.

That said, I'm leaving this issue open to collect other perspectives to consider before I dismiss it.

**Comment by pjedrzejewski** [comment]
I'm also in favor of leaving the term "project", which is taken from GTD. We just set the convention that project names are written in past tense and represent expected outcome/result. New people seem to pick-up the concept during the first tactical meeting.

**Comment by LouisChiquet** [comment]
I agree that the project in Holacracy is usually different from how it is used in most organisations, however as said before, just need a few meetings for people to fully catching it (and they generally catch it easily if it's during a training). Project have a pretty clear and concrete definition when compared to other Holacracy terms, therefore I don't see much the need to change it.

**Comment by brianjrobertson** [comment]
Dropping this idea given feedback above plus my own sense of it.
