### ISSUE TITLE
3.3.5b: Allow for Clarifying not just Answering Questions

### ISSUE THREAD

**Issue by chrcowan** [holacracyone/Holacracy-Constitution#244]
I was trying to interpret whether or not there is any place in Present Proposal (PP) or Clarifying Questions (CQ)...for someone to "ask" the Proposer, "Hey, could you walk me through the proposal again?" or "Could you kinda go over it again...what the tension is and what the proposal is?"

Because as far as I can tell, there is no justifiable interpretation I can make to do that....and yet...there is a certain sense about it in which it could be helpful for someone to request that...but it's an action, not a question.

I think maybe the problem is in how the constitution section 3.3.5b is written. 

It says, "The Proposer may answer each question," but the request to review the proposal isn't a question. So, for example, if someone asked a proposer to do that, as a coach I can't elegantly offer the proposer to say "Not specified." Instead, I might prompt the Proposer with, "And you can say, 'No.' You're under no obligation to explain the proposal," or something like that. Anyways, it's just a little different. 

I think if the constitution said, **"The Proposer may clarify,"** instead of "The Proposer may answer each question," then there would be more room for interpretation and I could better justify allowing someone to request that of a Proposer.

**Comment by brianjrobertson** [comment]
Hmm, I don't get that interpretation @chrcowan, so I'm going to need to see a few more people here who share it before I'm convinced this is a issue that affects more than just you Chris.  :-)

That definitely looks like a question to me, and the answer may be "Yes, I can; and here's the walkthrough...", which sure seems like an answer to a question to me.  And if someone really nitpicks that it's not (which I already don't get), then the question could just be rephrased "What's the tension and the proposal?", which is unambiguously a question that would allow a response of going over it again as far as I can tell.

**Comment by rogerpfaff** [comment]
In our relative short time with holacracy and in my role as facilitator I never had a problem with that question. In fact the question comes up now and then because we are doing the meetings remote and it is always important that people can ask this to comprehend the tension and proposal.

**Comment by chrcowan** [comment]
Well, when I've seen the request it's coming with a hint of energy or expectation like, "You need to explain this to me," or "You need to sell this idea to me," or something like that. It's subtle. With an emphasis that puts some pressure on the proposer to make sure the requester understands, which they obviously needn't do. I could always help them rephrase their question into, "What's the tension and proposal?" or something like that. But since I also understand the request as a legitimate attempt to gather information, I was trying to get more clarity on what to do with it. 

My thinking was that this change wouldn't restrict this type of clarification (or allow me to more easily interpret it as a valid request), but as I'm writing it out now, if my tension is really the pressure/expectation thing, then I can more easily define that as a reaction, and help the questioner rephrase. So, maybe that pathway is better left closed. 

I don't know. There is still something off with it. But it doesn't seem like a rule problem, and maybe just an execution/coaching problem.
