### ISSUE TITLE
Change "the lead link holds the purpose" to "the lead link handle the purpose".

### ISSUE THREAD

**Issue by jeanlucchristin** [holacracyone/Holacracy-Constitution#246]
Hello,
About the appendix A, I propose to change "The Lead Link holds the Purpose of the overall Circle" with "The Lead Link handles the Purpose of the overall Circle".
Holds, in my representation, means contains, prevents from living too intensely. This is not what is expected from the lead link. The lead link must discover the purpose of the organization, the "deepest creative potential the organization can sustainably express in the world". This purpose may changes at any time.
Handle is more like giving shape to what is there, appearing. If you touch your nose just now, you are more aware of your nose. (you handle your noze, you don't hold it). This is what the lead link must do: give shape to the purpose so that everyone can be more aware of the purpose up to date.

**Comment by brianjrobertson** [comment]
The line you're referring to is literally just saying that the purpose of the Lead Link role equals the purpose of the circle; it isn't trying to say there's any special duty to handle the purpose beyond that of every other role; each role has a purpose, and each person filling the role has the duties described elsewhere for expressing that purpose. Thus, this proposed change doesn't make sense to me.  I could see an argument for it saying the Lead  Link "has" the purpose, but not anything that implies the lead link should do something - this is just defining the role, not the duties.
