### ISSUE TITLE
Change concern about "adopting the proposal" to concern about "experimenting the proposal" ? 

### ISSUE THREAD

**Issue by jeanlucchristin** [holacracyone/Holacracy-Constitution#248]
"3.3 Changing Governance

Any Circle Member of a Circle may propose changing its Governance by circulating a “Proposal” to all of its other Circle Members, thus acting as “Proposer”. Before the Proposal is adopted, those other Circle Members must have the opportunity to raise concerns about adopting the Proposal."

I observe that the posture is not the same when people remember that it is possible to change a proposal at any time (in a future governance meeting) if its effects impact a role.
My proposal is to note it upstream, when presenting the principle of objections.

**Comment by LouisChiquet** [comment]
What do you mean by “_that it is possible to change a proposal at any time if its effects impact a role._”? As it's not really my interpretation of the Constitution.

If you mean, object during objection round, and that it impact their role, for me it's part of the [3.3.2 Criteria for Valid Objections](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#332-criteria-for-valid-objections) and just need to some coaching/pedagogy/understanding. Maybe there's the need to further clarify the 3.3, but at the same time, it's just the header of a sub-article (Article 3), which itself have sub-articles, such as the Criteria for Valid Objections. Maybe just stating “_Before the Proposal is adopted, those other Circle Members must have the opportunity to raise concerns about adopting the Proposal **following criteria in 3.3.2**._”, however as it's a header, I don't see much the utility, and knowing that there's also article [3.3.3 Testing Objections](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#333-testing-objections) and it concerns other sub-articles. I don't know if I'm aligned with your message?

**Comment by jeanlucchristin** [comment]
@LouisChiquet,
by “that it is possible to change a proposal at any time if its effects impact a role.” I mean that people can experiment with the proposal, observe if tensions arise, and in this case go back to the proposal and change it at any time in a governance meeting. 
I change the issue just now to be clearest

**Comment by brianjrobertson** [comment]
I'm not sure what this issue is concretely suggesting or calling for; what would you change, from what to what?

**Comment by jeanlucchristin** [comment]
I would change 

"3.3 Changing Governance

Any Circle Member of a Circle may propose changing its Governance by circulating a “Proposal” to all of its other Circle Members, thus acting as “Proposer”. Before the Proposal is adopted, those other Circle Members must have the opportunity to raise concerns about adopting the Proposal."

To

"3.3 Changing Governance

Any Circle Member of a Circle may propose changing its Governance by circulating a “Proposal” to all of its other Circle Members, thus acting as “Proposer”. Before the Proposal is adopted, those other Circle Members must have the opportunity to raise concerns about        EXPERIMENTING     the Proposal."

**Comment by brianjrobertson** [comment]
This seems to me like it would have a predominantly negative impact, by reducing the weight of the enacted governance, and encouraging people to try to change or stop the "experiment" without more governance to do so.  It's also misleading - the proposal is being adopted and that governance will stick around and be in full force and effect until changed.  So, I'm dropping this suggestion.
