### ISSUE TITLE
“People” term

### ISSUE THREAD

**Issue by LouisChiquet** [holacracyone/Holacracy-Constitution#249]
I see there's 3 times the usage of “people” in the Constitution. While the term Partners is clarified in the Preamble, and the term “external parties” which is used is pretty explicit to me, I'd like to clarify the term “people”, by saying “Partners and external parties”, which would give a change like this: https://github.com/holacracyone/Holacracy-Constitution/compare/master...LouisChiquet:patch-5

Don't know if it make sense?

**Comment by brianjrobertson** [comment]
While I think it'd be great to add this extra clarity, I don't think it's worth the cost of extra words and making the sentence harder to quickly read and understand.
