### ISSUE TITLE
1.4.1 Domains Impact

### ISSUE THREAD

**Issue by LouisChiquet** [holacracyone/Holacracy-Constitution#250]
This concerns [Article 1.4.1](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#141-circle-lead-holds-undifferentiated-functions), and [Article 2.2.1](https://www.holacracy.org/constitution#art221) in the 4.1, which is the following:
_The Circle Lead Role inherits the Purpose and any Accountabilities on the Circle itself, and controls any Domains defined on the Circle. However, within a Circle this only applies to the extent that those Accountabilities and Domains have not been placed upon one of the Circle's Roles or otherwise delegated._

Fortunately, there's [Article 2.1.2](https://www.holacracy.org/constitution#art212), however I find it “not beautiful” the way it is redacted (as it's a bit in opposition with 2.1.2), and would question why not just remove the “Domains” part from the second sentence?

**Comment by brianjrobertson** [comment]
The Domains part in there is what lets the Circle Lead allow an external role to impact the circle's domains.  I do agree though that this is a potential area for confusion and not yet beautiful; if you have any other ideas on how to resolve it, I'd love to hear them.
