### ISSUE TITLE
Surrogate for Absent Members

### ISSUE THREAD

**Issue by LouisChiquet** [holacracyone/Holacracy-Constitution#253]
This concerns [Article 2.5.3](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#253-surrogate-for-absent-members), which is: “_If an unelected Role invited to a Tactical Meeting is unrepresented in the meeting for any reason, a Circle Lead of the Circle **holding that Role** may act within that Role to cover the gap. If the Circle Lead Role is also unrepresented, any Next-Actions or Projects captured for the Role become requests for the Role to process after the meeting._”

“Holding that Role”, I suspect it means acting in replacement like if the Circle Lead was filling that role? However, that's not really that clear in my opinion, because as I currently read it, it means the Circle Lead have to be holding this role already? I preferred the “_the Circle’s Lead Link may act within that Role to cover the gap_” of the previous [4.2.4 of 4.1](https://www.holacracy.org/constitution#art424) which was more clear in my opinion, if that's shared? Maybe my English isn't good enough, but I feel the need to be specific on this one. Feedback?

**Comment by bernardmariechiquet** [comment]
I think the idea here is to cover the case when roles from different circles have been invited to such tactical meeting. There is a need for specifying the appropriate Circle Lead, i.e. the one whose circle *hold the role*.

**Comment by brianjrobertson** [comment]
+1 to what @bernardmariechiquet wrote; this covers the case of a cross-circle tactical meeting.  "Holding that role" here applies to "Circle", not to "Circle Lead".  Thus, it says "[the Circle Lead] of the [Circle holding that Role]"...  Hope that clarifies, but feel free to suggest a more clear wording if you have one.
