### ISSUE TITLE
Define Domain further

### ISSUE THREAD

**Issue by bernardmariechiquet** [holacracyone/Holacracy-Constitution#255]
As well done the concept of Policy has been further defined in Article 3. I would love to see the same with Domain by further defining it in order to make it more concrete and easily understandable for newcomers. Unless I'm mistaken, it is only defined as "things the Role may exclusively control and regulate as its property..." in [article 1.1](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#11-roles).
Any reactions?

**Comment by brianjrobertson** [comment]
I'm not sure what else we'd say about it; I have no specific ideas...

**Comment by bernardmariechiquet** [comment]
What I often use to explain when I am asked is : A Domain is like a "property" of the organization (e.g. asset, function, or process). I observe that enumerating the possible instances of this concept help people understand. "Things" is for many people too vague and "Domain" too conceptual.
