### ISSUE TITLE
Ambiguity re Role Governance Process in article 1.3.1

### ISSUE THREAD

**Issue by bernardmariechiquet** [holacracyone/Holacracy-Constitution#256]
Second part of [article 1.3.1](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#131-delegating-domains): 
"Once a Role controls a Domain, it may create its own Policies governing that Domain within its own Governance Process. However, the Circle that delegated the Domain still retains the right to define or modify its own Policies governing that Domain, and any such Policies trump those defined by the Role in the event of a conflict."
Such phrasing occults the fact that any Role has already got its own Domain that is "its own internal processes".
So I propose to change the phrasing by [this one](https://github.com/holacracyone/Holacracy-Constitution/compare/master...bernardmariechiquet:patch-4).

**Comment by brianjrobertson** [comment]
I'm not sure what the issue is here that you're referencing @bernardmariechiquet; can you clarify further or give an example?

**Comment by bernardmariechiquet** [comment]
I try to clarify. That's because a Role is also an *internal* Circle and as such has got its own Domains (i.e. activities and functions of the Circle) in addition of any other Domain which would be delegated by the Circle holding such Role/*internal Circle*. 
Put another way, if no Domain has been delegated to a Role by the Circle holding such Role, such Role (being also a Circle) still has its own domains, i.e. activities and functions. Is that clearer? Let me know.

**Comment by brianjrobertson** [comment]
In the current dev version of the constitution, there is no longer a default domain of that... the circle can still control its own internal processes and limit its Roles, per the scope of Policy in 3.1.1, but it's not achieved via a domain any longer, so I'm not sure if this change is still useful/needed...?

**Comment by brianjrobertson** [comment]
I'm closing this given my comment above, but please comment if you think it's still an issue.
