### ISSUE TITLE
Clarify the concept of a circle *internally* - art. 1.3

### ISSUE THREAD

**Issue by bernardmariechiquet** [holacracyone/Holacracy-Constitution#257]
My take on article 1.3 is that a Role being a Circle internally may create *internal* policies for itself whether or not it contains its own Roles to further break down how it achieves its Purpose and enacts its Accountabilities. Which would make sense IMO in the case of multiple Lead Roles (and even multiple Supporter Roles) into that Role with not yet any further defined roles into the circle, there could be a need for clarifying the way there may work together into the same Role. And a pathway to do so, would be through governance process. That would be an elegant way for multi-filled Roles to govern the work into the Role. 
I would then propose a [patch](https://github.com/holacracyone/Holacracy-Constitution/compare/master...bernardmariechiquet:patch-5) for make it clearer.
@brianjrobertson is it also your interpretation?

Another question here : does even a Role having just one Role-Filler may further break down its work withing the Role/Circle? Which could be interesting in order to give more clarity and prepare further differenciation?

**Comment by brianjrobertson** [comment]
Yes, that's my interpretation as well, in both cases.  I'm going to implement this with slightly simpler languaging; submit forthcoming...
