### ISSUE TITLE
Simplify language around which Circle Lead at which holarchic level assigns into roles

### ISSUE THREAD

**Issue by bernardmariechiquet** [holacracyone/Holacracy-Constitution#258]
@brianjrobertson I have some clarifying questions on that one.
A simple Role having just one Role-Filler being a Role Lead is automatically a Circle Lead within that Role's internal Circle, and may create (Sub-)Roles into such Circle and assign other Partners into such (Sub-)Roles in virtue of Circle Lead Domain, right? And the Circle Lead of the Super-Circle may assign other Partners into the Role either to support or to lead. So we would have 2 different kinds of assignments playing at the same time? One on the Super-Circle side, the other inside the Circle. Did I get it right or did I miss some piece here?

**Comment by brianjrobertson** [comment]
That's right; the broader Super-Circle lead is only assigning people as an overall Circle Lead (or Circle Lead supporters) to the overall Circle, not to specific Roles within the Circle; the Circle Leads of the Circle itself are assigning people into the Roles within the Circle, whether or not those people are also Circle Leads (or Circle Lead supporters).

**Comment by bernardmariechiquet** [comment]
@brianjrobertson Thanks I get it. I invite you to notice the difficulty of language to convey answers. You're using broader Super-Circle and overall Circle and Roles within the Circle. There is something I sense weird here.

**Comment by bernardmariechiquet** [comment]
It would be easier to refer one word for the Role/Circle concept and add the level of holarchy.
Roles level n are assigned by (Role Leads of) Roles level n+1. The language would be far easier.

**Comment by brianjrobertson** [comment]
Good point, it is definitely difficult to describe this clearly now.  I really don't resonate with the approach of using holarchic level numbers - I want the constitution to read as simple plain english, without anything that sounds too technical or makes you do mental math.  But I'll re-open this issue and try to find some simpler language.

**Comment by brianjrobertson** [comment]
I think this is much simpler now given some of the other recent changes, and I have one more minor tweak I'll submit here shortly.  Let me know if you think this is simple enough now, or if you still see opportunity for improvement.
