### ISSUE TITLE
Clarifying Rep Links definition in art. 1.5

### ISSUE THREAD

**Issue by bernardmariechiquet** [holacracyone/Holacracy-Constitution#259]
@brianjrobertson I am confused by the following phrasing at the very beginning of article 1.5:
"If a Circle contains Roles filled by Partners beyond just the Circle Lead(s) of the Circle"
The verb *contains* feel like this is referring to internal Roles. But we also need Rep Links for the Supporters filling the Role/Circle itself, so they have a pathway to process any tension they may have, right?
So I would suggest an [amendment](https://github.com/holacracyone/Holacracy-Constitution/compare/master...bernardmariechiquet:patch-6) to this.
Any reaction?

**Comment by brianjrobertson** [comment]
You're right, this is definitely a problem; I'd like to find some simpler language than your suggestion though, if possible - I've queued the issue up, and please feel free to suggest simpler language if you're so inspired, I'd welcome the help.
