### ISSUE TITLE
Clarifying Facilitator and Secretary definition - Article 1.6

### ISSUE THREAD

**Issue by bernardmariechiquet** [holacracyone/Holacracy-Constitution#260]
Similar issue as #259 because of teh word *its* at the very first sentence "Each Circle with more than one Partner filling its Roles automatically includes a “Facilitator Role” and a “Secretary Role”"
Or does it mean Facilitator and Secretary only appear when there are at least one Role into the Circle (and another Partner assigned into such Circle)?
In the latter I would recommend to open it up so that multi-filled Roles willing to structure the way they work into the internal Circle (even is there are no Roles defined into it) may lean on such Facilitator and Secretary capacities.
Any reaction?

**Comment by brianjrobertson** [comment]
You're right, this is a problem too, same reason as #259...
