### ISSUE TITLE
Define Circle Members along with Circles to avoid confusion?

### ISSUE THREAD

**Issue by bernardmariechiquet** [holacracyone/Holacracy-Constitution#265]
I think to clarify the *Circle internally* concept defined at Section 1.3, we should defined upfront the Circle Members, and the same moment than the definition of a Role being a Circle internally, and just after the introduction of Governance and Governance Process, so that the reader gets a clear picture of what is a Role/Circle and make it clear that Role Supporters are Circle Members as well as Role Leads.
See [patch 9](https://github.com/holacracyone/Holacracy-Constitution/compare/master...bernardmariechiquet:patch-9)

I also think we should define what is a Circle Supporter to get the Circle perspective of a Role Supporter such as we've got the Circle Lead, as this is not clear at all.

Reactions on that one?

**Comment by brianjrobertson** [comment]
The draft change you linked to requires you to use "Rep Link" before its defined, which I'm holding a hard boundary against doing; so something would have to shift here, like moving the Rep Link definition somehow (and I'm not sure that's practical).  That said, I'm also not sure why this matters or what value it achieves; why is this important to know when understanding Article 1, when it's only relevant once you get to Article 3?
