### ISSUE TITLE
"de minimis"

### ISSUE THREAD

**Issue by julianeroell** [holacracyone/Holacracy-Constitution#27]
I looked that one up in Wikipedia when I encountered it for the first time in version 4.0. (Section 2.3.3,  "Exclusion for De Minimis Allocation"). I had a hunch what it meant, but was not exactly sure. 

I see the value in using precise terminology - in this sense, using a legal technical term could be helpful - but I also see that this language makes it difficult for people to understand the meaning right away. 

Could a simpler, but equally precise wording be found for this?

**Comment by brianjrobertson** [comment]
Thanks, nice catch - I just replaced this language and snuck it into the v4.1 release.
