### ISSUE TITLE
Remove requirement that candidate be last to object in election process

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#276]
The rule that the candidate must be the last to object in the election process was inherited by default from sociocracy, where the election process came from.  I haven't yet seen any cases where this constraint is needed for effective Holacracy practices, and it adds a little bit of extra complexity, so I propose removing it - unless someone can share a good (and grounded) reason for keeping it.  Anyone?

**Comment by bernardmariechiquet** [comment]
+1 I don't see either the value added by such extra complexity.
