### ISSUE TITLE
Shift assignment power for Role Supporters to the Role Lead

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#279]
For simplicity and role/circle consistency, and to ensure a Role Lead has the autonomy to fully lead their role, I believe the power to assign (or unassign) a Role Supporter should rest with the Role Lead for that Role, not the Circle Lead; although this could always be further constrained if desired by a Policy of the Circle (e.g. to require Circle Lead approval, if that's really needed in a specific context).

**Comment by cassus** [comment]
Big 👍

**Comment by bernardmariechiquet** [comment]
@brianjrobertson Make sense! To simplify further, why not considering a Role Supporter like a (sub-)Role into the Circle, which is a kind of "service" Role with no explicit description.
