### ISSUE TITLE
Little tweak

### ISSUE THREAD

**Issue by bernardmariechiquet** [holacracyone/Holacracy-Constitution#28]
I would suggest to change the word 'of' by 'to' in section 3.2.3 Testing Proposals

"The Facilitator may test the validity of a Proposal by asking questions of the Proposer."

becomes:

"The Facilitator may test the validity of a Proposal by asking questions to the Proposer."

**Comment by brianjrobertson** [comment]
Hmm, that doesn't sound like customary English usage to me Bernard Marie; you ask questions of someone, not to them.  You direct questions to someone; but you ask questions of someone.

**Comment by bernardmariechiquet** [comment]
Thanks Brian for english lesson :)

**Comment by MiekeByerley** [comment]
I do understand @bernardmariechiquet's point somewhat. 'Asking questions of the proposer.' is not really correct either, 'Asking clarification of the proposer' or alternatively 'by questioning the proposer. 'Asking and Questions is actually doubling up the verb. :)

**Comment by julianeroell** [comment]
how about "by asking the proposer questions"? (This is how I changed it in my latest version. "Asking questions of.." sounded strange to me. https://github.com/martinroell/Holacracy-Constitution/commit/6bd775d328efa4e505768a3ba03debf0f3be1c5f)

(I like "questioning the proposer" too, but I get images of an interrogation with that. :-))

**Comment by brianjrobertson** [comment]
True, but the verb "asking" conveys a different (and more appropriate) energy than "questioning", which has a slightly more challenging connotation.  And it's not asking clarifications exactly...  So, while I don't like the doubling-up on the verb, I'm not sure I see a better approach in this case.

**Comment by MiekeByerley** [comment]
A good way to think about it is 'What are you Asking for' and 'Who are you asking it from'; or 'Who are you questioning' and 'What are you questioning for'.

**Comment by MiekeByerley** [comment]
Maybe this phrasing? The Facilitator may test the validity of a Proposal by asking the Proposer questions.

**Comment by brianjrobertson** [comment]
Brilliant, done.  :-)  And Martin had the same change suggestion for asking questions re validity of Objections, so I've changed that too.

**Comment by MiekeByerley** [comment]
:+1: Glad to be able to help
