### ISSUE TITLE
Allow Circle to change which internal roles outside role references point to

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#281]
Sometimes, governance outside of my circle references my circle as a whole or a specific role within my circle; when that's the case, as a Circle Lead, I'd like to be able to change that reference to point to a specific role within my circle or another role within my circle than was initially named, without having to make a proposal outside of my circle.  Said another way, I want to be able to treat all references into my circle as just references to my circle overall (and just a best-current-guess beyond that), and then control the further delegation of those references myself, without bothering the broader entity with that detail, and definitely without requiring integration outside of my circle (which violates our boundary and inhibits our ability to self-organize effectively).

So, for example, if I'm leading a Marketing Circle, and some governance outside the circle references sending something to my "Social Media Poster" role, but then my circle changes something and the most appropriate reference is now a "Social Media Strategy" role, I'd like to be able to just change that reference without any governance act required outside of my circle.  Or, another example: if some outside governance just references "notifying @Marketing_Circle", but we create a more specific role to receive and process that notification, I'd like to be able to define that and have that external reference update to the more specific role, without going through the outside governance process where that reference appears.

Open question: Should governance be required _inside_ of my circle to make these changes, thus requiring integration with my own circle's roles, or should this be an autocratic operational authority of a Circle Lead outside of governance; any thoughts?

**Comment by dawizsimpson** [comment]
I would lean towards allowing it to be an autocratic operational authority of the Circle Lead. I believe the Circle Lead should be the most familiar with its contained roles and going this route reinforces the concept of the external governance viewing that Circle Lead as just another role in the Super-Circle. It seems like unnecessary overhead to have to process these changes within the circle.

**Comment by cassus** [comment]
I'd go for Autocratic operational authority by default that can be changed by governance (same as all other LL authorities)

**Comment by bernardmariechiquet** [comment]
Should be an autocratic operational authority of a Circle Lead outside of governance per default.
