### ISSUE TITLE
Domains and Policies

### ISSUE THREAD

**Issue by jennyslack** [holacracyone/Holacracy-Constitution#286]
I was working on some internal training and had a realization that might just complicate things but might be worth exploring so I thought I'd throw it out there. I love the way the new constitution gets rid of the idea that a circle and a role are somehow different and I love the emphasis on simplicity. In that energy I wonder if Domains and Policies are also "the same" the way a Role and a Circle is "the same". Both domains and policies grant or restrict authority around an organizational resource, a domain does that broadly and a policy often does that more narrowly or specifically. Maybe there is value in the distinction between a domain and policy but I figured as the massive rewrite is occurring it would be worthwhile to offer that reflection up for thought.

**Comment by cassus** [comment]
If Domains weren't a thing I can imagine they would emerge as a policy-template that we copy-pasted a lot with some blanks and some places when sometime customize.

**Comment by LouisChiquet** [comment]
I very much like the idea mentally, however I don't see how it would concretise itself, plus those remain two very distinct concepts in the day-to-day and explanations even if both linked. Do you have some concrete cases of tensions pushing towards this? Or it's more an idea to theoretically “simplify”?

**Comment by cassus** [comment]
I can't remember the details, but I saw tensions around this when the circle granted a domain but still wanted to limit how the subcircle uses the domain. This created a separate Domain and Policy and it was hard for people to connect them mentally.
In practice I could imagine domains having a "name" and an optional "policy" field next to them in glassFrog if a circle wants to customize how they grant a domain

**Comment by jennyslack** [comment]
I would say I posted this less because I had a tension of it not working well but more because I had a tension that it could be better, simpler. I think when I explain holacracy domains and policies tend to be the hardest part for new practitioners to wrap their head around. There is certainly frequent confusion on our team about domains and policies both in understanding how to use them in governance and how to search current practice in glassfrog. I see a concrete need for this to be better but I also think the simplifying of the role/circle structure will already help.

**Comment by brianjrobertson** [comment]
I've reflected on this and am not seeing a path to simplify this by merging the two, without adding complexity in the process; so I'm going to close this, but if anyone has a concrete idea or wants to take a stab at implementing it, please do feel free to share...
