### ISSUE TITLE
Drop criteria to allow proposals to “clearly reflect activity that is already happening”

### ISSUE THREAD

**Issue by margauxchiquet** [holacracyone/Holacracy-Constitution#287]
Hi Brian,

We've encountered a case where someone brought a tension underlining the criteria “clearly reflect activity that is already happening” of its proposal. The proposal wasn't about that person but about the work of another person and this other person did the work once as individual action but didn't have the intention to do it regularly as it doesn't make sense. So, how the Facilitator can test that? If someone wants to clarify the work of another person, just to put reality that is in fact not a pattern or just something that person wants to do as support? Or, how can the person object?

Do you need more context?

For reminder:

3.2.1 Criteria for Valid Proposals
For a Proposal to be valid for processing, the Proposer must be able to describe a Tension that the Proposer senses, and give an example of an actual past or present situation in which the Proposal would have reduced that Tension. Further, the Proposer must be able to describe how reducing that Tension would help to better express the Purpose or an Accountability of the Circle, and of a Role in the Circle that the Proposer represents or has permission to temporarily represent from one of its normally authorized representatives. However, a Proposal is always valid regardless of the preceding criteria if it is made solely to evolve the Circle’s Governance to more clearly reflect activity that is already happening, or to trigger a new election for any elected Role.

If at any point the Facilitator becomes clear that a Proposal does not meet this criteria, then the Facilitator must discard the Proposal. However, in making this assessment, the Facilitator may only judge whether the Proposer presented the required example and explanations, and whether they were presented with logical reasoning and are thus reasonable. The Facilitator may not discard a Proposal based on the accuracy of the Proposer's argument, nor on whether the Proposal would adequately address the Tension.

**Comment by brianjrobertson** [comment]
I'm wondering if that clause is even needed any longer; I can't recall the last time I've seen it actually used and matter in any way.  And it would simplify things to remove it.

Anyone seen cases where that clause has actually been useful/needed?

**Comment by margauxchiquet** [comment]
Well, what we teach clients is this: “if there is no role and you want to do it, do it and then, since you are doing it, you can bring it to governance to reflect the reality”. This works well to help people initiate new stuff but don't know if it makes sense...

**Comment by brianjrobertson** [comment]
Yes, I say that a lot too... but have you seen someone actually proposing something based on that rule, which they couldn't have otherwise proposed?  If so, is it important they were able to, or would it have been sufficient if they couldn't, knowing the lead link could always propose it (and would have a clear reason to if it's ongoing IA within the circle)?

**Comment by margauxchiquet** [comment]
We had the case in a company in this industry where someone wanted to create hives and do that work on top of his d2d work (it is one of his leasure) but the LL didn’t agree. So we coached the person to just do it and then bring it to governance under the rule « capture what already exists ». And it worked. Even if that work wasn’t for customers directly since it is a factory that produces wood materials, it made sense because it was align with the purpose of the company.
Another example I can see often is multiple people assigned to a specific role willing to clarify the work of that role (adding accountabilities) with no specific tension, just to clarify what they do and make sure others align to it as well - no concrete case of someone not doing it, just clarification of the role.

**Comment by margauxchiquet** [comment]
I am wondering how it works with the rule of individual action. I haven’t read that rule in 5.0 but in 4.1, you can act outside of your roles (IA) but if recurring, you have to bring it to governance. So I guess that covers the « capture what is already done »?

**Comment by brianjrobertson** [comment]
Hmm, your examples there are giving me a sense that this rule is actually in the way; I think the org would be better served if a Lead Link could prevent what you describe in the first case, and in the case of adding accountabilities to one's own role, I'd also love to see someone have to explain why it serves the role's purpose to do so if asked (there are lots of good reasons it might, but seems better to prevent those that don't fall into one of those good reasons)...

Good point on the connection to Individual Action though; if this rule is dropped, the easiest way to do that would be to pitch a Lead Link to do it, which is a lot more indirect than propose directly (although still would meet the need).  Hmm...  I wonder if we even need that rule in IA though; is it critical that an instance of something ongoing be necessarily brought to governance by the person doing it?  Would it cause harm to just drop that clause?  ([This one](https://www.holacracy.org/constitution#art433))

**Comment by margauxchiquet** [comment]
I agree on the first point.
Re IA, I think that if you drop it, it remove the responsability from the person taking IA. Maybe something like this: the person affected by the IA can ask the person taking the IA to bring it to governance (and stop it but that's already the case). Like that, it doesn't prevent IA.
But I am wondering... if we don't force people taking IA to bring it to governance - if recurring - by this role, isn't it causing harm to the company? Bringing it to governance is a good behavior to ensuring the organization is building capacities and learning from reality...
I am a bit confused... 
@bernardmariechiquet Would you join this thread? I know you have some good thoughts about this.

**Comment by brianjrobertson** [comment]
Thinking about this further, I'm actually really liking removing the requirement to bring recurring stuff to governance; technically it's already covered by governance anyway, assuming it serves the purpose of the overall org, and the rule as-is creates a force towards everything being explicit, where other changes in v5 are balancing in the benefit of allowing implicitness until tension indicates otherwise; removing this requirement seems aligned with those other changes and better integrating that polarity, and enables the simplest way I can think of to meet the original intent of this issue.  So, that's my current vision for solving this one; if anyone has thoughts/reactions, I'd love to hear them!

**Comment by chourie2** [comment]
I can get that it’s not necessary to have this written in the constitution, given that you could find another path to carry your tension. As I see it, the simple fact that the formal structure (the governance) diverge from the real structure is a situation that’s clearly not ideal, and therefor a Tension that many could feel (Facilitator, Secretary, and even the operative Roles concerned).

My concern about removing this, is that such matters is critical for beginners Organization in Holacracy as it can be a cause of failure in the practice that the formal structure and the real one diverge. Given that, my interpretation of the current constitution for that matter is that it allow anyone that see such pattern to do something about it.

Removing it make sens, as it could prevent situation like the one @margauxchiquet describe, but it also remove the emphasis on how important this matter is.

My opinion is that the constitution should keep this emphasis even after removing the exception.

Ways to do so I can think of:
- Additionnal duty to alert the concerned Roles about the divergence one could sense, and duty to process it
- Right for someone to act as a Role if IA are taken but not regulate in the Governance, if they need to be
- Just emphasis (maybe it’s already there, somewhere, and I didn’t get it?)

**Comment by cassus** [comment]
I'm not sure about the how, but +1 for removing the exception to allow proposals only based on "clearly reflect activity that is already happening" while somehow keeping an emphasis on aligning governance to what's happening.

**Comment by LouisChiquet** [comment]
I well heard the pro of deleting it, but they are cons. The cons, it helps a lot to deal with PowerShift issues. Sometimes, if the Circle Lead is slow on something, for instance a new activity made, or else, having this rule help greatly to allow Circle Members to not depend of the Circle Lead, allowing people to challenge the Circle Lead on this.

Another thing is, when encoding is done, sometimes some things are missing, and it can be pretty useful to have this rule, making the person doing the activity propose it, rather then the Circle Lead as he'd propose directly a purpose he likes for instance.

It is something that “balance” power in the Circle, and can be very important at the start of Holacracy practice. I'm quite often asked about this rule in new clients.

**Comment by LouisChiquet** [comment]
Also big warning: @brianjrobertson You deleted “or to trigger a new election for any elected Role.”, which is a pretty important one, as some people like to ask for elections, and not state the reasons, because they don't feel comfortable with stating those because of inter-personal issues.

**Comment by brianjrobertson** [comment]
@LouisChiquet re:
> You deleted “or to trigger a new election for any elected Role.”, which is a pretty important one, as some people like to ask for elections, and not state the reasons, because they don't feel comfortable with stating those because of inter-personal issues.

There is no requirement to state the reason when calling for an election; the criteria for valid proposals only applies to making a "Proposal" (i.e. a change to the Governance), not to calling for an election.

Re:
> The cons, it helps a lot to deal with PowerShift issues. Sometimes, if the Circle Lead is slow on something, for instance a new activity made, or else, having this rule help greatly to allow Circle Members to not depend of the Circle Lead, allowing people to challenge the Circle Lead on this. 
 Another thing is, when encoding is done, sometimes some things are missing, and it can be pretty useful to have this rule, making the person doing the activity propose it, rather then the Circle Lead as he'd propose directly a purpose he likes for instance.

My current thinking is that allowing this is not a good thing, and not important for the power shift (or even harmful for the business needs).  See this comment of mine above for more:
https://github.com/holacracyone/Holacracy-Constitution/issues/287#issuecomment-426027247
