### ISSUE TITLE
Élection process : quickly clarify the criteria required by the role

### ISSUE THREAD

**Issue by jeanlucchristin** [holacracyone/Holacracy-Constitution#291]
hello I would like a step to be added in the integrative élection process to allow the participants to quickly have in mind the criteria required by the role. 

for example :

3.3.6 Integrative Election Process

(a) Describe Role

« (B) characteristics : 
the facilitator asks the circle members what characteristics should be fulfilled by the person assigned to that role.
characteristics may include skills, availability and motivation. »

(b) Fill Out Ballots

**Comment by brianjrobertson** [comment]
Is it important that the Facilitator be able to solicit that from the group vs. just share it themself (the latter is already allowed)?  If the former, can you share more about the need you're sensing behind wanting that, including any examples you've seen of where it would be helpful, and why?

**Comment by jeanlucchristin** [comment]
ok, I understand your need.

I have experimented with and without

Clearly, I observe that the circles are much more precise, effective, fast in the process after having invested a few minutes to define the required characteristics.
they are also automatically "role" oriented, with less temptation towards the "people" aspects

In short, we gain in efficiency, compliance, speed and focus.

**Comment by brianjrobertson** [comment]
The Facilitator can already define and set that context; is it important that the whole group be able to participate in that, and if so, why and what have you observed around that?

**Comment by jeanlucchristin** [comment]
hum
I'm afraid to repeat myself,

To answer, two points:
1) you writte "The facilitator can define and set that context"
My proposal is to had that sequence in the process

2) you writte "do you think it's important that the whole group be able to participate in that? "
Well, I have never practiced top down saying to members since the role of facilitator what characteristics are required.
The facilitator knows the accountability of the role, its purpose.
But the required characteristics which are the criteria of selection, it is for everyone to determine them in conscience.

I use the phrase "word cloud". 
"We will create a word cloud with the required characteristics, each one keeping the ones that matter to him".
It's a very fast work of awareness. I have observed as a result what I have named above: "Clearly, I observe that the circles are much more accurate, effective, fast in the process after having invested a few minutes to define the required characteristics.
they are also automatically "role" oriented, with less temptation towards the "people" aspects "


This is a tension towards an ideal that can be better than it is.

**Comment by brianjrobertson** [comment]
I'm closing this issue given we haven't seen more coaches jumping in to share experience indicating this would be helpful; however, I think when we figure something out for issue #221, it will likely involve the flexibility to modify the election process to some degree, which would at least enable this on a policy level per-org or per-circle.
