### ISSUE TITLE
Sample Constitution Link Broken

### ISSUE THREAD

**Issue by toddapetersen** [holacracyone/Holacracy-Constitution#293]
This [link](url
https://github.com/holacracyone/Holacracy-Constitution/blob/master/Adoption%20Declaration%20Sample.pdf) is broken on the main page.

**Comment by jeffanthony** [comment]
Has been fixed https://github.com/holacracyone/Holacracy-Constitution/commit/13adc4a61a3f54a1522acb3e8ff0d9ca0d465bfc
