### ISSUE TITLE
unclear language in 1.5 - external roles

### ISSUE THREAD

**Issue by colinfrei** [holacracyone/Holacracy-Constitution#298]
> A Circle may also adopt a Policy to invite an external Role to participate in its Governance Process, or to require one of its Sub-Circles to do so.
I first read this as _sub circles can be required to include roles in their (the sub-circle) governance_. That seemed strange to me, because usually the upper circle doesn't directly impact a sub-circle's governance.
Looking at it a bit later, I realized that this probably means that a policy can be requiring a certain sub-circle to invite a role into the upper circle, not into the sub-circle.

If my second interpretation was correct, is there a way to phrase that so it's a bit clearer?

**Comment by brianjrobertson** [comment]
Actually, the first interpretation is the intended one.
