### ISSUE TITLE
Hyperlinks from Holacracy-Constitution.md -> Appendix-A.md

### ISSUE THREAD

**Issue by djwork** [holacracyone/Holacracy-Constitution#3]
Would be nice to have hyperlinks defined for references to core roles in Holacracy-Constitution.md to the role definitions in Appendix-A.md

**Comment by RashidGilanpour** [comment]
@djwork not a priority for me at the moment but please feel free to make the changes on your own branch and do a pull request and I'll take a look at committing it.  Thank you!

**Comment by djwork** [comment]
done

**Comment by djwork** [comment]
doesn't look like I can get it working with gitprint
