### ISSUE TITLE
Move 'Defining priorities and Strategies' from Circle Lead onto Role Lead

### ISSUE THREAD

**Issue by benoitpointet** [holacracyone/Holacracy-Constitution#301]
I'd like to move the power of 'Defining priorities and Strategies' from Circle Lead onto Role Lead. 

It seems to me that setting priorities and strategies is useful for roles with lot's of fillers just as it is useful for circles. We have roles with 4-8 fillers that work quite independently, doing the same things in different locations, and which would benefit by aligning a bit "how they play" the role. turning the role into a circle for that sole purpose would be over-engineered.

**Comment by brianjrobertson** [comment]
It makes sense to me that a role would want to define strategies; and, in the draft version of v5, that's already possible, because each role is also a circle by definition - anyone filling a multi-filled role is a Circle Lead within the role's circle, and can define strategies for that role.
