### ISSUE TITLE
Clarify strategies and priorities as domain of the Lead Link

### ISSUE THREAD

**Issue by benoitpointet** [holacracyone/Holacracy-Constitution#302]
It seems "strategies and priorities" are an implicit domain of the Lead Link.
see thread https://community.holacracy.org/topic/are-strategies-and-priorities-an-implicit-domain-of-the-lead-link

I'd like to have that implicit domain become explicit in the constitution, at least in https://github.com/holacracyone/Holacracy-Constitution/blob/master/Appendix-A.md#circle-lead

**Comment by chrcowan** [comment]
I agree. Adding them as domains may increase complexity, but if the added complexity only shows up on the role description for the Lead Link, then I'd argue that making those domains explicit may technically increase complexity, but it would effectively reduce confusion for practitioners. They get roles. They get domains. And they spend meaningful time orienting and interpreting the Lead Link role, so having them explicit in the role-description would help a lot. By not including them there, I think it reduces the reader's ability to trust their own interpretation of the rules more generally.

**Comment by LouisChiquet** [comment]
I like the fact that it's open to interpretation, as often with clients, they have complementary processes/roles for various things which are all put under the word “strategy”, for instance “product strategy” role would be created without having to create a policy to restrain the LL authority or touch this possible domain. As it's also just an accountability, it's not a domain, can also be interpreted that I can have strategies of my own in my role. Plus, if we were to put a domain on this role, means no other role in the organisation can technically touch it because LL would have the domain, so even the sub-circles can't touch the strategy of their own. An accountability is clear, at least in my today's interpretation and the one I see being shared the most, so adding a domain would cause harm.

**Comment by benoitpointet** [comment]
I understand your perspective, @LouisChiquet .

Yet I still wish more coherence between the Constitution and the "role definitions" addendum:
- The constitution implies an "unspelled" domain on "Strategies and Priorities of the Circle" that is not represented in the addendum.
- The addendum explicits an accountability "setting strats and prios" that is not explicit in the constitution.

A few more specific answers:


> As it's also just an accountability, it's not a domain, can also be interpreted that I can have strategies of my own in my role.

A domain would have no impact on the rights of a role to have strategies of their own, and anyway 4.1.3.c (Circle Needs Over Individual Goals) applies.


> if we were to put a domain on this role, means no other role in the organisation can technically touch it because LL would have the domain, so even the sub-circles can't touch the strategy of their own.

If I apply this logic to role assignment, which is currently a domain of the Lead Link, then it would mean that Lead Links in the sub-circles couldn't do assignment. Which is not the case.  Clarification: this proposal is not to give the GCC Lead Link a domain on "all strategies" but to give every Lead Link a domain on "Strategies and Priorities of the Circle", just like the Appendix A gives them a domain on "Role assignments within the Circle".

**Comment by LouisChiquet** [comment]
I'd first like to remind issue #188 on the reason why the accountability changed from “_Establishing priorities and Strategies for the Circle_” to “_Judging the relative priority of Circle efforts on request to resolve priority conflicts across Roles_”.

“_The constitution implies an "unspelled" domain on "Strategies and Priorities of the Circle" that is not represented in the addendum._” => Given experience as shared in #188, and knowing it's not an expectation nor a domain but a possibility as defined in [1.4.1](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#14-circle-leads) in 5.0, I don't see the “unspelled domain”.

“_The addendum explicits an accountability "setting strats and prios" that is not explicit in the constitution._” => It was in 4.1, with the [2.2.2](https://www.holacracy.org/constitution#art222) in my interpretation. Now it's no longer an accountability as said in #188 and it's defined in [1.4.1](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#14-circle-leads).

“_A domain would have no impact on the rights of a role to have strategies of their own, and anyway 4.1.3.c (Circle Needs Over Individual Goals) applies._” The meaning of a domain is “one or more “Domains”, which are assets, processes, or other things the Role may exclusively control and regulate as its property, on behalf of the Organization.” therefore it'd impact de facto, and make more governance needed if we need a Strategy Product as I mentioned in my previous message. For the “anyway”: Yes, so if it applies what is the issue? Knowing that [4.1.3.c](https://www.holacracy.org/constitution#art413) (in 4.1) isn't a domain, but a duty.

“_If I apply this logic to role assignment, which is currently a domain of the Lead Link, then it would mean that Lead Links in the sub-circles couldn't do assignment. Which is not the case. Clarification: this proposal is not to give the GCC Lead Link a domain on "all strategies" but to give every Lead Link a domain on "Strategies and Priorities of the Circle", just like the Appendix A gives them a domain on "Role assignments within the Circle"._” => Then yes, would make sense to have it precise like assignments' domain, the “within the Circle” if this was to be a domain.

In 5.0, given [1.4.1](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#14-circle-leads) and [2.3.3](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#233-prioritizing-your-attention) I feel like it'd feel wrong to put a domain, as it's more subtile then that, as now the Circle Lead, in my interpretation of 5.0, only do this when needed given its new accountability “_Judging the relative priority of Circle efforts on request to resolve priority conflicts across Roles_”.. Maybe amend 1.4.1 to make this more clear? Thoughts @brianjrobertson ?

**Comment by benoitpointet** [comment]
I opened this issue on the basis of 4.1 and I should have looked at 5.0 with a lot more scrutiny. I notably wasn't aware of #188.

I feel much less tension with 5.0.

Thanks a lot @LouisChiquet for all explanations.
