### ISSUE TITLE
Simplify language - renaming accountabilities as tasks

### ISSUE THREAD

**Issue by AndrewLovettHome** [holacracyone/Holacracy-Constitution#304]
I was a bit bamboozaled by the use of the word Accountabilities in roles.  For me, accountabilities implies a responsibility to obtain a business outcome whereas my understanding is that the items under this heading should really just be the things that are done by the role.  Aren't they really just "tasks"?  Wouldn't that make things easier to comprehend if we changed the heading from "Accountabilities" to "Tasks"?

**Comment by brianjrobertson** [comment]
I don't think so; "tasks" is often used for one-time things with an end point, which are then complete (e.g. "a task"), which is a much greater confusion risk than the one you point out here in my view.
