### ISSUE TITLE
Please tag version 4.1 as release

### ISSUE THREAD

**Issue by julianeroell** [holacracyone/Holacracy-Constitution#31]
I see that version 4.1 has been released now, and that the master branch here shall be the development version going towards 5.0.

To help with making clear contributions, could you please tag the current snapshot (the one that is 4.1) as a "release" here on Github? (https://github.com/holacracyone/Holacracy-Constitution/releases) Thank you!

**Comment by brianjrobertson** [comment]
Done, thanks!
