### ISSUE TITLE
Require announcing intent before making hard-to-change decisions that impact circle-level domains

### ISSUE THREAD

**Issue by chrcowan** [holacracyone/Holacracy-Constitution#312]
In H1, we have a policy which I think is worth considering as a possible constitutional addition. 

The policy states, "**In any role, before you implement a decision that could have a substantial impact on the organization and where it will be substantially difficult or expensive to undo that impact, you must first share your intent to do so with any partners who you believe could have useful information to inform the decision, or who fill roles likely to be substantially impacted by it. You must then delay your decision for a reasonable timeframe to allow those partners to consider the potential decision and have time to try to address any tensions triggered by it. You must also respond to any clarifying questions they ask, and consider any reactions they share before you implement the decision**." https://app.glassfrog.com/policies/2937002

The purpose would be to address the need for some base-level, stable starting restriction, FROM WHICH, we could then genuinely say, "OK, with this in place, now let domains be tension-driven." 

In addition, coaches may want to recommend a few starting domains like "Hiring and Firing Process," and "Compensation Process," to again establish some base-level set of restrictions which seem reasonable for any organization to have as a starting point. This may also be something that is somehow required in the constitution, but I am less sure about how best to do that. At a minimum though, the "hard to reverse decisions," policy would seem to cover the broader concerns about how to restrict people from doing crazy things unless there is an explicit restriction, which is harder for new practitioners to really understand because it seems obvious that preventative restrictions sometimes make sense. 

The tension that lead to this idea was that I'm creating an online course for Lead Links, and I wanted them to understand how to appropriately apply domains in their organizations, which means I want to emphasize, especially for domains, that they should be tension-driven rather than preventative. However, this isn't completely true, because there are some things like, "Hiring and firing process," etc. that should be called out from the very beginning (it doesn't matter where you put them; the point is that it's the kind of thing that needs to be centralized somewhere).

**Comment by oliviercp** [comment]
Playing devil's advocate: 

One thought about the policy; I think it’s awesome and easy to misinterpret, because its application relies on the fact that each role-filler gets to interpret governance vs the boss telling you what it means. I could easily see this policy abused by ex power holders saying “wait no I consider this change of banner color on the website as a hard-to-change decision, so you must use that process”. That's a risk; I don't think these kinds of risks should prevent us from adding to the constitution, but I wanted to call it out.

**Comment by oliviercp** [comment]
I wouldn't be surprised if you responded something like that @chrcowan: 

> "I felt the same concern about possible abuse since it does seem to require some deeper understanding....BUT...I think it would actually be a step forward because that is the reality anyway, i.e. possible abuse of power, and at least "hard to reverse," gives everyone a little more clarity on the criteria being used, rather than more vague arguments."

Which would be a valid point :)

**Comment by brianjrobertson** [comment]
Hmm, so how or what mechanism would you use to specify when certain decisions **don't** need to use this process?  e.g. if you have a good firing process, presumably you wouldn't want someone to have to publish their intent to fire someone if they just used the firing process.

**Comment by brianjrobertson** [comment]
Aside from that question, I'd love to get other community input on the idea of encoding this constitutionally as well; anyone want to chime in?

**Comment by chrcowan** [comment]
@brianjrobertson well, it's an interesting question. What about just adding, "this can be changed by a policy?" >:)

**Comment by brianjrobertson** [comment]
@chrcowan What I don't like about that is how counter-intuitive it seems to do that when you already have domains delegated for something or processes defined for something that you kinda just naturally want to replace the need to get input; and how it requires being more explicit than seems useful/necessary....

**Comment by chrcowan** [comment]
@brianjrobertson 

Well, one solution could simply be to add somewhere, "...unless the domain impacted by your decision has already been defined and delegated to your role." 

But my sense is that you might not need that clause, because even if the domains are delegated and the authorities are clear, then....should someone think to themselves, "You know this is a pretty big, hard-to-reverse decision I'm about to make...," if they think that, well, this rule could give them some guidance about how to proceed. Now, they may not think about it that way at all. Nor might anyone else, but if that's true, then this rule wouldn't even come to mind. 

So, it seems useful for helping situations in which, 1) someone is going to make a hard-to-reverse decision (even if it will directly impact a domain they control)  and even though their intuition is telling them they might need to get more data, they inappropriately confuse this inner voice with "consensus-seeking," and therefore just bulldoze ahead potentially causing non-reversible (and avoidable) harm, which then reflects poorly on the rules ability to provide appropriate heuristics, and of course the role-filler themselves. In the absence of this rule, sense that potential is inherently already there, role-flller's are instead using implicit, and likely unconscious criteria. OR, 2) a situation in which someone else questions a role-filler's choice and they are not able to clearly describe what criteria they should be using, or what pathways that should use to either stop the decision before it is made, OR, if the decision was already made, then it could make it a lot easier to diagnose what went wrong and how to improve it going forward.  

So, if it's already intuitive and none of the parties involved think that "hard to reverse" applies, then it wouldn't get invoked. I think about all the decisions H1 roles make that COULD fit this description (e.g. like hiring decisions), but I haven't seen anyone request that roles making those decisions follow this policy. So, from how I've seen it used within H1 at least, it doesn't seem to be a problem.

**Comment by brianjrobertson** [comment]
Some kind of language like that might do the trick @chrcowan, but it'll be tricky to write it without violating the role/circle parallelism; it'd basically have to be done such that this hard-to-change decision restriction would apply only when impacting undelegated circle-level domains when you're not a Circle Lead (because serving as Circle Lead is the same as just filling the role in the broader circle that does own the domain).  But, that might be sufficient to get the value out of this - it's at least getting a lot of it.

I'm not sure why we wouldn't need a clause like that though; I'm not sure I'm following your logic.  Except the part about "it's working fine at H1", which is true, although this discussion helps me realize it's working fine for us because we're ignoring the policy in certain cases, and actually violating our own governance.  If it were in the constitution, we'd thus be violating that too, which is even worse.  So, since it is working for us, the question I have is "what heuristic are we naturally/unconsciously applying for when not to do this?" - because whatever that heuristic is, it's working and could be exactly what's needed as an explicit exception if we encode this into the constitution.  Any thoughts on that?

**Comment by chrcowan** [comment]
@brianjrobertson not sure about an answer to "what heuristic are we naturally/unconsciously applying for when not to do this?" BUT...it seems like we're both saying that it could make good sense for undefined/undelegated domains (when you're not the Circle Lead). That would solve the issue I think since my concern was sounding stupid when I say, "let domains be tension-driven..." when clearly there might be some you'd want to put up before someone makes a horrible, impactful, hard-to-reverse decision. I think that would do it!

**Comment by brianjrobertson** [comment]
Hmm, that's a really good point @chrcowan, sounds like this solution would actually solve the tension then, and may actually be the heuristic we've been unconsciously applying...

**Comment by brianjrobertson** [comment]
@chrcowan I'd love your review of the solution I implemented for this.  I took a slightly different approach than initially envisioned to keep the text and the rules simpler overall and internally consistent: basically, I wrote it to require Circle Lead permission to impact an undelegated circle-level domain if you believe the impact will be difficult or expensive to reverse.  However, you can get permission to impact a domain by announcing intent, under the rule already in place in v5-alpha for that, thus you can use that rule as well to get permission for a difficult/expensive impact on a circle level domain.

**Comment by chrcowan** [comment]
@brianjrobertson Yeah, I think that does it!
