### ISSUE TITLE
Add "demand" information to accountabilities 

### ISSUE THREAD

**Issue by benoitpointet** [holacracyone/Holacracy-Constitution#314]
_Somehow relates to the discussion in https://github.com/holacracyone/Holacracy-Constitution/issues/308_

I often found myself in the wish to know which role had demanded the addition of an accountability to another role, and to what end.

Such information could help revise accountabilities pertinence. It indeed is sometimes hard for a role to know "who actually benefits from / depends on me doing this?"

**Comment by brianjrobertson** [comment]
That does sound like useful information, though are you envisioning a tangible effect that would have (beyond just as information), and do you have thoughts on why that effect is really useful?  If so, I'd need that info to consider adding this as a constitutional construct; if you're envisioning it just as extra info, then it sounds like something a software tool could support without a constitutional construct, like we've done for tagging roles for example.

**Comment by brianjrobertson** [comment]
Closing this for now, but please feel free to add info and I'll re-open.
