### ISSUE TITLE
Removing a Circle Rep

### ISSUE THREAD

**Issue by sitron** [holacracyone/Holacracy-Constitution#315]
I just went through the Circle Rep definition again (https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#151-circle-reps). If i understand well a Circle may optionally create a Circle Rep but will not be able to remove it afterwards? 
> However, no Circle ... , nor remove the Role

Did i miss something?

**Comment by brianjrobertson** [comment]
No, it's not saying that; it's saying that you can't remove the role itself - that's separate than removing the assignment of a person into the role.  So the role always exists if someone fills it; and someone can optionally be assigned (elected by default) to fill it, and may later resign from the role (or be removed by some other defined process).

**Comment by sitron** [comment]
Ok, thanks. For whatever reason i had in mind that the Circle Rep was not mandatory in v5 which is why i got confused i guess. 
I now understand that only the assignment is on-request but that the Circle Rep role exist in all Circles, just like in v4.1 (for all Circles that have a Super-Circle that is)
