### ISSUE TITLE
Who is Secretary for cross-circle tactical meetings (and related questions)?

### ISSUE THREAD

**Issue by matthewgilliland** [holacracyone/Holacracy-Constitution#319]
The current Version 5 language for the Secretary accountabilities (Appendix A) includes: "Scheduling Governance Meetings and Tactical Meetings for the Circle and its Roles, and notifying all invited participants"

I understand that the "and its Roles" portion incorporates the idea that a Tactical Meeting doesn't have to be for a particular Circle as a whole or limited to Roles within just one Circle, which is great, _but_...

... this seems to introduce some items of potential confusion:
1. In calling a Tactical Meeting of Roles within a single circle where the Circle Secretary is explicitly invited by the meeting convener, that Secretary would clearly seem to be accountable for meeting scheduling. Is that still true if the Secretary is not invited?
2. In calling a Tactical Meeting of Roles within multiple Circles where the meeting convener has specified the Secretary of one of the Circles to invite, is that Secretary accountable for scheduling? Currently the text would seem to indicate that this is only the case if the meeting convener is convening from a role within that Secretary's Circle, yes? Should the convener be able to obligate the Secretary from his Role's Circle that way on demand? Say Role-filler in Circle 1 convenes a Tactical involving herself and inviting five Roles from Circle 2. Does it make sense for Circle 1's Secretary to be obligated to schedule that meeting?
3. In calling a Tactical Meeting of Roles within multiple Circles where the meeting convener specifically invites multiple Circle Secretaries or the Secretary of another Circle, who is responsible for scheduling?

There is something a bit strange about obligating a Secretary to schedule (a) meetings that Secretary has not been invited to as well as (b) any and all cross-circle Tacticals convened by any Role within their Circle without their agreement. I can make an argument for it, sure, but is that what makes the most sense?

It seems to me that making the meeting convener the default Secretary for non-Circle meetings makes more sense than obligating a Secretary from that Role-filler's own Circle to schedule a new meeting to which that Secretary may or may not be invited; that places the scheduling responsibility on the convener by default, but still allows the convener to find (or elect?) another scheduler if desired/needed. It also avoids the potential confusion of the above scenarios.

Thoughts?

**Comment by brianjrobertson** [comment]
I think you're right, all of that does seem quite strange, and unintended.  I think a simple solution is to keep the Secretary's scheduling accountability to just the regular/normal whole-Circle tactical meetings; anyone else who wants a Tactical Meeting can just schedule one for themselves.
