### ISSUE TITLE
Process for disposing of "rights" vs. spending assets

### ISSUE THREAD

**Issue by oliviercp** [holacracyone/Holacracy-Constitution#325]
Article [2.1.3 Don't Dispose of Assets](https://github.com/holacracyone/Holacracy-Constitution/blob/v5.0-alpha/Holacracy-Constitution.md#213-dont-dispose-of-assets) provides a process for _spending money or assets_, but it is unspecified how to go about disposing of the organization's _rights_. 

For example, if in my role I want to authorize an external party to record and publish a speech I make for my company, I'm essentially disposing of my company's copyright over that content, and it will limit what my company can do with that content in the future (e.g. it can't publish it online behind a paywall, since it's already online for free). 

Is the intent of article 2.1.3 to include this type of "spend" in the spending process? Or is the spending process limited to money and other assets? A (copy)right is an asset, but here I am not really "spending" it — or am I because it deprives the company from using it in the future, in the same way that money spent now cannot be spent later?

If the intent is for the disposing of rights to be included in the spending process, I think it should be conveyed more clearly. Most people don't think of rights as something we "spend", and although I can see a case for using that term in that context, I think it's confusing. 

If the intent is for the disposing of rights to NOT be included in the spending process, then it begs the question of how a role can get authorization to dispose of some of the company's rights. Currently it's unclear.

**Comment by brianjrobertson** [comment]
I'm not clear why this isn't clear; the text currently reads:

> It counts as spending if you dispose of significant property of the Circle, or significantly limit any of its rights.

And then the very next text beginning the next paragraph starts:

> To get authorized to spend...

... followed by the process for authorization.  Given the text immediately before that, how is it not clear that the same process applies for limiting rights?  And if you still think it's not clear, any suggestions for clarifying it without adding much complexity to the text?

**Comment by oliviercp** [comment]
Ah, indeed that clarifies it completely. I went back to the constitution to check the wording you quote, and realized that I had been looking at the wrong version... woops. In fact, in the current version article 2.1.3 is called "Don't Spend Money," not "Don't Dispose of Assets" anymore. 

So it looks like you clarified it already — thanks!
