### ISSUE TITLE
Should super-circles be able to demand a sub-circle accept a link?

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#327]
In v5.0 beta, a circle can invite an external role to link into itself, and it can also invite an external role to link into one of its sub-circles (i.e. it can demand a sub-circle accept a link).  Can anyone think of any cases where it’s important to allow a circle to demand a sub-circle accept a link, or can this safely be cut, to reduce the ability for a super-circle to mess in the inner workings of the sub-circle?  (Demanding a sub-circle accept a link seems to be effectively specifying the implementation details of the sub-circles purpose & accountabilities.)

**Comment by klaas1979** [comment]
Yeah I got two ideas:

1. Software Development coordinated for a lot of stakeholders. The IT-Product circle creates a subcircle for the product management where all stakeholders are included.
2. In our Company Network the anchor or other high-level circle enforces a Link to an external holacratic entity in our company network.

This could both be encoded via Purpose and accountabilities. I would **like, hope** and guess that the genereal definition of a policy could be enough to enforce such restrictions? So maybe it can be cut and encoded via policy.

**Comment by leword** [comment]
Top of head, similar to Klaas- I'm thinking you could get close enough with a very specific accountability.  Maybe "integrating closely with role/stakeholder-X" or even "providing role/stakeholder-X with representation in circle operations & governance", and pitch it be implemented with a link.  Assuming something like that is a valid accountability (?), I think I'd want to see/hear of cases where that failed and forcing a link would have worked before allowing forced-links.

**Comment by oliviercp** [comment]
I don't have a strong opinion either way, but I'm leaning toward allowing super-circles to demand a link into a sub-circle. The argument for stakeholder representation tips the balance for me, and trying to achieve that through an accountability seems convoluted. In any case, a link can be "demanded" by the super-circle only by adopting a policy, and the sub-circle Leads & Reps are part of the governance process to adopt that policy, so they can always raise an objection if it's an issue from their perspective. I'm not convinced of my position here, but that's where my reasoning goes for now.

**Comment by RS-DU34** [comment]
Brian, I'm not reading it so much in the way that you are I think; are you referring to 1.3.4?  
The way that you describe in your question is a dangerous interpretation; this could be granting a "backdoor" that's poking into a core principle of self-management. As long as the super-circle is allowed to drill into sub-circles for the purposes of accepting a link _(in an upper-management-like activity like this)_, we're losing the ability to tell Lead Links not to drill in at all.  
  
But I'm actually not interpreting that this door is open and instead in a reasonably positive way, allowing something of the sort:
Policy(ies): _"any sub-circle representing a scrum team must invite the role of scrum master and product owner as a link; any product owner or scrum master circle must accept link invites from development circles"_

**Comment by brianjrobertson** [comment]
Hmm, okay, thanks folks; I'm leaning towards keeping the current language for reasons @ocompagne articulates, and because it's just generally more flexible and seems safe enough given that it requires governance to achieve.  Thanks all!
