### ISSUE TITLE
Cross-circles have no name

### ISSUE THREAD

**Issue by RS-DU34** [holacracyone/Holacracy-Constitution#329]
v5beta Section1.3.5: Creating Circles Across Roles describes how to create circles across circles but no actual name to this entity is ever assigned.  
Should we be calling them "Circles Across Circles"; maybe, but it's a bit unclear due to the very descriptive nature of this sentence, it doesn't feel like a "name".  
Another issue here on GitHub called them Cross-circles and upon reading that, I had no doubts what they were talking about, yet that term doesn't exist in the constitution; perhaps it should...

**Comment by brianjrobertson** [comment]
My general principle has been not to introduce labels in the constitution unless they're needed in the constitution, and no other sections currently need to refer to this concept, hence no label...
