### ISSUE TITLE
clarify Circle Lead's authorities regarding money spending

### ISSUE THREAD

**Issue by plamarque** [holacracyone/Holacracy-Constitution#335]
in 2.1.3 Don't Spend Money : 

> however a Circle Lead of that Circle may revoke the authorization at any time.

My gap is that I don't find anything covering this in the Circle Lead Role's description in Appendix A, so it lacks clarity

Thus, I suggest to add a domain around these lines : _"reverse spending request escalation or revoke spending authorizations"_.
If a domain is not the appropriate vehicle, maybe an accountability around these lines could be forged : _"Fluidifying access and spendings of Circles resources"_

What do you think ?

**Comment by brianjrobertson** [comment]
I don't think a domain is the appropriate vehicle here, and I'm not sure an accountability is either; an accountability would be relevant if others need to be able to expect it of the Circle Lead (and thus expect the Circle Lead to take actions/projects around the function on request), especially if they need to expect it even beyond what the Circle Lead would choose to do on their own for the purpose of the Circle Lead role.  I don't think it's useful to try to clarify everything a Circle Lead should do in its Accountabilities, no more than a circle would for any other role; roles do lots of things to serve their purpose, and most are not useful to add as explicit accountabilities.  So, if this power is one that the Circle Lead can use for its purpose when they deem useful, but that others can't expect the Circle Lead to use beyond serving its own purpose, then no accountability is technically needed - it's just a power the Circle Lead has available to them.  It's still possible to use an accountability to clarify it, but I'd like to hear an argument for why that's useful and worth the added complexity.

So, what's the potential issue in not referencing this particular power in the role description?  Does anyone else think it's important that all Circle Lead powers somehow show up in the role description, and if so, why does that seem important or what's the potential concern with not having them all show up there?

**Comment by Aliocha-Iordanoff** [comment]
As described in [4.1.3 Get Authorization Before Spending Money](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#413-get-authorization-before-spending-money), the Circle Lead Role has a specific authority. 

I agree an accountability is not necessary.

However, as the only roles defined by the constitution are those defined in the appendix. It can therefore be expected that the definition given in the Annex fully describes the expectations towards these roles and their exclusive powers or authorities.

It seems to meet relevant to explicitate this power of reversing other's escalaton in the Role definition given in Appendix.

**Comment by brianjrobertson** [comment]
All Circle Lead accountabilities have now been removed to avoid this potential confusion / lack of clarity.  See [this comment](https://github.com/holacracyone/Holacracy-Constitution/issues/330#issuecomment-593192088) and others in the overall issue for details.
