### ISSUE TITLE
Make 1.2 easier to read

### ISSUE THREAD

**Issue by oliviercp** [holacracyone/Holacracy-Constitution#336]
I proposed the following change to article 1.2: #332 

I feel that it's easier to read by being more explicit about the Domain. This came up as I was working with someone to translate the constitution, and she asked me what this paragraph meant. I explained it, but realized it's not that obvious to a novice. 

I have an update wording (different from my commit): 

> A Role may control assignments into another Role by having a Domain of "Role assignment" for that role. This Domain gives the assigning Role the authority to assign or remove people from the target Role at any time. Anyone so assigned becomes the "Role Lead" for that Role. When a Role is unfilled, the Role Leads of the assigning Role are automatically considered the Role Leads of the unfilled Role as well.

I would like to get reactions - even if it's only a thumbs up or down :)

**Comment by matthiask** [comment]
I think the proposed text is a bit clearer but OTOH since the constitution isn't targeted at novices I'm not 100% sure it makes a difference (but I don't have to be)

In the sentence "Anyone so assigned ..." it may now be non-obvious to novices whether this refers to the role lead or other role fillers. 

Maybe "Anyone controlling this Domain becomes the ..." or something to that effect?

**Comment by oliviercp** [comment]
@matthiask FWIW, I didn't change the sentence "Anyone so assigned ...", but I agree that it is not super obvious language (although it's technically accurate). In this case, the "anyone" is referring to the Role filler of the Role being assigned, _not_ of the Role assigning. Maybe I should propose an change to that sentence too...

**Comment by MichaelDeAngelo** [comment]
I think the proposal is more clear and in "plain-talk"

**Comment by plamarque** [comment]
I like @ocompagne's proposal but I'm not comfortable with naming the domain "Role assignment" explicitly.

Also, since this paragraph offers a way to detach the Roles assignment Domain  from Circle Leads, I think it would be helpful to refer to it.

Here's an attempt : 

> Instead of relying on the Circle Lead, Roles assignment can be the Domain of a different Role, which can then assign or remove people to that Role at any time. Any person thus assigned then becomes the ***"Role Lead "*** of that Role. As for Circle Leads, when a Role is no longer assigned, it automatically reverts to the Role Leads who control the assignment domain.

**Comment by plamarque** [comment]
I just realized that this is allowed thanks amending Circle Lead Role which is described in 1.1.4.3.

I think it helps to further clarify to refer to it. Here's a newer version : 

> A Circle may amend its Circle Lead Role (as described in 1.1.4.3), by placing Roles assignment domain another Role, which can then assign or remove people to that Role at any time. Any person thus assigned then becomes the ***"Role Lead "*** of that Role. As for Circle Leads, any unfilled Role automatically reverts to the Role Leads who controls the assignment domain.

**Comment by oliviercp** [comment]
> I like @ocompagne's proposal but I'm not comfortable with naming the domain "Role assignment" explicitly.

@plamarque Out of curiosity, why not?

**Comment by plamarque** [comment]
> @plamarque Out of curiosity, why not?

OK, not a big deal and pretty much a matter of style preference. 

To me, it felt like an unusual use for double quotes in the constitution. I understood it like giving a fixed name for that domain. However, it seems to me that the Constitution consistently avoids naming things beyond the official concepts, and does it it in order to offer a maximum of flexibility. For example, some organizations may find it more logical to name this domain "staffing", "assignment", "role stewardship" or whatever makes sense in their context/culture.

Note : This concern is NOT the reason why I proposed an alternative and I'll take no offense if it's ignored. I just wanted to contribute to the resolution of the original gap : clarify 1.2

**Comment by oliviercp** [comment]
No problem, I was just curious. Calling out the domain name explicitly is part of what adds clarity to the article in my opinion. It makes it more concrete and helps the reader understand exactly how to go use it. I used the same domain name as what is already in the Circle Lead's domain definition for consistency.  As for the double quotes, I didn't check but I'm not attached to that ;)

**Comment by oliviercp** [comment]
@brianjrobertson does the discussion above influence your thinking on this issue?

**Comment by brianjrobertson** [comment]
@ocompagne My primary concern with your suggestion is what @plamarque points to above: the constitution consistently avoids quoted words/phrases except to define core constitutional concepts, and this doesn't need to be a constitutionally defined term.  So it's the use of quotes that are triggering my objection.  That said, I do see this paragraph as one of the more potentially confusing in the constitution at present; if you can suggest better language without using quotes, I'd love to see it.

Regarding @plamarque's suggested language: I see two issues with it: One, it introduces a cross-reference to another section; I think this generally increases the complexity and reduces the felt-readability of the document, so I've been holding a boundary around introducing them.  Two, it presumes/requires that role assignment domain delegations are always delegating from Circle Lead, which is not always the case; this clause needs to also cover (or at least clearly not disallow) using domains to control role assignment in a circle with no Circle Lead.

**Comment by oliviercp** [comment]
@brianjrobertson I see that point, and I don't have a great suggestion that brings both clarity and avoids defining the Domain at the moment. To be crystal clear, I'm not attached to the quotes themselves — any other way to write it that still defines the domain would still clarify the paragraph. 

But if I'm left weighing between two less-than-ideal solutions, I would prioritize making the paragraph clearer. I think it clarifies the paragraph significantly, not just marginally. I have witnessed two people, one of which has been through the PT prior, who could not make sense of it. Granted English is their second language, but so are many current and future readers of the constitution. I consider it a significant bug if it reduces usability that much.

A couple alternative ideas:

1. Not defining the domain per se but qualifying it - essentially just removing the quotes: 

> A Role may control assignments into another Role by having a Domain of role assignment for that role.

2. Making it an example: 

> A Role may control assignments into another Role as a Domain (by having a Domain of e.g. "role assignment for Role")

I don't really like #2 though it could probably phrased better. #1 is clearer IMO, probably because it's so close to my original suggestion.

**Comment by brianjrobertson** [comment]
Something like that first option might work; I'll play with the language a bit further myself and see if I can improve on it some.

**Comment by LouisChiquet** [comment]
I like the first one too. Why not just simplify to the furthest with “_A Role may control assignments of a Role through a Domain_”? As the last bit about role assignment for that role is de-facto there, at least following my interpretation.

**Comment by oliviercp** [comment]
I think it's important to call out "of _another_ Role" to be very clear. But I like the use of "through" better than "as" from the original text, it seems a bit clearer. However, overall it doesn't really address the core issue I see with this sentence/paragraph, i.e. it doesn't add enough clarity IMO. It doesn't give any example or indication as to what that domain should look like.

**Comment by oliviercp** [comment]
@brianjrobertson you closed it = no change?

**Comment by brianjrobertson** [comment]
@ocompagne No, I closed it with a change submission; see the link above (the number in blue) just after "closed this".

**Comment by oliviercp** [comment]
Ah ok - thank you!
