### ISSUE TITLE
Missing word in 2.2.5 Prioritizing Your Attention

### ISSUE THREAD

**Issue by plamarque** [holacracyone/Holacracy-Constitution#337]
I have difficulties understanding the following sentence in 2.2.5 : 

> In assessing that, you must integrate any relative prioritizations and Strategies of the Circle holding your Role, as well as any acting upon that Circle itself.

Is there a word missing between _any_ and _acting_ ?

**Comment by brianjrobertson** [comment]
No, it means "any [of them] acting upon...", or, more specifically "any [of those prioritizations and Strategies] acting upon...".

**Comment by plamarque** [comment]
Thank you @brianjrobertson  it's clearer now. It will help me to be more accurate in the translation work I have started.

So an Associate must integrate priorities and Strategies _of_ the Circle and _acting upon_ that Circle, right ?

Please correct me if I'm wrong :  Hence, it is assumed that the Associate has access and must consider all these "internal" (_of_ the Circle) and "external" (_acting upon_ the Circle) priorities and Strategies affecting the Circle before prioritizing any actions in his Role ?

**Comment by brianjrobertson** [comment]
Yes, that's right.

**Comment by plamarque** [comment]
Thanks!
