### ISSUE TITLE
Input requested: Where to put process to get permission to spend or impact domains?

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#342]
Hi Folks - I need opinions: which of these two organizations of content under "Authority of Role-Fillers" is better?  The [current version](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#41-authority-of-role-fillers), or the potential version below?  The actual content is the same, it's just the way it's broken down and split across sections that's different.  Please vote via a thumbs-up reaction if you think we should make the change to the version below, or a thumbs-down reaction if you think the current version is better.  Comments and arguments are welcomed and appreciated as well.

----

### 4.1 Authority of Role-Fillers

As a Role Lead, you have the authority to take any action or make any decision to enact your Role’s Purpose or Accountabilities, as long as you don't break a rule defined in this Constitution.

When prioritizing and choosing among your potential actions, you have the authority to use your own reasonable judgment of the relative value to the Organization of each.

You may also use your reasonable judgment to interpret this Constitution and anything under its authority. You may further interpret how these apply within any specific situation you face, and act based on your interpretations. However, you must interpret all Governance in the context of the Purpose and Accountabilities of the Circle containing it. You may not use any interpretation that conflicts with this context.

#### 4.1.1 Don't Violate Policies

While acting in a Role, you may not violate any Policies of the Role itself or of any Circle containing the Role.

#### 4.1.2 Don't Impact Domains

In service of your Role, you have the authority to impact and control your Role's Domains.

You may also impact any Domain held by a Circle containing your Role and not further delegated, or any Domain such a Circle itself may impact. But if you believe your impact will be substantially difficult or expensive to undo, you need to get permission.

You may not exert control or cause a material impact on a Domain delegated to a Role or Circle that doesn't contain your Role, unless you get permission. Nor may you do so on a Domain owned by another sovereign entity without permission.

#### 4.1.3 Don't Spend Money

While energizing your Role, you may not spend any money or other assets unless you first get authorized to do so. This authorization must come from a Role or Circle that already has control of those resources for spending purposes. It counts as spending if you dispose of significant property of the Circle, or significantly limit any of its rights.

### 4.2 Getting Permission to Impact Domains

When you need permission to impact a Domain, you may get it from whomever controls that Domain. You may also get permission by announcing your intent to take a specific action, and inviting anyone with a relevant Domain to object. You must then wait a reasonable time to allow responses. If no one objects in that time, you then have permission to impact any Domains owned by any Role in the Organization that your announcement reached. You may assume a written announcement reached anyone who typically reads messages in the channel you used. Any permission so granted only applies while taking the specific action you announced. A Policy may change or constrain this process.

### 4.3 Getting Authorization to Spend Money

To get authorized to spend money or other assets, you must announce your intent to spend in writing to the Role or Circle you're seeking authorization from. You must share this announcement where all Partners serving as Role Leads of that Role or within that Circle will typically see it. Your statement must include the reason for the spending, and the Role you'll spend from. You must then wait a reasonable time to allow consideration and responses. Any recipient of your announcement may escalate the spending for extra consideration, and you may not proceed with the spending if escalated. However, a Role Lead or Circle Lead of the target Role or Circle may reverse an escalation, as may the person who escalated it. Once a reasonable time has passed and no escalations stand, your Role gains control of those resources. You may spend them for your stated purpose, or further authorize others to. The Role or Circle you got authorization from in turn loses this control, however a Role Lead or Circle Lead of that Role or Circle may revoke the authorization at any time.

A Policy may change this process in any way, or directly authorize a Role to control spending of the Circle's resources without this process.

**Comment by jeanlucchristin** [comment]
I think that it is clearer, and that it is possible to go further.

4.1.2 Don't Impact Domains
The title does not match the content. 
The content is 2/3 to the domain authority of my roles and 1/3 about "do not affect the domain of others."

Proposal:
4.1.2 Respect the Domains

**Comment by matthewgilliland** [comment]
As much as I love the symmetry of Don't/Don't/Don't, I don't think it's the best way to organize the content here. I think the prior organization of the content might make sense _with_ these headers or similar:

4.1.1 Violating Policies
4.1.2 Impacting Domains
4.1.3 Spending Money

The prior organization seems strange currently because the content isn't all about "don't" (which I suspect might be the impetus for changing it). However, the change introduces a weird split of domain and money topics, and I think the prior organization _with_ different headings might be better-organized and more clear for someone looking for particular information within the Constitution.

**Comment by brianjrobertson** [comment]
@matthewgilliland That's really helpful, thanks!  What do you (or others) think of these sub-heads instead, with the organization kept as-is in the current dev version?:

4.1.1 Don't Violate Policies
4.1.2 Get Permission Before Impacting Domains
4.1.3 Get Authorized Before Spending Money

or maybe:

4.1.1 Don't Violate Policies
4.1.2 Respect Domains
4.1.3 Get Spending Authorized

**Comment by jeanlucchristin** [comment]
This one seems fluent to me : 

4.1.1 Don't Violate Policies
4.1.2 Respect Domains
4.1.3 Get Spending Authorized

**Comment by oliviercp** [comment]
@brianjrobertson I like your last suggestions much better!  The second one is cleaner, but the first one is clearer (i.e. allows me to understand the intent of the article better by just reading the title, thus increasing "skimmability"), so overall I prefer the 1st one

**Comment by matthewgilliland** [comment]
Both are an improvement, but I also prefer the clarity of the first version, with one edit: 
4.1.3 Get Authoriz**ation** Before Spending Money

(Since it's not the person getting authorized, it's the spending.)

**Comment by brianjrobertson** [comment]
That's really helpful, thanks all; I've made the change.
