### ISSUE TITLE
Chapter 1.2 Role Assignment is confusing

### ISSUE THREAD

**Issue by jeanlucchristin** [holacracyone/Holacracy-Constitution#343]
Reading this chapter, I got lost between "role lead" and "role assignment". I no longer knew what role each sentence was talking about.
I got used to it since then but I think it would be clearer by giving a title to the role that controls the assignment.

Here a proposal with the name "Role assigner":

1.2 Role Assignment
A “**Role assigner**” may control who fills another Role through a Domain of Role assignment for that Role. Anyone filling the Role assigner may assign the target Role to anyone who accepts the assignment, including to several people simultaneously. Anyone so assigned then fills the Role as its "**Role Lead**". A Role Lead may later resign from the assignment at any time, unless they’ve agreed otherwise. Whoever filling the Role assigner may also remove a Role Lead from the assignment at any time. A Policy may further constrain Role assignments or removals.

1.2.1 Default Assignment

When a Role is unfilled, anyone filling the Role assigner for that role is automatically considered a Role Lead of the unfilled Role as well.

When a Role has no Partners of the Organization among its Role Leads, then anyone filling the Role assigner for that role is automatically considered a Role Lead of that Role as well. However, this default assignment only applies to the extent that those normally assigned are not actively fulfilling the responsibilities and duties that come with the assignment.

**Comment by brianjrobertson** [comment]
I'd love to find a way to simplify this and make it more understandable, but the solution you're proposing here seems more likely to confuse to me, and it's not clear that the "Role assigner" is actually another Role (or whoever fills it).  So, if anyone has other ideas for improving [this section](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#12-role-assignment), I'd love to hear them.

**Comment by plamarque** [comment]
@brianjrobertson here's a proposal to replace the first sentence by :
> Assigning Partners to fill a Role may be controlled by a Domain of another Role.

which could even be reduced to IMO :

> Assigning Partners to fill a Role may be controlled by a Domain.

**Comment by brianjrobertson** [comment]
The grammar doesn't work in that given the definition of Domain (i.e. "Assigning Partners to fill a Role may be controlled by an [asset, process, or other thing a Role may exclusively control])", and that changes the meaning as well.  The point of that sentence is not that an asset or process can control assignment, which is how that suggestion technically reads when you put the definition of Domain in there; the point of that sentence is that you can control assignment by making an asset out of it and granting a Role the exclusive right to control that asset.

**Comment by plamarque** [comment]
Got it. Thanks for the clarification @brianjrobertson 

Would this work better?

> A Domain for assigning Partners to fill a specific Role may be created.

**Comment by brianjrobertson** [comment]
@plamarque That does resolve the issue with the original suggestion, though it uses passive voice, which I've been trying really hard to avoid whenever practical.  I'm also not sure it's any clearer than what's in there now, and I think it would undo what @ocompagne tried to solve with the change to the current wording (see #336), though Olivier, please tell me if I'm mistaken and you think something like this would be even better.

**Comment by plamarque** [comment]
I see. I'm trying to play with Domain as the subject, because it seems to me the confusion comes from using "Role" twice in the same sentence. Here's another attempt, removing passive voice:

> A Domain may grant authority to assign Partners to fill a specific Role

**Comment by brianjrobertson** [comment]
That's not actually what a Domain does; a Domain only constrains the authority of others (grants **_exclusive_** control), it doesn't grant authority.  You could say "A Domain may grant exclusive control of assigning Partners to fill a specific Role".  But I'm not sure that's any clearer than what's already in there?

**Comment by plamarque** [comment]
Thanks for the explanation @brianjrobertson . I like your last proposal : ""A Domain may grant exclusive control of assigning Partners to fill a specific Role"". It's clearer to me. 

@ocompagne  @jeanlucchristin  WDYT ?

**Comment by oliviercp** [comment]
> A Domain may grant exclusive control of assigning Partners to fill a specific Role

I like that wording better too, but it would lose the clarity added by specifying the domain itself. In my experience novice practitioners need things spelled out clearly. Domains being one of the more confusing constructs at the beginning, I can imagine someone asking "which domain do I need to enter to control that?".

Maybe this tension is best addressed outside of the constitution, e.g. GlassFrog could offer a dropdown of template Domains relevant to the constitution like Role Assignment, Partner Relationships, etc. 

Some guidance is needed somewhere IMO and absent anywhere else, I'm looking at the constitution to guide us. I'll try to think of an alternative wording

**Comment by vakil** [comment]
@brianjrobertson & @ocompagne 

I found this sentence confusing because the word "Role" is used 4 times.

**1.2 A Role may control who fills another Role through a Domain of Role assignment for that Role.**

Suggestion:
**A Role may decide who fills another Role, through a Domain of Role Assignment.**

I've chosen the word "decide" over "control" as that is more clearer to me.
Also suggesting a capitalizing Assignment because it forms part of the name of the domain.

**Comment by bernardmariechiquet** [comment]
@vakil I understand your point, but I think the four role words are necessary here. "through a Domain of Role Assignment" is not specific enough IMO.

**Comment by brianjrobertson** [comment]
Okay, I'm down to three options:
1) The current text: "A Role may control who fills another Role through a Domain of Role assignment for that Role."
2) The option above: "A Domain may grant exclusive control of assigning Partners to fill a specific Role."
3) This rewording: "A Role may hold a Domain of 'Role Assignment' for another Role." (Next sentence: "In that case, the Role holding this Domain may assign the target Role to anyone willing to fill it...")

Option 3 is probably clearest, but it has downsides: it introduces a term in single quotes, the only one like that in the constitution (I didn't use double quotes because that's used to define constitutional terms, and this isn't one of those), and it kinda makes a special thing of this particular domain language by naming it, when in reality this isn't really notably special as a domain, and other language should be just as good.

Which option do you all recommend?  Please reply soon; I'm closing down further edits in anticipation of v5.0's release before long.

**Comment by bernardmariechiquet** [comment]
Option 1

**Comment by oliviercp** [comment]
How about Option 3 but without the single quotes and with a small "a"?  (basically as it is used in Option 1). I feel like it's the best of both worlds. 

If not, then Option 1, even though it's significantly less clear

**Comment by vakil** [comment]
Some suggestions to option 3:

"A Role may hold a Domain of Role-Assignment for another Role. The Domain holder may assign the target Role to anyone willing to fill it."

**Comment by plamarque** [comment]
Option 2.
If not, then Option 3.

**Comment by MichaelDeAngelo** [comment]
I don't feel strongly about any one of the three. I probably would have worded #1 slightly differently: "A Role may control who fills another Role **by holding** a Domain **_for_** Role assignment for that Role." I would use **_of_** if you are calling out the domain explicitly: "Role by holding a Domain **_of_** 'Role **A**ssignment' for that Role." And use **_for_** if you are calling out the purpose "Role by holding a Domain **_for_** Role assignment for that Role." Three is probably clearer by calling out the Domain explicitly and then how to use it. However, I think #1 is fine as well.

**Comment by rebeccabrover** [comment]
@brianjrobertson
If I had to choose among these three, I would choose #3 with two discreet sentences but leave out the quotes with the following tweak, _Role assignment for a Role my be granted as a Domain to another Role._ Then the following sentence referencing what the role can do with the domain still works.
#1 reads to me as confusing and #2 brings in another term, _Partner_, which I know is already defined, but I think adds complexity with its use here.
Using #3 as is would still be my preference even with the quotation although I'm wondering if they are needed as an organization may choose different phrasing (assignment of xxx role, who fills xxx role, xxx role assignment) to convey the same meaning. I don't thin you have to identify 'Role Assignment' as the specific vernacular.

**Comment by chrcowan** [comment]
Option 3 would be my first choice, maybe with a slight rework like others have suggested.

**Comment by Pam-H** [comment]
Rebecca's tweaks to Option 3. With Michael's change of the word for to the word of, which would be this. Everything after the ... would be the same as it is highlighted in green, up through version 03c7487 from Oct 9, 2020.


Role assignment of a Role may be granted as a Domain to another Role. In that case, the Role holding this Domain may assign the target Role to anyone willing to fill it, ...

**Comment by brianjrobertson** [comment]
Thanks all, I took a stab at something part-way between option 1 and 3, with some parts of the suggested tweaks.  I'll submit momentarily, but please do let me know if you think this is more confusing than the prior version in any way, or if you have a new idea.
