### ISSUE TITLE
Clarify asset definition

### ISSUE THREAD

**Issue by leiomokusei** [holacracyone/Holacracy-Constitution#345]
The constitution refers to "assets" without defining what they refer to :
1- Are they assets belonging to the underlying legal structure? 
2- Can circles own assets ?

I assume that the correct answer here is 1-. This would mean that domains provide authority on assets which belong to the legal structure, and NOT to the assets owned by the circle itself.

This doubt make me wondering if that would make any sense of having circles owning assets (e.g. money) for the services they provide. After some thoughts it seems that it doesn't have much sense because the Lead could remove everyone from the roles and decide by himself to allocate all the money to himself. This said, happy to have your thoughts on that.

In order to clarify and remove any doubt for the reader, what about :
- Specifying that assets refer to assets owned by the underlying legal entity?
- Specifying that circles can't own assets?

**Comment by brianjrobertson** [comment]
I don't think this distinction is all that meaningful in the context of the constitution; the Anchor Circle controls (effectively "owns") all assets owned by the organizational entity itself, and that circle can delegate some or all of those ownership rights to sub-circles in Governance (granting a Domain grants most "ownership" rights, and a policy can grant most of the rest if desired).  So there's not really much of a difference.

**Comment by leiomokusei** [comment]
@brianjrobertson the info you mention would make it clear
> the Anchor Circle controls (effectively "owns") all assets owned by the organizational entity itself

but I don't see this info neither in the Constitution nor in the Adoption Declaration.

Is it written somewhere? If not, then I would suggest to mention it in one of the documents (constitution or adoption declaration). What do you think?

**Comment by julianeroell** [comment]
It's in Section 1.4.3: _"The Anchor Circle holds all authorities and Domains that the Organization itself controls (...)."_

**Comment by leiomokusei** [comment]
Thank you, all clear
