### ISSUE TITLE
Gap in accountability definition

### ISSUE THREAD

**Issue by bernardmariechiquet** [holacracyone/Holacracy-Constitution#348]
@brianjrobertson The evolution of the accountability definition between version 4.1 and version 5 introduced a gap. Indeed, there may hopefully be accountabilities in the service of external clients, for example, which are not internal Roles but sovereign entities.
https://github.com/holacracyone/Holacracy-Constitution/commit/aac1a68ff93e89b17e02960d542a18ca384f569f

**Comment by brianjrobertson** [comment]
@bernardmariechiquet Wouldn't that then be in service of the role's purpose?  If so, then it's already covered by the current definition, which allows an accountability to be any activity that would serve the role's purpose (or one that doesn't serve the purpose if it serves another role).  I'm not sure it makes sense to allow an accountability that is **_not_** for the purpose of the role nor to serve any other role in the circle; do you see cases where you think that makes sense?

**Comment by bernardmariechiquet** [comment]
@brianjrobertson The answer to your question is simple: we don't want implicit expectations from others, other internal roles, and other external entities. I already mentioned an example, let's be more specific:
Accountability: "Selling the company's products to customers remotely"
Purpose: "A top-notch customer experience!"

**Comment by bernardmariechiquet** [comment]
@brianjrobertson I would then recommend this simplest wording:

> (c) one or more “**Accountabilities**”, which are ongoing activities the Role will manage and enact in service of other entities.

**Comment by brianjrobertson** [comment]
@bernardmariechiquet I'm still not understanding; if an implicit expectation is causing an issue, someone just proposes it as an accountability; that expectation either serves that role's own purpose, or another role's purpose in the circle; if it doesn't, it probably shouldn't be added to that role.  In your example, wouldn't "selling the company's products to customers remotely" still serve that purpose?  If it wouldn't, why would the circle add it to that role, if no other role cared about it either?

**Comment by brianjrobertson** [comment]
@bernardmariechiquet I'm hoping to close-down further edits pretty soon in preparation for the constitution's release, but I'd like to get your thoughts on this still before then if you have any - let me know.

**Comment by bernardmariechiquet** [comment]
Thank you for asking @brianjrobertson  It's ok for me, at least for now, safe enough to try.
I sense something but I can't verbalize it. It will be for the next version, or not. As it's worded in the constitution to date, you're right, it works. I probably wanted to go further because of the additional models I use when I accompany clients at their request towards a culture of value creation at all levels. But we're may be beyond Holacracy.
