### ISSUE TITLE
Clarify "Defining Priorities & Strategies" type of power

### ISSUE THREAD

**Issue by leiomokusei** [holacracyone/Holacracy-Constitution#350]
I think it is unclear in the constitution what type of power are (in 1.5) :
- defining Priorities & Strategies
- Routing External References

If :
- Accountabilities: why not adding them in the Lead role accountabilities?
- "Responsabilities": why not adding them in "1.3 Responsibilities of Role-Filling"
- "Duties": why not adding them in the Lead role duties in Article 2?

**Comment by brianjrobertson** [comment]
These are none of those; they are authorities the Circle Lead may choose to use in service of the role's purpose.  They are not expectations (accountabilities, responsibilities, or duties) - i.e. not things that anyone else can expect the role to necessarily do, but just optional powers a role-filler may use if they so choose.  The closest parallel is §4.1, Authority of Role-Fillers, but §1.5 applies just to Circle Leads.
