### ISSUE TITLE
Clarify difference between Responsibility/ Duty/ Accountability

### ISSUE THREAD

**Issue by leiomokusei** [holacracyone/Holacracy-Constitution#351]
I find pretty unclear in the constituion what "responsibility"/"duty" mean.
Are they synonymous of accountability? Why using 3 different terms? 

Could we define them in the constitution in a way the difference with the other terms is clearer?

**Comment by brianjrobertson** [comment]
They are used with three different nuances of meaning.  An "Accountability" is an element on a role definition that the role-filler must do the meta processing "responsibilities" listed in §1.3 around; if we called §1.3 "Accountabilities" too, the definition would then be circular.  And "duties" is used similar to responsibilities in the constitution, but specifically for those things that others may want of you beyond what you must do for an Accountability - they are more "service to other" focused over "lead your own role" focused.
