### ISSUE TITLE
Allow Proposals based on Tensions that seek to limit potential harm

### ISSUE THREAD

**Issue by setpill** [holacracyone/Holacracy-Constitution#352]
The constitution allows Objections based on Tensions that seek to limit potential harm, if "the Circle wouldn't have an adequate opportunity to adapt before significant harm could result."

However, no such clause is built into the Proposal itself. This leads to the situation that if a Partner was not present for a governance meeting in which a Proposal that could cause harm was accepted, or only realizes this potential after the fact, they are disallowed from making a Proposal to improve upon this before the harm can result, as a Proposal requires them to "share an example of an actual past or present situation illustrating that Tension".

Am I misreading the constitution or am I correct that this seems like a bug?

**Comment by brianjrobertson** [comment]
I understand why it looks like a problem, but it's actually not in my interpretation.  If you sense a tension about a proposal just adopted, because of something that might or might not happen but that's not safe enough to try, that itself is your present Tension and your present situation - that should pass the proposal test no problem.

**Comment by setpill** [comment]
Is there a blog post/article/something detailing the process of testing proposals/objections for validity? Because your usage of "your present situation" does not mesh with my current understanding, which is that there needs to be an "actual past/present situation" in which the harm occurred.

I just feel that by having this criterion in one place but not the other, it implies different standards. If I were to propose a change it would be to hold the Tensions underlying both Proposals and Objections to the same standards as much as possible, by combining their criteria into a separate section that can be referred to by both, such that the difference in criteria (which is inherently tied to the difference between Proposals and Objections) is more explicit and clear. In this case, a perceived difference due to different wordings turns out to have not been intentional, and that in and of itself, is a Tension I have with the Constitution.

I will craft a PR to both illustrate what I have just described, as well as to provide an easy way to resolve my Tension in case my illustration is convincing.

**Comment by brianjrobertson** [comment]
The constitution does not say that there needs to be an actual past or present situation in which "harm occurred" - just one that "illustrates the Tension" that the Proposer is trying to resolve.  And a Tension doesn't mean "harm" necessarily, just a gap between current reality and a potential more ideal reality.  So it's certainly a Tension if you can describe a present situation where harm might occur that we wouldn't be able to adequately adapt to, and you can envision a situation in which there is no chance (or less chance) of harm happening beyond which we can adequately adapt to.  Thus, this seems pretty clear to me in the Constitution text, and I'm not seeing any reasonable interpretation counter to it.  If you think I'm missing something I'd welcome further arguments or other potential reasonable interpretations I'm not seeing, although for now I do believe the proposed wording change would make the Constitution harder to follow and understand, not easier.
