### ISSUE TITLE
"Waiting-on" not easily translatable to other languages

### ISSUE THREAD

**Issue by bugreport13** [holacracyone/Holacracy-Constitution#355]
In Section 2.2a of the latest version of the Holacracy Constitution beta 5.0, two sentences say

"If there are not, you must instead share what you're waiting on before you can take a Next-Action. If the Next-Action or waiting-on you share is part of a broader outcome for your Role to pursue, you must also capture and communicate that as a Project."

"waiting ON" in the first sentence is actually slang, because literally waiting ON in English means you are being waited on by a waiter or waitress or some kind of servant as a staff member. Waiting FOR would be non slang English such as waiting for some kind of information or waiting for someone to do something.

In the second sentence, waiting-on is being used as a noun, which it would not normally be in English. It would normally be 2 separate words. Even David Allen's GTD system such as the flow chart of the 2015 version of the Getting Things Done book simply says "Waiting" by itself.

I think it defeats what Brian says is a prominent goal of v5.0 of the Holacracy Constitution, to have the whole document easily translatable into other languages. 

It's fine to use hyphenated terms that are specific to Holacracy which you are defining in your document. "Waiting-on" is not an example of those.

It seems like it would be better for easy translation purposes into other languages, to change the 2 sentences to:

"If there are not, you must instead share what you're waiting for before you can take a Next-Action. If the Next-Action, or thing you are waiting for that you shared, is part of a broader outcome for your Role to pursue, you must also capture and communicate that as a Project."

One of several references you can find on the internet about appropriate use of waiting on versus waiting for:
https://www.abc.net.au/education/learn-english/learn-english-wait-waiting-on-or-waiting-for/8837546#:~:text=To%20'wait%20on'%20someone%20means,we%20are%20waiting%20for%20someone.

Thanks, P

**Comment by brianjrobertson** [comment]
Very helpful, thanks!
