### ISSUE TITLE
Role Assignment

### ISSUE THREAD

**Issue by margauxchiquet** [holacracyone/Holacracy-Constitution#356]
Sorry if I come “after the battle” but I am reading the constitution after some time, before the workshop and I have comments.

“1.2 Role Assignment
A Role may control which person fills another Role through a Domain of Role assignment for that Role. **Anyone** controlling such a Domain may assign the target Role to anyone **willing to fill it**, including to several people simultaneously. Whoever fills a Role becomes its "Role Lead". A Role Lead may later resign from filling the Role at any time, unless they’ve agreed otherwise. Whoever controls the assignment may also remove a Role Lead from filling the Role at any time. A Policy may further constrain Role assignments or removals.”

1/ “Anyone” => would put “Any role”.
2/ “Willing to fill it” => I find “willing to fill it” very unclear. Does it mean if I am not willing to fill it, I can't be assign. I would put “to anyone he/she thinks is the best fit for the role” and I would specify that that role controlling the role assignment should also monitor the fit.

**Comment by brianjrobertson** [comment]
Re suggestion 1:  I think "anyone" is more appropriate here, to reinforce and align with the fact that it is a human that acts (on behalf of a role), not the role itself that acts.

Re suggestion 2:  Yes, that means if you are not willing to fill it, you can't be assigned; or as I sometimes say, slave labor is not allowed in Holacracy practice. 😊  Re "monitoring fit", that was intentionally removed as an accountability of Circle Lead (even though it's likely important and something a CL may do in service of their purpose); see the discussion thread about that in the other github issue around removing the CL accountabilities (it was done to resolve a tension Bernard Marie raised).
