### ISSUE TITLE
Add a little more detail about Holacracy style Strategy to section 1.5.1

### ISSUE THREAD

**Issue by Pam-H** [holacracyone/Holacracy-Constitution#360]
I propose that the following 3 sentences be added to the end of section 1.5.1.

A particularly helpful version of a Strategy in Holacracy is to emphasize X, even over Y. Both X and Y are positives for the Circle, but at this stage of the Circle, the chosen Strategy is to prioritize X even over Y. This helps guide the activities of Roles in the Circle to prioritize one of the two potentially valuable activities or goals, even over the other.

My rationale: 
I think it is a big disservice to not give more guidance, to Holacracy practitioners and adopters, about what we find helpful as a heuristic in Holacracy. If a person has NOT read page 132 of Brian's 2015 Holacracy book, and they look on the internet for the definition of "heuristic", what they would find on Google Search in various dictionaries, as well as in Wikipedia, is NOT nearly as helpful and specific as the Holacracy book's definition. This helpful definition was discussed again by Chris Cowan way down in #3A of his article about Holacracy Strategy. I don't think we should just leave it to chance that people will or will not find that information.

**Comment by brianjrobertson** [comment]
I love the idea of providing more guidance to practitioners around this - that seems super important and useful to me.  And, the Constitution is definitely not the place I want to see that guidance inserted; that is outside the purpose of the document (and even contrary to it).
