### ISSUE TITLE
"these" unclear in 4.1 Authority

### ISSUE THREAD

**Issue by denniswittrock** [holacracyone/Holacracy-Constitution#362]
"You may also use your reasonable judgment to interpret this Constitution and anything under its authority. You may further interpret how **these** apply within any specific situation you face, and act based on your interpretations."

What are "these"? I assume, the rules of the constitution itself. 

proposed clarification:
You may also use your reasonable judgment to interpret this Constitution and anything under its authority. You may further interpret how these **rules** apply within any specific situation you face, and act based on your interpretations.

**Comment by brianjrobertson** [comment]
@denniswittrock "These" applies to the whole prior clause, i.e. "this Constitution and anything under its authority".  So your proposed clarification actually drops part of the intended (and needed) meaning (the part about "anything under its authority", which is beyond just "[the rules of] this Constitution".  We could of course replace "these" with "this Constitution and anything under its authority", but my own opinion is that this adds more downside in cumbersome language than it adds in the value of extra clarity ("these" seems pretty clear to me in this case).  But I welcome other opinions and push-back if you/others disagree...

**Comment by denniswittrock** [comment]
@brianjrobertson ok, now I get what is referred to by "these". I am trying to translate it, so it helps to understand which _two_ things it is referring to. In my superficial reading, I understood "this Constitution and anything under its authority" as merely _one_ thing, one chunk of meaning. Hence I was wondering about whether the word "rules" had accidentally been omitted, since "these" is clearly referring to plural things. We might still go for the repetition of "this Constitution and anything under its authority" in the German translation in the end though. I will run this by my colleagues to see which works better in German.
