### ISSUE TITLE
Testing for "harm" created by the proposal + amendment for (c)

### ISSUE THREAD

**Issue by denniswittrock** [holacracyone/Holacracy-Constitution#363]
Currently, Objection Requirements are IMHO not clear enough about what we are looking for when we are testing concerns about the adoption of a proposal. They should test for any **harm** created by the proposal. It's the main reason, why a concern gets validated as an objection. Instead, we hear about "reduction of capacity", "limit capacity", and "impact". Only criteria (d) mentions what should be the key word in my opinion: "**harm**".

Additionally, a nuance in criterion (c) should be spelled out more clearly so that it is not hidden "special" knowledge for advanced facilitators but visible to every practitioner.

CURRENT VERSION
5.3.2 Objection Requirements
A concern about adopting a Proposal only counts as an Objection if the Objector can provide a reasonable argument for why it meets all of the following criteria:

(a) The Proposal would reduce the capacity of the Circle to enact its Purpose or Accountabilities.
(b) The Proposal would limit the Objector's capacity to enact the Purpose or an Accountability of a Role the Objector represents in the Circle, even if the Objector filled no other Roles in the Organization.
(c) The concern does not already exist even in the absence of the Proposal. Thus, a new Tension would be created specifically by adopting the Proposal.
(d) The Proposal would necessarily cause the impact, or, if it might cause the impact, the Circle wouldn't have an adequate opportunity to adapt before significant harm could result.
However, regardless of the above criteria, a concern always counts as an Objection if adopting the Proposal would violate a rule in this Constitution.

PROPOSED CHANGES:
5.3.2 Objection Requirements
A concern about adopting a Proposal only counts as an Objection if the Objector can provide a reasonable argument for why it meets all of the following criteria:

(a) The Proposal would **create harm and thereby** reduce the capacity of the Circle to enact its Purpose or Accountabilities.
(b) The Proposal would **harm** the Objector's capacity to enact the Purpose or an Accountability of a Role the Objector represents in the Circle, even if the Objector filled no other Roles in the Organization.
(c) The **harm** does not already exist even in the absence of the Proposal. Thus, a new **harm** would be created specifically by adopting the Proposal. **Alternatively, to satisfy this criterion, it is enough for the proposal to increase an already existing harm.**
(d) The Proposal would necessarily cause the **harm**, or, if it might cause the **harm**, the Circle wouldn't have an adequate opportunity to adapt before significant harm could result.
However, regardless of the above criteria, a concern always counts as an Objection if adopting the Proposal would violate a rule in this Constitution.

**Comment by Pam-H** [comment]
I don't have a strong opinion either way, toward using the word harm throughout or toward leaving it the way it was. I do think consistency of wording is useful, whatever wording you pick. Especially when it will be translated into a long list of languages.

**Comment by brianjrobertson** [comment]
@denniswittrock The current wording avoiding "harm" is very intentional, and I think this proposed change would be a substantial move backwards.  First, "Harm" is a word with a much broader range of potential interpretations than "reduce the capacity of the Circle to enact its Purpose or Accountabilities" or "limit" or "Tension", and in these cases that broader interpretation limits the power of objection testing by allowing objections through that would be more effectively excluded; and second, at the same time, some common interpretations of "harm" I've seen will exclude things would be covered by "reducing capacity" or "limiting" (i.e. there are things one might likely consider to be "reducing capacity" or "limiting" that they wouldn't necessarily claim are "harming"), and these things are typically useful as objections and not something we'd want to exclude.  In my view, this proposed change would actually kill some of the real nuanced magic of objection testing in Holacracy; at the very least, in my experience facilitating, it would make me far less effective as a facilitator if I had to use these rules vs. what's in the constitution.

Also, the addition of "to satisfy this criterion, it is enough for the proposal to increase an already existing harm" is also problematic and intentionally excluded right now.

**Comment by denniswittrock** [comment]
@brianjrobertson thanks for the clarifications. I know you've already closed the issue altogether, but I would love to understand your points with more context. Could you provide some _examples_ you've seen (or can imagine) where the proposed changes would have likely led to ...well, "harm" (or "reduction of capacity" if that changes anything in your frame of reference) compared to the current wording? 

I am not sure if this a major semantic difference in the use of the word "harm" in English compared to "Schaden" in German with "harm" being at the very upper end of a "scale of harm", versus "reducing capacity" or "limiting" being at the lower end of it, but even then I am wondering: what is the _real_ problem if the proposal  "reduces the capacity" or "limits" a role? Isn't it that it is causing "harm" in the end as well? 

Or is your concern that you think that people wouldn't go so far as to claim a proposal would cause "harm" and are much more willing to consider, whether it would "reduce their capacity" or "limit" them? Again, examples would be really helpful here. 

Also, I wonder if the word "**damage**" instead of "harm" would resonate differently and where that would be located on the said scale. If we replaced "harm" with "damage" in my proposal, would it be equally unacceptable in your interpretation?

The other open question I had was with regard to the reasoning against the other proposal concerning the amendment for (c). I would be grateful to be able to better understand why exactly you think it is "problematic". Again, examples to illustrate your point are very welcome!


[By the way,  as much as I trust you in your Constitution Steward role and respect your vast reservoir of experience and nuance on all things constitutional as the champion of Holacracy, I notice that in cases like these I would actually prefer to use something like the existing process for testing objections for proposals and apply it to changing the constitution itself. This would reinforce the impression that there is actual rigor in the debate and would probably reduce my weird sense of being shut down immediately in this issue I opened, without you even waiting to hear how I receive your argumentation. Your role has the power to just close the issue whenever. Would have loved to hear what _others_ are thinking. This way it is relegated to invisibility after 16 hours. I am not supposing that you are doing this in bad faith, but this kind of power can potentially be abused or have a blind spot and from a Community of Practice point of view I wish there were more checks and balances. So maybe we could additionally think about how we could build on top of the governance rules to govern the evolution of the "Constitutional Commons", too. Just a thought. It is a different context, I know, but some of the mechanism used _within_ an organization might also be useful for governing _inter_-organizational spaces like these]

**Comment by brianjrobertson** [comment]
@denniswittrock Here's a 5-minute video response for you:  https://www.loom.com/share/90f57fc1b83848eaa7f14b6b03db3ea2

**Comment by denniswittrock** [comment]
Hey @brianjrobertson , thanks for sharing your thoughts in the video. I understand the limitations for you in processing all of the various contributions coming from various levels of maturity. If I try to put myself in your shoes, I have a lot more sympathy for how that must feel like for you. 

I still haven't heard any examples, but ok. Let's not overdo this. I will take your word for it for now. 

What I get is the value of having a clear definition of "harm" in the constitution. An "objection" is a reason why a proposal causes "harm".  In the current case, it is "reducing capacity, etc. ". So my last suggestion here (which you don't have to reply to) is to take the word "harm", add an explicit definition of its meaning the way you think it makes sense (the current one), and then still replace the other instances as  proposed above to have a more unified focus. 

This definition of "harm" could be achieved by tweaking the first objection requirement like this: 

(a) The Proposal would **create "harm" which is defined as reducing** the capacity of the Circle **or Role** to enact its Purpose or Accountabilities.

Another thought: 
My tension with the current criteria comes from practice. We found it is much easier if people really take a few moments to verbalize the concrete **harm** the proposal could cause. We will still focus on asking for "harm" by using our own version of the facilitation cards and our own didactics around that. This is independent of this discussion anyway. I guess I just hoped the constitution could reflect that clearer focus as well...

**Comment by brianjrobertson** [comment]
@denniswittrock I'm not sure what would be gained by this?  I resonate with your point about the value of getting someone to verbalize something concrete; but that value is met even better by getting them to verbalize concretely how it would reduce the circle's capacity to express its purpose - it's more concrete, and easier to get to a more concrete statement that way.
