### ISSUE TITLE
Change "Amend & Clarify" to "Option to Clarify"

### ISSUE THREAD

**Issue by denniswittrock** [holacracyone/Holacracy-Constitution#364]
In our own practice at Hypoport, we reversed the order of words in the **Amend & Clarify** step in IDM.

For us "**Clarify & Amend**" makes more sense, since we don't want to nudge people towards assuming they are expected to _amend_ their proposal in any way unless it serves them to better solve their tension. In our experience, this is more about responding to reactions the proposer heard before and clarifying the intent of the proposal anyway. 

Additionally, even _if_ amendments are made, these could be viewed as a form of clarification (of the proposal) as well. So for us, the emphasis should be on the "clarify" portion of the step. 

Even the description of the step itself in the constitution starts off with the proposer's reaction (i.e. clarification) part. The title should reflect that order as well. 

CURRENT VERSION
(d) **Amend & Clarify:** Next, the Proposer may share comments in response to the reactions and make amendments to the Proposal. However, the primary intent of any amendments must be to better address the Proposer’s Tension, and not Tensions raised by others. The Facilitator must immediately stop comments by anyone other than the Proposer or Secretary. Any engagement by the Secretary must focus solely on capturing the amended Proposal.

PROPOSED VERSION:
(d) **Clarify & Amend:** Next, the Proposer may share comments in response to the reactions and make amendments to the Proposal. However, the primary intent of any amendments must be to better address the Proposer’s Tension, and not Tensions raised by others. The Facilitator must immediately stop comments by anyone other than the Proposer or Secretary. Any engagement by the Secretary must focus solely on capturing the amended Proposal.

**Comment by brianjrobertson** [comment]
Hmm, something about this isn't resonating with me at all, though I'm not sure if I'm just used to the current order and missing it, or if it's a cultural difference, or something else.  Sounds like you're assuming that whichever word you put first in the name would be the one that creates the most pressure, and I'd actually assume the other way around - that the second word, the last one someone hears, is the one most likely to linger and set a tone for what they "should" do.  But again, that could just be a bias because of what I'm used to - I'm not sure.  Or maybe an English/German language nuanced cultural thing perhaps (just guessing; I really have no idea).  Either way, I'm left feeling like this change would at best be neutral, and possibly worse - something about it seems off to me intuitively and with how it sounds (although perhaps just because of what I'm used to).  If others have any strong opinions I'd love to hear them, otherwise I'm going to default to dropping this one.

**Comment by Pam-H** [comment]
Clarify and amend does seem to be a more logical order to me. However, it also seems true that putting amend after clarify does sort of imply that you need to end by amending something, which you don't necessarily. No strong opinion. Maybe leave it as it is??  It's almost like it could be Clarify and/or amend.... instead of just and...

**Comment by klaas1979** [comment]
I can just second @denniswittrock but I am working in the same context so I am maybe biased as well :) In my experience the changed order helps a bit to convey that there is no need to amend and sets a focus on the clarifying part. We are doing it for about two years now so the experience is sound.

**Comment by bernardmariechiquet** [comment]
@brianjrobertson There are certainly cultural nuances here. In my practice in French, I use the clarify-amend order which seems more natural and I observe that people do not seem to have any weight on having to modify.  Looking back, it seems to me that I started with the amend-clarify years ago and changed as I integrated deeper the process into my practice. It came naturally, which gives me a certain amount of confidence in that order. 
I like it because it seems to me that this order reduces the weight on modifying it. And it reduces the risk that the proposer will feel obliged to change as a result of people's reactions.

**Comment by julianeroell** [comment]
I can echo Dennis' and Klaas' experience: In my experience, "Amend & Clarify" does seem to put pressure on people to amend something, as if that were the normal/expected thing to do in this step. Changing the word order helps with this, emphasizing _creating clarity_ over _amending things_.

**Comment by brianjrobertson** [comment]
Given how cultural this one is, perhaps it makes sense to translate it "Clarify & Amend" even if the English stays as-is?  If that's your sense as native French/German speakers, that makes sense to me.  But I'm still unsure which order emphasizes amending more in English - I think often the thing we end on has more emphasis than the first thing in a list.  I'd love to hear from other native English speakers on this one...

**Comment by bernardmariechiquet** [comment]
Excellent, I just checked and this is what I had done during the localization of version 4.1 - "Clarify and modify".

**Comment by Pam-H** [comment]
5.4.5d says "**(d) Amend & Clarify:** Next, the Proposer may share comments in response to the reactions and make amendments to the Proposal. However, the primary intent of any amendments must be to better address the Proposer’s Tension, and not Tensions raised by others. The Facilitator must immediately stop comments by anyone other than the Proposer or Secretary. Any engagement by the Secretary must focus solely on capturing the amended Proposal."

It seems very clear to me that the Proposer **may** share comments and **may** make amendments, but with the main intention to better address the Proposer's Tension. So it seems like it is pretty clearly spelled out in writing here, regardless of the order of the two words in the title. I do find it interesting that the order of the two words, Amend & Clarify, in the title, does not match the order of the following sentence which talks about sharing comments to clarify, and then potentially make amendments.

To add more clarity that the Proposer does not need to make any amendment necessarily, you could repeat the word may a second time. Then the reader is absolutely sure that no amendment needs to be made.

"**(d) Clarify & Amend:** Next, the Proposer may share comments in response to the reactions and/or may make amendments to the Proposal. However, the primary intent of any amendments must be to better address the Proposer’s Tension, and not Tensions raised by others. The Facilitator must immediately stop comments by anyone other than the Proposer or Secretary. Any engagement by the Secretary must focus solely on capturing the amended Proposal."

**Comment by brianjrobertson** [comment]
Hmm, that triggers a thought:  What would we call the step if we didn't call it either "Amend & Clarify" or "Clarify & Amend"?  Is there an all-around better name that doesn't suffer from the risk of encouraging amendments?

**Comment by matthewgilliland** [comment]
I wonder if an "or" (e.g. Clarify or Amend) might diffuse some of the pressure? I can't point to much logical reasoning behind why it would, but my sense is that it lightens it and makes me more likely to think about which (if either or both) I would like to do. I suppose this might be implicit reasoning behind asking "Would you like to amend or clarify your proposal?"

**Comment by julianeroell** [comment]
> What would we call the step if we didn't call it either "Amend & Clarify" or "Clarify & Amend"? Is there an all-around better name that doesn't suffer from the risk of encouraging amendments?

"Clarification Round" comes to mind. (The thinking being that making-an-amendment can also be understood as an act of "Clarification"). 

(I'm not too sure about this, but I wanted to throw it out there to encourage more thoughts in the direction of finding an all-around better name.)

**Comment by julianeroell** [comment]
> What would we call the step if we didn't call it either "Amend & Clarify" or "Clarify & Amend"? Is there an all-around better name that doesn't suffer from the risk of encouraging amendments?

I was going to suggest "Clarification Round" until I realised that there is no "Round" in this phase of the process. :)  (The thinking was that making-an-amendment can also be understood as an act of "Clarification"). 

So... just "Clarification"? 

(I'm really not sure about this, but I wanted to throw it out there to encourage more thoughts in the direction of finding an _all-around better name_.)

**Comment by rebeccabrover** [comment]
I still think _Amend & Clarify_ is still the best option - at least over changing it. I do think changing to _or_ presents potential perception of a limiting the option to do either one or the other even if the proposer wants to do both.
I question whether changing the order would really remove the potential pressure to change or clarify a new proposer might feel. From the other comments, it's sounds like the facilitator's framing and vocal track is what really alleviates that pressure.
That being said - in English, forming an _A_ sound first and moving to a _C_ sound is more natural in the mouth, but I see no harm in going either way depending on the ease of communication in another language, if it comes out better.

**Comment by bernardmariechiquet** [comment]
I'm with @julianeroell's comment inviting to encourage more thoughts in the direction of finding an all-around better name.
Basically, this step allows the proposer to complete his or her first speech/output in the first **Present Proposal** step after being exposed to questions and then to the reactions of other participants. 
I think this **Amend & Clarify** step could be seen as an additional space offered to the proposer to complete his or her first speech/output at **Present Proposal**. There seems to be some kind of link between the two steps. The structure could be symmetrical.
I will then propose the name **Amend Proposal** as a name that would make sense with this way of looking at things.
In the same way that the proposer may describe the tension in step **Present Proposal**, the proposer may share comments in response to the reactions in **Amend & Clarify** step.
I'm wondering what is the added value in putting the word clarify in the title? In the same way that there is no word Tension (that could be described yet) in the title **Present Proposal**.
What we're opening here is the possibility to make the proposal evolve, isn't it? And space for comments.
This would present the double advantage of removing the confusion associated with the presence of two words in the title. And it makes things more consistent IMO.

**Comment by klaas1979** [comment]
In German the word clarify is enough, we would not need an "amend" in the title as stated by @julianeroell . If someone clarifies something it could include a change of the "it".

**Comment by denniswittrock** [comment]
How about "**Clarify Proposal**" to be in line with "Present Proposal"? 

I second that "clarify" ("klären") can both mean explaining the original intent or amending the wording (at least in German). You can clarify something _about_ the proposal or directly _clarify the proposal_ (by tweaking it).

**Comment by rebeccabrover** [comment]
@denniswittrock My concern with reduction to "**Clarify Proposal**" is the potential for implicit pressure. The alignment with "**Present Proposal**" doesn't quite match. Even if it is mushy and awful, it is not possible to move on from Present Proposal without at least something to start while it is totally possible (and often encouraged with new practitioners) to move past Amend & Clarify without making any changes or explaining anything.
I suggest something like, "**Option to Clarify**" to address the use cases of clarify working in multiple languages for both change and explain, and to explicitly reduce pressure to do either.

**Comment by oliviercp** [comment]
I've been thinking about switching the order of the terms too, if only because in practice the explanation/response from the proposer often occurs before an amendment is captured.

But I like the idea of changing the term entirely. I like **Option to Clarify** the best of what's been proposed, for it emphasizes the optional aspect of this step — it's the most important aspect to convey in my opinion. Having the Facilitator say out loud "Option to Clarify" when transitioning from reactions should help reduce the weight on the proposer's shoulders, even if the Facilitator is otherwise not very skilled and may not explain further the optionality of amending.

**Comment by brianjrobertson** [comment]
If the choice is between "Amend & Clarify" or "Clarify & Amend", I'd stick with the former - I agree with Rebecca that it just sounds more natural and less weird in English, and I don't think the first word is more emphasized than the last.  If we're going to change it entirely though, I'd prefer using just "Clarify" over "Amend" - the definition of "clarify" would include amending (that's also "clarifying" a proposal), but not vice versa.  I like the effect of adding the "Option" language as well, but "Option to Clarify" sounds awkward as a step name to me; does it to anyone else?  Is it really better than "Amend & Clarify"?  Would "**Optional Clarification**" sound/work better?

**Comment by rebeccabrover** [comment]
@brianjrobertson 
When spoken out loud in English, I think Optional Clarification is so much more of a mouthful than Option to Clarify. It’s only two less syllables but so much easier out of the mouth. 
When I think of all the practitioners trying to practice in English when that may not be their first language, I’m inclined to keep the words as simple and easy to say as possible.
My preference is to simply keep Amend & Clarify, but in my opinion, Option to Clarify is way better than Optional Clarification.
One other little thought is there is something congruent-sounding between Clarifying Questions and Option to Clarify (or Amend & Clarify) which gets muddier with Optional Clarification.

**Comment by rebeccabrover** [comment]
@brianjrobertson 
I disagree about the sound as a title of the step. When I think about word choice to transition to the step, Option to Clarify is easier to work with for me. My natural inclination when I practice framing out loud comes out something like, _We are now at Option to Clarify. Proposer, you now have the option to clarify your proposal or make any changes with not pressure to do either._ The words work and lend to step as an offer, not a command.
When I do the same thing with Optional Clarification, I find myself needing to add extra words. I sounds more like, _We are now at the Optional Clarification step..._ The rest is the same.
Just a bit more jargon-sounding, clunkier and harder to form elegantly.

**Comment by brianjrobertson** [comment]
Okay, I'm sold on that @rebeccabrover, let's drop "Optional Clarification" as an option.  So, do we switch to "Option to Clarify", or keep "Amend & Clarify"?

**Comment by rebeccabrover** [comment]
I’m surprised my little stabilizer self is going this way (particularly since I don’t think there is anything inherently wrong with Amend and Clarify), but I lean strongly toward Option to Clarify. It just makes it so clear (even for someone simply reading it from the card) that it is a choice. The built-in framing as the title of the step is a subtle, but powerful upgrade.

**Comment by bernardmariechiquet** [comment]
I like the way thinking progresses on this thread. 😀
I think **Option to clarify** makes a lot of sense and is IMO the most accurate title so far.

**Comment by klaas1979** [comment]
Great to find a solution that works for different languages. I really like **Option to clarify**, as stated before. It is quite clear!

**Comment by oliviercp** [comment]
I still prefer **Option to Clarify** as well. I don't really see any significant drawback to it

**Comment by denniswittrock** [comment]
Happy to go along with "Option to Clarify" as well. This still addresses my original tension. :-)
