### ISSUE TITLE
Include default rules ("stubs") for modular adoption as appendix

### ISSUE THREAD

**Issue by denniswittrock** [holacracyone/Holacracy-Constitution#366]
The default rules ("stubs") for modular adoption that were presented in the v5 webinar should be included as an appendix or as an extra paragraph after each article

Article 1: Organizational Structure
– Article 1 is required to use any other rules of the Constitution.
Article 2: Duties to Others
– If Article 2 is not adopted, the Circle Leads may specify the duties a Role Lead has to other Role Leads, unless otherwise specified by a broader Circle Lead or by the Ratifiers.
Article 3: Tactical Meetings
– If Article 3 is not adopted, the Organization will continue its current meeting habits, until otherwise changed by a Circle Lead for their Circle, or until otherwise specified by a broader Circle Lead or by the Ratifiers.
Article 4: Power Shift
– If Article 4 is not adopted, Role Leads must align all actions and decisions with any direction given by a Circle Lead of their Circle or any broader Circle, unless otherwise specified by a broader Circle Lead or by the Ratifiers.
Article 5: Governance
– If Article 5 is not adopted, Circle Leads exclusively may edit the Governance within their Circle at any time or allow others to do so, unless otherwise specified by a broader Circle Lead or by the Ratifiers.
Article 6: People & Partnership
– If Article 6 is not adopted, the Ratifiers may specify the process for adding and removing Partners of the Organization, and anyone they empower to make that decision may further specify the expectations and agreements required of the Partners.

**Comment by brianjrobertson** [comment]
They will be; I have a document I'm planning to submit.
