### ISSUE TITLE
Does "Defined Roles" in "2.6.1 Modifying Sub-Circles" imply sub-circles?

### ISSUE THREAD

**Issue by djwork** [holacracyone/Holacracy-Constitution#37]
In the second paragraph of [2.6.1 Modifying Sub-Circles](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#261-modifying-sub-circles)

> A Circle may also move its own Defined Roles or Policies into a Sub-Circle, or move any from within the Sub-Circle into itself.

Does "Defined Roles" imply whole sub-circles as well? 

From my understanding of 2.6.1 the governance process of Circle 1(C1) can promote Role 3(R3) from Sub-Circle 2(C2) into Circle 1. 
_eg: C1(R1,R2,C2(R3,R4)) -> C1(R1,R2,R3,C2(R4))_

But does this mean it is valid governance also promote or demote whole sub-circles as if they were a defined role? Sub-Circle 2(C2) has it's own Sub-Circle(C3), can Circle 1 (C1) promote C3?
_eg: C1(R1,R2,C2(R3,R4,C3(R5,R6))) -> C1(R1,R2,C2(R3,R4),C3(R5,R6))_

**Comment by brianjrobertson** [comment]
Yes, it does mean that's valid.

**Comment by djwork** [comment]
Worth rewriting the clause to make it clearer?

**Comment by djwork** [comment]
I mean that "Defined Roles" == "Sub-Circle"
I don't remember seeing it laid out that black and white

**Comment by brianjrobertson** [comment]
Hmm, possibly; I'll leave this as an open issue to consider for v5.0.

**Comment by djwork** [comment]
@brianjrobertson this kind of question is prompting a tension for me in the area of a pattern language for expressing governance states and transitions (maybe a notation similar to the above example eg: C1(R1,R2,C2(R3,R4)) -> C1(R1,R2,R3,C2(R4))).

If we had a pattern language we could write a series of tests that represent known valid and known invalid governance states and transitions. This test set could then be applied to new versions of the constitution at various stages in the development \ release cycle.

Also this test set may make it easier to translations the constitution into other languages.
I previously sent a mind map of this and other issues to @ocompagne.

**Comment by brianjrobertson** [comment]
Sounds cool, would love to see what you come up with!

**Comment by bernardmariechiquet** [comment]
@djwork Love the way you put things like C1(R1,R2,C2(R3,R4)) -> C1(R1,R2,R3,C2(R4)))
Would appreciate to get a copy of the mind map you mentioned.

**Comment by djwork** [comment]
Broadcast to the regulars, any suggestion on a notation to base the pattern language on? 
My preferences are:
-  Text based over graphics based, to avoid a dependency on a specific tool.
-  Needs to represent complex nested relationships between entities.

Otherwise I will knock up a prototype based on the above notation eg:

##Primatives
Circle = C 
Role = R
Domain = D
Policy = Pl

C1(D1(Pl1,Pl2),R1(D2(Pl3)),R2,R3,R4,C2(D3,R5,R6),C3(D4(Pl4)R7,R8)) =
a circle with:
-  domain D1 with 2 policies  (Pl1 & Pl2)
-  role R1
  -  Which has an assigned domain D2 that has a policy Pl3
-  Roles R2-R4
-  Sub-circle C2
  -  Which has an assigned domain D3 
  -  Roles R5,R6
-  Sub-circle C3
  -  Which has an assigned domain D4 that has a policy Pl4
  -  Roles R7,R8

##Cardinality
_Example_
Roles may have:
-  1..1 Purpose
-  0..n Domains
-  1..n Accountabilities

##Qualified Name Format
Dot notation, left to right, super to sub eg:
FQN for policy Pl4 = C1.C3.D4.Pl4

##Other Primitives
Partner = Pt
Organisation = Org

**Comment by djwork** [comment]
@bernardmariechiquet I will PM you on linkedin to work out how to send it.

**Comment by brianjrobertson** [comment]
Closing this issue for lack of any new contributions and because it seems to have drifted from the original subject (though please do open a new one, or perhaps post on the Community of Practice, if you want to inspire more discussion)...
