### ISSUE TITLE
Differentiating Circle Lead Role is a legitimate need at Anchor Circle. Let's fix it!

### ISSUE THREAD

**Issue by bernardmariechiquet** [holacracyone/Holacracy-Constitution#371]
@brianjrobertson This issue is following our comments on https://github.com/holacracyone/Holacracy-Constitution/issues/330#issuecomment-690938534 as you asked me for opening a separate issue.
So let me offer more specific cases/arguments and dive in more specific context.

As you may know, we (iGi institute) accompany more and more companies by training and coaching their managers, because of our deep experience in managerial matters (20+ years), added to our 10+ years experience in Holacracy we got with about one hundred companies. 
We have learned in the fieldwork that managerial excellence is a necessary condition to accompany people towards self-management. 
We have had to develop several apps and constitutional amendments to clarify the expectations of the role of Circle Lead. Among other conclusions, this brought us to https://github.com/holacracyone/Holacracy-Constitution/issues/330 that successfully impacted the v5.0 constitution with the elegant proposal you made in [Article 1.5.3](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#153-amending-the-circle-lead-role) 
During our last two clients training and coaching last summer, we co-constructed with these clients their managerial framework, which we do regularly with all our clients, and in these cases, tension arose. Several Circle Leads expressed the fact that it was difficult, if not impossible, for them to take care of the business of their circle and at the same time to accompany the role leads. They recognize the imperative need to accompany them and observe that they do not succeed in doing so, on a recurring basis. The reason being that holding these two polarities at the same time, managing the circle as a business and accompanying people, were not compatible. They, therefore, decided at the Board level (Anchor Circle) to create a managerial excellence app that integrates two distinct roles for all the circles in the organization: a Circle Lead and a "more HR" Circle Lead (not yet named).  
This has become obvious to me. I make the connection with other companies, two to be precise, which have not adopted Holacracy, partly for this reason, that is to say, they wanted to systematize two separate roles in lieu et place of the Circle Lead, because of these polarities "hardly compatible" at the same time under the same head.

@brianjrobertson You'll understand that we're not at all in the cases you and I've seen that seem to you/me too like a broader circle over-controlling, instead of just telling the sub-circle what they're accountable for and letting the sub-circle self-organize around it.

The overall pattern emerging here is about being able, from a set of Circle Lead accountabilities, to break them down into more than one role, at a whole org. level. Does this make sense to you?

**Comment by brianjrobertson** [comment]
@bernardmariechiquet What do you mean by "accompany" in your use of that word here?  What does this to-be-named "more HR Circle Lead" role do?

**Comment by brianjrobertson** [comment]
Also, help me understand why it's important to mandate a sub-circle have this extra role, instead of make clear what's expected of a Circle (or of every Circle Lead), and let them figure out if/how to create roles to do it?

**Comment by brianjrobertson** [comment]
@bernardmariechiquet Some questions, which point to my concerns about this:  Every role is a circle internally; does every role thus have this new role inside of it?  Even a role that has no other roles within?  What about a role/circle with just one other role within, filled by the same person as the broader role; is this role created as soon as you break your role down, even if just for your own organizational purposes?  The fact that these questions are difficult to answer "cleanly" points to me to something that's off in this potential feature.

Another question:  Why can't you achieve the need here with a simple policy under the current draft v5.0 rules?  I don't totally understand what this other role would be doing, but for example, something like an Anchor Circle policy that says "The Circle Lead may not assign or remove partners, other than themself, to any role within the circle, unless they have a separate role in the circle, filled by someone else, with the authority [or expectation] to [whatever you want this role to do].  This policy applies in all sub-circles recursively, and no sub-circle may modify or remove it."  You could go so far as to specify the specific accountabilities/domains on that other role in that policy if you wanted.  Seems like this would achieve the same result, and not require a constitutional adjustment; what do you think?

**Comment by bernardmariechiquet** [comment]
> @bernardmariechiquet What do you mean by "accompany" in your use of that word here? What does this to-be-named "more HR Circle Lead" role do?

Let me switch in french. Je veux dire "accompagner" les clients.
I mean providing services, training, coaching, consulting.

**Comment by bernardmariechiquet** [comment]
> Also, help me understand why it's important to mandate a sub-circle have this extra role, instead of make clear what's expected of a Circle (or of every Circle Lead), and let them figure out if/how to create roles to do it?

Happy to have a call with you, this requires me too much energy to write so deep and nuanced matters in English. In short, this is the same subject as the one in https://github.com/holacracyone/Holacracy-Constitution/issues/330 opening up the possibility of allocating "incompatible" accountabilities to multiple roles.

**Comment by bernardmariechiquet** [comment]
> @bernardmariechiquet Some questions, which point to my concerns about this: Every role is a circle internally; does every role thus have this new role inside of it? Even a role that has no other roles within? What about a role/circle with just one other role within, filled by the same person as the broader role; is this role created as soon as you break your role down, even if just for your own organizational purposes? The fact that these questions are difficult to answer "cleanly" points to me to something that's off in this potential feature.

You lost me, I don't get what is behind yoour questions, probably because I was not clear enough so that you would understand the whole thing.
> 
> Another question: Why can't you achieve the need here with a simple policy under the current draft v5.0 rules? I don't totally understand what this other role would be doing, but for example, something like an Anchor Circle policy that says "The Circle Lead may not assign or remove partners, other than themself, to any role within the circle, unless they have a separate role in the circle, filled by someone else, with the authority [or expectation] to [whatever you want this role to do]. This policy applies in all sub-circles recursively, and no sub-circle may modify or remove it." You could go so far as to specify the specific accountabilities/domains on that other role in that policy if you wanted. Seems like this would achieve the same result, and not require a constitutional adjustment; what do you think?

This is weird and I'd like the software to support that.

**Comment by bernardmariechiquet** [comment]
@brianjrobertson I suggest this patch as a solution https://github.com/holacracyone/Holacracy-Constitution/compare/master...bernardmariechiquet:patch-16
This would be a very natural mirroring on that's done with additions. 

_

> 1.5.3 Amending the Circle Lead Role
> A Circle may not modify the Purpose of its Circle Lead Role, nor remove the Role.
> 
> A Circle may add Accountabilities or Domains to its Circle Lead Role, and those additions automatically apply to every Sub-Circle's Circle Lead Role as well, recursively. A Circle may not add Accountabilities or Domains just to its own Circle Lead Role.
> 
> A Circle may remove any Accountabilities, Domains, authorities, or functions of its own Circle Lead Role. It can do this either by placing them on another Role in the Circle, or by defining an alternate means of enacting them. Doing this automatically removes the relevant element from the Circle's Circle Lead Role, for as long as the delegation remains in place.

_ **Those removals may automatically apply to every Sub-Circle's Circle Lead Role as well, recursively.**

**Comment by brianjrobertson** [comment]
@bernardmariechiquet Okay, I think I'm getting what you're wanting to do and why, though I'm not clear how that solution would help - I wouldn't interpret that as giving a circle the authority to mandate a specific role definition in every sub-circle.  Even if we added language that would allow that though, I think it would still be problematic; remember, every single role is also a circle internally - so, mandating a role (let's call it "Special Role") within each circle would mean every single role in the organization has that Special Role within its inner circle.  And I don't think that's what you're wanting.

Beyond that, it seems a policy-based solution is far more elegant here to me; per my example above, you could simply have a policy that prevented all circle leads from doing a specific function unless it were first carved out into a separate role.  Whether or not GlassFrog supports that is a separate issue from whether it goes in the constitution, so that's irrelevant to this constitution discussion from my perspective; even if it's not in the constitution directly, that doesn't mean GlassFrog can't implement a convenience feature to allow a templated role to be more easily created (or even to be automatically created in new circles, although that brings us right back to the problem of when to create it, because every single role is also already a circle).

If you think a call would be useful to dig into this further, I'm happy to schedule one with you, or to continue the dialog here, as you prefer.

**Comment by bernardmariechiquet** [comment]
@brianjrobertson I suggest we have a call, it will be much more efficient and productive. There are some things that will be easier for me orally.

**Comment by brianjrobertson** [comment]
Closing this based on the call I had with @bernardmariechiquet, in anticipation of a policy-based solution working coupled with software support for role templates.

**Comment by bernardmariechiquet** [comment]
Yep, we agree on that! 
@brianjrobertson It is interesting to notice that Holacracy is evolving from a simple constitution to a constitution and its software.  And that some mechanisms not described in the constitution are absolutely necessary for practice. So the software is an integral part of Holacracy. It's the first time that this is so obvious to me.
Probably it will be the software that will define Holacracy in the future, which I have been sensing for years, and already shared with @Tomthomison and @brianjrobertson  in early 2011.

**Comment by brianjrobertson** [comment]
Agreed @bernardmariechiquet - quite cool to see that actually happening!
