### ISSUE TITLE
Authorizing the Anchor Circle to clarify accountabilities on itself they already have due to external parties.

### ISSUE THREAD

**Issue by bernardmariechiquet** [holacracyone/Holacracy-Constitution#372]
We have encountered several cases in companies that we accompanied in the adoption of Holacracy, in particular, those whose legal form is "Executive Board and Supervisory Board". The adoption was ratified by the Executive Board, which is in accordance with its legal authorities. However, the Supervisory Board has not adopted Holacracy, it does not wish to do so. And it is OK. He has just been informed and has had the opportunity to raise tensions, but that is not the subject.
Because of the statutes and/or the mode of operation between the Supervisory Board and the Executive Board, the Supervisory Board may have expectations on the part of the Executive Board. Such as, for example, "To present to the Supervisory Board at least one report by the Executive Board on the management of the company at least once a quarter". In this case, the anchor circle, which corresponds to the Executive Board, has put this accountability on the anchor circle. This was necessary for them.
So i see the need to integrate that possibility in article 1.4.3.

**Comment by brianjrobertson** [comment]
This was already resolved in #368.
