### ISSUE TITLE
make "what can be overriden" clear and searchable

### ISSUE THREAD

**Issue by benoitpointet** [holacracyone/Holacracy-Constitution#375]
I wish for a clear marker of what in the constitution can be overriden.

Please consider using a same formulation in all places where the constitution sets a default construct/rule which can be overriden, like "Unless Governance says otherwise, …”.

That way we would only need to do text search for "unless gov" to identify such overridable elements.

**Comment by brianjrobertson** [comment]
I'm not sure how to elegantly implement this, but if anyone wants to take a stab and submit a pull request, I'll definitely consider it.

**Comment by sitron** [comment]
i have no idea how to implement it elegantly neither but wish a solution could be found as well

**Comment by brianjrobertson** [comment]
Given no suggestions for a few weeks, I'm going to drop this; if anyone wants to take a stab though, please feel free to comment and I'll re-open.

**Comment by benoitpointet** [comment]
I gave it a try yet I realize bringing it all to one formulation would complexify things. 

A proposal: it would be enough to make sure that "what can be overriden" is findable by either the "unless" word — working well atm — or by "A policy may" which is not so efficient atm because sometimes written "A policy **of the Circle** may".

Keeping the two wordings will at least give people more chances to find what is overridable.

**Comment by brianjrobertson** [comment]
I'm not feeling this tension enough myself to want to spend the time trying to do that, but if you are and want to take a stab at an update and submit it for consideration, I'd be happy to review and consider...
