### ISSUE TITLE
why even keeping the notion of circle?

### ISSUE THREAD

**Issue by benoitpointet** [holacracyone/Holacracy-Constitution#376]
Probably too radical for v5 yet …

Why not removing the dual  construct "role-circle" and just use the sole construct of "role", or move to another term like "holon"?

**Comment by bernardmariechiquet** [comment]
@benoitpointet I tried that one too 2 years ago in https://github.com/holacracyone/Holacracy-Constitution/issues/254 I would love only one word to point to one concept that is holon.
The "Role" is the outside view of the holon; a "Circle" is the inside view of the holon.
It seems, at least for now, that two words are still needed for many to get the concept. Many people not used to the meaning of this concept could get lost. 
Further, you still need something to refer to the appropriate level of holarchy.
And i appreciated @julianeroell argument https://github.com/holacracyone/Holacracy-Constitution/issues/254#issuecomment-411473132 
> For me, the two words are very much needed, if just for efficiency: From the position of a _Role_, I need to be able to reference my surrounding / higher system (currently: the "Circle"), and I need that reference to have a different name than that which I use for my peers (other "Roles").

How to replace the expression of these two positions/levels with another form of verbalization based on the word holon?

**Comment by benoitpointet** [comment]
Oh thx for the hints! I understand the challenges that such a change brings and don't have magic solutions.

**Comment by brianjrobertson** [comment]
Yep, agreed the arguments made against it in #254 still outweigh the benefits from my perspective.
