### ISSUE TITLE
circle members => governance members

### ISSUE THREAD

**Issue by benoitpointet** [holacracyone/Holacracy-Constitution#378]
The concept circle member is only present in article 5, now.

Why not clarifying its meaning and scope by renaming it to "governance members"?

**Comment by brianjrobertson** [comment]
Hmm, interesting; that does seem to fit a bit better.  The only reason I can think of not to do it is just the departure from old terminology could lead to a bit more transition pain, but that's probably not a good reason to not do it.  Anyone else have opinions about this?

**Comment by rebeccabrover** [comment]
As there are only two references to _Member_ (Appendix A and 3.3) outside of Article 5, perhaps it might just be cleaner about shortening it to just "Member" rather than trying to find another word to substitute. It would immediately make the next sentence cleaner by removing the two instances of Circle in a row. It would look like this:

Each Circle has a group of "Members" who may represent its Roles in its Governance Process.

A Circle's Members are those Partners filling its Circle Lead Role...

There are quite a few instances of _Circle's Circle Members_,  and _Circle Member of any Circle_ that would also be cleaner.

**Comment by chrcowan** [comment]
I find, "Circle member" to be intuitive and it's a term someone could reasonably predict would still be used regardless of what it's called in the constitution. I think I see what "Governance member" is going for, but it seems more like going for some sort of technical accuracy or trying to teach something through the term, which I think would actually get in the way. Just a quick reaction. Haven't thought through it that much.

**Comment by oliviercp** [comment]
I'm with Chris on this one. Circle member is automatically intuitive --> we have circles, so members of that circle are "circle members". It has never required any explanation in my experience. 

"Governance member" however, I would feel the need to explain it. "Governance" is broader than the circle; when the term is not qualified, typically it means the "governance of the organization". I imagine a new practitioner's question... "we are members of the governance? What does it mean?", "Oh, we're members of the governance **_of the circle_**, thank you." If anything, to be both clear and accurate, we should call it "Circle governance member", which is clunky...

As to just "Member", it sounds like it lacks a qualifier to be meaningful. In common parlance, we only use the term "member" alone when the context has been clearly identified. That being said, I do like the simplification of turns of phrases like "_Circle's Circle Members_" to "_Circle's Members_".

Maybe the word "Member" can be the defined terminology and it's used in context by clarifying "Circle Member"?

**Comment by rebeccabrover** [comment]
@ocompagne Yes! That is exactly what I meant. "Member" is the defined term and "Circle" is just a modifier as needed, which would remove the duplication.
Thank you for making it more concrete!

**Comment by benoitpointet** [comment]
Thx for those replies.
Why I came to the idea of "governance member": I was thinking that before adopting article 5, the term circle member would already be in use. Something I saw as unlucky. Yet, I had forgotten that the core/non-core mechanism is gone from v5 so every role lead becomes de facto circle member.
Got what I needed.
