### ISSUE TITLE
Change "Working Agreement" to "Relational Agreement"

### ISSUE THREAD

**Issue by rebeccabrover** [holacracyone/Holacracy-Constitution#380]
@brianjrobertson 

I think it makes sense to change "**Working Agreements**" to "**Relational Agreements**" to further clarify that the agreements are made in tandem, but outside of the working governance of the organization. Not only does it highlight that the agreements involve at least one person as a human (as they may be requested in service of a role), but they can detail how someone shows up in the relational space beyond their roles.

It looks to me like the current language works (pasted below for ease) and I think it's valuable to highlight the profundity of inclusion of human dynamics in the ruleset of the Constitution. The second sentence already defines the term using the word relate so this might make it even more simple as it's already there.

The change also works definitionally as _relational_ simply means the way in which two or more people or things are connected, which is exactly what the article describes.

***

6.2 Working Agreements
The Organization's Partners may make “Relational Agreements” with each other. These are agreements about how the Partners will relate together or fulfill their general functions as Partners. They must focus on shaping behaviors that generally underpin work. They may not set expectations of work to do in a Role, nor expectations about how a Partner will prioritize across different Roles. Further, they may only specify concrete acts to do or behavioral constraints to honor. They may not include promises to achieve specific outcomes or embody abstract qualities.

As a Partner, you may request a Relational Agreement of another Partner for your own personal preferences or to serve a Role you fill. That Partner may accept or reject the requested Relational Agreement based on their own personal preferences. Either party may later terminate the agreement without the consent of the other party, unless otherwise agreed.

As a Partner, you have a duty to align your behavior with any Relational Agreements you have made. Anyone facilitating a meeting or process may also enforce Relational Agreements during that meeting or process, as long as they don't conflict with anything defined in this Constitution.

**Comment by klaas1979** [comment]
This resonates with me. We adopted "working agreements" in v4.1 two years ago. but need to explain them a lot. With the switch to relational my guess is, that it is easier to understand and easier to convey the meaning.

**Comment by Aliocha-Iordanoff** [comment]
I support this proposal. "Relational Agreements" seems to me to be a better term to describe what is in this article.

The expression "Working Agreement" carries the ambiguity of meaning as to the possibility that this agreement concerns work and not the relationship between people.

**Comment by brianjrobertson** [comment]
I'm sold, let's do it.
