### ISSUE TITLE
Difficulties in Translating "1.4.1 Breaking Down Roles"

### ISSUE THREAD

**Issue by denniswittrock** [holacracyone/Holacracy-Constitution#381]
Hi Folks, 

I encountered difficulties in trying to translate "1.4.1 Breaking Down Roles". 

Therefore, I propose some changes that would make some things clearer in my view or at least this attempt will likely help me understand my misinterpretations regarding this passage, which still seems vague for me. 

"A role's inner Circle" is somewhat opaque for me. I picked up the term "internal" from the first sentence and applied it consistently throughout by calling it "the internal Circle of the Role". Additionally, I tried to highlight that "Role" or "Circle" and "Sub-Circle" or "Super-Circle" is a function of the perspective or view by indicating that perspective more than the original version. 

**CURRENT VERSION**
### 1.4.1 Breaking Down Roles
Every Role is also a Circle internally. A Role's inner Circle can hold Roles and Policies to break down and organize the work of that Role. This does not apply to the Roles defined in Appendix A, which may not be further broken down.

A Role's inner Circle is considered a “Sub-Circle” of the broader Circle that holds the Role, while that broader Circle is its “Super-Circle”.

**PROPOSED CHANGE**
### 1.4.1 Breaking Down Roles
_Viewed from its inside,_ every Role is also a Circle internally. This _internal_ Circle of a Role can hold _its own_ Roles and Policies to break down and organize the work of that Role. This does not apply to the Roles defined in Appendix A, which may not be further broken down.

The _internal_ Circle _of a Role_ is called _the_ “Sub-Circle” _from the perspective of that_ broader Circle which holds the Role. That broader Circle is called its “Super-Circle” from the perspective of the internal Circle of the Role.

-------
let me know what you think. 

One thing is sure: the original is confusing me terribly. At least the translation is very muddy and I am not sure the reason is my incapacity of translation. Rather, I suspect the source text could be clearer...

cheers, 
Dennis

**Comment by klaas1979** [comment]
I can just second that. We discussed this passage for 45 minutes and came up with 3 translations and in the end, we really asked ourselves what are core words thay may not be changed and what could be expressed in other ways. Quite curious about the interpretations here.

**Comment by bernardmariechiquet** [comment]
IMO English text is top. And it's true that translation into another language, at least for French, cannot be done in so few words. I envy English for its ability to be so simple.

**Comment by denniswittrock** [comment]
@bernardmariechiquet yes, I know exactly what you mean. :-) 

How do you deal with it in the French translation? Add some more words that make the intended meaning more digestible? 

Or do you stick as closely to the original words as possible trying to leave nothing out and avoiding adding anything not present in the original? 

Or both?

**Comment by bernardmariechiquet** [comment]
@denniswittrock I try both! The result is most of the time, more words in french  😉
My main focus is to stay focused on the deeper meaning for the sake of the practionner. Avoiding adding anything not present, and definitively trying to leave nothing out. And make it as digestible as possible.
I must confess I love that. This should not be called "translation" but "deep localization".

**Comment by brianjrobertson** [comment]
@denniswittrock I think everything you suggested in your version above is spot-on and true to the intended interpretation of that text... but I don't think it helps the English version (but it may in the German version of course, I don't know).  I could be wrong and welcome dissenting voices here, but it seems to me that, while your additions are technically correct, the added complexity makes the whole paragraph harder to follow and more potentially confusing.  Without that added complexity, the paragraph may have some extra potential ambiguity, but I think the intended interpretation is still the one someone would almost definitely arrive at - thus, the added complexity seems not worth it to me.  But again, I welcome pitches otherwise...

**Comment by rebeccabrover** [comment]
@brianjrobertson @denniswittrock 
I certainly understand the challenges with translations and have worked with translators in Spanish, Danish and Arabic to try and figure out how a phrase moves back and forth between languages. Sometimes it does take a few tries before landing on a translation, that when translated back, conveys the desired nuance.
That being said, I think the added complexity of your version makes it harder to understand in English, which is counter-productive. Internal Circle of a Role is very confusing in English. But I think it's close. I suggest the following:

**CURRENT VERSION**

### 1.4.1 Breaking Down Roles
Every Role is also a Circle internally. A Role's inner Circle can hold Roles and Policies to break down and organize the work of that Role. This does not apply to the Roles defined in Appendix A, which may not be further broken down.

A Role's inner Circle is considered a “Sub-Circle” of the broader Circle that holds the Role, while that broader Circle is its “Super-Circle”.

**PROPOSED CHANGE (DW)**

### 1.4.1 Breaking Down Roles
_Viewed from its inside_, every Role is also a Circle internally. This _internal_ Circle of a Role can hold _its own_ Roles and Policies to break down and organize the work of that Role. This does not apply to the Roles defined in Appendix A, which may not be further broken down.

The _internal_ Circle of a Role is called the “Sub-Circle” _from the perspective of that_ broader Circle which holds the Role. That broader Circle is called its “Super-Circle” from the perspective of the internal Circle of the Role.

**PROPOSED CHANGE (RB)**

### 1.4.1 Breaking Down Roles
_Viewed from inside_, every Role is also a Circle. This Circle can hold _its own_ Roles and Policies to break down and organize its work. This does not apply to the Roles defined in Appendix A, which may not be further broken down _into Circles_.

_A Circle contained within another Role is called the “Sub-Circle” _from the perspective of the_ broader Circle which holds the Circle. That broader Circle is called its “Super-Circle” from the perspective of the internal Circle._

If that doesn't work, if there are no better options, I think leaving it makes the most sense in English knowing the confusion in translation is temporary until a version is available in the native language (which might be up for translation interpretation at any time even if it's meant to be final).

**Comment by Pam-H** [comment]
I think I would leave it as it is.

**Comment by Pam-H** [comment]
...in the current version people listed above in this discussion of issue #381

**Comment by brianjrobertson** [comment]
Okay, I've made a few minor tweaks based on some of the suggestions in this thread; nothing huge, but I do think it's a bit clearer now.  Submission forthcoming.

**Comment by chrcowan** [comment]
I find Dennis's version easier to follow personally. I'll withhold further comment though until I see the new submission.

**Comment by oliviercp** [comment]
Personally, here are the versions I find easiest to read, from easiest to hardest:

- For the 1st paragraph: RB, Original, DW
- For the 2nd paragraph: Original, RB, DW
