### ISSUE TITLE
Integrate Article 6 (People & Partnership) content into other articles and remove as stand-alone article

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#385]
There was some discussion of where place Article 6 within Issue #358, and the question came up of whether it would actually be better to remove the article entirely as a stand-alone article, and integrate the content elsewhere.  This comment by @chrcowan was particularly compelling for me:

> As for 6.2, I think that fits well with Article 2: Duties to Each Other. It fits thematically, and seems like it's necessary to introduce that construct at the point in which the rules are describing explicit, but general, explications of each other. An argument against doing that is from the perspective of modularity, having all of that in play at that point could be a lot of complexity, but given that Article 2 is already leaning heavily on the differentiation of role & soul, i.e. driving the wedge between them, then it's necessarily creating ambiguity over how one can or should handle issues which peer-to-peer working agreements can solve.

I think I agree; the content in §6.2 does indeed seem to fit really well in the Duties to Others article.  In fact, I think §6.1 would fit in there nicely as well, at least if the article had a slightly broader framing/title, like "Working with Others" or "Working Together", which would then include sections on the Duties to Others, on Partner Relationships, and on Working Agreements.  (Note also that one small clause in §6.1 was recently pulled to the preamble, which I think makes this integration work a bit better than it would have before that change.)

Beyond that, the current organization, with Article 6 standing alone, seems more like an artifact of when this content was added rather than where it naturally integrates best (as others said in the other thread, it feels bolted on, just because it's new).  If we were creating this all from scratch today, I don't think I'd even think of putting this in a stand-alone article.

And finally, while I wouldn't use this as a primary driver of this decision, there's something I really like about having only 5 articles.  "Adopt Holacracy in 5 steps" just kinda makes some intuitive sense to me - it's enough steps to break up the journey nicely, but not so many as to be overwhelming just from the number.

Reactions?

**Comment by rebeccabrover** [comment]
@brianjrobertson I like this. I notice I'm feeling a little bit of the loss on the optics of featuring the additional of an article about the "human stuff" but I expect that will pass in about an hour.

Five steps is better than six for a lot of memory and marketing reasons. Unless you have a mutation or injury, I think there is something fundamentally comforting about a _handful of articles_. It's one thing I miss about the operational pathways now that projects and next-actions are together (although I think that still makes sense).

If you do add 6.2 up with Duties to Others, I think that would dovetail well with the suggestion I made to add 6.1 to the Preamble. Moving 6.2 up would introduce it sooner after in this case although keeping both 6.1 and 6.2 in Duties to Others might mitigate the issue I saw with the distance between the Preamble and 6. I'd have to see it changed but it makes intuitive sense.

**Comment by MichaelDeAngelo** [comment]
One argument to keep them separate is to apply the Agile principle of incrementalism by answering the question: what is the smallest increment of value that can be added. The whole point to the modular approach is to apply value incrementally. If people and partnerships is a different unit of value for the organization than duties to others then there is a case for it being separate.

**Comment by chrcowan** [comment]
@brianjrobertson I like Mike D's perspective above and I think it might actually make combining/integrating them more compelling. I'm not sure, but in terms of adding value incrementally, the differentiation of role and soul does add some discrete value, but in this case, it also happens to move things backwards; namely it necessarily creates ambiguity about how to address working agreement-style expectations which were previously conflating role/soul, yes, but were at least explicit.

**Comment by bernardmariechiquet** [comment]
@brianjrobertson I love the idea of merging article 6 into article 4. And to rename the new article 4 by including in the title something about cooperation. For example, rules of cooperation. This is how I naturally explain these rules when we train/coach.
It also allows also to make a link with/integrate more the human side that is often perceived as missing in the constitution. There would not only be roles, there would also be in the same article the relationships between people. This balance could greatly soften and facilitate adhesion.

**Comment by brianjrobertson** [comment]
If anyone wants to review the change above to verify I didn't break anything, I'd appreciate the help.  I'd also love to hear if the placement of former §6.1 into the Preamble makes sense to you, and/or if you have any better ideas for where/how to incorporate it.
