### ISSUE TITLE
Move Secretary definition and Conflicts of Interpretation section

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#387]
Currently, Secretary is defined within the Governance article, along with Facilitator, meaning it can only be used within that article.  That means the "Tactical Meetings" article can't refer to the Secretary, so it leaves it ambiguous who schedules them and captures outputs.  And it means that the section on "Conflicts of Interpretation" has to be in the Governance article, since it references Secretary, and not in the "Authority of Role Leads" article (formerly called "Power Shift"), which is where the related content lives that empowers each partner to interpret governance and act on their interpretation.

It strikes me that there's another possible organization here:  Secretary could be defined in Article 1, even though Facilitator is defined in the Governance article (and I think it should stay there regardless).  Secretary is (or could be) at least somewhat relevant even with just Article 1 adopted, because it's still useful to have someone in charge of record keeping and generally stewarding those records.  And if Secretary were defined in Article 1, then it could be referenced by any article; that means the Secretary could be accountable for scheduling Tactical Meetings and capturing outputs, even without the Governance article adopted.  And it means the "Conflicts of Interpretation" section could move to the "Authority of Role Leads" article, to rejoin the content already in there on empowering Role Leads to interpret the constitution (I think it generally fits better in this article too).

So, I'm looking for opinions:  Is it worth moving Secretary into Article 1 and the slight extra complexity that adds into Article 1, in order to get these benefits?

**Comment by SamirSaidani** [comment]
My proposal would be to amend "The Partner convening a Tactical Meeting must find someone to facilitate it." by "The Partner convening a Tactical Meeting must find someone to facilitate it and someone to schedule it and capture its outputs."

**Comment by rebeccabrover** [comment]
@brianjrobertson I'm pretty ambivalent about the change. I imagine that companies who have only adopted Article One would still rely on whoever currently schedules the meeting but I can also see the logic of @samir-s's suggestion to amend the language to include capturing outputs and scheduling.
I also think its fine to leave it where it is and keep whatever is in the legacy org, knowing it will tension the system with the grounded question of who schedules and captures.
One other thought is that if only Article One has been adopted, the org hasn't had elections yet.

**Comment by MichaelDeAngelo** [comment]
@brianjrobertson I can see the value of having the secretary in Article 1. The VP of article 1 is role clarity/governance so some role should be thinking about maintaining those records in some way. I also don't have a lot of concern the way it is and not load up too much in the first article.

**Comment by brianjrobertson** [comment]
Thanks all.  To be clear, the main driver for considering this is *not* the ambiguity around capturing tactical outputs.  It's the weird placement of the "Conflicts of Interpretation" section in the Governance article, instead of in the Authority of Role Leads / Power Shift article...

**Comment by bernardmariechiquet** [comment]
Yep @brianjrobertson I am with you on this one.

**Comment by SamirSaidani** [comment]
According to Article 3, nothing is said about the secretary. As a consequence, one could get rid of the secretary function for the Tactical Meeting, which sounds like a regression to me.

This amendment ease the Tactical Meeting process concerning the Facilitator Role, releasing the constraint to get the Facilitator Role attending the Tactical Meeting while keeping the facilitator function. But this amendment is also releasing the constraint to implement the secretary function during a Tactical Meeting.

I'm curious to understand which kind of concrete situation you've already experienced that leads you to release the secretary function constraint.
