### ISSUE TITLE
incoherence in "adding to the circle lead"

### ISSUE THREAD

**Issue by benoitpointet** [holacracyone/Holacracy-Constitution#389]
> A Circle may add Accountabilities or Domains to **its** Circle Lead Role, and those additions automatically apply to every Sub-Circle's Circle Lead Role as well, recursively. A Circle may not add Accountabilities or Domains just to **its own** Circle Lead Role.

How is an organization with a single circle supposed to interprete this? seems contradictory.

And how is a bigger org supposed to interprete it? Does that mean that if you add to the Circle Lead Role, you should do it for the whole org or parts of it but not "leaf" circles?

**Comment by brianjrobertson** [comment]
I'm not sure I understand the concern; can you elaborate?  An org with a single circle could at any moment become an org with many, given that any role can simply break itself down at any time; so it seems just as relevant in a single-circle org to me - you need to know that anything you add would also automatically apply in any sub-role that chooses to break itself down into a circle.  As to a bigger org case, I don't understand the question you're asking or the potential concern you're raising?

**Comment by benoitpointet** [comment]
I understand that what is meant with 

> A Circle may not add Accountabilities or Domains just to its own Circle Lead Role.

is that 

> A Circle may add Accountabilities or Domains to its Circle Lead Role, and those additions automatically apply to every Sub-Circle's Circle Lead Role as well, recursively. 

suffers no exception.

I believe that the phrasing is unfortunate: a Circle which has no Sub-Circle and which amends its Circle Lead Role is effectively and by accident _"adding … just to its own Circle Lead Role"_.

**Comment by brianjrobertson** [comment]
I added a clause that should resolve this; let me know if you disagree or have better ideas.
