### ISSUE TITLE
Accountability on many roles / sub-circles

### ISSUE THREAD

**Issue by benoitpointet** [holacracyone/Holacracy-Constitution#392]
Something the current v5 does not allow to do: to create an accountability on  many roles in a circle **in a single sentence**. Currently, like in v4, one has to add the accountability on every impacted role.

For a circle that works as a federation of sub-circles, one might want to represent accountabilities upon those sub-circles in a central and uniform manner.

Could that be something that a policy could do?

**Comment by brianjrobertson** [comment]
No, I definitely wouldn't allow a policy to be used for that - too many potential misuses and confusions from that.  In fact, even allowing this has I believe more potential for harm than good; I see circles wanting to do this all the time, but often it's an antipattern (a common solution with negative impacts), such as avoiding creating a new role to hold the "common" accountability, or to dodge the real need for an actual policy or a relational agreement.  So, I'm not sure why we'd want to allow this explicitly; if someone desires the same accountability on many roles they can certainly propose that, but I'm not sure we want to make that easier on them given the high potential for misuse...

**Comment by benoitpointet** [comment]
Think of an organization made of more than 10 rather independent business units.
There's the need to express common expectations upon all business units.
And a new role to hold the common accountability is not the solution. Nor is a relational agreement.
Until now, I've seen policies (mis-)used for that, since constraining is the twin of expecting.

I still wish for a clearer mechanism.

**Comment by brianjrobertson** [comment]
I think forcing the duplicate accountability is better than allowing a policy to do this, although I agree that's a bit cumbersome.  If you/anyone has any ideas, I'd love to hear them.

**Comment by klaas1979** [comment]
We use this (anti-)pattern in v4.1: Have a policy that states that all [qualifier]-Circles must have  [Role] or a [Accountability/ies] in their circle if [regulated thing/area].
I.e. If you spend money, you need to have a role "Cost-Manager" with the definition "xyz" and for filling in Partners the role-fillers must before be approved by the Role @[Link to main CostManager].
=> for a legacy Cost management System.

But this is a rare case, most of the times we just have the policy that restricts the way money is spent (or something else) and let the sub-cirlces handle this restrictions as the see fit. Normally the need roles or accountabilities for this, but they need to self-define, what the circle needs.

**Comment by benoitpointet** [comment]
Oh, thx! I've met that pattern a few times, at Liip and elsewhere.

And for every case I came to the conclusion that although it was a very borderline interpretation of the rules of the Constitution, the tension behind and the simplicity of the solution made somehow sense.

**Comment by brianjrobertson** [comment]
I'm not sure how to more easily enable this without causing more problems than we solve, so I'm going to close this issue; but if anyone has ideas, please do comment and I'll re-open.
