### ISSUE TITLE
REP role authority fine tuning

### ISSUE THREAD

**Issue by jeanlucchristin** [holacracyone/Holacracy-Constitution#395]
Reading this sentence, people might imagine that the REP role has the same authority as the lead role : 

4.1.1
...
The selected Circle Rep becomes a Circle Member of any Circle containing that Circle, with the authority to represent their Circle just like a Circle Lead.

Proposal : 
The selected Circle Rep becomes a Circle Member of any Circle containing that Circle, just like a Circle Lead, with the authority to represent their Circle.

**Comment by brianjrobertson** [comment]
@jeanlucchristin The intent is to say that the Circle Rep can "represent their circle" just like a Circle Lead (i.e. speak for it in Governance; make proposals and raise objections).  So the change you're suggesting is removing the intended meaning here.  Can you say more about what interpretation you're concerned about and trying to prevent?

**Comment by jeanlucchristin** [comment]
Well, 

I think the point is the difference between authority and accountability.

These two roles have the same authorities in the supercircle, not the same accountabilities.

here we speak of "**authority to represent**"; maybe this verb should be changed.

The circle lead doesn't have to represent the circle. Correct ? 
(he doesn't have to resolve tensions relevant to the super circle, this is the REP role purpose) in my understanding

**Comment by brianjrobertson** [comment]
I would say that both Circle Lead and Circle Rep can "represent" the Sub-Circle, in that they are both effectively filling that role and can raise proposals and objections on its behalf.  That's not to say that the Circle Lead has a duty to try to resolve tensions sensed by others within the Sub-Circle - that's not what "represent" is intended to refer to one way or the other in that usage.

So, I'm still not sure there's an issue with the current language, although I do see how it could be confusing and I'm open to suggested changes if you have any.

**Comment by jeanlucchristin** [comment]
thank you,
This issue turns into something much more interesting for me. It was not obvious in this version that the circle lead can represent the subcircle exactly like the circle-REP.

In France, people often explain that one would have to be schizophrenic to hold both roles. I don't agree with that because I often see people in real life playing both roles correctly.
But I believed that this position was that of holacracy.

Perhaps this action for the circle lead to represent his subcircle should appear clearly, in article 1.5 for example, after 1.5.1
or in appendix

**Comment by bernardmariechiquet** [comment]
The Circle Lead has no duty to try to resolve tensions sensed by others within the Sub-Circle, but he can do it if he senses those tensions. As stated in article 1.3.1, when filling a Role, you're responsible for trying to resolve those Tensions you sense. Nothing can prevent Circle Lead from doing it if he wants to do it.
This may often happen especially when the elected Circle Rep is not active/ or not at the right level of competence for trying to resolve tensions. This happens a lot in my experience. It's often quite difficult for a Circle to get the opportunity to rely on a good Circle Rep. That's why, as far as I'm concerned, I appreciate the flexibility brought with version 5, which closely follows what reality teaches us.
And at the same time, what a pleasure it is as a Circle Lead when the Circle Rep is on hand to try to resolve tensions sensed by others within the Sub-Circle.

**Comment by jeanlucchristin** [comment]
thanks i like that.

I wonder what the limit is according to holacracy. It is not obvious.

If I understood the answer correctly @bernardmariechiquet, the circle lead can act directly if the elected Circle Rep is not active / or not at the right level of competence.

What if the elected facilitator is not at the rigjt level of compence for example?
The circle lead can't act directly, correct?

**Comment by bernardmariechiquet** [comment]
> If I understood the answer correctly @bernardmariechiquet, the circle lead can act directly if the elected Circle Rep is not active / or not at the right level of competence.

This is not exactly what I said. I just said that the Circle Lead has no duty to try to resolve tensions sensed by others within the Sub-Circle, but he can do it if he senses those tensions.

**Comment by bernardmariechiquet** [comment]
> What if the elected facilitator is not at the rigjt level of compence for example?
> The circle lead can't act directly, correct?

Aks for a new election. In v5, the Circle Lead may be elected as Facilitator. See article 5.1.2  https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#512-facilitator-and-secretary

**Comment by bernardmariechiquet** [comment]
> I wonder what the limit is according to holacracy. It is not obvious.

There is no limit other than your interpretation of the constitution - see https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#22-interpretation-authority

**Comment by brianjrobertson** [comment]
@jeanlucchristin I have nothing to add beyond what @bernardmariechiquet already shared; he captured my perspective exactly.
