### ISSUE TITLE
Cut definition of & rules around "Partner Relationship"

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#396]
As part of removing the old Article 6 and integrating that content elsewhere, I moved the paragraph about Partner Relationships into the preamble.  This adds some complexity to the preamble that I really don't like, and has the potential to create needless alarm for people considering adopting this, given the potential intersection of that part with their local employment law, and their own employment structures/practices.  This is the paragraph I'm referring to:

> When the Organization grants Partner status to someone, it creates a **“Partner Relationship”** between that person and the Organization. Any promises either party makes to the other in conjunction with the grant of Partner status are part of that Partner Relationship. Unless otherwise agreed, each party needs the other’s consent to change these agreements. However, either party may still end the Partner Relationship without the consent of the other. Doing so immediately ends that person’s rights and responsibilities as a Partner.

So, what would be lost if we just cut that paragraph from the Constitution entirely?  Is it important that we keep this in (and if so, why), vs. leave it for either a standard app or just to each org to define in governance for itself?  “Partner Relationship” as a defined term is not used anywhere outside of that paragraph, so nothing else builds on this; it’s just a matter of how important it is to have some basic default specification like this for how adding/removing partners works, vs. leaving that to governance to define.

If we do cut that paragraph, is it useful to at least add some basic clarification to the paragraph before, the one that defines Partners, that says that the ratifiers or the organization itself can further define how the organization grants or removes partner status, just to make it clear that this is an area that needs to be further clarified in governance (so people aren't left trying to interpret how that works or infer some universal standard that Holacracy intends for how make someone a partner)?

Thoughts?

**Comment by Aliocha-Iordanoff** [comment]
I agree, this paragraph could be deleted from the constitution. And it could be helpful to keep a sentence anyway to specify that the ratifiers or the organization can further define how the organization grants or removes partner status, using the governance process.

**Comment by bernardmariechiquet** [comment]
> > When the Organization grants Partner status to someone, it creates a **“Partner Relationship”** between that person and the Organization. Any promises either party makes to the other in conjunction with the grant of Partner status are part of that Partner Relationship. Unless otherwise agreed, each party needs the other’s consent to change these agreements. However, either party may still end the Partner Relationship without the consent of the other. Doing so immediately ends that person’s rights and responsibilities as a Partner.
> 

Please do cut that paragraph, if not this is going to complicate things in any case with French labor laws.
And yes, you may add some basic clarification that says that the ratifiers or the organization itself can further define how the organization grants or removes partner status.
We, iGi institute have developed apps for such things with many companies practicing Holacracy, as they are more than needed.

**Comment by brianjrobertson** [comment]
Okay, I've cut that paragraph, but added a bit of clarity to the one before to make it more obvious that the Organization can define how to grant or remove Partner status.  If anyone wants to take a look at the text changes and offer feedback, I'd appreciate it.
