### ISSUE TITLE
Secretary accountability for making governance records available/accessible

### ISSUE THREAD

**Issue by stephaniedwelch** [holacracyone/Holacracy-Constitution#399]
The change resolving #387 removed "and publishing" from a Secretary accountability in Appendix A, which now reads `Capturing outputs for the Circle within meetings defined in the Constitution`.

After the removal of "and publishing," I can't find any other explicit rule or accountability that governance records be made readily available/accessible to other Partners, except to the extent specified by 4.1(g), to `share any other information that's readily available to you and won't cause harm to share`, but this only applies upon request.

This feels like an unintentional consequence of the removal; it would be unconstitutional for the expectation to be implicit on the Secretary, and it would be odd to wait for a tension on a case-by-case basis, since so many things clearly depend on Partners' ability to reference the current state of governance records.

If it needs to be distinct from the line about capturing outputs, then perhaps a separate Secretary accountability such as:
`Storing the Organization's governance records in a manner readily accessible to all Partners`

**Comment by brianjrobertson** [comment]
Nice catch, thanks!
