### ISSUE TITLE
Permission to substitute the term "Partner"

### ISSUE THREAD

**Issue by djwork** [holacracyone/Holacracy-Constitution#4]
I would like to have a clause in the constitution that permits individual practicing organisations to substitute the terminology partner (with for example associate, staff member, etc) if in their legal jurisdiction the term partner has unintended legal ramifications.

Edit: Clarification
I am not suggesting removing the term Partner, I am suggesting a clause to the effect:
_Should the term **"Partner"** cause tensions due to the legal implications of said term within jurisdictions relevant to the **"Organisation"** and alternative term may be substituted (e.g. Member, Associate, Officer, Employee, etc)_

Picking a single term Partner or otherwise will probably break even before we start trying to internationalise the constitution.

On a lighter note maybe we should use the term **"Decihuman"** in honour of the [Lord of Lamas](https://twitter.com/hsiehmyname)

**Comment by julianeroell** [comment]
I support this. 

I'd even consider going one step further and drop the terminology of "partner" in favor of the more neutral "member". 

I have found that people new to Holacracy get very confused over the word "partner": they think that Holacracy is only for "partnerships of equals" (like a consulting partnership), or that employees would automatically become owners, or that the shareholder agreements must change or... :dizzy_face:

**Comment by mileslasater** [comment]
Martin, I had have seen the same confusion with "Partner".  "Member" can have a legal meaning as well in US context for nonprofits or LLCs.  "Team Member" has less legal meaning, as does Associate, Staff Member.  The term "associate" or "staff member" might imply less agency to some.

I imagine that this has been considered and debated quite a bit.  Does anyone want to share why "Partner" was chosen and the options already considered?

**Comment by julianeroell** [comment]
I see djwork's edit to his comment above now. Hm. For us, "partner" causes a lot of confusion and extra work. Changing it to "member" (or maybe a different word) would help with that. 

On the original meaning of this issue (which I now understand as wanting to add a clause to the constitution that allows the organisation to... hm, do something related to wording. Hm, no, I don't really get down to the meaning.), I have no opinion.

**Comment by brianjrobertson** [comment]
Hmm, I do see the issue, though I think any word chosen is going to cause trouble, just different trouble, and "Partner" seemed the least offensive word overall of the many options we explored (though definitely agreed it's not perfect and causes confusion... but other words have equal/greater problems I think).  We could add a clause allowing a rename, though I see a few issues with that: (1) it's awfully specific; maybe better to just allow any term to be renamed, or none and let people fork the constitution if they want that; (2) if they rename it, they're going to trigger even more confusion when all of our other tools/resources keep calling it Partner (e.g. GlassFrog, Constitution Desk Reference, wall posters coming soon, etc.); and (3) there's a reason we didn't use most other words, and someone could unknowingly be setting themselves up for bigger problems by changing it...

So, I do recognize the issue, but I'm not sure what to do without causing yet more issues...

**Comment by djwork** [comment]
And if we use a completely new term (ie decihuman, fake tony hsieh cracks me up) to avoid conflict it will add to the whole Holacracy is a cult BS

**Comment by djwork** [comment]
How about option 1 with disclaimers?

**Comment by julianeroell** [comment]
[Structure & Process's partnership system](https://glassfrog.holacracy.org/policies/2104) has some "disclaimer"-like words:

At the top:

> _NB: In this document, the words "partner" and "partnership" are used in the sense of Holacracy: "partner" means "member of the organisation". 
> "Partnership" can take different forms: an associated freelancer can be a partner, as can be an intern, a co-owner or an employee._

and further down:

> ## Legal Status of Partners
> 
> "Partners" as defined by this policy are not legally partners or owners of the organisation, but only "partners" in the sense of Holacracy. 
> 
> Being granted partner status does not constitute ownership in the organisation or grant a right to a profit share or any other financial compensation.
> The exact relationship of a partner to the organisation may be governed by an individual partnership contract.

**Comment by MiekeByerley** [comment]
I have a similar issue, where the industry I work with is very averse to the term partner. I didn't realise this at first but for them it has a bucket load of negative connotations and the moment you utter that particular word It throws up defences. In my own documentation I now use the term Colleague, as it retains all the qualities of Partner but seems to provide an extra degree of Autonomy. It also has no Legal allegiance and is understood and used in every industry from corporate, medical, legal and even trade. Thus far it is the only term I have been able to identify that fulfils the needs.

**Comment by brianjrobertson** [comment]
Hmm, I get what you're saying about Colleague - it definitely meets the goal of being neutral - but the perspective seems wrong; it's a relationship between a person and another person (a colleague), as opposed to a construct describing the relationship between a person and the organization (e.g. Partner, Employee, etc.)...

**Comment by MiekeByerley** [comment]
I do get what you mean by that, as much as the organisation is not a person maybe this is not necessarily a negative as it does add the benefit of making it Human and provides a sense of connection. An alternative could be an Associate (which I did consider) but I personally find the degree of separation to Distant (kind of clinical).

**Comment by brianjrobertson** [comment]
Closing this issue for lack of any new/better ideas (though please do re-open if you have one!)...

**Comment by julianeroell** [comment]
Brian, what was the original reason for choosing "partner" instead of "member"? (Or, asking differently: what are good reasons against "member"?)
