### ISSUE TITLE
Secretary accountabilities for scheduling meetings and requesting elections

### ISSUE THREAD

**Issue by stephaniedwelch** [holacracyone/Holacracy-Constitution#400]
1. In relocating the Secretary function, https://github.com/holacracyone/Holacracy-Constitution/commit/c883219e5d5c342457d81ce83e6fe87bf3b61e10 also undid https://github.com/holacracyone/Holacracy-Constitution/commit/91a762eb0c1f99e8e15339ab178bc57c9a432aba, in which the Secretary accountability was previously reduced from scheduling meetings `for the Circle and its Roles` to just those `for the Circle`.

In #319, Brian's comment supporting the change was "anyone else who wants a Tactical Meeting can just schedule one for themselves."

#387 did point out that, without Secretary defined in Article 1, "the 'Tactical Meetings' article can't refer to the Secretary, so it leaves it ambiguous who schedules them and captures outputs" (although this was not the primary issue). 

But, nothing was added to Article 3 to do so; instead, `and its Roles` returned. This seems less effective than either:
- Dropping `and its Roles` from the accountability and updating 3.2 to say, "The Partner convening a Tactical Meeting must find someone to act as its Secretary and someone to facilitate it," covering the need to capture outputs via Secretary while leaving it up to the convener as to how to accomplish the scheduling of non-Circle meetings; or:
- Keeping `and its Roles` -- or possibly switching to `or its Roles` -- and using @matthewgilliland's #319 suggestion to "mak[e] the meeting convener the default Secretary for non-Circle meetings," since this now works with Article 3, such as updating 3.2 to: "The Partner convening a Tactical Meeting becomes its acting Secretary and must find someone to facilitate it."

---

2. Additionally, https://github.com/holacracyone/Holacracy-Constitution/commit/c883219e5d5c342457d81ce83e6fe87bf3b61e10 deleted the accountability for `Requesting elections for elected Roles after each term expires`. This looks like it may also be an accident as it didn't appear to replace this function anywhere and I can't find any discussions that address eliminating it.

**Comment by stephaniedwelch** [comment]
Further thoughts on ramifications of the two suggested options to resolve the scheduling accountability:

---

1. Dropping `and its Roles` + 3.2 "The Partner convening a Tactical Meeting must find someone to act as its Secretary and someone to facilitate it."
- If this is a non-Circle meeting, the person wanting to convene the meeting must take specific action to appoint a Secretary for capturing outputs (which they already had to do with someone to facilitate).
- This person may or may not be someone who is normally a Circle Secretary, or it may be the convener if they choose themselves.
- Since no one else is explicitly responsible for scheduling, the convener must figure this out (not difficult to grasp).
- If this is a regular Circle meeting, the convening Partner is the Secretary themselves, so it is easy to make these assignments.

---

2. Keeping `and its Roles` or `or its Roles` + 3.2 "The Partner convening a Tactical Meeting becomes its acting Secretary and must find someone to facilitate it."
- The person wanting to convene the meeting has the default responsibility for BOTH scheduling it and capturing the outputs.
- If this is a regular Circle meeting, the assignments are obvious, as above.
- **Downside:** They may not yet have access to Article 5 for finding a surrogate Secretary, if they do not wish to capture outputs themselves.
- **Downside:** `and its Roles` would be an odd construction to apply to someone who is not also a regular Circle Secretary and potentially implicates them in scheduling more meetings than they are meant to be responsible for.
- **Downside:** `or its Roles` potentially implicates regular Circle Secretaries in scheduling meetings they are not involved in.

---

This leads me towards Option 1, in this case, back to the original solution from #319.

**Comment by SamirSaidani** [comment]
Another solution, as I've already pointed out in #387 is to not refer to a Secretary Role at all, symmetrically to "someone to facilitate it", you might have "someone to schedule and capture its outputs". It applies both for non-circle & circle tactical meeting. Telling nothing about the "memory" function (aka Secretary Role) as Article 3 is now stated brings fuzziness and is a regression in my opinion.

**Comment by brianjrobertson** [comment]
Thanks @stephaniedwelch and @samir-s, nice catches here.  I'm implementing option 1, but with Samir's suggested tweak.

**Comment by stephaniedwelch** [comment]
This might have gotten buried above: c883219 also deleted the accountability for `Requesting elections for elected Roles after each term expires`. It looks like it may also be an accident as it didn't appear to replace this function anywhere and I can't find any discussions that address eliminating it.

**Comment by SamirSaidani** [comment]
Maybe the idea was to let tensions processing elections instead using accountability : anyone could request elections, including the elected one. If not, until a new election, maintain status quo. Holacracy style. Makes sense for me.

**Comment by stephaniedwelch** [comment]
@samir-s It's possible it was intentional, but the same commit also had other errors, so it gives extra reason to question.

Certainly anyone *can* request the elections, as always. But, the fact that 5.3.5(a) specifies that the Facilitator **chooses a term** for elections suggests that _someone_ ought to be responsible for doing _something_ when that term limit comes to an end (otherwise, what's the point?). It would seem odd for the Constitution to provoke that question (of who should do what about it) and then not answer it.

An alternative to restore consistency would be to remove the concept of term limits and allow the need for _that_ to be tension-driven, but I don't see any discussion suggesting that, either (and it would seem to decrease value in how elections support the power shift).

**Comment by brianjrobertson** [comment]
Thanks @stephaniedwelch, another nice catch here; it was indeed an intentional removal for the reason @samir-s suggests, but poorly documented (i.e. not at all).  Though reading your last comment above, I think you're right - something is definitely missing now.  I'm going to add the accountability back on to the Facilitator role instead of Secretary - I think it fits better there now for many reasons, and aligns with the role I see actually caring more in practice anyway.

**Comment by Aliocha-Iordanoff** [comment]
Does this change, according to your interpretation, mean that this accountability also applies to the Cercle Rep? If so, this means that once a Circle has designated a Circle Rep, it will always have one, whereas when it is created, I understand that this role is not compulsory. @brianjrobertson

**Comment by brianjrobertson** [comment]
Yes, Circle Rep is an elected role so this would apply just the same.  But no, I don't think that means the circle will always have a Circle Rep, any more than it always must have a Secretary or Facilitator.  If one of those roles is vacated intentionally before a term expires, the accountability language doesn't apply and the Facilitator can ignore the vacancy.  And even if a term naturally expires, this accountability doesn't mean the Facilitator has to trigger a new election - accountabilities are never demands to do a specific action, just a requirement to consciously consider what next-action makes sense towards that general activity; in some certain contexts, what might make sense is "no action" or some other action besides calling for a new election.
