### ISSUE TITLE
4.4 Relational Agreements to handle "terms of employment"

### ISSUE THREAD

**Issue by lsmith77** [holacracyone/Holacracy-Constitution#402]
We are currently expanding our terms of employment to handle ISO 9001/27001 related processes. This is all driven through holacracy roles (ie. the implementation is an accountability of a role, different aspects of the implementation are handled via accountabilities of roles). However since these processes apply to employees (f.e. clear desk policy) and not to a role, many parts of the implementation do not fit into holacracy v4.1.

We are now wondering if they would fit into holacracy v5 section 4.4. However, the ability for any partner to terminate the agreement does not fit the aim here. We would love to use holacracy to help shape and evolve the ISO related processes but it is also not feasible for certification to allow individual employees to terminate the agreement unilaterally.

Would it make sense to make this use case more explicit?

**Comment by brianjrobertson** [comment]
@lsmith77 This should already be nicely covered.  Within that section, the sentence that allows unilateral termination says:

> Either party may later terminate the Relational Agreement without the consent of the other party, **_unless otherwise agreed_**

Note the part at the end there; all you need to do is include in the agreement that it can't be unilaterally terminated.  You might also consider adding a policy that says no one may hire someone unless the candidate has agreed to the relevant agreement(s).
