### ISSUE TITLE
The Constitution vs. this Constitution

### ISSUE THREAD

**Issue by stephaniedwelch** [holacracyone/Holacracy-Constitution#403]
a732774 changes an instance of `the Constitution` to `this Constitution`. The update implies a possible value in having the Constitution be more explicitly self-referential by using `this`.

Upon counting, there are only 6 instances of `the Constitution` and 20 instances of `this Constitution`, further suggesting a strong preference toward `this`.

Does that suggest any benefit to updating any or all of the remaining 6 instances to `this`? At least 4 of the 6 look like good candidates to me:

**5.2.1:** `A Policy that changes a default rule or process in the Constitution applies only within the Circle that holds the Policy...`

**5.3.3:** `When an Objection is claimed because adopting a Proposal would violate the Constitution, the Facilitator may ask the Circle’s Secretary to interpret if that's true.`

**Facilitator purpose:** `Circle governance and operational practices aligned with the Constitution.`

**Secretary accountability:** `Interpreting the Constitution and anything under its authority upon request`

---

This one I'm on the fence about:

**Facilitator accountability:** `Coaching other Circle Members on the Constitution's rules and processes, either on request or when needed for effective meetings`

It makes sense and could be fine with `this`; there is even a precedent of `this Constitution's` possessive form in the preamble (`as soon as this Constitution's processes create something that replaces or contradicts them.`). But something about it just doesn't feel as smooth to me.

---

And this one I would suggest removing instead of changing:

**5.4.3:** `A Policy of the Circle may add to this process, but may not conflict with any rules or requirements defined in this Article of the Constitution.`

 `This` is already applied to `Article`, so further specifying `this Constitution` would be unnecessary and excessive. In fact, there are 3 other instances of `this Article` (4.3a, 4.4, & 5.4.5f), and they all stand alone, so it would seem `of the Constitution` could actually be dropped when indicating a specific article.

**Comment by brianjrobertson** [comment]
I agree that consistency to the extent practical is good here, and agree with your last point above re dropping that reference to Constitution entirely.  The part that I'm concerned about is changing the references in the Facilitator and Secretary Purpose and Accountabilities; it reads more awkward to me in that context to change to "this Constitution", and worse, those definitions appear verbatim in other places, such as in GlassFrog, where "this Constitution" would seem very strange, while "the Constitution" would be much more intuitive.  So I'm going to leave those as-is, but change the rest.

**Comment by stephaniedwelch** [comment]
Makes sense! With the Facilitator and Secretary accountabilities showing up verbatim in Glassfrog, it's no longer self-referential to the Constitution in that context.

The actual change in a732774 that prompted my opening the issue was in fact one of those: the Secretary's accountability for `Scheduling meetings defined in this Constitution for the Circle on a regular basis`. So, in that case, this one would need to be reverted.
