### ISSUE TITLE
Remove "Surrogate for Absent Members" rule from Tactical Meetings

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#405]
I’m looking for ways to simplify the Constitution, and specifically reviewing rules where I can't recall ever seeing a case where it was really needed - especially rules that grant some special-case power to Circle Leads.  To that end, I'm wondering if it’s safe to remove the Surrogate for Absent Members rule (§3.3 in the current dev version), which says a Circle Lead can represent someone’s role in a Tactical Meeting if the normal role-filler isn’t there.  Without that rule, any projects or actions requested of the missing role-filler could still be requested (and even captured the same in GlassFrog) and would just stay as requests instead of accepted projects/actions, which seems harmless.  Perhaps more impactful is that those present couldn’t look to the Circle Lead to make a decision in the role with the absent member, but I can’t think of a case where that really seemed to matter.  I'd love to hear from experienced coaches:  Can anyone think of a real case or at least a theoretical reason why this rule should stick around, or does it seem safe to cut it?

**Comment by brianjrobertson** [comment]
Also relevant:  Anyone (including Circle Lead) can still take Individual Initiative to fill a Role temporarily in a Tactical Meeting and make a decision in the role or accept an action/project for the role.  On top of that, a Circle Lead could even temporarily assign themselves into the role to do so for the duration of the meeting without taking Individual Initiative.  So, we're clearly not losing any important functionality in dropping this; we're losing an easy way for the CL to do it the feels super light-weight, which I actually think is a good loss...

**Comment by stephaniedwelch** [comment]
Not having experience with the scenario, I'm just playing it out as a thought experiment.

In the current version, it's more like coaching/guidance than a rule: it is already technically possible as you mentioned, and it also doesn't limit it to only the CL.

Without that section, the workaround version of CL or Individual Initiative temporarily assigning someone to a role to gain rights to speak for it and accept actions/projects for it is more of a ninja move -- among seasoned practitioners who aren't worried about breaking things or stepping on one another's toes, it could probably be used safely.

Among less seasoned folks, it might feel a little like cheating for someone to be able to claim previously unheld authority that way, and might potentially have a detrimental affect on the group's perception of the system, or of the person doing it. But, what are the chances of them coming up with the idea under those circumstances? They may just be at a loss as to how to include the absent role.

Providing a solution seems like it could possibly resolve confusion in a situation where they don't know what to do, and it could protect newer users from a disruptive-seeming solution that could add to their reservations about the process.

There is another section about surrogates, in 5.3.6, which gives many more options than CL, with first precedence going to someone specified by the absent role. Would it be valuable to create a cross-applicable surrogate policy for absent members that goes beyond Facilitator/Secretary in Governance Meetings?

**Comment by stephaniedwelch** [comment]
Perhaps if moved to Article 1 instead:

`1.6 Surrogates for Absent Role Leads`
`A surrogate may represent a Role when the normal Role Lead is unavailable when needed, or requests a surrogate for any reason.`
`Whenever a surrogate is needed, the surrogate is, in this order of precedence:`
`...`

This makes it applicable everywhere, with the only tricky element being item (b) that specifies Facilitator and Secretary when Facilitator has not been identified yet. But perhaps that could be addressed in Article 5 as the only special case.

**Comment by klaas1979** [comment]
In my opinion it is save to cut it. I did mention it more than once in different implentation, but as you said it has potential to defer the power shift and adds an accountability to the lead link that has a better mechanism, like Brian stated it in the second comment.

**Comment by bernardmariechiquet** [comment]
I'm with you here @brianjrobertson Safe enough to try. No use case on my side.
