### ISSUE TITLE
Secretary accountability: "on a regular basis"

### ISSUE THREAD

**Issue by denniswittrock** [holacracyone/Holacracy-Constitution#406]
CURRENT VERSION
the Secretary's accountability for 

_- Scheduling meetings defined in this Constitution for the Circle on a regular basis._ 

NEW: 

_- Scheduling meetings defined in **the** Constitution for the Circle._ 

1) I replaced "this" with "the" 

2) I erased "on a regular basis". It is confusing since **all** accountabilities are activities that are expected  "on a regular basis". Writing it out has the counter-effect of implying that _not_ writing it out means that we cannot expect it on a regular basis, if it is not written out. We would have to add "on a regular basis" to ALL accountabilities accordingly (which is highly redundant, given the definition of accountability).

Or am I missing something important here? Is it because some Secretaries only schedule meetings on demand but don't schedule them "on a regular basis"?

Still, the problem with spelling it out in _one_ accountability only (and not the others) and the unintended consequences of that would remain, IMO.

**Comment by brianjrobertson** [comment]
Nice catch, though I think this is no longer relevant given the change I just submitted for #404.
