### ISSUE TITLE
Remove Facilitator accountability for coaching others

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#407]
While working on #404, I noticed there was no clearly natural place to add the Facilitator accountability for "Coaching other Circle Members on the Constitution's rules and processes, either on request or when needed for effective meetings".  On reflecting further, I now suspect this is actually not needed at all; it clearly serves the purpose of the role to do that coaching in any useful case of it I can think of, and I don't see any added value by making it an explicit accountability beyond whatever the Facilitator thinks makes sense for their role's purpose.  So I'm going to cut this accountability, unless someone gives me a good reason not to.

**Comment by Aliocha-Iordanoff** [comment]
I understand that removing accountability does not prevent the role from doing so. 

Nevertheless, I think it's a shame to lose that because I see in companies that adopt Holacracy that it really helps to become aware of the strategic place that the facilitator can play. It helps to grasp the possibility of moving towards a coaching posture rather than just facilitating a process.

**Comment by brianjrobertson** [comment]
Yes, I have seen how it can help with that, and I do think that's important; and, I don't want to complicate the constitutional rules just to serve a training/coaching function, but rather rely on other tools and methods to serve the training/coaching need (like HolacracyOne's new online learning/onboarding courses, which I think also help people grasp that, and probably a lot better than that accountability ever did).

**Comment by Aliocha-Iordanoff** [comment]
I understand this intention. Indeed, the constitution is not a training medium. 

The question I was asking myself is: is this role expected to do so (to coach circle members). If so, making it explicit in an accountability makes sense :)

But I understand that it is the same intention that made you lighten the descriptions of the other constitutional roles. Ok, I follow!

**Comment by bernardmariechiquet** [comment]
I don't think such accountability is needed. In fact, I sense this would be counterproductive, and putting the bar too high. A new facilitator would not be able to embrace it, an experienced facilitator does not need it in order to coach. Training is the key success here.

**Comment by julianeroell** [comment]
At Structure & Process, we had an explicit Role of "Holacracy Coach" and some policies for how the Role was permitted to intervene in Tactical and Governance meetings.

We found it helpful to have the Coach be at least a different _Role_ from the Facilitator, and ideally a different person: this allows the Facilitator to really be a neutral guardian of the Holacracy process. Having the Facilitator also teach/coach during meetings can create strange power dynamics.
