### ISSUE TITLE
Linked rôles are invited by a Policy

### ISSUE THREAD

**Issue by Aliocha-Iordanoff** [holacracyone/Holacracy-Constitution#410]
1.4.4 >>
_A Role may link into another Circle if a Policy of that other Circle or any Super-Circle thereof invites it._

Does this mean the Leader of the invited role may refuse ? 

"invite" might let it understandable that way

**Comment by brianjrobertson** [comment]
Yes, that's the intent; another circle can't force any random role to be subject to its governance process - it can only invite the role in.
