### ISSUE TITLE
Potential loophole when role has only name and domain

### ISSUE THREAD

**Issue by benoitpointet** [holacracyone/Holacracy-Constitution#415]
While 1.1 retains the formula "A Role definition consists of a descriptive name and **one or more of the following**: …", 4.2.c is hard to interprete when a role would solely be composed of a name and a domain:
> 4.2.(c) Requests to Impact Domain: Others may ask to impact a Domain controlled by one of your Roles. You must allow the impact if you see no reason it will reduce your capacity to enact your Role's Purpose or Accountabilities. If you do see such a reason, you must explain it to the requester.

One interpretation could then be : if the role is only composed of a name and a Domain, then there's no ground on which that role may refuse to another role to impact the Domain.

**Comment by brianjrobertson** [comment]
Yeah, that could be one interpretation, and if folks interpret it that way, perhaps that will trigger tension to do something differently.  But for me, I never interpret the absence of an explicit purpose as meaning there is no purpose, just that it's not specified and I have to infer the purpose based on history, context, role name, etc., and then I can object from that.  Either way, I don't think we need to change anything here - even if folks interpret it as you suggest, that will just lead to tension to resolve the issue.
