### ISSUE TITLE
Where is the default authority for role assignments within the Anchor Circle?

### ISSUE THREAD

**Issue by stephaniedwelch** [holacracyone/Holacracy-Constitution#417]
Given 1.4:

`The Anchor Circle has no Circle Leads, unless a Policy of the Circle says otherwise.`

and 1.4.1:

`No one other than a Circle Lead may assign a Role or revoke a Role assignment within the Circle, unless the Circle has delegated control of Role assignments to a different Role or process,`

where is the default authority for role assignments within the Anchor circle?

**Comment by brianjrobertson** [comment]
There is none; if there are no Circle Leads, no one may assign a Role or revoke an assignment unless/until the Circle delegates control of Role assignments elsewhere.
