### ISSUE TITLE
Integrative Election Process

### ISSUE THREAD

**Issue by Aliocha-Iordanoff** [holacracyone/Holacracy-Constitution#418]
“Integrative Election Process” is mentioned with quotes and its definition in 5.3.5, instead the terme is used before, in 5.1.1 (Circle Reps) and 5.1.2 (Facilitator & Secretary)

**Comment by brianjrobertson** [comment]
Yes, that's unfortunate, but I didn't see a great way around it, hence the addition of "defined herein" after the first two uses of it, just as a little pointer that it'll be defined later.
