### ISSUE TITLE
Definition of Domains - Authority, not Asset?

### ISSUE THREAD

**Issue by stephaniedwelch** [holacracyone/Holacracy-Constitution#419]
After Tuesday's ecosystem call about domains and policies, I discussed it with a client I'm coaching in a non-profit org in Canada. They are writing Holacracy into their by-laws and adding additional definitions in order to comply with the legal requirements of Canadian non-profits. One such definition that worked better with an adjustment was "Domain."

The suggestion is that, like a Role represents the work to be done and not the person doing it, the Domain refers to *the authority to impact* an asset or process, not to the asset or process itself. Distinguishing the authority from the asset seemed to improve understanding. Would this be a beneficial adjustment across the board?

Currently written as:
1.1 (b):
one or more “Domains”, which are assets, processes, or other things the Role may exclusively control and regulate as its property, for its purpose.

Suggestion: 
1.1 (b):
one or more “Domains”, which are grants of authority to exclusively control and regulate a specificied asset, process, or other thing that the Role may wish to impact for its purpose.

**Comment by brianjrobertson** [comment]
I'm not seeing this as adding any clarity or simplicity over the current language, at least when combined with the rules around impacting domains, so I'm inclined to dismiss it as just one lawyer's take that's not usefully generalized...
