### ISSUE TITLE
Confusion about the concept of Tension

### ISSUE THREAD

**Issue by bernardmariechiquet** [holacracyone/Holacracy-Constitution#429]
I come back on the subject which remained without continuation in this [thread ](https://github.com/holacracyone/Holacracy-Constitution/pull/394#issuecomment-739648865 )

Tension is defined in [article 1.2.1](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#121-processing-tensions) as a gap between the actual expression of your Role’s Purpose and Accountabilities to your vision of their ideal potential 
_**1.2.1 Processing Tensions
You are responsible for comparing the actual expression of your Role’s Purpose and Accountabilities to your vision of their ideal potential, to identify gaps between the two (each gap is a “Tension”). You are then responsible for trying to resolve those Tensions.**_
I've seen many people confuse what tension is with a problem, which it is not. And that effects self-management capacity development.

We had to define an amendment in several organizations : 
**The concept of "tension" as defined in section 1.2.1 is clarified by this amendment. A tension is not a problem or a concern, a tension is a gap "felt" by a person in a role when he/she has stepped back from a problem and dares to hold the gap between the current situation he/she has described and the ideal he/she is seeking, which he/she has also described. The person is no longer reacting to a problem, but creating value toward a vision by defining small steps from the brakes and the drivers that he has identified. Being understood that an ideal cannot be to "solve the problem", the posture is here centered on an ideal to reach, for which the felt problem seems to be a brake.**

So I open this thread for further exploration on this. 

In the continuity of the thread, and following [@brianjrobertson 's reaction](https://github.com/holacracyone/Holacracy-Constitution/pull/394#issuecomment-741515783), I propose the following modification:
https://github.com/holacracyone/Holacracy-Constitution/pull/430/commits/ec3be58af161f2f1a9c957dc3569dc3e047f2813

**Comment by brianjrobertson** [comment]
Ah, interesting; in our prior thread I didn't really understand where you were coming from or why it was a concern, but now I do.  It seems to me like you're pointing to a much more useful frame/mental-model/meaning-making than the default "problem" oriented frame most people coming into Holacracy tend to hold.  And I agree that the shift you're helping them make here is a useful upgrade to their frame; seems like this is an aspect of the human development that Holacracy benefits from when the humans involved can make the leap.

At the same time, I'm not sure if a constitutional change is the right move here - it seems like something that's more naturally  addressed through development-oriented activities and coaching.  I'm not opposed to a constitutional change as well if it makes those easier, but I'm not seeing how the one you proposed would help much; what's your thinking behind it?  I'm also sensing that "consciously" in this context is probably just redundant; if someone is going to "compare" something, doesn't that already imply doing so consciously (especially given the rest of that sentence and the context)?

**Comment by bernardmariechiquet** [comment]
> Ah, interesting; in our prior thread I didn't really understand where you were coming from or why it was a concern, but now I do. It seems to me like you're pointing to a much more useful frame/mental-model/meaning-making than the default "problem" oriented frame most people coming into Holacracy tend to hold. And I agree that the shift you're helping them make here is a useful upgrade to their frame; seems like this is an aspect of the human development that Holacracy benefits from when the humans involved can make the leap.
> 
You got it!

**Comment by bernardmariechiquet** [comment]
> At the same time, I'm not sure if a constitutional change is the right move here - it seems like something that's more naturally addressed through development-oriented activities and coaching. I'm not opposed to a constitutional change as well if it makes those easier, but I'm not seeing how the one you proposed would help much; what's your thinking behind it? I'm also sensing that "consciously" in this context is probably just redundant; if someone is going to "compare" something, doesn't that already imply doing so consciously (especially given the rest of that sentence and the context)?

What I observe is that in reading the definition of a Tension as described in the constitution, there is no ambiguity. And yet the default "problem" oriented frame remains at work for the most part. 
So I think instead we need to reinforce this shift in the constitution - like adding a nudge that makes this shift more accessible, and ideally inevitable. The definition as it stands is not enough, which is why several organizations have added a constitutional amendment to emphasize this. Not paying attention to this new mental model becomes more difficult.

**Comment by brianjrobertson** [comment]
I'm open to the idea in general, but I'm not sure what change would actually help, and I don't think adding "consciously" does much but hurt the constitution.  Any other ideas?

**Comment by jeanlucchristin** [comment]
Hello

One proposal to solve that : 
« in reading the definition of a Tension as described in the constitution, there is no ambiguity. And yet the default "problem" oriented frame remains at work for the most part. »

1.2.1 Processing Tensions
You are responsible for comparing the actual expression of your Role’s Purpose and Accountabilities to your vision of their ideal potential, to identify gaps between the two (each gap is a “Tension”, whether it's a motivation or a concern). You are then responsible for trying to resolve those Tensions.

**Comment by bernardmariechiquet** [comment]
Let's try to move the subject forward. I propose to modify [article 1.2.1](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#121-processing-tensions) as follows :

"You are responsible for comparing the actual expression of your Role’s Purpose and Accountabilities to your vision of their ideal potential, to identify gaps between the two (each gap is a “Tension”). You are then responsible for holding those Tensions and taking baby steps to move towards the outcomes you envision. In case the current situation is seen as a problem, "solving the problem" is not considered as an envisioned outcome."

**Comment by SamirSaidani** [comment]
Another idea : get rid of the concept of Tension in the Constitution. Learning how to lead a Role is in my view outside the scope of the Constitution (though necessary), and Tension is about how to lead a Role. The Constitution does not have to teach you how to lead a Role, but just give you some institutional spots & pathways where you might express your leadership... Less is more. No concept of Tension, no confusion possible. Problem solved.

**Comment by bernardmariechiquet** [comment]
Sorry but I don't agree with your comment @SamirSaidani . The concept of Tension is above all the form that the Organization takes to evolve. This one is a living entity in its own right, driven by its life force, its evolutionary purpose that evolves through and by the tensions of the roles, sensed by people. The Constitution must not remain static but include this evolutionary device IMO.

**Comment by brianjrobertson** [comment]
@SamirSaidani The whole constitution and process of Holacracy hangs on that concept/definition, so that approach doesn't resonate with me.

@bernardmariechiquet I get why that language would help with the way you're teaching and framing this, but I think it forces a specific teaching frame on everyone, whereas I think the constitution should stay more neutral; on top of that, it seems confusing to me and I imagine to many readers - it's not clear what it's trying to achieve.  I'm open to language updates here, but this one feels way off; I think we need something really simple yet broad, and universally applicable.

**Comment by bernardmariechiquet** [comment]
> @bernardmariechiquet I get why that language would help with the way you're teaching and framing this, but I think it forces a specific teaching frame on everyone, whereas I think the constitution should stay more neutral; on top of that, it seems confusing to me and I imagine to many readers - it's not clear what it's trying to achieve. I'm open to language updates here, but this one feels way off; I think we need something really simple yet broad, and universally applicable.

@brianjrobertson Interesting! I get your point re "staying neutral". At the same time, we know by experience - we have many of them - that not framing this dynamic tension concept risks strongly to undermine the adoption of a good practice of Holacracy in the long run.

Apart from the fact that, on another polarity, I may find it strange to call that "remaining neutral" where it could be considered that it is non-assistance to an organization in danger to leave the door open to such misunderstanding of what is a tension. I do wonder where is the place of this kind of things - and there are others re Accountability for ex. - that are also important in the practice of Holacracy. Would you call that another software - like Post Holacracy - above this Holacracy Operating System. 
Do you have any idea on this?

**Comment by brianjrobertson** [comment]
I'm not sure, I'm still trying to figure out what makes sense to me around this.  I do believe that if we are to add language to the constitution, it needs to be very simple and general - like your original idea of adding one word ("consciously"), although I don't think that specific word helps or adds anything valuable/meaningful in this case.  But I think the general direction that's most likely to make sense to me here is something along those lines (doesn't have to be just one word, just relatively short, and simple and general).

**Comment by jeanlucchristin** [comment]
@bernardmariechiquet 
I wonder: doesn't the wording "whether it's a desire or a concern" resolve 80% of your point?

**Comment by bernardmariechiquet** [comment]
@jeanlucchristin Thanks for your help!
I don't see how this addition solves the tension I hold.
A Tension is not a concern nor a desire but a gap between the two.
Can you elaborate more on what you are thinking?

@brianjrobertson Let me try the following change...

**_1.2.1 Processing Tensions
You are responsible for comparing the actual expression of your Role’s Purpose and Accountabilities to your vision of their ideal potential, to identify gaps between the two (each gap is a “Tension”). You are then responsible for trying to reduce those Tensions by taking Next-Actions towards your vision._**

What do you think?

**Comment by bernardmariechiquet** [comment]
Going further, I observe that the notion of tensions is less well treated in the constitution than the notion of project which is defined in article 1.2.2 and set in motion in article 1.2.3.
By taking a step back, I do not see why these different concepts should be treated in different ways, which would avoid certain blind spots in the constitution that make this concept of tension is not treated at the same level as that of Project in the GlassFrog software, which is in a certain way an illustration and a consequence that the notion of tension is more put forward.

I suggest a pull request in order to be more specific.

https://github.com/holacracyone/Holacracy-Constitution/pull/434
https://github.com/holacracyone/Holacracy-Constitution/pull/434/commits/d017dabe46983480749ccb526721e32c72a0882f

**Comment by brianjrobertson** [comment]
Hmm, fascinating!  Thanks for moving this forward and the continued ideas @bernardmariechiquet - I think we're getting closer to something that makes sense to me and feels like an improvement.  Let me respond to the first idea above for now, and then I'll come back to the latter separately.

To recap, your suggestion is to change the sentence after Tension is defined from this (the current text):
> You are then responsible for trying to resolve those Tensions.

to this:
> You are then responsible for trying to reduce those Tensions by taking Next-Actions towards your vision.

I like where you're going with this.  I see two components here: you're replacing "resolve" with "reduce", which ties better to the definition of Tensions as "gaps", and implies more of an ongoing journey to continually reduce the gap, vs. a one-time act of resolving them entirely.  That makes a ton of sense to me and I can see how that subtle shift would help address the issue you're sensing here.

The other component in your suggestion is adding a means of how one would reduce a Tension ("by taking Next-Actions").  I really like that this makes the clause more concrete, and ties it to the concept of Next-Actions.  But I don't like that it focuses the clause on just taking Next-Actions, when Tensions are often processed by other means - projects, governance proposals, requests of others, relational agreements, etc.

One could argue that there's always technically a Next-Action there to get to the others (e.g. capture a project, craft a governance proposal, e-mail a request, etc.), but do we want to have to rely on that implicit argument?  Could that create more confusion and problems than this change would solve, or is it still a step in the right direction?  Any thoughts?  It doesn't make sense to me to try to enumerate all the pathways in that clause, so it seems our options are:

1. Keep the current version of that part, with no mention of how to reduce Tensions.
2. Go with your suggestion of using Next-Action, and accept the downside I described above.
3. Add the how clause (including tying back to "your vision", which is helpful), but using more generic catch-all wording instead of referencing Next-Actions as the means; something like "You are then responsible for trying to reduce those Tensions by taking steps towards enacting your vision" or, a simpler version, "You are then responsible for trying to reduce those Tensions and work towards your vision".  We could also swap the order here and put the vision part before the part about reducing the Tensions, such as: "You are then responsible for trying to enact your vision by taking steps to reduce those Tensions" or the simpler version, "You are then responsible for trying to enact your vision to reduce those Tensions".  We could also use "realize" or "work towards" instead of "enact" - not sure which I prefer.

Thoughts?

**Comment by brianjrobertson** [comment]
Regarding your other suggestion and pull request:  I'm mixed on this one.  There's something appealing about it to me for sure, but I worry the appeal is more just the aesthetic structural symmetry and simplicity of it, and it might actually hurt by conveying a subtly different and perhaps less useful distinction.  The current construction supports and conveys that a Tension is at a different level than Project and Next-Action in some way and not a parallel construct to them, and I've always thought of that as a more useful frame than thinking of them as totally parallel.  Tensions lead to Projects and Next-Actions, and even to the selection of which Next-Action to take when breaking down a Project.  In that sense, Tensions precede Projects and Next-Actions, they don't stand parallel or co-arise with them.  The current construction seems to better communicate "Tensions are the ultimate driver of everything and everything flows from them", where the change we're contemplating perhaps communicates something more like "Projects, Next-Actions, and Tensions are the ultimate drivers of everything and everything flows from one of them".

Thoughts?  Am I sensing something that's actually important here, or just stuck in my original mental model enough that I'm missing how this is actually a more useful one?  I'm very open to shifting my mental model here if you/someone can help convince me why this one is actually better.

**Comment by bernardmariechiquet** [comment]
> 3\. Add the how clause (including tying back to "your vision", which is helpful), but using more generic catch-all wording instead of referencing Next-Actions as the means; something like "You are then responsible for trying to reduce those Tensions by taking steps towards enacting your vision" or, a simpler version, "You are then responsible for trying to reduce those Tensions and work towards your vision".  We could also swap the order here and put the vision part before the part about reducing the Tensions, such as: "You are then responsible for trying to enact your vision by taking steps to reduce those Tensions" or the simpler version, "You are then responsible for trying to enact your vision to reduce those Tensions".  We could also use "realize" or "work towards" instead of "enact" - not sure which I prefer.

I like what you're digging into. I was hesitating with "baby steps" instead of "Next-Action"
**"You are then responsible for trying to reduce those Tensions by taking baby steps towards your vision."**
I like "baby" as it lowers the bar and and puts people in motion more easily.

**Comment by brianjrobertson** [comment]
I'd go with "small steps" over that, just to avoid the colloquial language, but I don't think it makes sense to limit it to just that - we don't want to exclude large steps from the responsibility when that's really needed.  We could perhaps say "incremental steps", that might capture what you're going for without limiting to just big or small ones...?

**Comment by bernardmariechiquet** [comment]
> Regarding your other suggestion and pull request: I'm mixed on this one. There's something appealing about it to me for sure, but I worry the appeal is more just the aesthetic structural symmetry and simplicity of it, and it might actually hurt by conveying a subtly different and perhaps less useful distinction. The current construction supports and conveys that a Tension is at a different level than Project and Next-Action in some way and not a parallel construct to them, and I've always thought of that as a more useful frame than thinking of them as totally parallel. Tensions lead to Projects and Next-Actions, and even to the selection of which Next-Action to take when breaking down a Project. In that sense, Tensions precede Projects and Next-Actions, they don't stand parallel or co-arise with them. The current construction seems to better communicate "Tensions are the ultimate driver of everything and everything flows from them", where the change we're contemplating perhaps communicates something more like "Projects, Next-Actions, and Tensions are the ultimate drivers of everything and everything flows from one of them".
> 
> Thoughts? Am I sensing something that's actually important here, or just stuck in my original mental model enough that I'm missing how this is actually a more useful one? I'm very open to shifting my mental model here if you/someone can help convince me why this one is actually better.

I'll come back on this one as I see it very important from a mental model perspective.
Many people don't step back - don't get off the bike and watch themselves pedal - and therefore don't identify tension in the sense of a gap between what is and what could/aspires to be.
And yet they take projects requested by others and of course actions.
So the mental model "Tensions are the ultimate driver of everything and everything flows from them" is not true. 
Of course the life energy, the impulse, the stress, the problem are the ultimate driver of everything and everything flows from them. But that is different from a sensed tension that requires to sense both current reality and a vision - which makes you in a different state - a creative one not a reactive one.
The real tensions require work from these life triggers to identify the vision and then to manage the incremental steps over time.
I think your thinking considers that the tension is there whether the vision is explicit or not. 
But this is not true from my point of view. The tension is only there when the vision is conscious.
Maybe I don't help you enough here. Tell me.
Anyway I will come back to you. At the moment I don't have much time because I have to go sailing on a boat with my wife. I would have liked to have more availability to put more care in my answer.

**Comment by bernardmariechiquet** [comment]
> We could perhaps say "incremental steps", that might capture what you're going for without limiting to just big or small ones...?

Superb! @brianjrobertson

**Comment by MichaelDeAngelo** [comment]
I like where this change is ending up; I think it improves the articulation of the intent. Specifically,  calling out "steps" instead of "Next-Actions" is way better and less likely require a coach to explain how Projects fit into that. I think adding "incremental" in front of steps is definitionally redundant although I don't think it causes harm.

**Comment by chrcowan** [comment]
"You are responsible for comparing the actual expression of your Role’s Purpose and Accountabilities to your vision of their ideal potential, to identify gaps between the two (each gap is a “Tension”). **You are then responsible for trying to reduce those Tensions by taking incremental steps towards your vision."**

This makes sense to me. I resonate deeply with the change from "resolve" to "reduce." I don't care as much about the other bits.

**Comment by rebeccabrover** [comment]
I like where this is going. I think the idea of a role having a vision is often a lot to land for new practitioners, but that's not new. I also really like _incremental steps_ vs. _next-actions_ as it's more common language. I really like _reduce_ as an addition but feel the loss of _resolve_ as it is also possible. I think it's important to acknowledge that some tensions involve lengthy or complicated balls of yarn to untangle, and some can be solved with one request for information, which, when provided, often leads to a new tension, but does include a version of resolution.
I'd love to see both to serve as reinforcement that Tensions come in all shapes and sizes. I also think the preposition is off but hold that really lightly.
**You are then responsible for trying to resolve or reduce those Tensions through incremental steps towards your vision.**

**Comment by oliviercp** [comment]
Interesting discussion. I personally prefer the following proposed version:

> You are responsible for comparing the actual expression of your Role’s Purpose and Accountabilities to your vision of their ideal potential, to identify gaps between the two (each gap is a “Tension”). **You are then responsible for trying to enact your vision by taking ~~incremental~~ steps to reduce or resolve those Tensions.**

* I love the idea of putting the vision first — tensions are sensed in service of the purpose (which "vision" points to), they are central to everything but they're only a mean to an end. This order of the sentence is a subtle reminder to that. 
* I would not add "incremental" because I agree with @MichaelDeAngelo that's it's redundant, and I think it can suggest "small" steps, whereas we want to limit the responsibility to small steps towards resolving tensions. The word "step" itself already suggests "partial" resolution, since a step implies other steps. 
* I like @rebeccabrover's addition of "reduce or resolve" for the reasons she explains. It may add a bit of "noise" to add more words, but in this case the benefit outweighs the cost IMO.

**Comment by brianjrobertson** [comment]
@bernardmariechiquet Regarding [this comment](https://github.com/holacracyone/Holacracy-Constitution/issues/429#issuecomment-967828641) of yours above about restructuring the text to make Tension parallel to project/action definitions:  I'm intrigued, and realize I'm not at all confident of my prior stance against this, although also not totally sold on it, but I think it's definitely worth exploring further.  Would you be willing to create a separate GitHub issue for this and link your suggested pull request in it, so we can have a dedicated thread to discuss this part further, and leave the rest of this thread to the other change contemplated above?

**Comment by brianjrobertson** [comment]
Okay, I think @ocompagne sold me on his version above; I'm going with that unless someone has a further pitch to consider.
