### ISSUE TITLE
Clarify the threshold from being governed by your circle leader to being governed through the governance process

### ISSUE THREAD

**Issue by bernardmariechiquet** [holacracyone/Holacracy-Constitution#431]
@brianjrobertson I think - unless I didn't see where it would be clarified - we should clarify into the constitution what is the threshold for moving from a circle governed by a circle lead to a circle governed via the governance process.

Beginning of [article 5](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#article-5-governance-process) **"Changing a Circle's Governance requires using the “Governance Process” defined herein."** doesn't seem quite right IMO. Indeed, when a role lead adds structure to the inner circle, he does so without going through the governance process. It would be necessary in my opinion to clarify this first sentence of article 5  by adding at the end something like "except in the case where the circle is still governed directly by a circle lead".

I saw that in GlassFrog you had taken the option of setting this threshold to the first election in the circle of one of the elected roles, which might be another option to make this threshold explicit.

And same question for the opposite direction: how is the transition from a circle governed via the governance process to a circle governed directly by a circle lead, if possible?

I'd appreciate your thoughts on that.

**Comment by brianjrobertson** [comment]
Even with just a single Circle Lead, that Circle Lead is still changing the Governance through the Governance Process: i.e. by ensuring no Circle Member has any Objections to a proposed change (i.e. they don't have any objection themself).  So there is no distinction needed here; it is the same Governance Process, rules, and threshold regardless.

**Comment by LouisChiquet** [comment]
However that's not how it is on GlassFrog. On GlassFrog, there's the need of first electing a role, to then be constraint to use the governance process. Not when there is the first Partner filling a role in the inner circle of the role. That would mean that GlassFrog isn't compliant on such?

**Comment by brianjrobertson** [comment]
GlassFrog is fully compliant; with only one person filling Circle Lead, the Circle Lead editing the governance is aligned with the constitutional rules required for the Circle's Governance Process.

**Comment by LouisChiquet** [comment]
Yes that it is. However prior if I was adding someone to my inner role, I could still change the governance as I wanted as Circle Lead. But I see that it's now fixed.
