### ISSUE TITLE
V5 and removing accountabilities for the Circle Lead role.

### ISSUE THREAD

**Issue by mvletter** [holacracyone/Holacracy-Constitution#432]
This is my first time opening a ticket, where we have been doing Holacracy for over 6 years so bear with me.

We have adopted V5 of the constitution. In V4.2 the LL had visible accountabilities for strategy and relative priority in Glassfrog. In V5 this is moved to article 1.4.3 of the constitution. I love the new phrasing. 

_A Circle Lead may judge the relative value of potential circle efforts to resolve priority conflicts across roles. A circle lead may also define a “strategy” for the circle, or many strategies, which are heuristics that guide prioritization in the circle._

1. Some circles also have roles that are accountable for strategy or priority. Within the current text the Circle lead _may also define a “strategy”_. That leads to lack of clarity; a role that is accountable and a role that "may also define". Is there something in the constitution that states that these accountabilities are deemed irrelevant for the circle lead is a process or another role energizes this accountability? And if not what would be a nice way to solve this? 
2. (This is a technical one) In Glassforg you can only give a Circle Lead of the GCC accountabilities via a policy which is then also transferred automatically to deeper circle leads. The concept is nice and I think it adds value. The problem is such policies are far less visible to the org. Al least far less then it is when you see them as accountabilities for every circle lead role. I know this is a technical challenge within Glassfrog, which I understand. A new feature for one role with adoption like this will be a tricky thing. I also notice the current way of solving this leads to tensions, so this might be something that needs to be picked up.

**Comment by brianjrobertson** [comment]
Thanks for the contribution!

To your first point, I'd say that seems like more of a coaching question about how to use/interpret the rules, vs. an issue with the rules themselves that might lead to a change in the constitution text, and this platform is meant for the latter, so I suggest you post that on the Community of Practice instead - that should get you some insight on how that works.

To your second point, I totally agree, this is an issue, though it's an issue with GlassFrog, not the constitution itself (and this platform is for the latter).  I'd normally suggest you e-mail GlassFrog support instead, but in this case, I'm pleased to report that the GlassFrog team is actively working on the feature needed to support that, and it should be shipped soon. 😊
