### ISSUE TITLE
Definition of Policy

### ISSUE THREAD

**Issue by jeffwllms** [holacracyone/Holacracy-Constitution#433]
In the Holacracy Constitution v5 section 1.1 defines a policy as follows:

_A Role may also hold “Policies”, which are grants or constraints of authority, or special rules that apply within that Role._

If the default is that a Role Lead has authority to energize their roles as they see fit and long is it does not violate the constitution or any policies of circles, or governance, etc.  It seems as though it would be counter productive that policies should be used to "grant" authority.  It would also better fit the generally understood idea that policies are rules, constraint, and other guiding principles.   In my experience it seems like a generally accepted best practice of a policy would be not to list all the things that are allowed, the assumption is that unless not allowed via policy it is allowed.  I supposed this would be different if the default was you cant take action unless a policy or other governance grants the ability to take action, but that does not seem to be the default in Holacracy.

**Comment by brianjrobertson** [comment]
The "grant" language covers those times when the role already controls something exclusively via a governance act of its containing circle, such as that circle granting the role a Domain to exclusively control, but that role then wants to create a policy to allow others to impact that Domain in specific cases without getting permission.

**Comment by jeffwllms** [comment]
Ah, I see.  I did not think of a policy as a means granting permission to impact.  I see the relevant language in 4.1.2.  I can also see then how it would apply with Sending Money in 4.1.3.  These are area where the constitution default to not having authority.  

It does make more sense then.  Thanks for the clarification.
