### ISSUE TITLE
PDF versions of the releases ?

### ISSUE THREAD

**Issue by dienkwik** [holacracyone/Holacracy-Constitution#44]
Hi, 

I was wondering if it's possible to have the pdf versions of the documents in the releases ?
I think it will be easier if when people download the latest release of the constitution, the pdf versions are available.

Thanks,

Dien.

**Comment by brianjrobertson** [comment]
We publish PDF versions on our website instead, to allow for some more context and a nice web-formatted version as well; it's all at http://holacracy.org/constitution.  Note you can also use the link in the intro file in github to generate a PDF on the fly of whatever version you're looking at...

**Comment by cloudlena** [comment]
@brianjrobertson, there's no download link for version 5 on the website yet, is there? That would be very helpful :smiley:
