### ISSUE TITLE
Is there a reason that the German version 5.0 requires participants to be extremely woke and left wing to accept it?

### ISSUE THREAD

**Issue by geek-42** [holacracyone/Holacracy-Constitution#444]
The [German 5.0 version of the Constitution](https://github.com/holacracyone/Holacracy-Constitution-5.0-GERMAN/blob/main/Holacracy-Verfassung.md) uses a [Gendersternchen](https://en.wikipedia.org/wiki/Gender_star) which [is not part of the official langue](https://de.wikipedia.org/wiki/Gendersternchen#Ablehnung_des_Gendersterns_oder_aller_Genderzeichen) but a strong sign of "virtue signaling" of woke or left wing communities.

This makes it very hard for some organizations to adopt the constitution because it seems like it forces a certain political agenda upon the signers.

I would propose to have a second alternative German constitution in official German language without the Gendersternchen.

This would allow organizations to adopt the version that fits their culture and still refer to an "official" holocracyone document.

**Comment by oliviercp** [comment]
@geek-42 Very good question, and I look forward to a discussion on this issue. But this repository you're posting in is for the English version of the constitution, not the German translation. As much as possible, HolacracyOne is trying to keep only one official translation for any given language. 

That said, translations of the constitution are also on GitHub to allow for collaboration, and they can evolve when issues are pointed out.  I suggest you open this issue in the repository for the German translation that you linked to, and have a healthy discussion there on how to best translate the constitution into German.

**Comment by geek-42** [comment]
The reason I opened an issue here is that I think it is a general issue about the gist of the constitution. The translation adds a spin to the constitution that I don't see in the original English version here. As far as I can see, the German constitution follows the paragraphs of the English version but it has a subtext that is very political. It feels like someone wants to enforce a certain woke political view on the reader.

If the German constitution is independent of the version here, then it can to what it wants. But it feels strange to me, that the German version is politicized. 

I also wanted to have a more general discussion  in English....

But I created an issue on the German translation: https://github.com/holacracyone/Holacracy-Constitution-5.0-GERMAN/issues/4

**Comment by brianjrobertson** [comment]
@geek-42 I don't speak German so I can't speak to the validity of your premise.  If I take that as a given, I agree with you completely - the constitution definitely shouldn't use language with that kind of bias built-in, and if the current translation does, I'd consider that a major problem.  But of course that's only if the premise is valid, and I'm not qualified to assess that either way; although if it strikes you that way, that itself is at least one data point.  Regardless, @ocompagne is correct that this forum has nothing to do with the german translation, so I'm glad to see you opened the issue over where it can get acted upon.  Feel free to tag me there if there's anything I can assist with, although without speaking German I doubt I'll be much use.
