### ISSUE TITLE
Unclear which clauses are not to be changed via policy

### ISSUE THREAD

**Issue by dienkwik** [holacracyone/Holacracy-Constitution#446]
I'm still unclear about which parts of the constitution are actually unchangeable via policy.

I am clear that the portions of the constitution that have the "unless specified otherwise" phrase, means that you can indeed change them through policy.

I am also clear on the portions of the constitution that say something is a must or that something is not allowed. 

For the rest which do not say whether it's a must or forbidden, and also do not have the "unless otherwise specified" phrase, is the intent to forbid any changes via policy ?

Let's take the Process Breakdown and the Process Restoration article as examples. Is the intent to forbid any other ways of declaring process breakdown as well as other ways of process restoration?

**Comment by bernardmariechiquet** [comment]
> Let's take the Process Breakdown and the Process Restoration article as examples. Is the intent to forbid any other ways of declaring process breakdown as well as other ways of process restoration?

Interesting! To join you in your questioning, can you point me to another path you have encountered or are encountering to declare a process breakdown, and that would not be included in what is written in section 5.5?

Or can you tell me what other paths you have practiced or are about to practice to conduct the process restoration?

**Comment by dienkwik** [comment]
Hi, @bernardmariechiquet:

The process breakdown and restoration was actually meant as an example of a clause which does not specify that you must do it this way, but also does not specify that you can alter it through policy.  In this instance, I was wondering if the intent was to disallow any kind of deviation from it.

Having said that, there is a specific case in our organization where not all facilitators and secretaries are well versed in the constitution. We should ofcourse rectify this, but in the short term we would like to be able to declare process breakdown and restoration, but only by experienced facilitators. We were thinking of creating a policy that say only facilitators that have already earned a certain badge can call process breakdown and conduct process restoration.

So in essence limiting the authorization further with policies. However, it is not clear if the intent of the constitution is to forbid this and why it is forbidden.

The same thought goes for other clauses like this, i.e. the ones that don't say that you must or you can't and don't specify that you can change them through policy, which are most of them actually. Are we to treat them as unmodifiable ?

**Comment by bernardmariechiquet** [comment]
> The process breakdown and restoration was actually meant as an example of a clause which does not specify that you must do it this way, but also does not specify that you can alter it through policy. In this instance, I was wondering if the intent was to disallow any kind of deviation from it.

I'm not aware of any intent to disallow any kind of deviation, this is the reason why I was looking for an example to dive in more with you.

**Comment by bernardmariechiquet** [comment]
> Having said that, there is a specific case in our organization where not all facilitators and secretaries are well versed in the constitution. We should ofcourse rectify this, but in the short term we would like to be able to declare process breakdown and restoration, but only by experienced facilitators. We were thinking of creating a policy that say only facilitators that have already earned a certain badge can call process breakdown and conduct process restoration.

This case, I experienced it not exactly the same way as you, but in a similar way.
It can happen with novice facilitators who are not familiar with the rules of integration or the requirements for a proposal, and may get stuck in integration.

So, it may happen that the process does not get to a final proposal with no objection, and in these cases, some organization may propose to authorize using a policy or a constitutional amendment, the facilitator/secretary to stop the meeting to let things "rest" until a next meeting to be organized at the request of the facilitator or secretary. And in the meantime, the facilitator and secretary should draw lessons to understand what happened, alone or with others more competent than themselves.

The choice of whether to use a policy or a constitutional amendment depends on the interpretation of the constitution by the relevant role concerned. Personally, I believe I have encountered rarely the policy option. And I don't remember some organization I know, using the amendment option. 

Although honestly, this common sense rule probably does not always need to be made explicit in one possible caveat interpretation of Article 5.5. As the constitution says "The Facilitator or Secretary of a Circle may declare a Process Breakdown in their own Circle or any Sub-Circle, using their reasonable judgment". I would rely on the "reasonable judgment" any facilitator/secretary, even not very experienced ones. 

> So in essence limiting the authorization further with policies. However, it is not clear if the intent of the constitution is to forbid this and why it is forbidden.

For me, there is no one answer here, let's use reasonable judgment as defined in section 4.2 of whoever role is concerned when such situation occurs.

> The same thought goes for other clauses like this, i.e. the ones that don't say that you must or you can't and don't specify that you can change them through policy, which are most of them actually. Are we to treat them as unmodifiable ?

My general answer would be a priori no - I would recommend using reasonable judgment in any situation that occurs. And at some point, I may - with a specific case - open an issue on GitHub to share the situation with others and sees if any potential evolution of the constitution is needed.

**Comment by dienkwik** [comment]
> My general answer would be a priori no - I would recommend using reasonable judgment in any situation that occurs. And at some point, I may - with a specific case - open an issue on GitHub to share the situation with others and sees if any potential evolution of the constitution is needed.

Yes, I think this is a reasonable way to tackle this issue.

However, this question still bothers me though:  what is the purpose of specifying that certain clauses are to be followed unless otherwise specified (i.e. can be modified), when the rest of the constitution that is not specified as such (and not explicitly forbidden), can also be modified (with reasonable judgment) ?
