### ISSUE TITLE
multi-filled roles and circle leads

### ISSUE THREAD

**Issue by BjoerndG** [holacracyone/Holacracy-Constitution#448]
Hi there,

I have a conceptual issue:

When a multi-filled role becomes a circle (i.e. anyone of the role-leads of that role can make it a circle anytime), it becomes _one_ circle with all role-fillers becoming this circles circle-leads. Same if an existing circle gets multi-filled - within that circle it results in multiple circle-leads. 

With a Focus set it still makes sense in working towards the purpose of the broader role. However, it creates a strange situation within the circle. Who of the many circle-leads is accountable for the duties of a circle-lead as defined in §1.4? Who holds the domain of filling roles as defined in $1.4.2? I cannot make sense of that with the current constitution. The focus does not help in here, it’s only directed outwards.

As I understood Brian this function should help role-leads of multi-filled roles to use governance and tactical to collaborate and organize their work, communicate amongst each other etc. That somehow makes sense to me, but on the other hand the concept of multi-filled roles and (sub)circles is not the same to me (albeit reading this sometimes here).

To me a multi-filled role with focus is much more like separate roles. Brian wrote something similar here (https://github.com/holacracyone/Holacracy-Constitution/issues/412 ), expressing that there is an epic on glassfrogs roadmap treating multi-filled roles with focus as separate roles when it comes to linking them into other circles. Makes total sense to me, as linking multi-filled roles is a pain right know and such a solution could solve a lot of problems organizations have.

Therefore, wouldn’t it be more logical if multi-filled roles that become circles would be treated as separate circles as well? i.e. if one of the role-leads decides to create subroles it would only affect his/her role, but not the roles of the other role-leads? I admit – it seems more logical but also would be quite difficult to visualize.

Alternatively, it would need some more clarification on how to threat the special case of multiple circle leads, i.e. who is the one accountable in the end.

Or we could drop the idea of multi-filled circle-leads / circles and do not allow for that altogether. It seems to be a rather complicated thing, very difficult to explain and at least I cannot come up with a lot of benefits from it.

Happy to hear other perspectives and especially examples where multi-filled circle leads create a benefit. 

Best
Björn

**Comment by brianjrobertson** [comment]
Re:

> Therefore, wouldn’t it be more logical if multi-filled roles that become circles would be treated as separate circles as well?

This is already the case, per [§1.4.1](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#141-assigning-roles), "When a focus is used, each assignment focus behaves like a separate Role."

**Comment by BjoerndG** [comment]
Hi Brian,

thanks for the (partial) answer. 

However, multifilled circles don't behave like seperate circles (at least in glassfrog) but as one circle with multiple circle-leads. No matter if a focus is set or not. 

In any case it would be either quite confusing to have multiple parallel circles for multifilled circles or we would still have the unsolved problem with mutliple circle leads (at least in the case where no focus is set). 

To me both seems to be rather not helpfull or at least I cant see the benefit in it yet. 

Pls consider reopening the case :)

Best
Björn

**Comment by brianjrobertson** [comment]
Re:

> However, multifilled circles don't behave like seperate circles (at least in glassfrog) but as one circle with multiple circle-leads. No matter if a focus is set or not.

That's a current limitation in GlassFrog, and in every other Holacracy support tool at present - none have supported this particular constitutional spec for Holacracy yet (we have plans to do so in GlassFrog, though we haven't gotten there yet).  But despite the lack of tool support, the constitutional rules are very clear: multi-filled roles (and thus circles, since they're also roles) with a focus behave like entirely separate roles.

To re-open the issue, I need you to make a case (ideally with concrete examples from actual practice) for how the current constitutional rules are getting in the way.
