### ISSUE TITLE
Add PDF Download of Constitution Version 5

### ISSUE THREAD

**Issue by cloudlena** [holacracyone/Holacracy-Constitution#452]
On the [page of the constitution v4](https://www.holacracy.org/constitution/4-1), there is a "Download PDF (English)﻿" link. It would be great if that also existed on the [page of the constitution v5](https://www.holacracy.org/constitution/5).

Another idea might be to add the PDF to the [Releases](https://github.com/holacracyone/Holacracy-Constitution/releases) page as "Assets" here on GitHub.

**Comment by oliviercp** [comment]
Agreed @cloudlena. In the meantime, you can pretend-print and save it as PDF; there is a decent print-friendly css style on the v5 page. It's not as pretty as the carefully formatted PDF for v4.1, but it works.

**Comment by brianjrobertson** [comment]
Closing this issue, as this forum is just for evolving the constitution content itself, not the presentation of it on holacracy.org (for feedback like that, please submit on the Contact Us page at holacracy.org, though no need in this case, as @oliviercp has it queued up now).
