### ISSUE TITLE
“Partner” term being adaptable

### ISSUE THREAD

**Issue by LouisChiquet** [holacracyone/Holacracy-Constitution#457]
The terminology “partner” is quite often out of place for orgs (because it is a legal term, or because the term is too “harsh” etc.), and we are therefore pushed to define other terms in order to adapt it. Such as “associate”; “actor”; “captain”; etc. And so would think it best, as discussed with other french providers, to make it adaptable (like tactical meeting or other functionalities) in the Constitution de-facto.

**Comment by brianjrobertson** [comment]
How is this not already the case?  Such as a simple Anchor Circle policy saying "Associate" has the same meaning as "Partner"?

**Comment by LouisChiquet** [comment]
Constitution generally specify when something is “per default” and can be changed, e.g. Tactical Meeting, spending money, etc.
It doesn't in the case of “Partner”, and so use constitutional amendments to do so currently, since technically the constitution doesn't allow such change. At least in my interpretation.

**Comment by brianjrobertson** [comment]
That's for changing rules, and you're not changing a rule, just defining another term to mean the same thing as "Partner" - there's no way that requires the constitution to allow it, or you basically couldn't ever define any term whatsoever outside of the constitution.
