### ISSUE TITLE
Why does the Anchor Circle not have a Circle Lead?

### ISSUE THREAD

**Issue by MichaHumbel** [holacracyone/Holacracy-Constitution#458]
I'm trying to better understand the Holacracy Constitution. 

As per definition of '1.4 Circle Lead' the Anchor Circle has no Circle Leads.

What is the reason behinde that? Who executes the 'normal' tasks of a Circle Lead like Assigning Roles, Covering Unfilled Roles,Defining Priorities & Strategies or Routing External References?

Thanks for clarifying this.

**Comment by brianjrobertson** [comment]
This forum is exclusively for discussing potential changes to the constitution, not for learning about it; you might try asking this on HolacracyOne's [self-management accelerator](https://www.holacracy.org/sma/) forums instead.
