### ISSUE TITLE
When are the version 5 changes due to appear?

### ISSUE THREAD

**Issue by djwork** [holacracyone/Holacracy-Constitution#46]
Hi All
        I have been holding off on some posts for the version 5 changes to start appearing so that I can avoid bringing up tensions that are already in the process of being resolved. 

Is there an updated ETA on version 5 changes?
Thanks
Daniel

**Comment by brianjrobertson** [comment]
Hi Daniel - The bad news is we de-prioritized working on v5.0 for now, so it's on-hold; I'd guess we'll pick it up again early next year.  The good news is, we did that to focus more on developing apps, so we should have some other exciting releases coming sooner instead.
