### ISSUE TITLE
Sample Declaration not present

### ISSUE THREAD

**Issue by djwork** [holacracyone/Holacracy-Constitution#5]
https://github.com/holacracyone/Holacracy-Constitution#how-is-this-document-intended-to-be-used
_This Constitution is intended to be referenced by whatever declaration or agreement captures the decision to organize using the Holacracy system. That may be a formal set of legal bylaws or similar operating agreement, or a simple board resolution or CEO policy declaration similar to the sample one attached at the end of this document. See Article V for key adoption-related matters, and note also that this explanatory page and **the sample declaration at the end** are included for informative purposes but do not constitute part of the core Constitution document._

I assume that this text was copied from another web page and there is no longer a sample declaration?

**Comment by RashidGilanpour** [comment]
@djwork thank you for catching this!  I've fixed this issue now.
