### ISSUE TITLE
The Anchor Circle Secretary can Amend the Constitution

### ISSUE THREAD

**Issue by dlocke** [holacracyone/Holacracy-Constitution#50]
Section 3.4 allows the secretary of the Anchor Circle to publish an interpretation on any part of the constitution with no mechanism for appeal.  This effectively gives the secretary of the Anchor Circle absolute power which can be used to (among other things) declare that Section 5.5 gives them the authority to amend the constitution.

**Comment by brianjrobertson** [comment]
This is outside the scope of the constitution to address, especially without a concrete case of this actually happening, and one where just calling for a new election was insufficient.  There are plenty of constraints on what a Secretary can do - there's the burden of reasonableness, as well as staying within the meaning of "interpret".  If the Secretary really goes beyond all of that and an election won't work to resolve, then that's the domain of the ground authority under the constitution to address (e.g. a court or an arbitrator, if it's a legal adoption at a bylaw level).

**Comment by dlocke** [comment]
Brian,

To me, it seems like the constraints on what a Secretary can do are implicit more than they are explicit.  The burden of reasonableness is mentioned at the start of section 3.4, but in context of all partners.

As for staying within the meaning of "interpret", it's ultimately up to the Secretary of the Anchor Circle to decide what the meaning of "interpret" is and thus it's not a meaningful constraint.

I do agree that escalating the resolution of the conflict is a possible means of dealing with this issue.  However, I also think that allowing a single person to DOS the entire organization is a flaw that could be addressed in version 5.0.

David

**Comment by dlocke** [comment]
Brian,

I should add that if the Secretary uses their authority to fullest extent possible, there won't be any means of replacing the Secretary in the newly amended constitution and thus it's very, very likely that you'll need to escalate the resulting conflict to the domain of the ground authority under the constitution.

David
