### ISSUE TITLE
Restoring Due Process in the Anchor Circle

### ISSUE THREAD

**Issue by dlocke** [holacracyone/Holacracy-Constitution#51]
Section 3.5.3 describes what happens between when a process breakdown is declared and when "the Facilitator of the Super-Circle concludes that due process has been restored".  However, in the unfortunate event that a process breakdown is declared in the Anchor Circle, there will not be a Facilitator of the Super-Circle that can conclude that due process has been restored.  This leaves the end point of the authorities granted in Section 3.5.3 open for interpretation.

I think it would be good to update the constitution to clarify who will conclude that due-process has been restored in the Anchor Circle because delaying the interperatation until the circle is in the middle of a process breakdown has the potential to cause harm in a way that is not "safe-to-try".

**Comment by brianjrobertson** [comment]
Fixed with an earlier change.
