### ISSUE TITLE
Lack of clarity (at least for non english native readers)

### ISSUE THREAD

**Issue by bernardmariechiquet** [holacracyone/Holacracy-Constitution#52]
In art 2.3.2 Exclusion for Multi-Filled Roles, at the end I think there is either a missing part or a lack of clarity in the following piece ", exactly as a Rep Link would were the Role a Sub-Circle,"
I get what is meant but I think this could be more clearly phrased.

2.3.2 Exclusion for Multi-Filled Roles
If multiple Partners are assigned to the same Defined Role in a Circle, the Circle may enact a Policy that limits how many of them are Core Circle Members as a result of that Role assignment. However, the Policy must allow at least one of the Partners filling the Role to represent it as a Core Circle Member, and must specify how that representative will be determined.

In addition, any Partners representing the Role have the duty to consider and process Tensions conveyed by the excluded Partners, exactly as a Rep Link would were the Role a Sub-Circle, unless the Policy defines an alternate pathway for the excluded Partners to process Tensions related to that Role.

**Comment by julianeroell** [comment]
I drafted a possible change (see above).

**Comment by brianjrobertson** [comment]
@martinroell - looks good, please do feel free to submit that edit and I'll merge it in.

**Comment by martinroell** [comment]
Here is a new try: changing the order of sentences for better understandability.
