### ISSUE TITLE
Add an "S" to Domain - art. 2.6.2

### ISSUE THREAD

**Issue by bernardmariechiquet** [holacracyone/Holacracy-Constitution#53]
Would recommend to add an "S" to Domain in the first sentence of 2.6.1

2.6.1 Modifying Sub-Circles

A Circle may modify the Purpose, Domain, or Accountabilities on a Sub-Circle.

A Circle may also move its own Defined Roles or Policies into a Sub-Circle, or move any from within the Sub-Circle into itself.

Any of these modifications may only be done via the Governance Process of the Circle.

Beyond these allowed changes, a Circle may not modify any Defined Roles or Policies held within a Sub-Circle.

**Comment by julianeroell** [comment]
That makes sense to me. I committed a proposal (see above).
