### ISSUE TITLE
Confusion in 2.6.4 Rep Link to Super-Circle

### ISSUE THREAD

**Issue by bernardmariechiquet** [holacracyone/Holacracy-Constitution#55]
"However, this election is not required when a Circle lacks any Core Circle Members other than those serving as Lead Link and Cross Links into the Circle. 2.6.4 Rep Link to Super-Circle"
Does this mean that even if there are Defined Roles in the Sub-Circle that are filled by the same persons that those filling either Lead Link or Cross Links Roles, there would not be a Rep Link?
If answer is yes, then my question is Why?
My take on it is that in such a case, there would be a need for a Rep Link as there are Defined Roles.

**Comment by brianjrobertson** [comment]
That's what it means... there was a case behind it where this was useful, and I don't think the rep link is needed in this case, but I'm not going to describe it all here because I think much of this section will go away or get heavily reworked in v5 anyway, given other planned changes...
