### ISSUE TITLE
Allow Facilitator & Secretary to preside over integration outside of meetings

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#59]
As a role-filler of a role where governance requires me to integrate objections from other roles for certain operational decisions, I'd like to be able to rely on the Facilitator and Secretary to hold a more formal IDM process with those other roles if needed (including testing objections), so that I can get the rigor of IDM outside of governance meetings for those operational decisions that do require integration across roles.

**Comment by brianjrobertson** [comment]
Implementation here should be pretty straightforward:  Just need to clarify that if governance demands integration for an operational decision, then the rules of Article 3 apply: the Facilitator can be asked to facilitate the decision-making process (but only if requested from the role-filler seeking integration), the process breakdown rules can be used if needed, etc.

**Comment by MiekeByerley** [comment]
Hmmm, I can understand the principle and the desire to use the IDM, but would it not be possible to use an Advice Process ( I am aware you stepped away from this) for this? I am trying to keep in front of me the Cynfin Framework of decision making here, and mindful of using the appropriate tools for the differing contexts. By doing this are we not running the risk of defining processes to the extent of constraining individual human decision making? This would also relate to your Multi-filled Role issue, your Cross-Link is the mouth for the Multi-filled role elected by the other members thereby vested with the authority to integrate etc on their behalf. An advice process should be used on the part of the Cross-Link in doing this as well, lets face it if they don't they won't be the Cross-Link very long. My thoughts only, but you should be able to run the IDM next to the Advice Process and other decision making frameworks depending on context, this will give you greater diversity and more Natural Process Agility.

**Comment by brianjrobertson** [comment]
Not sure I fully understand where you’re coming from here; you can setup whatever required advice process you want via governance, so that’s all already possible.  This issue is just to ensure people can rely on accountabilities of the elected Facilitator and Secretary outside of formal meetings, should they choose to setup an operational decision that requires IDM.  It doesn’t preclude a circle from setting up governance to rely on a different process for some operational decisions.

**Comment by MiekeByerley** [comment]
Ah, would this then entail a facility within the Tactical Meeting to use IDM? Or are you thinking more along the line of using IDM outside of Governance Meetings altogether beyond that stated in Sub-Section 3.2.1? With the express expectation that when done so the Facilitator and Secretary would need to be engaged under all circumstances of IDM regardless of context?

**Comment by brianjrobertson** [comment]
> Ah, would this then entail a facility within the Tactical Meeting to use IDM?

That's not an intended effect, although someone could easily interpret this as allowing that.

> Or are you thinking more along the line of using IDM outside of Governance Meetings altogether beyond that stated in Sub-Section 3.2.1?

That's right - this is to cover cases where the acting governance requires integration around an operational decision.

> With the express expectation that when done so the Facilitator and Secretary would need to be engaged under all circumstances of IDM regardless of context?

No, the intent isn't to require them to be engaged, just to allow others to rely on them for it if desired/needed.

**Comment by LouisChiquet** [comment]
Considering that the Facilitator and Secretary in [Appendix A](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Appendix-A.md) now have as accountabilities “_Facilitating the Governance Process and Tactical Meetings of the Circle or for its Roles_” and “_Scheduling Governance Meetings and Tactical Meetings of the Circle or called by its Roles, and notifying all invited participants_”, “_Capturing and publishing the outputs of Governance Meetings and Tactical Meetings of the Circle or called by its Roles_” respectively (following the new possibility of calling tactical meetings by any role and inviting any roles) does this treat that issue, or did I misunderstood the issue?

My interpretation is that, with the “_its Roles_” it covers your issue, but maybe not?

**Comment by brianjrobertson** [comment]
That does indeed cover some of it @LouisChiquet, but we still need to clarify that the rules of governance still apply to operational decisions requiring integration.

**Comment by brianjrobertson** [comment]
Hmm, on further thought, I think that might actually be enough; it does leave something up to interpretation for sure, but I think the slight downside of that ambiguity is more than balanced by having one less section/rule to deal with in the constitution.  And the ambiguity can be resolved by either a secretary interpretation or by governance, so it's not a major block even if it becomes an issue.  Okay, I'm going to call this issue implemented given the broader Facilitator accountability for facilitating the governance **_process_** (not just governance meetings).
