### ISSUE TITLE
Is requirement for regular governance meetings needed?

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#60]
Currently, the constitution requires each circle schedule "regular" governance meetings; the frequency is left to the Secretary, and a Secretary could decide that monthly, quarterly, or even annually is appropriate.

A question has surfaced several times now about whether this requirement gets in the way and should be removed.  For example, in circles with more experienced practitioners, I sometimes feel that it'd be more efficient to just deal with tensions via asynchronous proposals until a special governance meeting is actually requested.  As another example, one company had a circle that wasn't actually doing much operationally itself, but just acting as a holding grounds for its various sub-circles, so they didn't want governance meetings except when someone actually requested one.

The challenge is, for inexperienced practitioners, regular meetings help tremendously - people are unlikely to call for a governance meeting before they get in the groove of tension processing via governance, yet when there's a regular meeting, they often try it out and learning happens (for both them as Holacracy practitioners and the circle via the resulting governance changes).  Is there a danger that these important governance meetings for novice practitioners just won't happen if the "regular" requirement were dropped, and thus novice Secretaries felt more comfortable just not scheduling any?  Or is it that just a training/coaching burden, to add to the already-long list of other points a novice Secretary (or any role) needs to understand?

Thoughts?

**Comment by julianeroell** [comment]
The requirement / constitutional expectation that "regular" meetings happen has been bugging us for some time. Removing it would make things much easier: there are many good cases where deviating from "regular" makes sense, and very few (IMO) where "regular" must be forced. 

This seems safe to me: When someone on a circle senses that regular meetings may be useful or necessary (e.g. for the reasons you mentioned above), they can always propose a policy for this.

**Comment by madeangelo** [comment]
Maybe the guidance should be added to the habit app. Remove the "regular" from the constitution and add it to the habit app. This would reinforce the best practice for new circles but allow experienced circles to do the work asynchronously.

**Comment by brianjrobertson** [comment]
Hmm, perhaps a middle-ground path here would be to keep the "regular" language, but add something like "whenever the Secretary decides is appropriate", to be clear that it does need to happen "regularly", but the Secretary can still decide when those regular meetings should happen?  Those two almost contradict, but perhaps that's helpful here, to clarify that both are true...

**Comment by julianeroell** [comment]
In my view, the simpler the constitution, the better. This allows for other roles or policies to emerge that take care of the different needs e.g. around "regular" meetings. (E.g. we have a role that takes care of inexperienced Holacracy practitioners. This role can request meeting scheduling from the Secretary if they find it useful or necessary.)

Or, more fundamentally: in this area of the constitution, I think it should be less "opinionated" about what "good practise", necessary elements are, but leave it to the practising organisation (its culture & its Secetary's judgement) how to properly enact the Governance process.

**Comment by brianjrobertson** [comment]
Tony's suggestion:  "i would suggest that once there has been an initial governance meeting, then regular governance meetings (maybe suggest quarterly minimum) are required. but initial governance meeting would not be required, unless requested by an existing circle member."

**Comment by smichel17** [comment]
@brianjrobertson How's this for a middle ground? Remove the 'regular' requirement altogether, but specify that all new circles come with a policy that requires regular governance meetings -- a policy that can later be removed through the regular governance process.

**Comment by brianjrobertson** [comment]
Dropping the regular requirement.
