### ISSUE TITLE
Allow Circles with no Lead Link

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#61]
As Constitution Steward, I'd like a general way that circles can be formed and operated with no lead link to govern cross-stakeholder processes, so that the special-case exception allowing an Anchor Circle with no lead link can be replaced by whatever general pattern it is a special-case expression of.

_And, another story pointing to the same implementation I think:_

As the Lead Link of a Circle that has some processes and property to govern that are also highly intertwined with an external party (perhaps a circle within my organization, or one in another organization), I'd like to be able to form a new sub-circle in collaboration with that other entity and cede some control from each founding circle into it, yet without the new sub-circle needing to be fully "owned by" or contained within either founding circle, so that we can form joint ventures of various sorts to govern shared interests via a cross-cutting circle, without having to create a new entity and adopt the constitution separately for it (we'd currently have to do that to be able to each appoint cross-links to its Anchor Circle; and even if we did do that, it's still largely unclear how we delegate some of our control to that new entity and how it can influence us back across that boundary).

**Comment by brianjrobertson** [comment]
Some implementation notes/details:

• If the "founding circles" described in this story appoint roles as Cross Links into the new cross-cutting sub-circle, that sub-circle can then add accountabilities to them and those accountabilities will still be expected by roles in the founding circle.  This allows, for example, delegation of a process to a sub-circle, perhaps made of roles from many parts of the organization, and gives that sub-circle the ability to partially govern those roles as-needed for its purpose, in addition to the circles that created those roles.

• This should remove the current inelegant and weird rule that sometimes allows a circle with no Rep Link in [§2.6.4](http://www.holacracy.org/constitution#art264), as this achieves the same thing but is more symmetrical, as the circle would have no lead link and no rep link, just cross-links in from the founding circles (and perhaps others?).

**Comment by brianjrobertson** [comment]
Another note:  Once issue #57 is implemented, we could perhaps implement this story as just a circle having multiple Lead Links appointed from different circles (or even the same), and use the rules for multi-filled roles added by #57 to achieve the same effect as the current special-case rules in Article 5 for integrating across multiple Cross Links when a circle has no Lead Link.  Although that would challenge our current mental model around what a "lead link" is, it would likely simplify the implementation of this story quite a bit, and move us one step closer to obsoleting Cross Links entirely as a separate construct, which I think would be a huge positive if done right.

**Comment by julianeroell** [comment]
:exclamation: to your third comment, Brian! I think this is the way to go: Obsolete Cross-Links, and allow for Multi-Assignment of Lead Links. Love the possibilities of cross-organisational collaboration that this offers!

**Comment by dlocke** [comment]
@martinroell I think that section 2.6.3 already allows the Lead Link role to be filled by multiple partners.

**Comment by brianjrobertson** [comment]
@dlocke:  That's actually entirely unintentional, although I see why it could easily be interpreted that way...

**Comment by brianjrobertson** [comment]
#186 would actually address part (but not all) of the felt need for lead-link-less circles...

**Comment by brianjrobertson** [comment]
I believe the newly implemented capacity to have multiple lead links (with the new and forthcoming clarity on how multi-filled roles work) has removed most of the need for this feature, except for some of the latter half of the original post.  So, I'm closing this issue, and have opened the new issue #236 to capture the remaining part needed here.
