### ISSUE TITLE
Allow "Holacracy Lawyers" to represent roles

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#62]
As a partner trying to process a tension, I'd like to be able to invite someone else to represent my role (both operationally and in a governance meeting) and help me process the tension, so that I can engage someone more experienced with Holacracy's rules to be my "Holacracy Lawyer" and help me get my tensions processed.

**Comment by brianjrobertson** [comment]
I'm a bit concerned about this one and what it might lead to, so wondering what constraints are needed to keep it safe enough to try...  or if it should be cut entirely and first tested as a constitutional amendment somewhere before constitutional integration.  That said, it's not that different from what a Rep Link does already, and the same restrictions that act on a Rep Link should be relevant here.

As an example of where the need for something like this has shown-up: imagine a restaurant where the wait-staff has a high turnover and limited capacity to learn to engage effectively in Holacracy's governance process, yet definitely have tensions worth processing.  Or, a brand-new partner in a mature Holacracy practice, who needs some help while learning the system...

**Comment by julianeroell** [comment]
Very interesting! I know a few people on my team who would _love_ this! Seems safe to me, but I am curious to hear perspectives on what might be dangerous with this.

**Comment by dlocke** [comment]
I'm not sure that a constitutional amendment is needed to implement this.  Sections 3.2.2 and 3.2.4 allows for another partner to be granted permission to submit a proposal and object on behalf of another role in governance meetings.

For tactical meetings, Section 4.2.3 states that, "the Facilitator processes agenda items by simply allowing the agenda item owner to engage others in their Roles and duties as desired, until a path for resolving the Tension is identified."  I think that this is broad enough to allow a tension sensor to engage a "Holacracy Lawyer" role as part of resolving the tension.

Is there something that I'm overlooking?

**Comment by brianjrobertson** [comment]
@dlocke:  Those clauses you reference don't give the person the right to bring someone else into the meeting who isn't already invited (i.e. who isn't already a Core Circle Member); the proposed change here would allow for that...

**Comment by smichel17** [comment]
@brianjrobertson @dlocke Yes, but you could create a 'holacracy lawyers' circle in the anchor circle, then create cross links to it in every other circle.

**Comment by brianjrobertson** [comment]
@smichel17:  That wouldn't achieve the desired result here, of letting a "Holacracy Lawyer" represent a role in its own governance meeting.

**Comment by smichel17** [comment]
@brianjrobertson As I understand it cross links are by definition core circle members of their respective target circles, thus are invited to governance and tactical meetings -- even though they wouldn't actually attend unless needed -- and then may represent members of those circles the way @dlocke proposed.

I'm not sure what I'm missing here? I admit I have not been to any Holacracy trainings -- only done a significant amount of internet research -- so my reading of the constitution may not be (read: almost certainly isn't) in line with its intent... but I think right now we're debating on the "is it possible?" level, not the "is it intended?" one.

**Comment by brianjrobertson** [comment]
@smichel17 Ah, you mean cross links _from_ (vs. _to_) the Holacracy Lawyers circle into every other circle.  That would mostly do it, yes (though it's weird/complex enough that a more direct route is still indicated).  It still wouldn't let the Holacracy Lawyer and the actual proposer both act as Proposer at the same time in one proposal (e.g. both answer Clarifying Q's, both talk during Amend & Clarify) - but that brings up the broader question: is that more useful or harmful to the process?  I'll need to reflect on that further myself...

**Comment by brianjrobertson** [comment]
As of https://github.com/holacracyone/Holacracy-Constitution/commit/9b8a1614984fa90cfd3bd13d014af9da7213b262 this is now effectively possible by assigning someone to a Role as a Role Supporter (who thus becomes a Rep Link for the Role and can represent it but without any duties); or, if the goal is to allow anyone to pull in a "Holacracy Lawyer" without needing a Lead Link role assignment, then that's possible via a policy that allows the Role Lead of any Role to themselves assign a Role Supporter for their own Role, perhaps just from among the role-fillers of a Holacracy Lawyer role...
