### ISSUE TITLE
Allow expressing intent to count as getting no-objections to impact Domain

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#64]
As a partner in a Holacracy-powered company, I'd like to be able to express my intention to take some action (via writing in an appropriate and customary forum), and after a reasonable delay have that count as getting no-objections from any role with a relevant domain that would be impacted by the intended action I've shared, so that I don't have to figure out exactly what domains my action would impact, and to further encourage a culture of self/role-leadership and empowered entrepreneurial action-taking over asking permission.

Note:  H1 has had a policy to this effect for a little while now; it reads:

> Normally, you need permission to impact the Domains of other roles via your actions, per Constitution §1.3. However, for the purpose of §1.3, you are automatically considered to have explicit permission to impact all relevant domains via an action, if you share your intent to take that action in advance and no one with a relevant domain asks you not to within a reasonable timeframe. However, to count as getting permission under this rule from a given individual, your intent to act must be shared via a standard written communication method customarily used for sending messages to that individual.

**Comment by julianeroell** [comment]
This would very much simplify onboarding of new partners: Instead of teaching "before taking an action, you must check domains: use search in glassfrog, and _my authority_ and in doubt ask the Secretary", we could teach: "If in doubt: announce your intent, wait a bit, and go for it."

**Comment by djwork** [comment]
I like this but can it be combine with a default domain (ie Intent Publication) so that organisation specific tensions such as how and when a partner should broadcast can be defined via governance?

**Comment by brianjrobertson** [comment]
Not needed - you can already use the default domain on all circles to govern that...

**Comment by smichel17** [comment]
This seems like an elegant solution, but you need to make sure intent expressions actually get seen by the roles with relevant domains. This is a two-part challenge:
1. [Easy] Intents need to go somewhere that roles with relevant domains can look at, and decide whether the intent impacts their domain and is acceptable.
2. [More difficult] In your quest to achieve (1), you need to make sure you're not adding too much spam processing to the queue of any role with a domain, as you scale to a larger company.

This is a purely theoretical tension at this point, so this is not a valid objection. More of a thing to be on the lookout for.
