### ISSUE TITLE
Expand Policy definition to cover stuff besides grants/constraints of authority

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#67]
The definition of Policy is limited to a grant or constraint of authority, to filter out things that should really be accountabilities or agreements between people (or people and organization).  However, the constitution defines other decisions that it claims are Policies but which don't clearly fit this definition, such as using a "policy" to encode a decision that could be made by a lead link, or changing the tactical meeting process via a "policy", or setting a time-limit for responding to asynchronous governance proposals in a "policy".  The definition of policy needs to be expanded to allow for general "rules" like these, while still preventing accountabilities and other undesired constructs from sneaking into policies.

**Comment by brianjrobertson** [comment]
Ensure the solution to this removes the need for this specific rule (or re-add it somewhere if it doesn't):

> A Policy of a Circle may constrain Role assignment within that Circle and within Sub-Circles, recursively.

**Comment by brianjrobertson** [comment]
Ensure the solution removes the need for these two lines:

- Solely for the purpose of limiting a Circle’s own Roles, each Circle has an automatic Domain over its own internal functions and activities.
- Like a Circle, a Role also holds an automatic Domain over its own internal functions and activities, which may be governed by Role Leads solely to constrain the authority of the Role's Role Supporters.

**Comment by bernardmariechiquet** [comment]
@brianjrobertson What do you need here? Not clear enough for me helping here on such interesting matter.

**Comment by brianjrobertson** [comment]
I'm actually working on this now; as soon as I submit something, I could definitely use a review and any feedback that surfaces for you.

**Comment by brianjrobertson** [comment]
@bernardmariechiquet If you have a chance, take a look at what I just submitted, and let me know what you think, and if you see any issues or possible improvements.
