### ISSUE TITLE
Add Coaching accountability to Facilitator role

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#70]
As a new Holacracy practitioner, I'd like to be able to expect the elected Facilitator to provide some Holacracy coaching during meetings, so that I can rely on them not just to hold to due process, but also to help me learn that process and how to use it effectively.

**Comment by julianeroell** [comment]
I resonate with the user story you posted, Brian. At the same time, as an overwhelmed Holacracy-experienced person in my organisation, I would also like to be able to nominate a less-experienced person as Facilitator, knowing they can _facilitate_ well, and can rely on a different role (we call it "Holacracy Coach") to provide coaching, when that becomes necessary.

Basically: a default accountability for coaching on the Facilitator would be difficult for us. We'd need at least a possibility to remove that accountability, or to override it somehow.

**Comment by bernardmariechiquet** [comment]
I fully agree on that one Brian and would add same expectation on Secretary Role.

**Comment by brianjrobertson** [comment]
@martinroell:  Hmm, I don't think it's practical for the Facilitator **_not**_ to have that expectation - they've got to do at least some coaching during a meeting with novice practitioners, or it blocks tension processing.  You can always have a separate coach role, but I think it kills the governance process if the facilitator doesn't at least try to give some coaching when needed...

**Comment by julianeroell** [comment]
Yes, that makes sense to me. No objections. ;-)

**Comment by dlocke** [comment]
Brian,

I'm trying to envision how this would end up working out in a bootstrapped implementation of Holacracy.  I'm not sure if this "new" accountability would be harmful or helpful but since I'm not practicing Holacracy yet, I can only rely on speculation.

Do you think that this change would be helpful or harmful to an organization that tries a bootstrapped implementation of Holacracy?

David

**Comment by brianjrobertson** [comment]
@dlocke:  Should be helpful...

**Comment by andreafare** [comment]
For the "in meeting" part of the coaching I would clarify that it must be constrained to timeouts, and specify timeouts must be asked for by using an agreed upon signal.

**Comment by brianjrobertson** [comment]
Some facilitator coaching does happen in-meeting/in-flow, so not sure that would make sense...

**Comment by andreafare** [comment]
... looks like my comprehension of "in meeting coaching" is flawed then, sorry.

**Comment by fardrum** [comment]
OK now i get it! thanks Brian for dedicating time to this specific topic in the training.

**Comment by andreafare** [comment]
Now I get it, thanks for focusing on this specific topic during the training Brian.
