### ISSUE TITLE
Shift metrics definition from Lead Link to any Circle Member

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#73]
As a Circle Member, I'd like to be able to ask a fellow circle member to regularly share data via metrics, in the same way I can now for Checklist Items, so that I can get my role's goals met without needing lead link intervention when I need to see regular data from another role.

_And:_

As Constitution Steward, I'd like the same mechanism to be used for requesting ongoing reporting of both Checklist Items and Metrics, so that the constitution is simpler and Holacracy easier to learn, and so that the mechanisms become as similar as the conceptually equivalency of these two information sharing pathways.

**Comment by djwork** [comment]
Can requesting checklist items and metrics of other roles be part of the governance IDM?

So that the role (being modified) can object / integrate tensions created by the change (if any)?

**Comment by brianjrobertson** [comment]
@djwork:  Try submitting a different issue to discuss that...

**Comment by ebabinet** [comment]
@brianjrobertson I worked in an organization where we created a policy to allow roles other than Lead Link to request Metrics, so I like the idea of the mechanism being the same for both Checklist Items and Metrics. They're both just data, although tracking of Metrics can create more work than Checklist Items. 

The mechanism for requesting Checklist Items and Metrics seems similar to that of requesting Projects and Next actions described in  [4.1.2b](http://www.holacracy.org/constitution#art412) and I'd like to see a bullet added to that Duty of Processing section to cover them. (e.g. If you deem it a reasonable Metric or Checklist Item to take on, you must accept it and report on it during Tactical Meetings. If not, then you must explain your reasoning, or report on a different Metric or Checklist Item that you believe will meet the requester’s objective.)

**Comment by gmitterer** [comment]
@brianjrobertson I think this would be very useful based on our experiences as well. The more it tackles a related issue that it is for many people actually not clear now, why only the Lead Link has the authority to add metrics, since it is not a domain of that role. I hear that question very often.
