### ISSUE TITLE
Obsolete Cross Links

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#74]
As Constitution Steward, I'd like to obsolete Cross Links as a distinct third type of link, without losing any needed functionality, so that the constitution is simpler, Holacracy practice is simpler, and common bad habits with overuse of Cross Links are avoided.

**Comment by brianjrobertson** [comment]
Some notes:

• In many cases, the "Cross Link Role" is really just a normal Defined Role, so in that case we can use existing rules but simplify the language and not refer to them as a "Cross Link" to avoid confusion (this will also make more sense in the context of Issue #61 as well).

• When the Cross Link Role is representing a whole circle or an external group, I think we can just generalize the Rep Link role very slightly and call it that, so Rep Links are about representing one circle/group within another, and not solely for representing a Sub-Circle in a Super-Circle.

• In the case of the Anchor Circle (or possibly other circles, per Issue #61), we can either structure that as a circle having multiple Lead Links or multiple Rep Links to the circle, and then use the rules defined per Issue #57 to cover how that works.

**Comment by julianeroell** [comment]
This is a very interesting idea! I don't have a concrete idea of his this could be implemented yet, but I would be happy give feedback to or collaborate on some else's first draft!

**Comment by smichel17** [comment]
@brianjrobertson could you provide an example(s) of where cross links are commonly overused?

**Comment by smichel17** [comment]
Depending on your answer to the question above, I have a possible implementation:

A Link becomes a special type of role, responsible for channeling tensions to/from an entity outside the circle. A Rep Link (easily abbreviated to "Rep") becomes a specific link: the one to the super-circle.

**Comment by brianjrobertson** [comment]
@smichel17, re examples:  Don't have time to document examples here, but it's a common issue in implementations - if you post the question in the Community of Practice, others may be able to offer some examples or general coaching around it.

**Comment by julianeroell** [comment]
One current thread about the topic is at http://community.holacracy.org/topic/cross-link-good-bad-and-ugly

**Comment by MiekeByerley** [comment]
I like the idea of the Cross-Link and have seen it as a vital function, however I have also discovered that there is vague guidance and context around it enabling abuse/over-use of the role. 

Rather than getting rid of it maybe a revisit to the original Intention of the role needs to happen and a tightening of the Domains, Accountabilities and Purpose of this role Type needs to be defined. Simplification is good but oversimplification is going to cause more harm than good. Remember Diversity is important even if initially it is a little complex to get around.
