### ISSUE TITLE
Add default hiring/firing processes

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#78]
As a Ratifier, I'd like the constitution to include clear default processes for how partners can be brought into and removed from my organization - ones that scale to any size company and don't require a huge change process to enact immediately upon adoption - so that we're not left relying on our legacy hiring/firing processes and the shadow power structure they create.

**Comment by LouisChiquet** [comment]
For the firing part, I feel like it's a bit similar in terms of cons then issue #203, which is that naturally you have legal restraint on this. For instance, you can't fire someone (at all) from a Public Administration in France, or you have a long and many criteria for some other companies, and it's really something very much regulated in France (with risk of Prud'Homme and other associations if handled “badly” or even just “not conventionally”).

For the hiring process, I'd be open. However I always have this feel like that, Holacracy is really about Governance and how to organise things, not defining the process, but in the other way, with 5.0, you have a spending process per default so would make sense, but again no, as it's only addressing issue for the roles, it's not like talking about Humans (at least not in the HR way in my thinking), so I have mixed feelings on including this in the Constitution. I'd be curious to know if you have some cases inciting an org to call for having a hiring process per-default in the Constitution, knowing that already now many apps exist?

**Comment by brianjrobertson** [comment]
I'm dropping this one; on further reflection, I'm not seeing a strong enough argument to include this at the constitutional level, given that it can easily be done via apps in the initial structuring.
