### ISSUE TITLE
"must"

### ISSUE THREAD

**Issue by KoenVeltman** [holacracyone/Holacracy-Constitution#8]
What about taking out the word "must" throughout the whole constitution?

There are very few things in life you really must. It always comes down to your personal powered "choice" (although recognizing we must to go the bathroom every now and then, but cannot come up with anything else  yet..)

Sentences like "You must regularly consider how to complete each project you are actively working towards for your role, including by defining any Next-Actions useful to move the project forward"in 1.2.3 reads a lot more enaging when it starts with "You regularly consider...". and probably doesnt reduce the likelihood people actually take action on what now is a "must".

**Comment by djwork** [comment]
For me the "musts" are part of the "good fences make good neighbours". Yes it is not nice when "musts" are directed at me personally but the knowledge that the same "musts" apply equally to all other members of the organisation is reassuring.

**Comment by mileslasater** [comment]
Alternative suggestions for alternatives to "must":

You are "expected" to
it is your "responsibility" to do...

**Comment by julianeroell** [comment]
I find "must" very clear. Because, in fact, you _must_ do x, y and z (follow the constitution) if you work in our organisation. If you don't, I fire you. :-) "Must" is clear: you _must_ do it. If not: clear, and sharp consequences. 

"You are expected to" is more vague. It would suggest to me that if I did not do it, there might be consequences, or there might be not. This is not what I'd like to see the constitution express. I would like to see it as sharp as possible in the places where it... must. Ehm. Needs that. Where that is useful. :-)

**Comment by djwork** [comment]
I'm with @martinroell on this except I think "your responsibility" is getting close enough. If I am responsible for something and I don't do it I know I am in for a negative outcome.

**Comment by brianjrobertson** [comment]
While I agree that "must" is really weird unless someone has agreed to the requirement in the first place, that's part of the intended use of the constitution in an organization - you need people to agree to follow its mandates, and once they do, "must" seems appropriate here (e.g. all of our partners sign an agreement upon joining that they will follow the constitution's rules and abide by those "musts"; other organizations really need something similar).  Although, I do see that "your responsibility is to" works as well, but it's replacing one word with three, which generally seems like a move backward unless there's a really strong reason to.  Anyone else have thoughts/pitches here?

**Comment by KoenVeltman** [comment]
thanks all for the comments. What I like about it and think we all resonate with is that the constitution should be simple in its language (eg not increase the number of words) and extremely clear in its expectations. 

what the dictionary says about the auxiliary verb "must": to be required or compelled to, as by the use or threat of force, to be compelled to in order to fulfill some need or achieve an aim.

What Brian describes as "weird" to me means the difference between powerful language and forceful language. And typically forceful language is not experienced as powerful although it is intended in that way. Think about a parent-child relationship. We just dont like foreceful language. Although it is clear you really would like to forget it. Humans typically also easier follow powerful language and typically tend to disobay foreceful language. Thats exactly what we intend to free organizations of in the function managers used to play and the mindset managers typically have. 

Here another three ideas to replace "must". Lets test if these are a step forward:
1) the preamble addresses primarily the organization's "ratifiers". and only in a by sentence "anyone else". What about making "anyone else" more explicit to follow the constitution and have them sign it as well? In an Holacracy implementation I typically see the owner of the business sign/adopt the consitution. why not everybody?

2) Paragraph 1.2 already states "As a Partner of the Organization, you have the following responsibilities for each role you are assigned to." What could we add there that creates additional clarity that all the articles here are expected of you? When that is clear from the start the partners of an organization will read and accept the rest of the requirements to energize a role naturally. And must is not needed going forward. Resulting in more powerful language instead of forceful language. 

3) make the effect of not doing this explicit. eg what is the escalation route of not conforming the consitution? that creates real choice. eg does it go to the lead link to evaluate if you fill the role properly? is it brought up as tension in governance? knowing the consequence typically creates more energy to do something than being told "you must".

**Comment by brianjrobertson** [comment]
Okay, thanks for that pitch - I'm sold on reducing the usage of "must" wherever practical, and replacing with something like "You are responsible for" or something similar.  I'll queue up an action to do that and submit.

**Comment by brianjrobertson** [comment]
Just submitted changes to dramatically reduce usage of "must".  I'm closing this issue, but any further feedback/reactions are welcomed...

**Comment by julianeroell** [comment]
I very much dislike this change. What was sharp and clear now seems vague to me.
