### ISSUE TITLE
Multi-Level Circle/Role Movements

### ISSUE THREAD

**Issue by bunchbunchbunch** [holacracyone/Holacracy-Constitution#80]
2.6.1 Currently specifies a process for moving a circle/role into a sub-circle.  My belief is this section technically breaks true self-organization, but necessary for efficient practical changes to governance.  At Zappos we have experience a big need for this to extend to Multi-level moves.  Lets look at the example of a circle from 4 levels down one circle structure that wants to move 4 levels down in another circle structure and there are no objections sensed anywhere in the organization.  Processing this given the current 2.6.1 would be very challenging.

**Comment by tensiondriven** [comment]
Adding section 2.6.1 for context:

```
2.6.1 Modifying Sub-Circles

A Circle may modify the Purpose, Domains, or Accountabilities of a Sub-Circle.

A Circle may also move its own Defined Roles or Policies into a Sub-Circle, or move any from within the Sub-Circle into itself.

Any of these modifications may only be done via the Governance Process of the Circle.

Beyond these allowed changes, a Circle may not modify any Defined Roles or Policies held within a Sub-Circle.
```

Link: https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#261-modifying-sub-circles

**Comment by brianjrobertson** [comment]
So, how should this work?  Anyone have ideas on how to resolve this tension with minimal risk of a super-circle mucking in the structure of sub-circles?

**Comment by Roflcopterpaul** [comment]
I personally feel that if both the Lead Link and Rep Link of every Circle in the chain have no Objection to the move, it is perfectly fine. This could be handled like special governance (Slack, e-mails, etc.) between just those individuals. If someone objects, it must be handled through individual Governance meetings of each Circle in the chain (or at least for the pieces of the chain that objected).

This allows a quick way to move Circles across even large organizations, but still ensures proper and fair representation from every single Circle involved so that it is not a matter of top-down control.

**Comment by bunchbunchbunch** [comment]
I agree Paul's thoughts on this.

**Comment by brianjrobertson** [comment]
My intended implementation:  Allow proposals that impact multiple circles at once, via async or special real-time governance meeting, with every circle member of every impacted circle invited to participate (but a special clause allowing a Secretary to decline scheduling a real-time one if it would have too many people to be productive); define a multi-level role/policy move as a change that impacts every circle the role/policy is moved across, and thus requires no-objection from everyone in all of the circles it moves across; then let technology automation (e.g. GlassFrog async governance) handle the work of getting a proposal to all the relevant circles and making it all happen.

Reactions?

**Comment by brianjrobertson** [comment]
Note also this change: https://github.com/holacracyone/Holacracy-Constitution/commit/81dba62740544dc396627cf41a473c229aa0e3f6

That added threshold would still need to be met as well.

**Comment by karilen** [comment]
Why not just let the links do the hard work of weighing in on the governance change...if there is notice then a role filler can go to their rep link after all...

**Comment by brianjrobertson** [comment]
Until we find cases where more than this is needed, I decided to go with a simpler solution of just allowing multi-level moves with a normal governance proposal and no one extra from sub-circles involved (at least those that meet the added threshold in the change linked above).  Of course the Circle Lead or Rep Link from the immediate Sub-Circle could certainly choose to invite someone else from further in/down the holarchy to join the meeting to process that proposal, or get their input first.  But I'd like to keep it simple until we know a more restrictive process must be constitutionally required.
