### ISSUE TITLE
Tighten language to clarify Lead Link can't remove circle policies outside of governance

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#81]
Per this thread:
http://community.holacracy.org/topic/changes-to-policy

**Comment by tylerdanke** [comment]
per that thread the original poster was using version 4.0 of the constitution. Martin Roll says Ryan, you seem to be using an older version of the constitution (version 4.0?). In Version 4.1, section 2.2.1 simply reads:

"Further, the Lead Link may not define Policies that limit the Circle’s Roles, except via the Governance Process of the Circle."

(Which, I think, still has the ambiguity that you found, but is slightly clearer to me in its meaning.)

**Comment by smichel17** [comment]
@brianjrobertson Can this issue be closed, then?

**Comment by brianjrobertson** [comment]
No, while the language is simpler, I think the issue still exists.
