### ISSUE TITLE
Need for more clarity

### ISSUE THREAD

**Issue by bernardmariechiquet** [holacracyone/Holacracy-Constitution#85]
In Section 3.4.3 , I don't get the meaning of last sentence ".**Once contradicted however, the new logic and interpretations become the acting standard that all future rulings must align with.**" and the key I don't get is the sense of "however". and the "new" of "new logic". Does it mean that even if there is a contradiction based on a compelling argument - all future ruling should align only with what is already published without taking into consideration the new argument.

_3.4.3 Interpretations Become Standards

After ruling on an interpretation, a Secretary may choose to publish that interpretation and the logic behind it in the Governance records of the Circle. If published, the Secretary of that Circle and the Secretaries of any contained Circles are responsible for attempting to align any future rulings with the previously published logic and interpretations.

A Secretary may only contradict previously published logic or interpretations once a compelling new argument or circumstance supports a reversal.**Once contradicted however, the new logic and interpretations become the acting standard that all future rulings must align with.**_

**Comment by Roflcopterpaul** [comment]
Bernard, I believe what this means is that if a Secretary makes a new ruling about what something means, that becomes the "law" from then on. Say I create a Policy and the wording is iffy. The Secretary may say, "That is NVGO for reason X." After that meeting, the Secretary publishes the ruling for all to see.

For all future proposals, if "reason X" is in play, we have to use the same reasoning as the Secretary's last call that was published. Say in a future meeting, I were to say, "Oh, here is another way of looking at that, actually." The Secretary may then change their mind and decide that makes more sense, which we shall call, "reason Y". That is where this comes in:

**Once contradicted however, the new logic and interpretations become the acting standard that all future rulings must align with.**

Now that the Secretary has made a ruling (reason Y) that contradicts a previous ruling (reason X), they cannot go back and change their mind to the initial reason. So, if we have yet another meeting and this situation comes up a third time, the Secretary would have to go with the latest interpretation provided (reason Y) (unless entirely new information became present that made the Secretary change their mind back).

This is essentially to prevent Secretaries from going back and forth on what things mean, to help ensure fairness in how things are interpreted and alignment within Circles. That is my thought behind it, anywho. Hopefully this helps (and is correct)!
