### ISSUE TITLE
simplify "abandon" description

### ISSUE THREAD

**Issue by KoenVeltman** [holacracyone/Holacracy-Constitution#88]
would it be possible to simplify the language of the "abandon section". The tension I have is that at the start of an implementation I ask a "CEO" to sign the constitution without him having read it (and potentially understood it, or seen the value of it). Which for many then doesn't make sense to sign it.

So either they rubber stamp it (degrading the value/meaning) or they wait with signing till a successful pilot emerges.

What would solve it is to make the section on abandoning Holacracy much simpler. so that a "CEO" can understand what he signs up for (and what he is allowed to do to get out of it) without understanding every clause in the constitution he signs.

**Comment by julianeroell** [comment]
Koen, which section do you mean? 5.5, "Constitution Amendments and Repeal" says:

> The Ratifiers or their successors may amend this Constitution or repeal it entirely, using whatever authority and process they relied upon to adopt it.

which seems pretty clear to me. What would you like to see simpler?

(I think I understand your basic point, but the request that you make from it puzzles me.)

**Comment by KoenVeltman** [comment]
Thanks Martin. Lets explore. I like article 5 as it is pretty simple in it's language. 

what could add to article 5.5 is make explicit that temporary repeal or "living above the law" is not allowed. 

what could solve my tension alternatively - and not changing the constitution- is to add the exact text of article 5 to the adoption declaration the CEO signs. And maybe even make explicit the time frame for which he commits to run a "pilot/experiment" with either the full or part of the organization.
