### ISSUE TITLE
simplified simplified language

### ISSUE THREAD

**Issue by KoenVeltman** [holacracyone/Holacracy-Constitution#89]
What would a much simplified constitution read like? 

An analogy I used before is with magnificent work like Adam Smith's "Wealth of Nations". Nowadays the economic concepts are pretty straight forward, but reading his initial work I found pretty incomprehensible. And it takes 100+ pages which is nowadays explained in a few chapters or paragraphs. 

The Holacracy constitution (although existing for several years) is also relatively in an very early phase. And I dont want to disregard the amazing simplification already ongoing (e.g., from 4.0 to 4.1).

What would a constitution read like when it is seasoned and aged? With its text just focused on people who truly understand it and live it.

What I could imagine is that there is a very simple straightforward first 1-3 page section of the constitution that is sufficient for folks working fully with a self-managed mindset and equally supported environment. And a second section that contains all the further detail, caveats, counter-actions, or exceptions which you would only need at the start of an implementation or in abnormal situations (e.g., process breakdowns). 

Alternatively putting some of the details in appendixes could work (e.g., tactical/governance meeting processes, or the election steps). For the people "in the know" the sentence "follow the set tactical and governance agenda's would just do fine.

Sorry to be a bit philosophical. Lets see if we get this one pragmatic.

**Comment by KoenVeltman** [comment]
just adding an additional idea. A simplified constitution could lead to much more relevant apps. For example an "election app". Elections are important to do and to organize properly. But do we need it in the constitution. Can we trust a good Holacratic run organization to just have a working policy that describes how elections are done. Having these core topics as policies instead of constitution articles makes it much more agile, accessible and hence able to evole for a specific organization. 

Does it require a mindset of trust in an organization that with processing tensions they will get it right and these policies do not need to be baked into a heavy format like a constitution?

So in practice what it looks like could be a bare bone constitution with "preferred" apps in the form of policies that you include at the start of an implementation.

**Comment by julianeroell** [comment]
Thank you for putting this out, @KoenVeltman ! I love this thinking and I'd join an effort to come up with a first draft of this! (Off for a holiday now, back in April.)

**Comment by dienkwik** [comment]
Hi, all:

I like the idea of a simplified constitution but I also like all these different thinking that are going on for V5.

One thing that I've found confusing in the current constitution is which part of the constitution can be changed via policy and which part can't or shouldn't or will defeat the whole purpose of adopting Holacracy in the first place.

Perhaps one way is to have the core constitution consisting only of these "should never be changed" clauses, and then have a "Core Defaults Appendix" of the constitution which has all the defaults for all cases that should be there, but can be changed if needed. 
This way, the core constitution would be a lot simpler and shorter, but we will still have all the defaults for when we actually need them.

I'd also really like it if there's some sort of a short Holacracy Manifesto, which contains all the core philosophy that need to be followed when making changes, so that we can gauge whether we are still following the spirit of Holacracy or if our changes are pulling us back to our old ways. 

Thanks,

Dien.

**Comment by KoenVeltman** [comment]
again adding a simplification idea. another way to simplify is to separate articles that describe what you should do vs what you shouldn't do. In the early days of a holacracy adoption an organization probably benefits from reading explicitly you shouldn't do. But a few quarters/years down the road that is obvious to everybody. Just moving all the "shouldnts" to an appendix probably simplifies. For example the lines about that operational points cannot be recorded in governance meeting output

**Comment by brianjrobertson** [comment]
Appreciate these ideas/thoughts all!  I'd love to find ways to simplify the document further, so keep ideas coming if you've got them...

**Comment by brianjrobertson** [comment]
@dienkwik I'll open another issue to specifically cover making explicit which parts can be modified via governance and which can't (or feel free to open that issue yourself if you get to it before I do).

**Comment by KoenVeltman** [comment]
hi @martinroell @dienkwik . Still up to discover what a simplified constitution could look like?

**My intention with a simplified constitution is two-fold:**
- make it easier to read and understand
- allow for further differentiation (with a simplified constitution, more of the current meat of the constitution will be in the active governance of an organization and hence more subject to evolution)

**Just as a side note:** I do find the current Holacracy setup extremely powerful. So for example I dont feel the need myself to have a different check-in round description. But once worked for an organization that by themselves had an elaborate check-in procedure. Which for them was so important that they would have enacted it in their governance records. Or like Blinkist did with their Blinkracy to also consider revising metrics and checklist as part of the organization's structure and hence part of the governance meetings. Or like I understood that Zappos is experimenting how a circle would run without having a lead link.

I don't know if these ideas are better or worse. But by having many of the constitution articles as policies in your active governance you have the opportunity to make it much more your own. (you can of course add policies that alter the tactical/governance meeting process. but then its still separated physically in two different places. and is more an addition than an integration)

**As example lets set a bare minimum for article III Governance:**
_what remains in the constitution is very simple:_
- scope of governance - like in 3.1. but could link for simplicity of what now is in article II structure
- requirement to have a governance process explicit that governs the organization. 'each organization has an explicit described process (f2f, asynchronous or both) described as policy in its anchor circle. The governance process enables every person that fills a core role'

_Whats in the active governance of the circle_ (eg you could just add with a new organization these articles as policies in the anchor circle. together with a policy on the process how to change them and maybe a role that guards/nurtures it):
- 3.3 Governance meeting process
- 3.x Governance asynchronous process
- 3.2 Requirements for changing governance
- 3.4 Interpretations
- 3.5 Process breakdown

_What could a policy look like that safeguards these core policies but does allow for evolution?_ I have a big trust level in people in general. And would go the next step by providing people in their organization more ownership on the rules of the game they play. (and if they want to abuse it they would do it anyway, or drop Holacracy in general)

It just requires a setup that makes it safe enough to try. We could take elements from H1s active governance like how the role Brand strategy needs to integrate objections from all GCC members first (https://app.glassfrog.com/roles/8266) or from the making hard decisions policy (https://app.glassfrog.com/policies/2937002). Or for example create a constitution steward role with at least a few (or a dozen? whatever you like) people fill this role. And create a policy that anyone in this role can propose a "core policy" change, needs to process it in a specifically organized meeting with at least 75% of constitution stewards present, integrate all objections from other constitution stewards, wait for at least 3 weeks to allow for new information to surface, hold a second meeting, and then with no further objections to integrate accept the policy change). Or something else that makes it safe enough to translate these governance articles into the active governance of an organization.

Similarly this was discussed (for better or worse) last night at the UN security council. When the policy of veto rights by the core members came under discussion and the existing powers use their veto right to veto a change in the policy on the use of the veto right.  

**What could the full constitution look like?**
Besides this example of the Article on Governance process. This is what the full constitution could look like.
- _Article A: Structure._ would rather start with the organization's structure. as for me the organization (and its purpose) is more leading than how to energize a role which is currently Article I. But probably include here Article 1.1 on role definition which is a structure thing. 
- _Article B: Energizing roles_ (combine basics of 1.2 and 4.1) rest to active governance
- _Article C: Governance_ see above
- _Article D: Operations_ requirement to have an operational alignment process - and further simplified
- _Article E: Adoption & restoration_Define the starting point when adopting Holacracy that you start with all the policies that currently make the constitution. and that you as an organization are required to have a restoration process when breakdown happens.

While typing it became a rather long post... Thank you for reading this far...
Looking forward to discuss this further!

**Comment by brianjrobertson** [comment]
I'm closing this issue just because it's too broad to be actionable in the current editing process, and the overall goal of the constitution is already as simple as practical without removing the needed guide rails to avoid stuckness/harm; that said, please do submit other more specific issues for any of the ideas presented here that seem worth implementing and we can take each one at a time.
