### ISSUE TITLE
remove "Link" from the title "Lead Link", use "Link" for *inter-circle* only not *intra-circle*

### ISSUE THREAD

**Issue by wolftune** [holacracyone/Holacracy-Constitution#93]
I get that the idea was that roles in a circle all link together to make the circle, but that has basically zero ramifications to anything, it's just poetry.

"Rep Link" is actually connecting two circles. Same with "Cross Link". The term "Link" should be reserved for intra-circle roles.

Thus, drop the "link" from "lead link" and everything is clearer to everyone, especially newcomers.

**Comment by smichel17** [comment]
Additional context: I'm from the same organization as @wolftune. We've just begun the process of implementing Holacracy. I've taken the lead on understanding Holacracy clearly and training the other team members.

When explaining, we felt like these three names did not offer sufficient clarity, specifically because it's easy to confuse the concepts of "a link in a circle" and "a link between two circles."

Related: #74

**Comment by wolftune** [comment]
Since we're adding context, I should say that for the few _years_ I've known about Holacracy, the terminology of "lead link" always struck me as awkward and even colored my impression about the rest of the terminology, i.e. led me to be skeptical that the jargon was sensible at all. And I realize now that _most_ of the terminology is actually fine, and all the problems come from the totally inconsistent and unimportant idea of links being within circles. The rest of the terminology (tensions, circles, lead, facilitator…) makes total sense.

**Comment by brianjrobertson** [comment]
Not sure I understand where you're coming from here - the Lead Link is a link between circles.  A broader circle appoints a Lead Link as its representative into the sub-circle; they're Core Circle Members of both circles, and serve to connect them in many ways.  In addition, dropping "link" and calling them just a "lead" would be even more misleading than "lead link" in terms of people assuming they have traditional manager authorities.

**Comment by wolftune** [comment]
Ah, thanks for the clarification. So "link" is appropriate, but the problem with the term is that "lead" doesn't seem to modify "link" per se. I thought that they _are_ like a lead but have no authority over other roles in the sense that everyone follows the Holacracy rules… but like a lead link is the role with authority to generate the rest of the roles for a circle, so they are the lead of that circle in that sense, right?

Maybe the source of the confusion is the (arbitrary?) connection between being the rep-from-the-higher-circle and being the lead-generator-of-roles for this circle. So, if my thinking is right, Holacracy _could_ have said that a role of some sort in one circle can decide to make a sub-circle, create roles for that sub-circle, and then for that new sub-circle that original creating role becomes the rep link. I mean, there's no particular reason that the creator of the circle needs to be the lead link vs the rep link is there? If those two responsibilities were different role titles, I think I may have not gotten confused… Maybe both _should_ be the same, and _maybe_ both have a "lead" capacity in some ways, but they definitely seem like distinct responsibilities, and so I'd forgotten about one while considering the other.

**Comment by brianjrobertson** [comment]
Hmm, @wolftune, there are a few other misunderstandings in there as well that I'd love to clarify if time allowed, though my focus with my time in this forum is on constitution evolution vs. education; maybe consider posting in the [Holacracy Community of Practice](http://community.holacracy.org) for more clarity, or even attending a Holacracy workshop or training, and then revisiting this forum?

**Comment by wolftune** [comment]
@brianjrobertson thanks, I think I actually cleared up my misunderstandings mostly. Closing the issue.
