### ISSUE TITLE
Making explicit which parts of the Holacracy Constitution can't be changed

### ISSUE THREAD

**Issue by dienkwik** [holacracyone/Holacracy-Constitution#95]
As a Circle Member proposing changes in governance, I'd like to know for sure which parts of the Holacracy constitution can be changed through governance and which parts can't, so that I don't inadvertently make changes that violate the most fundamental elements of Holacracy and the Holacracy Constitution.

**Comment by smichel17** [comment]
I wonder if "the parts of the Holacracy Constitution that can be changed" should even be in the constitution at all. Instead, what if they were all as policies in an appendix, and the Constitution specifies that when you adopt the constitution you also adopt that appendix by default.

Is it possible to separate out those parts so well? If so, is it desirable?

**Comment by brianjrobertson** [comment]
I believe the new clarity in the new "Scope of Policy" section (within the Governance article) now makes this explicit.  I'd love for someone else to review this and verify that it's clear enough now with real examples you've seen that were previously ambiguous.
