### ISSUE TITLE
Creating a Holacracy Manifesto

### ISSUE THREAD

**Issue by dienkwik** [holacracyone/Holacracy-Constitution#96]
As a Circle Member proposing changes in governance, I'd like to be guided by a set of fundamental guiding principles (something like the Agile Manifesto), so that I stay true to the spirit of Holacracy even when the changes don't violate the Holacracy Constitution.

**Comment by jimscarver** [comment]
These are good to keep in mind though not really what you are looking for.

open: welcoming to everyone — equipotentiality is adopted as an organizing principle,

fair: distributing revenues according to the actual involvement and contribution of each participant,

meritocratic: ensuring that people have influence on decisions that affect them, in proportion of their peer-assessed, demonstrated expertise,

transparent: leveraging the blockchain to provide unfalsifiable and verifiable traces of distributed decisions and transfers of value.

From [free ftopia](https://medium.com/free-ftopia/free-ftopia-a-new-beginning-ee41a58edbd1#.6n79agrx5)

**Comment by brianjrobertson** [comment]
Hmm, this seems off in the Constitution itself - its power is as a neutral rule set, a tool to be used for many ends, not as a philosophy to promote.  And doing that could risk causing harm by baking in a polarity imbalance (by over-emphasizing one of a million principles that are all valuable to some degree, and under-emphasizing the positive version of its opposite).  But I'm open to being convinced.  Got any examples of what might go in there, that doesn't risk the above?

**Comment by brianjrobertson** [comment]
(An alternative of course is to create something like that via some guidelines for implementing or practicing Holacracy, but not in the Constitution itself...)

**Comment by MiekeByerley** [comment]
The constitution is not a stand alone document in an organisation as Brian
mentions the function is a Neutral Rule set that defines methods of
coordination. The constitution is one of three mechanisms in an
Organization that enable, support and facilitated the Purpose, Mission,
Vision etc. The other two mechanisms are a Philosophy (Culture Manifesto)
and a Code of Ethics/Conduct they each have a very distinctly different
function but are also intrinsically connected (so need to align and not
contradict) to create the guidance frame.

**Comment by brianjrobertson** [comment]
Closing this one as something likely worthwhile but not for inclusion in the constitution itself.
