### ISSUE TITLE
2.3.1 Confusing use of "by defining..."

### ISSUE THREAD

**Issue by chrcowan** [holacracyone/Holacracy-Constitution#97]
Section 2.3.1 says "You are responsible for regularly considering how to enact your Role's purpose and each of your Role's accountabilities, **by defining**: 
(a) each Partner filling a Defined Role in the Circle;" 

I don't know exactly what is intended here. It is about Base membership, so I get that "defining" means, defining base membership, and I get that the sentence, "You are responsible for regularly considering how to enact your Role's purpose..." means that, as a part of your base membership, you are supposed to do those things. However, the sequence of those two ideas without further clarification is confusing. 

For example, it seems like it's saying that I enact my Roles by defining.... "each partner filling a defined role in the circle" which of course doesnt make sense. 

ALSO, aside from the point above, I was wondering if there should be an "and" at the end of each a,b, c, and d. Like, "(a) each partner filing a defined role in the circle; **and**" because that would be consistent with pages 03, 29, and probably some others.

**Comment by brianjrobertson** [comment]
@chrcowan: Not sure what you're looking at, but Section 2.3.1 most definitely doesn't say that!

**Comment by brianjrobertson** [comment]
See:  http://www.holacracy.org/constitution#art231

**Comment by chrcowan** [comment]
yep! I see that now. Updating the desk reference and see that it is a copy/paste mistake. thanks!
