### ISSUE TITLE
4.3.4 Clarify Corollary requirements for individual action

### ISSUE THREAD

**Issue by chrcowan** [holacracyone/Holacracy-Constitution#98]
Section 4.3.4 mentions that the "corollary" requirements for taking IA should be higher than regular work, but it might be clearer to mention that the corollary requirements are listed in section 4.3.2 and 4.3.3. Maybe that's obvious, I dont know.

**Comment by lynoure** [comment]
Sounds like a good clarification to add.

**Comment by brianjrobertson** [comment]
I'm trying to keep section number references out of the document when not really needed, to keep it feeling lighter-weight...
