### ISSUE TITLE
Small issue: "Pathway" over "Path"

### ISSUE THREAD

**Issue by chrcowan** [holacracyone/Holacracy-Constitution#99]
Small thing, but Section 4.2.3 (e) mentions, "...others in their Roles and duties as desired, until a **path** for resolving the Tension..." and I think "pathway" is better than "path." 

I think pathway is better for conceptual consistency with how we talk about Holacracy in practice, as in, "the five pathways." 

Also, I think the change could make sense for internal consistency since Section 2.3.3 uses "pathway" e.g., "...unless an alternate **pathway** is defined for the..."

**Comment by lynoure** [comment]
At least to a (fluent but) non-native speaker "path" is clearer, and "pathway" sounds weird. Some other sources: http://www.wikidiff.com/path/pathway http://forum.wordreference.com/threads/path-vs-pathway.1545329/

**Comment by brianjrobertson** [comment]
Anyone else have thoughts on whether "path" vs. "pathway" serves better here (and elsewhere)?

**Comment by tylerdanke** [comment]
path seems to serve equally as well as pathway. Simpler is better. There are 2 instances of the word pathway and one instance of the word path. I believe that path would be best for all three instances. I am not familiar with "the five pathways".

**Comment by karilen** [comment]
I just vote for consistency Brian, and to make it easier would defer to strong pitches from those who are non native English speakers. (I don't have a strong sense myself.) Also, something like method, mechanism, or way could also work.

**Comment by julianeroell** [comment]
I prefer direct words over metaphorical expressions. Therefore, I suggest to replace the two instances of "alternate pathway" (in 2.3.2 and 2.3.3) with "alternative" and replace "path" (in 4.2.3.(e)) with "way". (A path is a thing to walk on, a way is "a method, style, or manner of doing something." (and also a thing to walk on. ;-))
